### ISSUE TITLE
CPU:50%, Memory:100MB

### ISSUE THREAD

**Issue by hotlittlewhitedog** [duckduckgo/Android#100]
Hi all,
Please check the performance of the application, my CPU was at 50% and 100MB of memory (without TOR).
It's very high.
++

**Comment by subsymbolic** [comment]
Hey, thanks for letting us know! Are you referring to the app in the Play Store? This one is still unreleased.

**Comment by hotlittlewhitedog** [comment]
On F-Droid

**Comment by subsymbolic** [comment]
Ah thanks for clearing that up. That's our legacy app, so we're not updating it at the moment. We'll soon be replacing it with the new app in this repo.

If you want to test out the new app (be warned it's still rough around the edges) you can get the apk from our releases page https://github.com/duckduckgo/Android/releases

**Comment by hotlittlewhitedog** [comment]
Ok thanks
