### ISSUE TITLE
window.innerHeight should not include navigation bar height

### ISSUE THREAD

**Issue by repraze** [duckduckgo/Android#1012]
**Describe the bug**
Currently `window.innerHeight`  is the size of the screen and does not include space for the URL bar at the top. This causes issue for single-page non scrollable application where dragging will cause the window to scroll to show the remaining height on the page. To note that preventDefault() on window "mousemove"/"touchmove" events doesn't prevent the page to scroll.

**How to Reproduce**
1. Create a page with the body height set to `window.innerHeight` or `document.documentElement.clientHeight`
2. You still have a scrollbar to hide the url/search bar

`innerHeight` should define the content (height) area of the window. I believe this content area, with the search/url bar and any other browser components, should not exceed the smartphone window.

**Expected behavior**
The url/search bar height to be removed from `innerHeight` / sizing information. This currently prevents making single page non scrollable application like games. This would make the computation similar to android chrome.

**Smartphone (please complete the following information):**
 - DDG App Version: 5.69.0 zi
 - Device: OnePlus 7T
 - OS: Android 10

**Comment by repraze** [comment]
A few samples on full-page applications I found with dragging issues:
 - Any drawing apps
   - https://www.pixilart.com/draw
   - https://drawisland.com/device
   - http://quickdraw.withgoogle.com/
 - Map applications
   - https://www.google.com/maps/
   - native duckduckgo map
 - Applications with joysticks

**Comment by cmonfortep** [comment]
Thanks for reporting this issue and for the thoughtful explanation from your side. We are aware of this issue, I will close this one as duplicated of https://github.com/duckduckgo/Android/issues/914

Thanks again for all the info provided and the links you shared.
