### ISSUE TITLE
Support for Android TV

### ISSUE THREAD

**Issue by nom3ad** [duckduckgo/Android#1016]
It would be really nice to see DuckDuckGo in Android TV play store.  Currently, there isn't many options when it comes to Android TV for a good browser. 

Manually installing from APK file works great for DuckDuckGo.  I have been using this for a while and no issues found so far.

**Comment by AlSufyaniT1** [comment]
> سيكون من الرائع حقًا رؤية DuckDuckGo في متجر ألعاب Android TV. حاليًا ، لا توجد العديد من الخيارات عندما يتعلق الأمر بتلفزيون Android لمتصفح جيد.
> 
> التثبيت اليدوي من ملف APK يعمل بشكل رائع مع DuckDuckGo. لقد كنت أستخدم هذا لفترة من الوقت ولم يتم العثور على مشكلات حتى الآن.

**Comment by cmonfortep** [comment]
Forgot to post here the internal task I created to discuss this
https://app.asana.com/0/0/1199610872492403/f

**Comment by cmonfortep** [comment]
Hello @nom3ad  , thanks for taking the time to submit this feature request.

After internal discussion with the team, we've agreed that there's no plan in the foreseeable future to support this request. Should this change in the future, we'll update this conversation appropriately.
