### ISSUE TITLE
Images are downloaded as media.bin

### ISSUE THREAD

**Issue by uraza** [duckduckgo/Android#1018]
**Describe the bug**
Images are sometimes downloaded as media.bin or media-X.bin (with X being a number).

**How to Reproduce**
1. Go to 'https://mobile.twitter.com/thesebosscats/status/1330002995799420928'
2. Long press the image to download it.
3. See that the image got downloaded as media.bin (media-5.bin in my case)

![image](https://user-images.githubusercontent.com/3456223/99870428-18da8500-2bd3-11eb-926e-40386305e9b7.png)

**Expected behavior**
The image should be downloaded as a jpeg, as confirmed on another browser.

**Smartphone (please complete the following information):**
 - DDG App Version: 5.68.0 (from F-Droid)
 - Device: Samsung Galaxy A51 5G
 - OS: Android 10

**Comment by cmonfortep** [comment]
Thanks.
I've created an internal task: https://app.asana.com/0/0/1199338046770253/f

**Comment by cmonfortep** [comment]
Small update:
We've analyzed this issue. We currently rely on the Download Manager to download files, and we try to obtain the filename from the URL. In some cases is not possible to extract the filename from the URL and we end up using `.bin` extension. -> https://github.com/duckduckgo/Android/blob/e1e00ebcb49e86c37f246ed98e3a2605dc2a5594/app/src/main/java/com/duckduckgo/app/browser/downloader/FilenameExtractor.kt#L65

It will possible to improve that part if instead, we build our own download solution, that way we will be able to extract the filename from the network headers. We have scope a project for that https://app.asana.com/0/414730916066338/1199350832762474/f. 

If someone else has any other approach we can introduce, please let us know.

**Comment by idavydov** [comment]
Potentially related, I  encountered an example when an image file with a wrong file extension is downloaded into `/document/XXXX`, where `XXXX` is a number. I'm not an expert, but it's really bizarre that a file is downloaded outside `/storage`.

**Comment by Lalisfeed** [comment]
What if there is a rename option for the file when tried to download?

**Comment by Lalisfeed** [comment]
I tried to download python (.py) files and it asked me to save it as `uploads.bin`

**Comment by bonninf** [comment]
Hello. I tested with DuckDuckGo 5.113.1 from the Play store on a device G One Android 7.0 by trying to download an image from a Twitter post.
The image is well downloaded and readable from the Android's Files Explorer.

**Comment by cmonfortep** [comment]
This is now fixed. Closing the issue.
