### ISSUE TITLE
Protection against fingerprinting

### ISSUE THREAD

**Issue by uraza** [duckduckgo/Android#1019]
**Is your feature request related to a problem? Please describe.**
I just ran the "Cover Your Tracks" tool from EFF, available here: https://coveryourtracks.eff.org/
I found out that the browser has a nearly unique fingerprint (I got similar results on other mobile browsers I tried).

![image](https://user-images.githubusercontent.com/3456223/99873878-5c3cef80-2be3-11eb-93de-e1f928815304.png)

**Describe the solution or the user experience you'd like**
It would be great to have some protection against fingerprinting.

Thanks.

Jeremy

**Comment by uraza** [comment]
This request was also mentioned in #935.

**Comment by cmonfortep** [comment]
Thanks for sharing with us that report. We have a project in our backlog that should improve our fingerprinting protection (https://app.asana.com/0/1163321984198618/1199130622356231/f). Actually, some work is already coming to our iOS app https://github.com/duckduckgo/iOS/pull/795

Closing this issue as we have clear next steps. Thanks.
