### ISSUE TITLE
Fix WebRTC Leaks

### ISSUE THREAD

**Issue by Ryan451** [duckduckgo/Android#1029]
**Is your feature request related to a problem? Please describe.**
I ran a WebRTC test at [BrowserLeaks](https://browserleaks.com/webrtc) and I found out that RTCPeerConnection and RTCDataChannel are not disabled.

**Describe the solution or the user experience you'd like**
If possible, kindly disable WebRTC by default or please give us an option to disable it manually.

**Additional context**
WebRTC vulnerability: https://threatpost.com/webrtc-found-leaking-local-ip-addresses/110803/

Steps to Reproduce:
1. Open DuckDuckGo Privacy Browser App.
2. Go to https://browserleaks.com/webrtc . The test will start automatically.
If the values for RTCPeerConnection and RTCDataChannel are true, then WebRTC is not disabled.
![BrowserLeaks](https://user-images.githubusercontent.com/75673731/101558630-4f4d3800-39fa-11eb-821c-fa28577621a4.jpg)

**Comment by Ryan451** [comment]
I noticed that this request was a duplicate of #429

**Comment by aitorvs** [comment]
Hey @Ryan451, thanks for reporting this. If you don't mind I will close it in favor of #429
