### ISSUE TITLE
DuckDuckGo Secure DNS

### ISSUE THREAD

**Issue by Ryan451** [duckduckgo/Android#1032]
I hope that you add a built-in "Secure DNS" feature to DuckDuckGo Privacy Browser in the near future.

![IMG_20201210_202706](https://user-images.githubusercontent.com/75673731/101773862-51151980-3b28-11eb-8f75-c69ace842fe0.jpg)

**Comment by cmonfortep** [comment]
Closing this issue as duplicated of https://github.com/duckduckgo/Android/issues/470.

Please, use our templates to create future issues. It's really helpful for us to get as much info as possible from the community in order to correctly address each request.

**Comment by Ryan451** [comment]
@cmonfortep noted. I also found a solution in this issue. I changed my DNS at the IP settings from DHCP to Static. However, unlike in issue #470 , it didn't solved the problem about encrypting SNI
