### ISSUE TITLE
Browser Audit

### ISSUE THREAD

**Issue by Ryan451** [duckduckgo/Android#1034]
If you do find some time to spare, kindly run a test at https://browseraudit.com/ . This may help you identify some browser vulnerabilities.

![IMG_20201211_193843](https://user-images.githubusercontent.com/75673731/101900179-03f97c00-3bea-11eb-8782-72ba54b67026.jpg)

**Comment by cmonfortep** [comment]
Thanks for sharing. We are always looking forward to introducing new privacy/security improvement in our browser. Some folks already shared with us some audits using other tools, and we have plans to introduce new improvements (https://app.asana.com/0/1163321984198618/1199130622356231/f).

Closing this issue as it's similar to others.
