### ISSUE TITLE
Support for Oblivious DNS over HTTPS (ODoH) and Encrypted Client Hello (ECH)

### ISSUE THREAD

**Issue by Ryan451** [duckduckgo/Android#1036]
Cloudflare & IETF released open sourced protocol proposals, ODoH and ECH. I was hoping that DuckDuckGo would review and adopt these in the future updates

Oblivious DNS over HTTPS: https://github.com/cloudflare/odoh-rs
Encrypted Client Hello: https://github.com/tlswg/draft-ietf-tls-esni

**Comment by Ryan451** [comment]
Duplicate of #470 but with newer protocols

DNS over HTTPS -> Oblivious DNS over HTTPS
Encrypted SNI -> Encrypted Client Hello

**Comment by Ryan451** [comment]
Duplicate of #470 but with newer protocols:

DNS over HTTPS -> Oblivious DNS over HTTPS
Encrypted SNI -> Encrypted Client Hello

https://www.theregister.com/2020/12/08/cloudflare_privacy_protocols/

**Comment by cmonfortep** [comment]
Thanks for listing the new protocols in the other issue. I'm going to close this issue as duplicated.

**Comment by Ryan451** [comment]
Welcome @cmonfortep , I'll look forward seeing DuckDuckGo Privacy Browser adopt these security features in the future
