### ISSUE TITLE
Feature Request: Navigation history 

### ISSUE THREAD

**Issue by bonninf** [duckduckgo/Android#1039]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm not able to retrieve web pages than I had recently seen but I have closed the tab myself.

**Describe the solution or the user experience you'd like**
Adding the ability for the user displaying a special tab with its navigation history from the main menu.

**Additional context**
The navigation history feature is available on most browsers.

Below screenshot is an example about how the navigation history is displayed within Chrome Android:
![Screenshot_20201217-155817](https://user-images.githubusercontent.com/1090995/102505249-0ba1a080-4082-11eb-9416-6d9db7721e77.png)

**Comment by cmonfortep** [comment]
Thanks, @bonninf. This is something we internally talked about not a while ago, but we decided to give more priority to other projects. We are a small team and we just prioritized new privacy features, improving some features requested by our users, and new improvements related to the Fire button (to make it more flexible). I'm sure our team will talk about this in again, but wanted to share that we are not planning to store browsing history in the short/mid-term.
