### ISSUE TITLE
Feature Request: Private Navigation Tab

### ISSUE THREAD

**Issue by bonninf** [duckduckgo/Android#1040]
**Is your feature request related to a problem? Please describe.**
Sometimes, I would like to navigate without leaving any trace such as history, cookies, information entered in forms

**Describe the solution or the user experience you'd like**
Adding the ability simply navigating incognito inside a specific tab.

**Additional context**
For example, the Chrome Android browser includes the *New incognito tab* item from its main menu.

See the screenshots: 
![chrome_incognito_1](https://user-images.githubusercontent.com/1090995/102557010-82628c00-40ca-11eb-88d4-d2b57c43f42b.png)
![chrome_incognito_2](https://user-images.githubusercontent.com/1090995/102557014-842c4f80-40ca-11eb-9e71-ff64ab6eb59b.jpg)

**Comment by gursewakk** [comment]
Bro duckduckgo is already private browser when you click on fire it clear all traces

**Comment by bonninf** [comment]
Thanks for your response, but in this case the purpose is to have a specific tab being private. It should not need to clear all traces such as the user is able to navigate as private punctually.

**Comment by cmonfortep** [comment]
Thanks, @bonninf. AS @gursewakk we are private by default, and using the Fire button will remove all stored data by websites.
However, I understand what you mean by being able to burn a specific session or concrete tabs. We explored that and we were a bit restricted by how WebView works. There are many elements that are shared between all tabs, or stored in the file system.

We know users like to be able to clear any trace but at the same time, there's info they don't want to lose. We are trying to introduce new features and improve current ones to make the fire button more flexible for our users. To give you an example: you can manually fireproof a site (see options when you click the 3 dots button) to avoid losing your data in there. We still remove tabs when clearing all data, but if you logged in on a fireproof site, you should not be logged out.

Hope that one, and other features coming will be helpful for you :)
