### ISSUE TITLE
Duck Duck Go Crash 

### ISSUE THREAD

**Issue by NSTAdventure** [duckduckgo/Android#1044]
**Describe the bug**
DDG Crash Instantly When Launched
This Bug Occurs When You Disable Android System Webview

**How to Reproduce**
1. Use Knowledge To Disable Android System Webview
2. Now Try To Launch DDG Browser
3. DDG Crash Instantly :) 

If applicable, please include information about any settings that may be relevant to this issue (e.g. selected theme, auto clear option, etc).

**Expected behavior**
They shouldn't crash
**Since Android System Webview Only Usefull To Display Web Content Apart from the browser**

**Smartphone (please complete the following information):**
 - DDG App Version: 5.68.0
 - Device: Realme 5i 
 - OS: Android 10 Realme UI
 - There Is No Screenshot Available

Best Regards
NST_Adventure

**Comment by cmonfortep** [comment]
Thanks. Our browser is built on top of the WebView component. This behavior is expected if you disable WebView on Android.
