### ISSUE TITLE
Add stop button "X"

### ISSUE THREAD

**Issue by woheller69** [duckduckgo/Android#1047]
**Is your feature request related to a problem? Please describe.**
I am annoyed wehen pages are automatically loading videos, scripts, etc  that take a long time to load

**Describe the solution or the user experience you'd like**
Other browsers like firefox provide a "X" button next to reload button to stop loading the rest of the page

**Additional context**

**Comment by cmonfortep** [comment]
Thanks, I've created an internal task to keep track of this feature request.

https://app.asana.com/0/0/1199514257586704/f

**Comment by cmonfortep** [comment]
Hello @woheller69, thanks for taking the time to submit this feature request.

After internal discussion with the team, we've agreed that there's no plan in the foreseeable future to support this request. Should this change in the future, we'll update this conversation appropriately.

We have a project in our backlog to improve our menu options and settings, and it's possible that changes in the URL will be also applied. This feedback will be considered in any case.

**Comment by denuoweb** [comment]
I am switching back to firefox browser on android because of this missing feature. I like to stop news sites from loading after the text appears. DDG browser does not let me do this unfortunately.
