### ISSUE TITLE
Safe Browsing

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#1048]
Any plans on adding a Safe Browsing API (Example Googles API), While Ddg has good privacy features it would be nice to see some security behind the browser, especially as it built off WebView.

**Comment by nesara-cmd** [comment]
https://ci3.googleusercontent.com/proxy/TPdfc_lIDXbTnNdrn6nCRslk1u0BDbLhPD2JgEbNebqf3Egzwxo5cY6U6Jb5ECh1fs_uxoLAC5PelpPSkYkxXfWbre5ZFesB8NDyBrWA9OAeeapYYIWbkDBjZ_G6=s0-d-e1-ft#https://cdn.bonnerandpartners.com/BBD/signatures/bill-bonner-signature.png

**Comment by cmonfortep** [comment]
Please use our GitHub templates so we can understand better your request. Thanks.
