### ISSUE TITLE
Image results cutoff when switching to desktop mode

### ISSUE THREAD

**Issue by jameswhite7** [duckduckgo/Android#1049]
**Describe the bug**
Image results get cut off along right side when switching to desktop mode 

**How to Reproduce**
1. Search for something that has a lot of image results like "gay porn"
2. Switch results from text results to Image results and the default mobile version will show the images 3 across correctly resized to fit the page
3. Use the menu at the top right and switch to Desktop
4. The page refreshes to display additional image thumbnails but they are cut off along right side until you manually do a pinch unzoom to see all the images.

**Expected behavior**
When you switch to Desktop mode,
and the page refreshes to show additional images 
the refreshing code should do a resize to fit to browser page dimensions 
(whose dimensions are probably determined by device screen size), 
making it so that images DO NOT cutoff along right side 
and no manual pinch unzoom is necessary to workaround the images being cut off along the right side of the browser window.

This expected behaviour is what the android app version of mozilla firefox does automatically!

Here's my main advice to the dev team---
Study the top android browsers and have the development team draw up IT'S OWN features wishlist (that is publicly published),
so aggrevated users of the duckduckgo app 
(with expectations derived from using other top android browser apps) 
don't have to make up a github feature requests and bug notices one by one 
for every missing feature found in the android chrome and firefox apps!

Think about if Microsoft had released a version of Word that supposedly wasn't a beta version, but it looked like it was barely more than Windows Notepad --with no way to change text fonts or wrap text to screen.

Then Microsoft used some web software designed for developers 
(instead of users) to take feature requests for YEARS before 
eventually getting a Microsoft Word version that had 
half the features that WordPerfect for DOS had..

Thats what the DuckDuck go app feels like right now!!!

It shouldn't be news to the dev team that:
The firefox and chrome android apps seem way way way more advanced than the duckduckgo app.
For instance..
The firefox android app has a refresh button, and "x" button to stop stuck pages from loading (yeah these are already user feature requests, 
but I can't believe the DDG app didn't have this in version 1.0!

The default behavior for opening new tabs from links should be 
to load them IN THE BACKGROUND (automatically)
--the only way to do such a background load now in your app 
seems to be is to do it MANUALLY,  
using "Open in background tab" from the options list that pops up 
from long pressing on a link..

This behaviour should be settable (under settings) to load ALL new tabs (generated from tapping in links) IN THE BACKGROUND automatically (as the firefox app can do)
versus the default behavor currently in your app
which is to (annoying) switch to the new tab right away 
if you do a quick tap on a hyperlink.

The chrome android app has folders for organizing bookmarks --and I see its already a feature request but I wish Chrome (and your app) would allow exporting folders and bookmarks to an html or xml file..or even a csv file..any kind of text file that has brackets for enclosing the folder names --study how a windows .ini file looks if you don't understand what I mean..

Importing bookmarks from Chrome with folders intact would be very desireable feature as well..

The best browser bookmark manager is the one in the Desktop version of Mozilla Firefox. Feel free to copy shamelessly if you want a good starting point for a developing a state of the art bookmarks manager! <*wink*>

I've read through all the issues and feature requests here and it's all stuff that firefox/chrome has had for years now.

Don't blame the fact that you are a small dev team for the fact that this a "beta" version of an android browser app AT BEST!!!

Label this app as "BETA" in the address bar 
and make up a feedback wiki on the Duckduckgo site,
instead of demanding users signup for github account 
just to post bugs and festure rquests. 

Users are NOT developers. 

Do you understand that?!
--and github is for developers (and maybe users acting as beta testors).

Since the duckduckgo devs seem completely clueless 
I will switch back to using the mozilla firefox android app and 
NOT be selecting Duckduckgo as my search engine!

Someday someone will come up with a decent SECURE browser app 
with all the features of a modern android browser --but this isn't even CLOSE!

**Tablet info**
 - DDG App Version: REALLY BETA ONLY!
 - Device: ASUS 8 inch zenpad
 - OS: Android 7
 - Github is to hard to upload screenshots onto...maybe when you start using a wiki on the duckduckgo site you will be better able to interact with the android user community globally...then I will use imgur links in the markup for my wiki posts.

**Comment by cmonfortep** [comment]
Thanks for sharing your user request with us. I've created a new issue (https://github.com/duckduckgo/Android/issues/1054) summarizing your main request, as the rest of the feedback is already tracked in other issues.

You can send us any further feedback directly from the app. There's an option inside settings -> Leave feedback if that's easier for you.
