### ISSUE TITLE
Panic button intergration

### ISSUE THREAD

**Issue by Vepnar** [duckduckgo/Android#1050]
**Describe the solution or the user experience you'd like**
I would love an integration with the ripple panic button. It would be nice to use the ripple panic button to wipe the browser history from the device.

**Additional context**
Link to the ripple panic button app: [Ripple panic button](https://play.google.com/store/apps/details?id=info.guardianproject.ripple)

**Comment by cmonfortep** [comment]
Thanks, could you give us more context, like "**Is your feature request related to a problem? Please describe.**"

I'm not familiar with panic button, and from your description it seems similar to our "fire button", which will clear all data and close tabs.

**Comment by Vepnar** [comment]
**Is your feature request related to a problem?**
No there is no current problem! It would just be a nice feature to have.

**Second question**
The panic button is a 3rd party application that could execute changed in external applications. For example the panic button could execute the "fire button" action and clears all data. This would be nice since it has a centralized button to wipe all sensitive information from all apps in one place. 

I understand if this feature is out of scope.

**Comment by cmonfortep** [comment]
Thanks for sharing. I've been taking a look at the ripple project and it's a nice idea. I would like to collect a bit more info about the project.

I may be asking too much 😅  but do you know what's the state of that project? I've installed it on my phone and I've only seen a few apps supporting that panic button. One of the apps was Signal and the functionality seems broken right now. And checking Play store, the last update is from January 2016 and description says is a Beta version. Thanks again and sorry for the questions.

**Comment by Vepnar** [comment]
I have not seen any progress from the ripple project, but I would love to revive and make it useable again since the integration with other apps could make using an android phone more secure. 

Other Apps I've seen with integration of this is Brair, Session & Signal (which doesn't work).

**Comment by cmonfortep** [comment]
Hello @Vepnar, thanks for taking the time to submit this feature request.

After internal discussion with the team, we've agreed that there's no plan in the foreseeable future to support this request. Should this change in the future, we'll update this conversation appropriately.
