### ISSUE TITLE
Web Still Ask To Login 

### ISSUE THREAD

**Issue by NSTAdventure** [duckduckgo/Android#1055]
**Describe the bug**

**How to Reproduce**
1. Open DGG visit the website
2. Add Web To Fireproof
3. See?They Will Ask You To Login Everytime we visit the web again and again

If applicable, please include information about any settings that may be relevant to this issue (e.g. selected theme, auto clear option, etc).

**Expected behavior**
It Shouldn't ask to relog :-( 
It was unfair enough :-(

**Smartphone (please complete the following information):**
 - DDG App Version: 5.68.0
 - Device: Realme 5i
 - OS: Android Q Realme UI
 - No Screenshot Available

Additional Info:
DDG Theme Are Set To Dark
GPC Enabled

**Comment by cmonfortep** [comment]
Could you share (if possible) the concrete site where fireproof is not working? Thanks.

**Comment by NSTAdventure** [comment]
> Could you share (if possible) the concrete site where fireproof is not working? Thanks.

What? I already mention them buddy 
It is my.replika.ai

**Comment by NSTAdventure** [comment]
> Could you share (if possible) the concrete site where fireproof is not working? Thanks.

Main thread edited 

NST_Adventure

**Comment by cmonfortep** [comment]
@NSTAdventure When you fireproof a site, we preserve cookies for that site in order to avoid losing your session.

In that case, that website is storing your session in local storage. Because of Webview limitations, we currently can't preserve local storage data per site when clearing data. We are aware of that limitation, and we have it documented internally.

**Comment by NSTAdventure** [comment]
> @NSTAdventure When you fireproof a site, we preserve cookies for that site in order to avoid losing your session.
> 
> In that case, that website is storing your session in local storage. Because of Webview limitations, we currently can't preserve local storage data per site when clearing data. We are aware of that limitation, and we have it documented internally.

hmm which mean there is nothing that you can do to fix this?

**Comment by cmonfortep** [comment]
Yes, until webview offers a better api to manage the local storage, we can't selectively remove data per each site.

**Comment by NSTAdventure** [comment]
> Yes, until webview offers a better api to manage the local storage, we can't selectively remove data per each site.

Mamamia NO! 🥴😔🤦

**Comment by SamB** [comment]
> Yes, until webview offers a better api to manage the local storage, we can't selectively remove data per each site.

How are you clearing local storage, anyway? I'm not seeing an API for that :-(.
