### ISSUE TITLE
add lite version as selectable search engine

### ISSUE THREAD

**Issue by NSTAdventure** [duckduckgo/Android#1059]
**Is your feature request related to a problem? Please describe.**
i want you add this:
https://lite.duckduckgo.com/lite
https://html.duckduckgo.com/html
as selectable search engine so beside using traditional DDG we can choose one of them 

**Describe the solution or the user experience you'd like**
i want you add them as selectable search engine

**Additional context**
nothing

**Comment by cmonfortep** [comment]
Thanks for reaching us.

It's not in our roadmap to include them as selectable search engines. However, you can use our Bangs (https://duckduckgo.com/bang) to redirect your searches directly to the lite or the html version.

As an example try directly on our search bar:`!lite duck` or `!nojs duck`

**Comment by NSTAdventure** [comment]
> Thanks for reaching us.
> 
> It's not in our roadmap to include them as selectable search engines. However, you can use our Bangs (https://duckduckgo.com/bang) to redirect your searches directly to the lite or the html version.
> 
> As an example try directly on our search bar:`!lite duck` or `!nojs duck`

Hey gimme list of !bang command that i can use beside !lite duck or !nojs duck 😔

**Comment by cmonfortep** [comment]
You can check the list on the website I posted in my previous message. Thanks!

**Comment by NSTAdventure** [comment]
> You can check the list on the website I posted in my previous message. Thanks!

Ok 
And now how do i disable ALL JS on website?
I already done this on DDG now how to do it on website???

**Comment by WillHick** [comment]
> > You can check the list on the website I posted in my previous message. Thanks!
> 
> Ok 
> And now how do i disable ALL JS on website?
> I already done this on DDG now how to do it on website???

You can not disable JavaScript on the DDG Mobile Browser... Sadly

**Comment by NSTAdventure** [comment]
> > > You can check the list on the website I posted in my previous message. Thanks!
> > 
> > 
> > Ok
> > And now how do i disable ALL JS on website?
> > I already done this on DDG now how to do it on website???
> 
> You can not disable JavaScript on the DDG Mobile Browser... Sadly

Nah pls add these feature man :-( i'm low on bandwidth :-(

**Comment by lippfi** [comment]
I've just created a fork of DuckDuckGo that allows to change the default search engine
It does not support lite as an option out of the box, but you can add it via a PR - https://github.com/lippfi/SearxDuckGo
