### ISSUE TITLE
Duplicate bookmarks

### ISSUE THREAD

**Issue by ru2saig** [duckduckgo/Android#1067]
**Describe the bug**
By "Add Bookmark"ing a website multiple times, I'm able to get multiple bookmarks of the exact same webpage. 
See screenshot below:
![Screenshot_20210118-222631_DuckDuckGo](https://user-images.githubusercontent.com/42857541/104944170-d4097980-59dc-11eb-84b0-47aae4bf42bb.jpg)

**How to Reproduce**
  .0. Go to any website
  .1. Tap on Add Bookmark in the kebab menu a couple of times [ Optional ] Tap a couple more times for good measure
  .2. Going to Bookmarks, there are multiple bookmarks of the same page.

**Expected behavior**
Only one bookmark per a unique webpage.

**System and App Information**
 - DDG App settings: Settings -> 5.74.0 (57400)
 - Device: Samsung Galaxy S7 Edge SM-G935T
 - OS: Android 8.0.0 and Samsung Experience Version 9.0

**Comment by cmonfortep** [comment]
Thanks for reporting the issue. I agree it's something we should try to avoid. Thanks.
