### ISSUE TITLE
F-Droid version stuck on v5.68

### ISSUE THREAD

**Issue by Crashillo** [duckduckgo/Android#1069]
Last app update on F-Droid was made on Nov, 1st. More details https://f-droid.org/en/packages/com.duckduckgo.mobile.android/

Usually, there's a gap (GPlay vs FDroid) about one-version, or a few weeks, but now there are 6 versions ahead. Is there any issue deploying there?

**Comment by cmonfortep** [comment]
Thanks for reaching us. We are aware of the problem and we are trying to solve it together with the f-droid team. It seems our builds are failing on their side. New versions should be available soon. 

More detailed info here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7676
