### ISSUE TITLE
Website detect DDG blocker

### ISSUE THREAD

**Issue by NSTAdventure** [duckduckgo/Android#1071]
While visit this website:
https://www.thewindowsclub.com/download-old-version-software

Web say please disable your adblock 🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦 currently using latest version of ddg from f-droid.org

**Comment by cmonfortep** [comment]
Thanks, we are aware that some products are considering our browser as an ad blocker. We already have some work in progress to address that issue. Thanks.
