### ISSUE TITLE
Text formatting isn't properly cleared on copy-paste

### ISSUE THREAD

**Issue by yakkomajuri** [duckduckgo/Android#1074]
**Describe the bug**

Pasting larger text (e.g. headers) into the address bar doesn't completely clear the formatting:

<img src="https://user-images.githubusercontent.com/38760734/105640534-85ddf580-5e76-11eb-9002-253f81b00784.jpeg"  height="400"/>

**How to Reproduce**
1. Copy some header text (like the title of this issue) into the address bar
2. Watch it stay as "large text"

**Expected behavior**

The text should be cleared of formatting and standardized/

**Smartphone (please complete the following information):**
 - DDG App Version: 5.74.0 zu
 - Device: OnePlus 8T
 - OS: Android 11
 - If applicable, add screenshots to help explain your problem.

**Comment by cmonfortep** [comment]
Thanks for reporting that one. I will leave this task open in case anyone from our community wants to provide a fix.

**Comment by yakkomajuri** [comment]
On [our repo](github.com/PostHog/posthog) we get a lot of community action from our `good first issue` tag - you could maybe add it?

I would give this a look if I wasn't too busy to setup an Android dev environment

**Comment by hotchemi** [comment]
Opened https://github.com/duckduckgo/Android/pull/1105🙇

**Comment by cmonfortep** [comment]
Closing this as it has been resolved. Thanks @hotchemi
