### ISSUE TITLE
Optimise app to be more power efficient

### ISSUE THREAD

**Issue by Cyberdroid1** [duckduckgo/Android#1077]
**Is your feature request related to a problem? Please describe.**

I have noticed several times that this app consumes a bit more battery than other browsers (e.g Samsung Internet). I would like to request if some optimizations can be done here and there to make it less battery hungry.

**Comment by cmonfortep** [comment]
Thanks for the feedback. We haven't noticed any problem (or received feedback) related to battery usage but we will take a look to ensure everything works as expected.

To share any further feedback with us please reach us via our web form or via our in-app feedback form inside Settings (https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#share-feedback)

Thanks!

**Comment by Cyberdroid1** [comment]
Ok thanks!
