### ISSUE TITLE
Swipe down to refresh too sensitive

### ISSUE THREAD

**Issue by Ammako** [duckduckgo/Android#1081]
**Describe the bug**
When scrolling up from a webpage, once you reach the top of the page, the swipe down to refresh begins to activate. Sometimes, this is way too sensitive, and a refresh gets triggered pretty much right away, without giving enough time to avoid it. It's like scrolling up the page also "revs up" the refresh motion, and once you reach the top of the page the arrow has already reached full circle and it causes a refresh.

**How to Reproduce**
1. Go on any web page
2. Scroll down a bit
3. Scroll back up to the top of the page
4. Repeat a few times until it happens

**Expected behavior**
Ideally, I think scrolling up from a page should never trigger a refresh unless you explicitly lift your finger from the screen and swipe down a second time after having reached the top of the page. This bug is annoying, but it's still possible to accidentally trigger a page refresh sometimes just from swiping down too much when scrolling up a page, and that can be a bit irritating.

**Smartphone (please complete the following information):**
 - DDG App Version: 5.75.1
 - Device: Nexus 5
 - OS: Android 7.1.2

https://user-images.githubusercontent.com/43770697/106349595-149aaa00-629d-11eb-81b5-99ade90d6999.mp4

**Comment by Ammako** [comment]
Okay, so you don't actually need to be scrolling up much for this to happen. I've had it happen earlier where I was near the top of the page (youtube video), scrolled up just a little bit to reach the top of the page, and it just instantly refreshed the page.

**Comment by cmonfortep** [comment]
Thanks for reporting the bug. I agree, I've noticed that non consistent behavior in our app and sometimes pull to refresh is triggered unexpectedly. 

I've created an internal bug to track the issue: https://app.asana.com/0/414730916066338/1199888021167463/f

However, we accept community contributions to fix this bug. Thanks
