### ISSUE TITLE
Delay in search result

### ISSUE THREAD

**Issue by Amanraj13** [duckduckgo/Android#1086]
Hi There!
There is delay in the search result. When i search for anything in the duckduckgo android app a blank white page appears for a few seconds before the result appears.
This happens with all my android device and only with duckduckgo.

Please fix this as soon as possibe

**Comment by cmonfortep** [comment]
Hi @Amanraj13 could you use the bug template to report any issue? It will be good to know app version, android version, etc.. and any screenshot/video will be very useful too. 

I will close this one as invalid, please reach to us again.
