### ISSUE TITLE
Custom URL-name while adding to desktop

### ISSUE THREAD

**Issue by sandoxy** [duckduckgo/Android#1092]
Hey!

When I add many links from one website to my android-desktop in my duckduckgo-browser, then the name is always the same, the basic webdomain-name. The problem ist, that those links on my desktop all look the same. It woul be great, if the links had names dependent on the special location of the site I am serving.

Thanks.

**Comment by cmonfortep** [comment]
Hi @sandoxy, is this a bug report? feature request? or feedback?

It's not clear to me what's the problem you are trying to describe. 

"When I add many links from one website to my android-desktop in my duckduckgo-browser" Could you clarify this? what do you mean by "android-desktop"?

Thanks.

**Comment by sandoxy** [comment]
Sorry for the confusion. Here are two screenshots, which could help. I added two different github-projects to my android-desktop, but the names on the desktop are the same. It is not a bug, I think. It is more a wish, that the link-names tell something about the destination.

![Screenshot_2021-02-08_19-17-09_1_1](https://user-images.githubusercontent.com/38521726/107264456-46e99b80-6a43-11eb-8e42-a1b1e7035dfa.png)
![Screenshot_2021-02-08_19-20-03_1](https://user-images.githubusercontent.com/38521726/107264459-47823200-6a43-11eb-85a0-b162d42c38b1.png)

**Comment by cmonfortep** [comment]
Oh thanks. I see what you mean, it's when you add a website to you home screen. Thanks. I will share this feedback internally.

**Comment by anddam** [comment]
Reopening this feature request.

Please let us name the home screen shortcut before adding it.
Assigning the name is very handy to manage multiple shortcuts.

To add more context, Chrome's behavior depends on some website metadata: trying to add github.com pops a dialog where the shortcut name is not editable and is just the FQDN, but adding news.ycombinator.com pops the same dialog, this time with the name in an input field.

I am adding screenshots for the two scenarios just described

![Screenshot_20240527-124715](https://github.com/duckduckgo/Android/assets/689872/941461bf-56be-4eea-8d18-ed330b26f63a)

![Screenshot_20240527-124737](https://github.com/duckduckgo/Android/assets/689872/c8557351-f575-4203-9047-90dafe307972)
