### ISSUE TITLE
Tap on url bar no longer selects the entire url

### ISSUE THREAD

**Issue by Ammako** [duckduckgo/Android#1095]
**Describe the bug**
On newer versions of the app, tapping the url bar only places the cursor into the url, instead of selecting the entire thing. So if you were wanting to copy the url, or clear the addess bar to make another search or type a different address, you'd have to do a long press to select all before being able to do so.

This might be intended behavior for duckduckgo search pages, because in that scenario it's very useful to be able to just tap once on the url bar and be able to add more search terms right away or move the cursor around, but when on other web pages, when a user taps on the url bar, chances are they're trying to either copy the address, or clear it to type a search term/another site's address.

It's a bit annoying to use this way, when you're used to it working the other way. And even though one may get used to this behavior eventually, it's a bit unfriendly to use.

**How to Reproduce**
1. Go to any web page
2. Tap on the url bar
3. Cursor gets placed where you tapped, instead of selecting the entire address bar

**Expected behavior**
Tapping the address bar should default to selecting the entire address bar for sites other than duckduckgo search pages (don't know if it's possible to have different behavior between sites though.)

**Smartphone (please complete the following information):**
 - DDG App Version: 5.76.1
 - Device: Nexus 5
 - OS: Android 7.1.2

On 5.75.1 it was fine, so it's either 5.76.0 or 5.76.1 that changed the behavior.

**Comment by cmonfortep** [comment]
Thanks, we have a task in our internal backlog to address this issue: https://app.asana.com/0/414730916066338/1199931182139250/f

**Comment by Ammako** [comment]
8f46aa7

Confirmed fixed in 5.77.0
