### ISSUE TITLE
For what purpose a privacy aware app like DuckDuckGo web browser lists all my installed apps?

### ISSUE THREAD

**Issue by jpstotz** [duckduckgo/Android#1114]
In the class DeviceAppLookup DuckDuckGo lists all my installed apps and saves the data to an internal data structure.
For an app that claims to be privacy aware listing all my apps is a bit strange:

https://github.com/duckduckgo/Android/blob/7cfabe189e29bfa760520685494546d979fdca56/app/src/main/java/com/duckduckgo/app/systemsearch/DeviceAppLookup.kt#L85-L97

I am aware that this code does no longer work on Android 11 (`PackageManager.getInstalledApplications()` does no longer work without additional entries in `AndroidManifest.xml`)  but as the number of users running 10 and lower is very high this is still an issue from my perspective.

Can somebody shed light upon the fact why this code is included in DuckDuckGo browser respectively unter what circumstances this code is executed? 

Im my opinion the usage of privacy problematic function should always include a large comment in code describing why and for what purpose the code exists...

**Comment by cmonfortep** [comment]
Hi @jpstotz This code is part of the functionality of our home screen widget. We query it to show them as suggestions based on the keyword the user entered. This is the behavior other similar widgets offer and we are just offering this functionality to meet our user expectations when using the widget. 

![image](https://user-images.githubusercontent.com/4747865/109287095-6fcfa600-7823-11eb-9b1c-6a17c32c30b1.png)

See "From this device" at the bottom as an example:

![image](https://user-images.githubusercontent.com/4747865/109287120-7b22d180-7823-11eb-8548-9744d87ee37d.png)

Does this answer your question?

**Comment by jpstotz** [comment]
@cmonfortep Thanks for your response. Then the widget is providing functionality to work as an app launcher (I assume this mimics behavior of the default Google search bar widget). 

I was able to verify that behavior using Frida.

Are you aware that this feature will not work on Android 11+? For that platform the additional permission `QUERY_ALL_PACKAGES` would be required. 

See the details e.g. in this article: https://proandroiddev.com/how-to-get-users-installed-apps-in-android-11-b4a4d2754286

**Comment by cmonfortep** [comment]
Yes, we are aware of that and we have a ticket in our backlog to review it. Thanks for pointing out that part.
