### ISSUE TITLE
Adding the option to mute/unmute a site

### ISSUE THREAD

**Issue by codepoet2017390** [duckduckgo/Android#1117]
I use the DuckDuckGo Android app on a daily basis. I'd love to add the feature to mute/unmute a site playing audio to DuckDuckGo Android App. Just as a scenario of how it would work is, imagine you play a video on Youtube, and without altering any sound setting on Youtube I can mute the tab playing Youtube while the video still plays silently. I'd love to contribute code for this feature in any way I can if it is possible.

**Comment by woheller69** [comment]
I would even prefer to have videos muted by default.

**Comment by codepoet2017390** [comment]
> I would even prefer to have videos muted by default.

Nice suggestion @woheller69 , waiting for someone from the team to reply

**Comment by cmonfortep** [comment]
Thanks for reaching us to submit this feature request. And thanks @codepoet2017390 for being open to contribute here. However, for these changes, we prefer to keep them internally as they need to be reviewed and approved by our product team.

I'm closing this issue as we are currently only accepting bug reports as Issues. Please review our [contribution guidelines ](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md) for more details.
