### ISSUE TITLE
Keyboard stays closed when tapping on input field after fullscreen mode

### ISSUE THREAD

**Issue by helbling** [duckduckgo/Android#1121]
**Describe the bug**
After being in fullscreen mode, tapping on input fields would not open the keyboard anymore.

**How to Reproduce**
1. Go to 'youtube.com
2. Open a video in fullscreen mode
3. exit fullscreen mode again
4. try to search another video by clicking on the magnifying glass of youtube (top right)
5. Keyboard stays closed

**Expected behavior**
Keyboard opens so I can write my search query

**Smartphone:**
 - DDG App Version: 5.77.2
 - Device: Nokia 8.1
 - OS: Android 10

**Comment by cmonfortep** [comment]
Thanks for reporting, we are aware of this issue and it will be fixed in our next release.

PR: https://github.com/duckduckgo/Android/pull/1113
