### ISSUE TITLE
Add NoScript functionality

### ISSUE THREAD

**Issue by woheller69** [duckduckgo/Android#1122]
**Is your feature request related to a problem? Please describe.**
Many pages are a lot faster if Javascript is disabled. Also annoying cookie banners are blocked on many pages if Javascript is off.
Therefore I like to use NoScript and only allow scripts that are needed for my needs.

**Describe the solution or the user experience you'd like**
Integrate the functionality of a NoScript Firefox plugin

**Additional context**

**Comment by cmonfortep** [comment]
Thanks, we don't have plans to support extensions or plugins in our current backlog. Thanks for sharing this feedback with us.

Please take a look at our [contribution guidelines for sending feedback](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#share-feedback). If you would like to share any further feedback please reach us via our feedback site or the embedded feedback form in our browser. We consume the feedback we receive in there and that's a good way to give us visibility on our users' needs. Thanks!
