### ISSUE TITLE
Can I use DuckDuckGo android source code to make my own browser?

### ISSUE THREAD

**Issue by manish2525** [duckduckgo/Android#1127]
Can someone use your code to make a third party app or their own app? Or the source code is just for the review? However the licence says anyone can do anything with the code.

**Comment by manish2525** [comment]
Hi initpwn,

I am still concerned about some APIs this app has like text suggestions and privacy dashboard related.
Are the APIs open to everyone to use?

Thanks!!

**Comment by cmonfortep** [comment]
@manish2525 see @initpwn comment. The source code is under Apache License Version 2.0 (see https://github.com/duckduckgo/Android/blob/develop/LICENSE)

About using our APIs, many of them can only be consumed from our app.

Thanks.
