### ISSUE TITLE
DuckDuckGo as a built-in system app

### ISSUE THREAD

**Issue by Ammako** [duckduckgo/Android#1128]
I'm interested in including DuckDuckGo by default in my rom, replacing Jelly as the default browser. However the app doesn't run when installed as a system app.

```
03-10 16:44:01.097  3769  3811 E AndroidRuntime: FATAL EXCEPTION: Thread-6
03-10 16:44:01.097  3769  3811 E AndroidRuntime: Process: com.duckduckgo.mobile.android, PID: 3769
03-10 16:44:01.097  3769  3811 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/app/DuckDuckGo/DuckDuckGo.apk!/lib/armeabi-v7a/libhttps-bloom-lib.so" not found
03-10 16:44:01.097  3769  3811 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
03-10 16:44:01.097  3769  3811 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1562)
03-10 16:44:01.097  3769  3811 E AndroidRuntime: 	at com.duckduckgo.app.httpsupgrade.BloomFilter.<init>(BloomFilter.kt:24)
03-10 16:44:01.097  3769  3811 E AndroidRuntime: 	at com.duckduckgo.app.httpsupgrade.HttpsBloomFilterFactoryImpl.create(HttpsBloomFilterFactory.kt:54)
03-10 16:44:01.097  3769  3811 E AndroidRuntime: 	at com.duckduckgo.app.httpsupgrade.HttpsUpgraderImpl.reloadData(HttpsUpgrader.kt:95)
03-10 16:44:01.097  3769  3811 E AndroidRuntime: 	at com.duckduckgo.app.global.DuckDuckGoApplication$initializeHttpsUpgrader$1.invoke(DuckDuckGoApplication.kt:273)
03-10 16:44:01.097  3769  3811 E AndroidRuntime: 	at com.duckduckgo.app.global.DuckDuckGoApplication$initializeHttpsUpgrader$1.invoke(DuckDuckGoApplication.kt:75)
03-10 16:44:01.097  3769  3811 E AndroidRuntime: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
03-10 16:44:01.099  2225  2237 W ActivityManager:   Force finishing activity com.duckduckgo.mobile.android/com.duckduckgo.app.launch.Launcher
```

If I install an update to the application, then it works, of course. But it would be nice if I could have the base apk working from /system/app. What do I have to include, and how?

Bromite System WebView does something similar with being unable to run under /system/app, but including `libwebviewchromium_loader` and `libwebviewchromium_plat_support` in Android.mk makes it work. And of course I can't put `LOCAL_REQUIRED_MODULES := libhttps-bloom-lib` in DuckDuckGo Android.mk, that would be too easy. There are additional steps, but I'm not sure where to go next. Any pointers?

**Comment by cmonfortep** [comment]
Sorry @Ammako I'm not familiar with how to install apks as part of the system.

Posting some more info about our bloom filter (the one that is failing you). That's added into our project as a git submodule. The codebase can be found here https://github.com/duckduckgo/bloom_cpp. It's just a cpp library we use for our https ugrades. Package names are important because jni calls....and I don't know what more to say tbh 😅

**Comment by Ammako** [comment]
Yeah, that's fair. It's just odd because I'm not building DuckDuckGo myself, I'm using the pre-built apk that is available for download here. So the library should already be available within the apk, and yet for some reason it can't find it when the apk is in /system/app, but it can find it if it's installed onto /data/app. Some weird Android black magic I guess.

I'll probably have to look for advice somewhere that is better-versed in rom building or something. I know about the bloom_cpp repo but I figured there was no way simply adding `bloom_cpp` to required modules would help in any way... but then again, I haven't tried. Figured I would most likely have to at least include it as an external repo first, which I'm not sure how to do right now.

**Comment by Ammako** [comment]
Following up on this...

```
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := DuckDuckGo
LOCAL_SRC_FILES := duckduckgo-5.75.1-release.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MULTILIB := both
ifeq ($(TARGET_CPU_ABI), arm64-v8a)
    LOCAL_PREBUILT_JNI_LIBS := lib/arm64-v8a/libhttps-bloom-lib.so
else
    LOCAL_PREBUILT_JNI_LIBS := lib/armeabi-v7a/libhttps-bloom-lib.so
endif
LOCAL_OVERRIDES_PACKAGES := Jelly
include $(BUILD_PREBUILT)
```

`libhttps-bloom-lib.so` must be extracted from the apk, it will be included at `/system/app/DuckDuckGo/lib/[arm/arm64]/libhttps-bloom-lib.so` and the app will work without crashing.

👍
