### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#1130]
While the DuckDuckGo Browser provides a great experience while browsing, Id like to know does the browser have measures in place to prevent attacks via JavaScript, XSS, Third Patry Highjacking and any others linked from below:

https://dzone.com/articles/javascript-attacks-in-webviews
https://www.checkmarx.com/blog/javascript-attacks-webviews/

And by adding certain features such as HTTP blocking if a page can't be upgraded to HTTPS and JS enable/disable (As a switch in the Privacy Protections Dashboard).

Add Block Lists (Malware, Adware/Phishing domains, Adult sites etc)

Thanks

**Comment by cmonfortep** [comment]
Thanks for reaching us. We are currently only accepting Github Issues for bug reports.

We are always focused on protecting user privacy and provide security protections when browsing the web. If you have noticed any security issue related to the list you provided, please reach us via https://hackerone.com/duckduckgo

Check out our [contribution guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contributing-to-duckduckgo) to know more details. There's a specific section about how to send feedback, questions, or security reports. Thanks.
