### ISSUE TITLE
OpenStreetMap unusable

### ISSUE THREAD

**Issue by Ammako** [duckduckgo/Android#1132]
**Describe the bug**
Trying to scroll the map down on OpenStreetMap triggers a page refresh instead of moving the map

**How to Reproduce**
1. Go to https://www.openstreetmap.org/
2. Zoom in on map with the + button
3. Scroll around and try to scroll the map down several times
4. At first it works, but very quickly it refuses to scroll anymore and just refreshes the page instead

**Expected behavior**
Should be able to scroll the map without refreshing the page

**Smartphone (please complete the following information):**
 - DDG App Version: 5.78.0
 - Device: Nexus 5
 - OS: Android 7.1.2

**Comment by cmonfortep** [comment]
@marcosholgado do you have time to take a look at this one and triage it? Thanks!

**Comment by cmonfortep** [comment]
I've created an internal task to investigate the issue. https://app.asana.com/0/414730916066338/1200092328111314/f

**Comment by Ammako** [comment]
I've come across a dailymail article this morning, and it turns out that site exhibits similar behavior. In case that might be helpful.

It can also sometimes trigger swipe down to refresh while the address bar is still hidden (#900)

**Comment by marcosholgado** [comment]
> I've come across a dailymail article this morning, and it turns out that site exhibits similar behavior. In case that might be helpful.
> 
> It can also sometimes trigger swipe down to refresh while the address bar is still hidden (#900)

Thanks, any sites where we can reproduce this are definitely helpful for us :)

**Comment by mabuckman** [comment]
Another example: https://www.walmart.com/grocery/
