### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#1142]
**Home Page**

Not sure if this is a bug or the start of a re-design but the DDG home screen logo is off center and higher up the page.

![Screenshot_20210321-194330_DuckDuckGo.png](https://user-images.githubusercontent.com/48844761/111896307-9331ed80-8a7d-11eb-810d-a0f0f2405d7a.png)

- Latest App Update On Android 10

**Comment by cmonfortep** [comment]
Thanks @WillHick This is an intended change, not a bug.

**Comment by WillHick** [comment]
> Thanks @WillHick This is an intended change, not a bug. 

Sweet as, new home page?

**Comment by cmonfortep** [comment]
We are working on some improvements and new changes will come soon 👍
