### ISSUE TITLE
Read mode 

### ISSUE THREAD

**Issue by moshpirit** [duckduckgo/Android#1143]
One thing that I like to do when I use Firefox on my laptop is reading articles using the read mode. I think it's even more useful for phones and I think DDG should implement this feature

**Comment by Ammako** [comment]
Note, feature requests are not currently accepted in the issue tracker. They should be directed [here](https://github.com/duckduckgo/Android/discussions) instead.

**Comment by cmonfortep** [comment]
Thanks.

We will migrate the existing Feature requests as Discussions very soon. Closing this one as duplicated https://github.com/duckduckgo/Android/issues/861
