### ISSUE TITLE
Search Box issues with RTL text

### ISSUE THREAD

**Issue by Xashyar** [duckduckgo/Android#1144]
Hello, I know this is not the right place for the issue but it's the closest place I could find to raise two really chronic issues wrt DDG Search Box (on duckduckgo.com) with RTL texts.

1. When you switch your input keyboard in the middle of typing a search phrase, the search box loses focus, and you need to bring back the focus on it manually every time.

2. The search box does not support auto direction functionality dependent on the input text, so no matter what the input everything gets aligned from left-to-right which is horrible in terms of functionality.

Hopefully someone can point out the right place where the appropriate team can see this?

**Comment by cmonfortep** [comment]
Hey @Xashyar , thanks for taking the time to write this.

Unfortunately, seems like your issue does not belong in this repository as you mentioned. To share feedback please visit this site (https://help.duckduckgo.com/duckduckgo-help-pages/company/contact-us/) 

In your case I guess the one that fits your request will be: 
"For feedback regarding DuckDuckGo Search, use the “Send feedback” link in the side of the results pages."
