### ISSUE TITLE
"Open in Background Tab" does not REALLY open in background

### ISSUE THREAD

**Issue by oldphones68** [duckduckgo/Android#1148]
App version: 5.78.1

Steps to reproduce the bug: Long press on any link > Select 'Open in Background Tab'

Expected behavior: Tabs opened in BG should 'open' or 'load' in the BG.

Actual behavior: When selecting Open in Background Tab, tabs not really 'Open' in BG. It remains as a blank page in the background UNTIL user switch to that tab.
I think, it contradicts the concept of efficient tabbed browsing.

**Comment by cmonfortep** [comment]
Hello @oldphones68 , thanks for taking the time to submit this feature request.

After internal discussion with the team, we've agreed that there's no plan in the foreseeable future to support this request. For us, the current behavior is the expected one.

Should this change in the future, we'll update this conversation appropriately.

**Comment by oldphones68** [comment]
Ok brother!
Hoping for the best! @cmonfortep
