### ISSUE TITLE
Swipe To Refresh On NTP

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#1162]
On The New Tab Page (NTP) The Swipe To Refresh Shows Up At Random When Opening A New Tab After Browsing.

Attempting To Reproduce Issue Is At Random Tends To Happen The Most While Browsing.

Images:
![Screenshot_20210406-171908_DuckDuckGo.png](https://user-images.githubusercontent.com/48844761/113662630-97f0d580-96fc-11eb-9140-06197b3776b3.png)

![Screenshot_20210406-171859_DuckDuckGo.png](https://user-images.githubusercontent.com/48844761/113662636-9b845c80-96fc-11eb-84cc-e4f7e47c4ddb.png)

**Comment by cmonfortep** [comment]
Taking a look at this issue.

Very easy to reproduce, for possible contributors:
1. open a new tab
2. visit any site
3. press back (this will go back to the home tab)
4. user is able to pull to refresh

**Comment by aayush287** [comment]
@cmonfortep Can I work on this issue?
