### ISSUE TITLE
While moving on a map, moving the finger down will refresh the page

### ISSUE THREAD

**Issue by dukearena** [duckduckgo/Android#1165]
**Describe the bug**
While navigating on a map inside a website, I was trying to go north moving my finger down but the refresh icon appeared and refreshed the page, making me start from the beginning.
This behavior occurs every time I do the same steps (see below).

**How to Reproduce**
1 - Go to any website that has a map (e.g. maps.google.com)
2 - Pan inside the map, moving the finger down
3 - The refresh icon will appear from the top and, as soon as I release the finger, the page is refreshed. It also blocks the map to pan in the desired direction.

This issue is verifiable with any theme or auto-clear option.

**Expected behavior**
While moving the finger down inside a map, should not refresh the page and the map should pan.

**Smartphone (please complete the following information):**
 - DDG App Version: 5.79.0 (57900)
 - Device: Redmi Note 8 Pro
 - OS: Android 10 QP1A.190711.020 (MIUI Global 12.0.4)

**Comment by Ammako** [comment]
https://github.com/duckduckgo/Android/issues/1132

**Comment by cmonfortep** [comment]
Thanks @dukearena we are aware of this issue with sites that contain an embedded map. 

Closing as dup in favor of https://github.com/duckduckgo/Android/issues/1132
