### ISSUE TITLE
Animation Menu

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#1181]
Can We Make The "Animation" Have A Capital "A", Would Be Great Thanks

![Screenshot_20210411-115810_DuckDuckGo.png](https://user-images.githubusercontent.com/48844761/114287775-d0f2c680-9abd-11eb-8b4d-f8ba30be805a.png)

**Comment by prosperian** [comment]
Hi, can i work on this?

**Comment by prosperian** [comment]
Hi, can i work on this?

**Comment by cmonfortep** [comment]
Thanks for sharing, after taking a look at the bug report we are closing this because that behavior is intended.

Friendly reminder: please use bug templates or issues could be closed. Thanks.
