### ISSUE TITLE
Feature Request: Privacy Redirects

### ISSUE THREAD

**Issue by mabuckman** [duckduckgo/Android#1182]
It would nice if users had the ability to redirect certain websites to privacy friendly alternatives. There is an extension called [Privacy Redirect](https://addons.mozilla.org/en-US/firefox/addon/privacy-redirect/) that  provides this functionality.

You can redirect sites like this: 
Twitter &rarr; Nitter Instance
YouTube &rarr; Invidious Instance
Instagram &rarr; Bibliogram Instance
Reddit &rarr; Teddit Instance
Google Maps &rarr; OpenStreetMap

The alternatives also perform better in the browser. Here is a couple examples:

> teddit frontpage: ~30 HTTP requests with ~270 KB of data downloaded vs. Reddit frontpage: ~190 requests with ~24 MB

> Nitter is on average around 15 times lighter than Twitter, and in most cases serves pages faster (eg. timelines load 2-4x faster).

Thanks!

**Comment by cmonfortep** [comment]
Please, use discussions to share feature requests. Only bug reports are expected to be accepted as issues. thanks.
