### ISSUE TITLE
Favicons get swapped!

### ISSUE THREAD

**Issue by oldphones68** [duckduckgo/Android#1188]
**Describe the bug**
Favicons get swapped.
This seems close to the issue #975. 

**How to Reproduce**
1. Go to 'Bookmarks'
2. See error

Although in #975 seeming @aitorvs has provided a patch, but I'm seeing this bug is still existing.

**Expected behavior**
Favicons should show correctly. 

**Smartphone**
 - DDG App Version: 5.80.0
 - OS: Android 6

**Comment by Ammako** [comment]
Yup. Mine shows github with a reddit favicon.

**Comment by cmonfortep** [comment]
Could you provide more info like: how many bookmarks you have? does it happen right after opening the screen or when scrolling? Do you see the same error on the tabs screen or only in the bookmarks screen?

**Comment by Ammako** [comment]
4 bookmarks

Right when opening the screen

Only bookmarks screen

**Comment by cmonfortep** [comment]
Thanks. That's weird, we use the same class to retrieve bookmark icon in the bookmarks screen and the tab screen (the one where you see all your tabs). 

We will investigate what's happening there

**Comment by oldphones68** [comment]
18 bookmarks so far.

It happens after opening the browser.

Happens on the bookmarks menu. Didn't noticed (yet) in the tab screen.

@cmonfortep

**Comment by cmonfortep** [comment]
@oldphones68 @Ammako another question from my side.

The sites that have a wrong favicon, do they show a favicon of a site that is also a bookmark? For example: in the case of @Ammako "github with a reddit favicon", do you have both sites bookmarked?

**Comment by cmonfortep** [comment]
We have created an internal task to further investigate this issue: https://app.asana.com/0/414730916066338/1200206978219280/f

**Comment by Ammako** [comment]
I don't have reddit bookmarked, no. Only github. But it must have picked up the favicon from when I was browsing reddit, either way.

Fire button to clear data doesn't fix it. Github is fireproofed, reddit is not.

**Comment by cmonfortep** [comment]
Thanks so much @Ammako, does GitHub show the wrong favicon in fireproof websites too? I guess the answer is yes, but just to double check with you as we can't reproduce it in our side.

**Comment by Ammako** [comment]
Reddit data gets cleared due to not being fireproofed, github data stays because it's fireproofed. Reddit favicon stays.

(I'm not entirely sure what you meant, so don't hesitate to elaborate if this doesn't properly answer your question.)

Also, this would probably be a difficult issue to reproduce, because it only happens rarely, and randomly.

**Comment by cmonfortep** [comment]
"Github already had its correct github favicon in bookmarks, at some point in the last few days the favicon was replaced with reddit's favicon." ...huh, interesting...

My question was related to the Fireproof sites list inside settings (settings -> fireproof sites). Inside there, we list all fireproofed sites, I wonder if GitHub shows the wrong favicon on that screen too.

**Comment by Ammako** [comment]
> My question was related to the Fireproof sites list inside settings (settings -> fireproof sites). Inside there, we list all fireproofed sites, I wonder if GitHub shows the wrong favicon on that screen too.

It does!

**Comment by oldphones68** [comment]
> "Github already had its correct github favicon in bookmarks, at some point in the last few days the favicon was replaced with reddit's favicon." ...huh, interesting...
> 
> My question was related to the Fireproof sites list inside settings (settings -> fireproof sites). Inside there, we list all fireproofed sites, I wonder if GitHub shows the wrong favicon on that screen too.

For me, not yet noticed. I'll keep watching this. @cmonfortep

**Comment by Ammako** [comment]
The favicon fixed itself by un-fireproofing github, and after re-fireproofing it remains fixed.

**Comment by cmonfortep** [comment]
@Ammako thanks for the info.
From what I see, GitHub got the wrong favicon at some point (we need to understand why), and because it was a fireproof website we were just keeping that wrong favicon for the site between sessions.

One question: the problem was fixing but just un-fireproofing the site or did you also clear all data?

Thanks.

**Comment by Ammako** [comment]
Just by un-fireproofing.

**Comment by oldphones68** [comment]
@cmonfortep I tried to look deeper into this issue. I guess, it happens more after clearing cache fron the system (or phone) manager app.

And, from my experience, if I not make mistake, 'It happens in the morning'!!
Sounds funny, huh!? I also think so.

I can assure that, I have NO automatic cache cleaning app which clear the cache overnight.

By the way, I doubt, whether DDG store the favicons persistently on the device or not?

If DDG needs to connect with a server each and every time it is opened, it may be a fetching issue. But, if the favicons are on _**load once, used always**_ basis, it should **not** be like this, should it?

Besides, if DDG requires every time to connect to the server for loading the favicons, I think it can also be treated as a **_security_** issue besides being treated as a convenience or performance issue.

**Comment by cmonfortep** [comment]
@oldphones68 we don't rely on any server for favicons, that logic was changed some time ago. We currently rely on the webview component and the info that component provides to us. Thanks for the info in any case, we will continue investigating this issue.

**Comment by oldphones68** [comment]
@cmonfortep
> we don't rely on any server for favicons, that logic was changed some time ago. We currently rely on the webview component and the info that component provides to us. Thanks for the info in any case, we will continue investigating this issue.

Okey! If that's the situation, then this portion below may help, I hope. 

> I guess, it happens more after clearing cache fron the system (or phone) manager app.
And, from my experience, if I not make mistake, 'It happens in the morning'!!
Sounds funny, huh!? I also think so.
I can assure that, I have NO automatic cache cleaning app which clear the cache overnight.

**Comment by oldphones68** [comment]
@malmstein Updated to 5.81.0.

But faced this problem today **_morning_**

I have no fireproof sites, but this issue happened again. 

![IMG_20210425_091402](https://user-images.githubusercontent.com/51379704/115979292-ddd7e580-a5a6-11eb-8bd7-559d3e14446d.png)
![IMG_20210425_091445](https://user-images.githubusercontent.com/51379704/115979299-eaf4d480-a5a6-11eb-9fbb-2bca72aa24bf.png)

**Comment by malmstein** [comment]
> @malmstein Updated to 5.81.0.
> 
> But faced this problem today **_morning_**
> 
> I have no fireproof sites, but this issue happened again. 
> 
> ![IMG_20210425_091402](https://user-images.githubusercontent.com/51379704/115979292-ddd7e580-a5a6-11eb-8bd7-559d3e14446d.png)
> ![IMG_20210425_091445](https://user-images.githubusercontent.com/51379704/115979299-eaf4d480-a5a6-11eb-9fbb-2bca72aa24bf.png)
> 
> 

@oldphones68 5.81.0 went out before this PR was merged, this fix will be available in the next release. Thanks for letting us know though!

**Comment by fredrik-nti-johanneberg** [comment]
This is still an active issue. I have been experiencing swapped favorites favicons for the last couple of years on my Xiaomi A2 Android 10 device with DDG 5.227.1. When swapping phones to more recent Pixel 8 Android 15 device with DDG 5.228.2 I was annoyed to see it still persists. Currently I have 5 out of a total of 23 favorites showing wrong favicon. For example two band.us bookmarked URLs show a Facebook favicon (yes I do have a few Facebook bookmarks there as well). I've got edition.cnn.com showing a Favicon from a news site I never bookmarked (www.expressen.se).
