### ISSUE TITLE
Add option to disable Javascript for site

### ISSUE THREAD

**Issue by woheller69** [duckduckgo/Android#1191]
**Is your feature request related to a problem? Please describe.**
Many pages are a lot faster if Javascript is disabled. Also annoying cookie banners are blocked on many pages if Javascript is off.

**Describe the solution or the user experience you'd like**
Add a checkbox "Disable Javascript for site" like "Fireproof site" or "Desktop site".

**Additional context**

**Comment by cmonfortep** [comment]
Thanks for reaching us. We are currently only accepting Github Issues for bug reports.

Please, use discussions to share feature requests. Only bug reports are expected to be accepted as issues. Thanks.

[Contributing guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code)
