### ISSUE TITLE
Urgent: Needs a workaround to export bookmarks, to avoid data loss.

### ISSUE THREAD

**Issue by h908714124** [duckduckgo/Android#1192]
**Describe the bug**
After using the DDG app for about 2 years, I have around 1000 bookmarks stored inside it.
All of these will be lost when I eventually switch phones, or my old phone stops working.
A method to export these bookmarks to _any_ format is urgently needed, in order to avoid a complete data loss.

**How to Reproduce**
1. Install DDG app
2. Add some bookmarks
3. Notice the problem

**Expected behavior**
A basic "export bookmarks" functionality should be added to the DDG app.
If this is not possible in a timely fashion, instructions to locate the bookmarks data on the Android file system
 should be provided, to facilitate manual recovery.
See also [this discussion](https://github.com/duckduckgo/Android/discussions/1170).

**Smartphone**
 - DDG App Version: 5.80.0
 - Device: Pixel 2 XL
 - OS: Android 11

**Comment by malmstein** [comment]
Hello @h908714124, thanks for filing this in. 

As you very well point out, there's a [discussion](https://github.com/duckduckgo/Android/discussions/1170) about this topic. That is the proper place to make this feature request more visible. 

One of the reason why we moved to discussions in the past weeks is to surface old feature requests, and this is exactly what's happening with this feature.

As you can see in our [Contributing guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code), Github issues are for flagging errors in the app, and Github Discussions are to discuss feature requests. For that reason, I'm closings this issue and moving our conversation to the Discussion.

**Comment by h908714124** [comment]
@malmstein 
Please consider reopening. This is not resolved.
I specifically asked about the location of the bookmarks data on the file system.
Could you please keep the issue open, at least until that question has been answered.

**Comment by malmstein** [comment]
@h908714124 where in this issue are you asking about the location of the bookmarks data on the file system? I struggle to find that information on the issue description.

It seems to be that what you'd like is to have the ability to export bookmarks, and avoid losing them if you change phones. For everything related to that feature request, we have the Discussion as mentioned above.

**Comment by h908714124** [comment]
Understood. To clarify my intention, I will open a new issue where I explicitly ask about the location of the bookmarks data on the file system, and nothing else. Thank you
