### ISSUE TITLE
Please provide the location of the bookmarks data on file system

### ISSUE THREAD

**Issue by h908714124** [duckduckgo/Android#1193]
**Describe the bug**
After using the DDG app for about 2 years, I have around 1000 bookmarks stored inside it.
All of these will be lost when I eventually switch phones, or my old phone stops working.
A known method to extract these bookmarks from my phone is urgently needed, in order to avoid data loss.

**How to Reproduce**
1. Install DDG app
2. Add some bookmarks
3. Notice there is no way to backup your data

**Expected behavior**
Instructions to locate the bookmarks data on the Android file system should be provided,
to enable manual backups or recovery.

**Smartphone**
 - DDG App Version: 5.80.0
 - Device: Pixel 2 XL
 - OS: Android 11

**Comment by malmstein** [comment]
@h908714124 all your bookmarks are stored in Room database, unfortunately that file can't be accessed. The good news is that we've just opened https://github.com/duckduckgo/Android/pull/1211 that will allow you to Import / Export bookmarks in the very near future.
