### ISSUE TITLE
Please add dark theme feature for webpages too

### ISSUE THREAD

**Issue by ganesh903** [duckduckgo/Android#1201]

**Comment by malmstein** [comment]
@ganesh903 as part of the [Contribution guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md ) state this belongs to [Github Discussions](https://github.com/duckduckgo/Android/discussions).

There's also a discussion there about this very topic https://github.com/duckduckgo/Android/discussions/1180, so I'll close this one out.
