### ISSUE TITLE
Browser Closes Automatically

### ISSUE THREAD

**Issue by oldphones68** [duckduckgo/Android#1213]
**Describe the bug**
Browser closes automatically. 

**How to Reproduce**
1. Work some 20-30 minutes
2. See error

Theme - Black , Auto clear option - Off.
It happens suddenly. Then after that, when reopened, browser works 30-40 minutes without any problem. Then it happens again and (with less interval), again.

___I've needed to write this issue two times for this reason.___

**Expected behavior**
Browser should not close automatically.

**Smartphone (please complete the following information):**
 - DDG App Version: (e.g. 5.85.0)
 - OS: Android 6

I can assure that, ***neither*** automatic system cleaning ***nor*** the in-browser automatic cleaning is enabled.

**Comment by cmonfortep** [comment]
@oldphones68 when the browser closes automatically, do you see any error in the screen?

**Comment by oldphones68** [comment]
@cmonfortep 
No.
Nothing at all. No glitches, no flash, no error message before, during or after closing.

If I reopen, the tabs I was working, those loads again.

**Comment by oldphones68** [comment]
@cmonfortep Today it was happening just few moments ago.
At this time, it was closing just right after opening.
Cleared the cache from system manager, no improvement.
Then restated the phone, then the problem has stopped.

**Comment by cmonfortep** [comment]
Thanks @oldphones68 for reaching us again to inform the issue disappeared after restarting the phone. Usually those unexpected and random bug/crashes are related to the webview component and are difficult to reproduce. Let us know if it happens again. Thanks

**Comment by oldphones68** [comment]
It has reduced to a significant extent.
But, sometimes it happened again. After automatic closure, I have to re-open.
But, on that day, it was happening repeatedly, so I restarted the phone.
By the way, thanks for responding. 
@cmonfortep
