### ISSUE TITLE
Touch events

### ISSUE THREAD

**Issue by qwerty193** [duckduckgo/Android#1226]
Absolutely positioned DIV-element has touch events and uses **ev.preventDefault()** in touchstart & touchmove functions. But seems that it bubbles / propagate events all the way to body-element and thefore scrolls the window.

Nothing helps, not _preventDefault_ nor _stopProgation_ nor _stopImmediatePropagation_.

Same code have always been working in every other browsers.

**Comment by cmonfortep** [comment]
Please use our GitHub templates so we can understand better your request. Thanks.
