### ISSUE TITLE
FR: Domain Highlight

### ISSUE THREAD

**Issue by mimi89999** [duckduckgo/Android#1230]
In some specially crafted URLs it might be difficult to identify the domain for non experienced users.

https://wiki.mozilla.org/Firefox/Features/Locationbar_Domain_Highlight
https://wiki.mozilla.org/URL_highlighting

**Comment by cmonfortep** [comment]
Thanks for reaching us. We are currently only accepting Github Issues for bug reports.

Please, use discussions to share feature requests. Only bug reports are expected to be accepted as issues. Thanks.

[Contributing guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code)

**Comment by mimi89999** [comment]
@cmonfortep I implemented this feature in Firefox Android (https://bugzilla.mozilla.org/show_bug.cgi?id=1812898) and could also implement it in the DuckDuckGo if you are willing to accept such a contribution.
