### ISSUE TITLE
Urgent

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#1231]
**Describe the bug**
So theres this bug making all DDG Browser users sick of light menus and burning our poor eyes at night.

**How to Reproduce**
1) Open the browser and go to any menu, careful you might burn your eyes or become sick due to the white menus on the dark theme

**Expected behavior**
Dont just close this request please listen to your users :'))))))

**Smartphone (please complete the following information):**
 - DDG App Version: Every build made
 - Device: Every device made
 - OS: Every OS made

 - If applicable, add screenshots to help explain your problem. (I got some, just because of your eyes)

![Screenshot_20210510-202944_DuckDuckGo.png](https://user-images.githubusercontent.com/48844761/117629857-b1d77980-b1ce-11eb-936f-f02d8c52c663.png)

![Screenshot_20210510-202934_DuckDuckGo.png](https://user-images.githubusercontent.com/48844761/117629868-b4d26a00-b1ce-11eb-9517-2a54a32aba1a.png)

![Screenshot_20210510-202926_DuckDuckGo.png](https://user-images.githubusercontent.com/48844761/117629880-b734c400-b1ce-11eb-9fbc-c1836587946c.png)

**Comment by cmonfortep** [comment]
Hi @WillHick This request is already captured under https://github.com/duckduckgo/Android/discussions/1180

I'm closing this issue as a duplicate, but we still listen to your requests :) Feel free to go there and upvote the request.
