### ISSUE TITLE
Doesn't download files correctly (file metadata?)

### ISSUE THREAD

**Issue by Ammako** [duckduckgo/Android#1239]
**Describe the bug**
Sometimes DuckDuckGo can't download certain files properly, either the file name is totally wrong or it just can't get a file name at all, and the file fails to download or it downloads incorrectly.

On F-Droid for example, downloading .apks you just get "repo.apk" instead of the actual file name. It still works and installs fine though. On GitLab, you try to download an .apk from [a project's release page](https://gitlab.com/AuroraOSS/AuroraStore/-/releases), and instead of getting the properly named .apk (AuroraStore_4.0.5.apk in this example), you get a .zip named after the owner of the repository (AuroraOSS.zip in this example.) You can rename it from .zip to .apk and it works fine, though. In contrast, downloads from GitHub releases work perfectly. 👍

Then on my government's website, when I go to download my proof of vaccination I get no file name DuckDuckGo just sits at "downloading" with no progress bar. Eventually it goes through and I get a file that's just a random string of letters and numbers, with no file extension. Knowing that it should be a pdf from having downloaded it using a different browser though, I can add .pdf at the end and the file is actually fine, DuckDuckGo just fails to get any information about the file at all (filename, file type, file size.)

In the case of some other sites, downloads just fail entirely. This used to be the case on GitLab, it was impossible for me to download anything from GitLab releases before. It seems to "work" now though, so I'll have to get back to you if I see something else that fails to download.

**How to Reproduce**
1. Go to a page for a file that is affected by this ( GitLab or F-Droid release pages for instance)
2. Click on the download link or file name for the file
3. App fails to get the proper information for the file and downloads it incorrectly, and in some cases downloads simply fail entirely.

**Expected behavior**
Should be able to download files correctly.

**Smartphone (please complete the following information):**
 - DDG App Version: 5.85.3
 - Device: Nexus 5
 - OS: Android 7.1.2

**Comment by cmonfortep** [comment]
Thanks for so thoughtful description, we really appreciate the effort. We are aware of this issue and we have plans to provide a fix in the near future.

We are tracking the bug under this issue here (https://github.com/duckduckgo/Android/issues/1018#issuecomment-745330878). 

Closing this as issue as the fix for https://github.com/duckduckgo/Android/issues/1018#issuecomment-745330878 will address this problem too.
