### ISSUE TITLE
Polish translation - small typo in Settings

### ISSUE THREAD

**Issue by grzechuzet** [duckduckgo/Android#1259]
**Description**
In main menu phrase "Bezpiecza witryna internetowa" missing letter 'n' in the first word. Correct is 'Bezpieczna ...'

**Steps to reproduce the behavior:**
1. Open App and click Seetings.
2. Menu list is displayed.
3. On the menu options list is **"Bezpiecza witryna internetowa"**

**Expected behavior**
Correct phrase is **"Bezpieczna witryna internetowa"**

**Smartphone:**
 - DDG App Version: 5.86.2 (58602)
 - Device: Motorola G9 Power
 - OS: Android 10
![Screenshot_20210531-075411](https://user-images.githubusercontent.com/33828523/120148638-d54b7e00-c1e8-11eb-862a-87f30c595c52.png)

P.S. Sorry I didn't just do PR but I don't have a way to test the app currently before PR.

**Comment by cmonfortep** [comment]
Thanks, I've fixed the wrong copy in our translations system. The copy should be fixed in one of our next releases.
