### ISSUE TITLE
Mega & Github: No Site Support

### ISSUE THREAD

**Issue by ChiIllHOLA** [duckduckgo/Android#1262]
![194781567_160411022644725_1877929870516217824_n](https://user-images.githubusercontent.com/84558486/120266322-3b60ff80-c2d4-11eb-99c5-f1e4547e065b.jpg)

![194398965_208391554453430_7524698977220459667_n](https://user-images.githubusercontent.com/84558486/120266321-3b60ff80-c2d4-11eb-9fde-14fe78fe3928.jpg)

**Describe the bug**
I chose Duckduckgo browser because it's very lightweight, it has a lot of privacy and security features, and is minimal in requirements when it comes to permissions. However, when I try to visit sites such as Mega or even Github, it recognizes the browser as outdated (I'm on the latest version as of writing this), or either unsupported meaning I can't even access the site anymore. It forces me to switch to another browser it recommends which is really inconvenient since I do most of my browsing on it :(

**How to Reproduce**
With my current setup, all visits to aforementioned sites leads to an error stating that the browser is either outdated or unsupported even though it's based on Chromium. 

**Expected behavior**
If you visit either Github or Mega, it blocks all access to the site forcing me to change to another browser. This could theoretically happen to other sites as well that don't support the browser's current configuration. 

**Smartphone**
 - DDG App Version: 5.86.2
 - Device: Redmi 4
 - OS: Android 6.0.1

**Comment by WillHick** [comment]
Ive just checked this and can not replicate the issue (Android 11, Latest DDG Version). There is a high chance that it could be due to your Android version you said youre on (6.0.1) as features in WebView might be outdated.

**Comment by ChiIllHOLA** [comment]
I was hoping you wouldn't say that. Just one more question, what version of Chromium is the browser using? Does it have anything to do with other browsers being able to access those sites?

**Comment by WillHick** [comment]
Version 90.4 (WebView Latest Build) and Have not had this issue on other browsers (E.g. Firefox, Chrome, Kiwi etc)

**Comment by WillHick** [comment]
Remember the DuckDuckGo Browser is built off WebView, a smaller version of Chrome's Webkit, Just like Firefox has GeckoView

**Comment by ChiIllHOLA** [comment]
That's weird. Welp, thanks for the help!

**Comment by WillHick** [comment]
Try update WebView via the Playstore (or install the Beta) there is also the Bromite WebView you can install if that helps (via there website) (You can remove this devs if I cant refer the Bromite WebView) 🤟

**Comment by Ammako** [comment]
To clarify: this browser doesn't use any specific version of Chromium webview; it runs off the one you have on your device.
