### ISSUE TITLE
Opening a background tab and going back to tabs makes tabs window to scroll to top

### ISSUE THREAD

**Issue by eccul** [duckduckgo/Android#1273]
**Describe the bug**
Opening an uncached/not loaded/background page in tabs window and then going back to tabs seems to scroll it to the top which may get annoying if you have a lot of tabs open

**How to Reproduce**
The most reliable way would probably be..
1. Open some page and open a new background tab from there
2. Return to tabs 
3. Enjoy the scroll

**Expected behavior**
Tabs window should stay at the same position you are opening the link from, as it has been in previous builds

**Smartphone (please complete the following information):**
 - DDG App Version: 5.87.0
 - Device: Xiaomi Redmi 8
 - OS: Android 10

**Comment by cmonfortep** [comment]
@eccul I'm trying to reproduce this issue, but it seems to work for me. So let me double check with you if I understand the steps you posted there.

1. Open some page and open a new background tab from there -> I have multiple tabs open. From any tab, I long click a link and then I select "Open in Background tab"
2. Return to tabs
3. Enjoy the scroll -> In my case, the tab selected is the one where I was and I don't need to perform any scroll. 

am I missing any step? thanks

**Comment by eccul** [comment]
Thanks for trying to reproduce this! I think a consistent way to repro this is:
1. Let's assume you have a handful of tabs opened. Focus on a tab from somewhere in the middle (from my testing, there's no issue with tabs at the bottom) 
2. Close the app and reopen it
3. Return to tabs

But generally you should be able to reproduce whenever you open a non-loaded page and return to tabs, or open a background tab from such page.

**Comment by cmonfortep** [comment]
Does it still happen in the latest release (5.88.0)? I managed to reproduce the issue on 5.87.0 but not in the latest one.

**Comment by eccul** [comment]
Yeah, I've been on 5.88.0 all this time, so I can reproduce on latest.

**Comment by michaldrabik** [comment]
Hi all - just going to jump in on this one. I'm also able to reproduce it on 5.88.0
Attaching video: https://drive.google.com/file/d/1YJfP-jeKJaCTv4NwBZxvq6AuaJ42nxi9/view?usp=sharing

To be honest I'm not sure that this is related to background/cache loading etc. It seems like Recycler / UI thing. It's not in a video but I am also able to notice a moment the list scroll up even before new tab slides in from the bottom. I would need to take a peek into the code to verify any of this.

**Comment by cmonfortep** [comment]
Thanks, we have created a task to investigate the bug and try to fix it.

**Comment by michaldrabik** [comment]
Thanks @cmonfortep seems to be working fine now. Not ideal though. Using `.post { }` is an obvious quick fix but the list will still jump around. If you select tab tile that's currently at the top of the list and then "go back" (as the Activity is actually recreated) the Recycler will scroll to it's bottom. 

It's just slightly annoying, no big deal. I see current implementation and see how this might be a little bit more tricky to do 100% perfect.

Thanks again.

**Comment by eccul** [comment]
Hey, don't know if it matters, but seems fixed in 5.89.1 as I can't repro anymore. (:

**Comment by cmonfortep** [comment]
@eccul Thanks for reaching us to confirm the issue was fixed. We included a fix in our latest release. 👍
