### ISSUE TITLE
Ads not blocked / extension support

### ISSUE THREAD

**Issue by Github-com-foss** [duckduckgo/Android#1281]
**Describe the bug**
Ads block does not work in most of websites eg.youtube,imbd. Or please add extension support like ublock origin. Pls block the redirect links goes to some unwanted sites.

**Comment by cmonfortep** [comment]
Hi @Github-com-foss

Related to your first comment "Ads block does not work in most of websites": we only block third-party ads that we consider to be tracking our users. Internally we use the domain list provided by https://github.com/duckduckgo/tracker-radar

Related to your feature request "add extension support like ublock origin": We are currently only accepting Github Issues for bug reports. So please, use discussions to share feature requests.

[Contributing guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code)
