### ISSUE TITLE
ads not blocked

### ISSUE THREAD

**Issue by NSTAdventure** [duckduckgo/Android#1287]
here is url of the ads that not blocked by ddg:
https://click.a-ads.com/1648168/100233/

this ads appear while I visit this web:
https://techyneed.com/wp/how-safe-is-your-job-here-are-7-signs-that-are-career-red-flags/

well pls add click.a-ads.com to blacklist so next time this ads are blocked by ddg browser @duckduckgo

thanks 😊

**Comment by cmonfortep** [comment]
Hey @NSTAdventure, thanks for taking the time to write this.

We block ads that we consider to be tracking our users. For that, we consume the dataset provided by https://github.com/duckduckgo/tracker-radar If you think that domain should be added to the block list, feel free to ping the team in that repo. Thanks.

**Comment by NSTAdventure** [comment]
> Hey @NSTAdventure, thanks for taking the time to write this.
> 
> We block ads that we consider to be tracking our users. For that, we consume the dataset provided by https://github.com/duckduckgo/tracker-radar If you think that domain should be added to the block list, feel free to ping the team in that repo. Thanks.

wait don't close this yet i will try to report that just wait :)
