### ISSUE TITLE
FLoC on DDG browser?

### ISSUE THREAD

**Issue by runboy93** [duckduckgo/Android#1289]
DDG extension and search does not allow FLoC, but what about DDG browser?

**Comment by cmonfortep** [comment]
Thanks for reaching us. We are currently only accepting Github Issues for bug reports.

We posted an article related to FLoC in our website. If you are interested, you can read it [here](https://spreadprivacy.com/block-floc-with-duckduckgo/).

Check out our [contribution guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contributing-to-duckduckgo) to know more details. There's a specific section about how to send feedback, questions, or security reports. Thanks.
