### ISSUE TITLE
Section to view all Downloads is needed

### ISSUE THREAD

**Issue by Lalisfeed** [duckduckgo/Android#1295]
It becomes hard for a user to view 👀 all the downloads made using the DDG Browser when there is no downloads section.

Since the browser has feature to download files from any site, I think there must be a download section like the bookmark section to view all downloads made at one place.

Would you please add it?

**Comment by cmonfortep** [comment]
Thanks for reaching us. We are currently only accepting Github Issues for bug reports.

Please, use discussions to share feature requests. Only bug reports are expected to be accepted as issues. Thanks.

[Contributing guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code)
