### ISSUE TITLE
News/Info Scrolling, Triggers Loading Bar

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#1307]
Issue:
 • Progress Bar, starts twitching/showing when navigating web content.

Expected:
 • Holding/Scrolling shouldn't cause progress bar (Loading Bar) too twitch/load on the Toolbar, when navigating.

Reproduce:
 • Go to "google.com" for example search "news" etc and navigate across news title in the horizontal layout.

Proof (MP4 Video):
https://user-images.githubusercontent.com/48844761/124402565-24a34200-dd85-11eb-9f81-2cfd03d66658.mp4

Device:
 • Samsung A72
 • Android 11
 • DDG Latest Version

**Comment by cmonfortep** [comment]
I've been investigating the issue and I don't see a clear fix for this one. We rely on WebView events, and that news feed it's triggering a callback that indicates loading progress.

We are going to discard fixing this issue for now, that may change in the future if we get enough user feedback or we see the issue happening in more sites than expected.

Thanks for reporting it.

**Comment by WillHick** [comment]
👍👍
