### ISSUE TITLE
Tilde (~) shown instead of number of tabs >99

### ISSUE THREAD

**Issue by Jonta** [duckduckgo/Android#1331]
**Describe the bug**
When >99 tabs are open, the number disappears, and is replaced by the ~-symbol

**How to Reproduce**
1. Open >99 tabs
2. See that you now don't know how many tabs are open anymore

**Expected behavior**
a. Shows number of tabs that are open (going beyond bounding box if necessary. I know it makes screenshots uglier, but it's still more informative than "~". And yes, that's better than what Firefox and Chrome are currently using as symbols, but just as uninformative). Or
b. Shows 1st 2 digits of number of tabs open, with apostrophe at the end, e.g. `59'` for 592 tabs. Or
c. Shows number of tabs somewhere else. Or
d. Elongate that bounding box. There's sooo much room on both the left and right sides of this thing

It's right here: https://github.com/duckduckgo/Android/blob/c38e39e4b962725c36f7143b2ab0a7d6873f3501/app/src/main/java/com/duckduckgo/app/browser/TabSwitcherButton.kt#L39

Volunteer your non-technically inclined grandparents who could _not_ improve that line to my liking. I dare you! =)

**Emotional appeal start**

Now.

Why. Why should y'all do this?

I've had hundreds of tabs open at the same time for well over a decade. If your mind boggles at that: Congratulations. You're more normal in this regard than I am.

- Different people work differently
- If y'all want to hint at me that I've got a lot of tabs open, go for the box-breaking solution: Boom. You're already doing it. I can see that this box ain't big enough for that number
- Ditto the apostrophe-solution
- Who uses DDG-browser? Unusual people. Who has >100 tabs open on mobile? Unusual people
- Competition: What are they doing? The same thing. Such a small thing to get ahead of them on
- Chrome on mobile: last time I tested it (not synthetically), I could have >600 tabs open at the same time before I noticed performance issues. Not a flagship phone, but a ~$200 one. >3 years ago. That's great! And I'm guessing DDG could do the same. But when I finally Do The Right Thing™, that the people shocked at the number of tabs really want me to do, I want a progress indicator. Gimme dopamine, baby
- Firefox lets me know by having synced tabs -> Open here -> "Do you really want to open 361 tabs?"
- Bookmark export/import: I know about it. Doesn't come close enough to solve this problem

I dislike reading long things like this

I wrote it, because I thought it would significantly improve the chance of this being taken seriously. What with the time and thought I've put into it

"It'll be ugly!" - We're technical enough to know. And we probably know that we're in the minority. But we still exist. We still use these browsers. And after a decade, I at least, seem unlikely to change. How many people even _know_ that DDG uses ~ for >99? Exactly. Just the people who've seen the code, and those who've surpassed 99 tabs. If you have 99 tabs, then counting them is not one of your problems. And it shouldn't be at 100 either. Or 1000. Two numbers that now look identical, even though they're so far apart.

Instead: "It'll be impressive!" - And what an easy thing to impress people with. "Look at DDG browser! You can have 10 times as many tabs open in it, by the looks of it. No snarky smileyface or useless infinity-symbol there, just a nice, informative "658"."

I'm sure there are people who would be fascinated to know all about "how do you even _use_ a browser when you have that many tabs", but I'm not going to expand upon it here.

Thank you for maintaining DDG for Android.

**Emotional appeal end**

**Smartphone**
n/a

**Comment by Akshit6828** [comment]
Well, I think we can show the first two digits ending with a ` .` (dot) signifying a short form of  `....` (too many dots).

#### Points to be considered:
- [x] It is more human-understandable.
- [x] It won't look ugly even in screenshots.


Eg: 
* 1000 can be shown as `10.` 
*  5555 can be shown as `55.`


### If this fits well, can I contribute to it?

**Comment by Akshit6828** [comment]
Please check #1333  and let me know if any changes are required. 😃

**Comment by aitorvs** [comment]
Thanks @Jonta for flagging this. This is however more a feature request than a bug. For those you can open a [Discussion](https://github.com/duckduckgo/Android/discussions) (see our [contributing guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md))

Closing this issue for now.
