### ISSUE TITLE
Req: Export/dump currently open tabs/URLs

### ISSUE THREAD

**Issue by Jonta** [duckduckgo/Android#1332]
**Describe the bug**
Got [a lot of tabs](https://github.com/duckduckgo/Android/issues/1331) open, can't sort through them on a proper computer without doing a bunch of manual work

**How to Reproduce**
1. Open a lot of tabs
2. Bookmark none of them
3. Realise you want to keep these
4. Sigh

**Expected behavior**
"Bookmark all open tabs"-feature, and then exporting it. Seems like the most DDG-esque way of going about it, seeing as [it was added recently](https://github.com/duckduckgo/Android/discussions/1170)

(It's possible in Firefox on Desktop, per-window: Ctrl+Shift+D)

**Smartphone**
n/a

**Comment by cmonfortep** [comment]
Thanks for reaching us. We are currently only accepting Github Issues for bug reports.

Please, use discussions to share feature requests. Only bug reports are expected to be accepted as issues. Thanks.

[Contributing guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code)

**Comment by Jonta** [comment]
Discussion started at https://github.com/duckduckgo/Android/discussions/1383
