### ISSUE TITLE
Allow downloads in referer links.

### ISSUE THREAD

**Issue by Kita2345** [duckduckgo/Android#1336]
**Describe the bug**
Go to https://dl.twrp.me/guacamole/twrp-3.5.2_9-0-guacamole.img.html and try to download the .img file.

After download the file is 6,71KB instead 34,04MB, because the browser downloads the HTML instead of the .img file.

**Comment by cmonfortep** [comment]
Hi, could you use the bug template to report any issue? It will be good to know app version, android version, etc.. and any screenshot/video will be very useful too.
I will close this one as invalid, please reach to us again.

Please use our GitHub templates so we can understand better your request. Thanks.
