### ISSUE TITLE
Weird RTL behaviour.

### ISSUE THREAD

**Issue by Endem10n** [duckduckgo/Android#1340]
**Describe the bug**
Strange feel and look if any of RTL locales is switched on.

**How to Reproduce**
Steps to reproduce the behaviour:
1. Go to device settings.
2. Select any RTL language as system language (Arabic, Hebrew, Persian, Urdu, e.t.c.)
3. Launch DuckDuckGo.
4. Go to settings screen, go to some other screens.
5. You will see quite strange UI with some layouts mirrored, some not, with strange aligned English text.

**Expected behaviour**
Back icon at ActionBar should be mirrored, if RTL is on. As we at current moment app do not have any translation to any of RTL languages, looks like it's better to switch off RTL support flag in manifest. If not, looks like at least layout bug in "app icon" line in settings should be fixed not to overlap icon and text.

**Smartphone (please complete the following information):**
 - DDG App Version: 5.91.0 (59100) (Google Play build).
 - Device: Vivo Y11s (reproducible on any device with at least one RTL locale in device settings)
 - OS: Android 11 (reproducible on any supported Android version)

![Screenshot_٢٠٢١٠٧٢٨_٢٢٣٠٣٥](https://user-images.githubusercontent.com/86627724/127396258-39a81bf8-1c2b-4c6a-a5c0-3fb77b3d09fa.jpg)
![Screenshot_٢٠٢١٠٧٢٨_٢٢٣٠٤٩](https://user-images.githubusercontent.com/86627724/127396282-de76032e-a168-4c03-91dc-1c34c5d59df8.jpg)
![Screenshot_٢٠٢١٠٧٢٨_٢٢٣٥١٢](https://user-images.githubusercontent.com/86627724/127396295-1c0ff3cd-e816-471f-b46a-9df09de79cf9.jpg)
![Screenshot_٢٠٢١٠٧٢٨_٢٢٣٦٤٩](https://user-images.githubusercontent.com/86627724/127396304-b7c99050-fda9-4925-b4ad-1b11244520c3.jpg)
![Screenshot_٢٠٢١٠٧٢٨_٢٢٣٨٥٧](https://user-images.githubusercontent.com/86627724/127396324-d12be5a2-6848-4bcd-9e4d-738c3593401d.jpg)

**Comment by cmonfortep** [comment]
Thanks @Endem10n for reporting this issue. We are aware of this problem, however, the list of languages we support is limited (see [full list here](https://github.com/duckduckgo/Android/blob/develop/TRANSLATIONS.md#list-of-languages)) and we don't currently support any RTL language. We would love to support as many languages as possible, but we are still a small team. 

In any case, I encourage you to open a discussion if you would like to get support on any specific language, OR send us Feedback ([see how](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#share-feedback)). That way we can get an idea of how many users are interested in any specific topic and we will prioritize accordingly.
