### ISSUE TITLE
URLs trigger search engine search instead of loading site

### ISSUE THREAD

**Issue by oldphones68** [duckduckgo/Android#1346]
**Describe the bug** 
Many times when I try to open a site typing the address - instead of going to the site, the browser goes for a DDG search.

**How to Reproduce**
1. Go to 'address bar'
2. Type 'bing.com' or 'youtube.com'
3. See error

**Expected behavior**
How about implementing something like this:
IF
the input has a period (I mean full-stop) AND there is NOT any space before OR after the period
THEN
consider this as a website address and go to the site
ELSE IF
there is no site found in the address
THEN
consider this input as a search string or keyword AND do a search in the search engine.

**Smartphone**
 - DDG App Version: 5.92.0
 - OS: Android 6.

**Comment by malmstein** [comment]
Hey @oldphones68, I just tried to reproduce this but I can't. Could you update a video of this behavior? 

https://user-images.githubusercontent.com/531613/129531941-4b9437a4-3c03-40a8-a0ee-642d490af98c.mp4

For context, https://github.com/duckduckgo/Android/blob/develop/app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoRequestRewriter.kt already takes care of the logic you mentioned.

**Comment by oldphones68** [comment]
@malmstein I got the issue.

When we select from the suggestions and when the magnifying glass icon appears left to the suggestion, it goes for DDG search instead of directly going to that site.

How will it be, even if choosen from suggestion, it will go to the site?
Is that a feasible solution?

It may become helpful when in search bar we misspel a web address. 

https://user-images.githubusercontent.com/51379704/130001303-1b0e3c79-757a-4d45-8f41-5104c1651484.mp4
