### ISSUE TITLE
Swipe to next/previous tab

### ISSUE THREAD

**Issue by fabianMendez** [duckduckgo/Android#1355]
It would be cool to be able to switch to the next or previous tab by swiping on the address bar. This is a common feature implemented in other browsers like Chrome or Firefox.

**Comment by cmonfortep** [comment]
Thanks for reaching us. We are currently only accepting Github Issues for bug reports.

Please, use discussions to share feature requests. Only bug reports are expected to be accepted as issues. Thanks.

[Contributing guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code)
