### ISSUE TITLE
Greek accented characters don't display on search results

### ISSUE THREAD

**Issue by ugggf** [duckduckgo/android#136]
Hi there. I'm using the DuckDuckGo app on an Android 4.2.2 smartphone. When searching with greek words the results fail to display greek accented characters - instead they're replaced with a box. The same characters are correctly shown in the search input bar. Here's a screenshot:

![screenshot_2014-11-16-18-56-37](https://cloud.githubusercontent.com/assets/8597179/5069786/c9fcce90-6e67-11e4-8336-bc19538bb5f5.jpeg)

I suppose it's a matter of the font type and encoding used in the app but it seems that I cannot change it.

Thanks for your attention.

**Comment by thm** [comment]
marking complete as this seems to be fixed

![screenshot_2015-10-12-11-06-42](https://cloud.githubusercontent.com/assets/1379822/10424675/7762b240-70d1-11e5-97b5-5696e4e8daec.png)
