### ISSUE TITLE
[Bug] Colors get replaced in Dark mode

### ISSUE THREAD

**Issue by RiedleroD** [duckduckgo/Android#1377]
### Describe the bug

This has obviously been implemented on purpose, but it's really nasty. I'll explain what I mean.

Basically, when dark mode is on, duckduckgo replaces some of the text colorations and background colorations with an inverted or otherwise modified variant. This breaks… pretty much every moderately complex website. I've done a bit of testing here: https://riedler.wien/music/testing.html, maybe this small site of mine can help you guys. 

### How to Reproduce

Go to any site that has a very dark or very light text color or a very light background

### Expected behavior

colors get displayed as they should, according to HTML standards (or CSS standards, maybe both, I haven't checked)

### Environment

```markdown
- DDG App Version: 5.92.1
- Device: Xiaomi Mi Mix 3
- OS: MIUI EU 12.0.3 (Android 10)
```

**Comment by malmstein** [comment]
@RiedleroD when you choose Dark theme in Settings, we only apply changes to our UI elements. `WebView` and the websites displayed in them are not modified by that selection. 

There is however a proposal https://github.com/duckduckgo/Android/pull/1314 to apply dark theme to websites, but it's still under review

**Comment by RiedleroD** [comment]
mate, have you even opened the link I sent you? ddg isn't the only mobile browser that does this, but the list doesn't seem to correlate to which browsers use webview. I could use a bit of help from an expert here, regarding which project I should submit this issue to, if not to ddg.

![screenshot of how this site looks on my end](https://user-images.githubusercontent.com/57227431/129532358-c05c0e1c-623d-4404-98f9-8dec9e53f35d.jpg)
