### ISSUE TITLE
Fix The Menu Size

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#1388]
After the latest update, ive seen the menu has been resized but has gotten really small and looks really odd 🤣 any plan to fix this as ive got a bigger phone and looks terrible

![Screenshot_20210819-154842_DuckDuckGo.png](https://user-images.githubusercontent.com/48844761/130004696-4e0e0fed-1cab-4154-8cd3-f28227b46bea.png)

**Comment by malmstein** [comment]
@WillHick this is the desired size and won't be making any changes. We are continuously looking for feedback, and if this becomes an issue we will review it, however that's not the case for now.

**Comment by WillHick** [comment]
> @WillHick this is the desired size and won't be making any changes. We are continuously looking for feedback, and if this becomes an issue we will review it, however that's not the case for now.

Damn, it even got 3 likes 🤣 would be nice to see it just a bit bigger

**Comment by Ammako** [comment]
It looks a lot nicer with the changes from 5.95 at least

**Comment by WillHick** [comment]
> It looks a lot nicer with the changes from 5.95 at least

Much agreed bro
