### ISSUE TITLE
Burn menu is not showing 'Cancel'

### ISSUE THREAD

**Issue by oldphones68** [duckduckgo/Android#1390]
### Describe the bug

When pressing the burn menu, only "Clear All Tabs and Data" is showing.
'Cancel' is not appearing!

### How to Reproduce

Click on 'Burn Icon'
See error.

### Expected behavior

'Cancel' should appear.
![IMG_20210821_183100](https://user-images.githubusercontent.com/51379704/130321927-0f49fd26-2a88-4fba-9ba6-1e9bd9c72652.png)

### Environment

```markdown
- DDG App Version: 5.94.3
- OS: Android 6.0
```

**Comment by oldphones68** [comment]
It happens in the dark mood.

**Comment by oldphones68** [comment]
It happens when the dark theme is applied to the browser.

**Comment by Shawlaw** [comment]
@4shutosh I see, but after I did some analyzation on this bug I found it is not a complex bug.
So I created a PR try to fix it.
I think this can somehow help make DuckDuckGo a better app and also can help anyone who wants to know more about the bug.

**Comment by malmstein** [comment]
This is solved by https://github.com/duckduckgo/Android/pull/1394

**Comment by oldphones68** [comment]
Thanks! When the update may go live via G Play Store? @malmstein

**Comment by malmstein** [comment]
> Thanks! When the update may go live via G Play Store? @malmstein

@oldphones68 I'm guessing next week, there are a couple of big features being added. Check the [Releases page](https://github.com/duckduckgo/Android/releases) to make sure.
