### ISSUE TITLE
Option to use system default theme and respect Android values

### ISSUE THREAD

**Issue by vatonbero** [duckduckgo/Android#1397]
### Describe the bug

Android 10 allows you to toggle system theme between light and dark and Android 11 added option to schedule theme change eg. you can set light theme during the day and dark theme during the evening.

One would expect DuckDuckGo browser to toggle and change themes after you change something in Android 10+ settings however that is not possible because there is only manual toggle in the app and not the option to honor and follow system defaults.

### How to Reproduce

On android 10:

- go to "Settings"
- go to "Screen"
- Toggle "Dark theme"

### Expected behavior

One would expect DuckDuckGo browser to toggle and change themes however that is not possible because there is only manual toggle in the app and not the option to honor system defaults.

### Environment

```markdown
- DDG App Version: 5.94.3 (59403)
- Device: Motorola One Fusion+
- OS: Android 10
```

**Comment by malmstein** [comment]
https://github.com/duckduckgo/Android/pull/1398 is taking care of this
