### ISSUE TITLE
Voice assist

### ISSUE THREAD

**Issue by ildar** [duckduckgo/Android#14]
I wonder: if the app can replace Google search, could it replace also Google Voice assist?
AFAIK free ASR are available
why not?

**Comment by SmithSte** [comment]
Well mait, I can do some voices. The acting/actor part. Reproducing sounds, beats.

Nothing more. 

Contact me if you need.

Bye

**Comment by SmithSte** [comment]
If you are wondering, why I'm saying that. It might not replace it/or it can't replace it, but we can try to do something that can. This is my part.

**Comment by cmonfortep** [comment]
Hello @ildar  , thanks for taking the time to submit this feature request. Sorry for the late response.

After internal discussion with the team, we've agreed that there's no plan in the foreseeable future to support this request. Should this change in the future, we'll update this conversation appropriately.
