### ISSUE TITLE
ToSDR Ratings (From Site To App)

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#1410]
Issue :
For alot of sites the ToSDR rating isnt the same as the site, example Facebook is rated as a C+ in the browser is but on ToSDR it is rated at a grade E. (Also under privacy practices for Facebook for example there is very few listed in app but on ToSDR there are alot displayed)

**Grades Images**

Photo - (DDG Grade)
![Screenshot_20210906-141157_DuckDuckGo.png](https://user-images.githubusercontent.com/48844761/132150993-8342475a-1798-41a9-94fc-633a316be955.png)

Photo - (ToSDR Grade)
![Screenshot_20210906-141220_DuckDuckGo.png](https://user-images.githubusercontent.com/48844761/132151060-6726bc32-3df1-426e-af0f-19f1c92f82d3.png)

**Privacy Practices Images**

Photo - (DDG Practices) (Very Little Shown)
![Screenshot_20210906-142010_DuckDuckGo.png](https://user-images.githubusercontent.com/48844761/132151592-0170973f-bc11-4e9d-a123-6e571894d9b6.png)

Photo - (ToSDR Practices) (More Listed)
![Screenshot_20210906-142003_DuckDuckGo.png](https://user-images.githubusercontent.com/48844761/132151622-5d2f9592-6bb1-4f44-8798-6b4b5918fa3d.png)

Expected :
DDG Browser to display correct Grades from  ToSDR (im aware that there is privacy protection) unsure if this changes the rating  and for the privacy practices to list all points on the ToSDR site. (All Practices shown on ToSDR to be listed in the app)

**Comment by malmstein** [comment]
@WillHick we don't display ToSDR ratings in our app, nor there is plan to do it in the foreseeable future. We calculate our own grades (you can check the code to see how), so it's normal that both grades are different.
