### ISSUE TITLE
[Bug] Dialog Fragments do not follow Dark theme

### ISSUE THREAD

**Issue by 4shutosh** [duckduckgo/Android#1411]
### Describe the bug

DialogFragments (example: from settings activity) do not follow the theming options of the app

### How to Reproduce

Open Settings Screen:
- Click on Fire Button Animation (Dark theme being enabled)
- The dialog does not follow the dark theme

### Expected behavior

- The dialog fragments should follow the app theming options

### Environment

```markdown
- DDG App Version: develop branch
- Device: Pixel 4XL
- OS: Android 11
```

**Comment by 4shutosh** [comment]
I would like to work on this issue. @malmstein Can you please assign this to me?

**Comment by malmstein** [comment]
Thanks for filing this one @4shutosh! 

I appreciate your desire to help, however we'll take this one internally. The main reason being, we need input from the Design team to decide colors and background and an internal review from different stakeholders. It would take too long to go back and forth.

**Comment by 4shutosh** [comment]
Got it @malmstein Thank you for the explanation.

I'll try to look into some issues which won't require an internal process for further continuity :)
Also please feel free to assign me any issue/task of your choice, I'll be more than happy to work on it.

**Comment by cmonfortep** [comment]
This has been already fixed and published in our latest release 5.95.0

**Comment by 4shutosh** [comment]
I've installed 5.95.0 from google playstore and this does not work foe me.
![Screenshot_20210913-225815_Settings~2](https://user-images.githubusercontent.com/53831987/133129794-056c99f1-c697-478c-9559-515000c877b8.png)
![Screenshot_20210913-225828_DuckDuckGo](https://user-images.githubusercontent.com/53831987/133129810-314335eb-ade3-453e-ba11-9fbf3aeb9629.png)

**Comment by 4shutosh** [comment]
@cmonfortep Can you please corroborate?
( Device: Pixel 5, Android 11 )

**Comment by cmonfortep** [comment]
Sorry, you are right! Thanks for the screenshot. We fixed the confirmation dialog to clear all data. 

I'm reopening the issue.

**Comment by 4shutosh** [comment]
Sure 🙌🏻  Can I please work on this issue 😄 ?

**Comment by cmonfortep** [comment]
@4shutosh 👍👍
