### ISSUE TITLE
Assistant App no longer working

### ISSUE THREAD

**Issue by AlEilers** [duckduckgo/Android#142]
Hi,  

since the last update that app supports no longer to be an assistant app (long press home button to open the search).

It's probably an easy fix. I think it would be enough to just add an intent for [ACTION_ASSIST](https://developer.android.com/reference/android/content/Intent.html).

**Comment by AlEilers** [comment]
I made a pull request (#143) that shows how i could be solved.

**Comment by CDRussell** [comment]
Fixed by #143 

Thanks for the contribution @AlEilers 👏
