### ISSUE TITLE
[BUG] Some Text Not Showing as Should

### ISSUE THREAD

**Issue by IJohnDoeI** [duckduckgo/Android#1437]
### Describe the bug

When pressing the fire button, at the bottom "Clear All Tabs..." appears but the "Close" part does not appear.

Also on certain websites bits of text does not appear, for example on dominos the amount in the basket doesn't appear. I don't know whether these are related but this is what happens.

Thank you

### How to Reproduce

This happens whenever the app is opened

### Expected behavior

Close at the bottom missing but should appear

### Environment

```markdown
- DDG App Version:5.94.3
- Device:Pixel 5
- OS:GrapheneOS
```

**Comment by cmonfortep** [comment]
Thank you for reporting that issue. We already fixed it, and it's available in our latest release. Please update your app and that bug should be gone. 🦆
