### ISSUE TITLE
[Feature] Show Bookmark Folder name on Bookmark Saved Snackbar

### ISSUE THREAD

**Issue by 4shutosh** [duckduckgo/Android#1440]
**Feature Description**
The user should be shown the folder name where the bookmark is saved, enabling it will give the user chooses to change the location at the moment of saving the bookmark.

**Comment by cmonfortep** [comment]
@4shutosh similar to my comment in https://github.com/duckduckgo/Android/issues/1439. Please open a discussion to suggest any bookmark improvement. 

More info in our [contributions guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code).
