### ISSUE TITLE
[Typo] Punctuation Mistake

### ISSUE THREAD

**Issue by migarabhanu** [duckduckgo/Android#1444]
### Describe the bug

_In the README, there is a Topic called Discuss. Under that topic, the description is written as,_

Contact us at https://duckduckgo.com/feedback if you have feedback, questions or want to chat. You can also use the feedback form embedded within our Mobile App - to do **so** please navigate to Settings and select "Leave Feedback".

_There should be a comma between the words **""so""** and **""please""**. Otherwise it can be considered as a **punctuation mistake**._

### How to Reproduce

1. Go to [README.md](https://github.com/duckduckgo/Android/blob/develop/README.md) file.
2. Check the description under the Topic 'Discuss'.
3. Fix the punctuation mistake.

### Expected behavior

_But the description under the topic 'Discuss' of the README.md should be written as,_

Contact us at https://duckduckgo.com/feedback if you have feedback, questions or want to chat. You can also use the feedback form embedded within our Mobile App - to do **so,** please navigate to Settings and select "Leave Feedback".

So by editing like that, We can solve the punctuation mistake ( the **comma** between the words 'so' and 'please' !) of the above description. 

### Environment

```markdown
- DDG App Version: 5.97.0
- Device: Dell Inspiron 15
- OS: Microsoft Windows
```

**Comment by pratik2315** [comment]
Hello sir, If this issue is still available can i work on it?
