### ISSUE TITLE
ViewBinding migration (replacing kotlin synthetics)

### ISSUE THREAD

**Issue by cmonfortep** [duckduckgo/Android#1478]
### Description
We are currently migrating to ViewBinding since Kotlin synthetics have been deprecated.

This is a great opportunity for contributors to help our Android team.

We are accepting contributions to remove kotlin synthetics usages and replace them by using ViewBinding.

Inside our codebase, we have already migrated a bunch of classes that you can use as a reference:
- Fragments: InitialFeedbackFragment, ShareOpenEndedFeedbackFragment, etc.
- Dialogs: DaxDialog
- RecyclerView.ViewHolder: AppIconsAdapter,SearchSuggestionViewHolder, BookmarkSuggestionViewHolder,
- CustomView: TabSwitcherButton

### How to work on this issue

But there are still some pending migrations.
- Fragments: EmailAutofillTooltipFragment, SavedSiteDialogFragment, DefaultBrowserPage, WelcomePage, BrowserTabFragment, DownloadConfirmationFragment
- Dialogs: FireDialog
- Adapaters: BookmarksAdapter, FavoritesAdapter, BookmarkFolersAdapter, FavoritesQuickAccessAdapter, etc...
- CustomView: TrackerNetworkLeaderboardPillView

**Just leave us a comment** that you would like to work on the issue and what classes you will migrate. That will avoid conflicts with other contributions migrating the same classes.

Thanks!

**Comment by droid-it** [comment]
I would like to help with all the fragment classes. Let me know!

**Comment by mslalith** [comment]
@cmonfortep okay

**Comment by kolanse** [comment]
Is it safe to say that this issue has been resolved ?

**Comment by Zoo-M0** [comment]
Do you still need help here?

**Comment by AndroidPoet** [comment]
i have started working on classes if someone is already working on something please let me know

**Comment by cmonfortep** [comment]
You can work on any of the ones we haven't yet migrated (except browserTabFragment which we will refactor internally since it's too complex)

**Comment by AndroidPoet** [comment]
Thanks! i was bit confused about the two approched
Getter property 
![171803609-14689af6-f990-4800-9ea8-ba09b6802798](https://user-images.githubusercontent.com/13647384/171847405-4e450fc1-ade7-4314-902a-f3cee33bcaa3.png)
kotlin delegate
![171803416-78ab227c-87c5-480b-baa9-01da4c9acdcc](https://user-images.githubusercontent.com/13647384/171847413-efddb850-9140-4f4f-b901-3b21f83dd29a.png)
which one is recommended?

**Comment by GauravGupta17** [comment]
I would also also like to work on this issue , please let me know which classes i can work with

**Comment by cmonfortep** [comment]
We will continue the migration internally. Closing the issue.
