### ISSUE TITLE
home screen widget is missing

### ISSUE THREAD

**Issue by vanyasem** [duckduckgo/Android#148]
there is no home screen widget after the last update. it's useful and needs to be added back

**Comment by haloboy777** [comment]
The widget is so important for my workflow! Please bring back the widget.

**Comment by CDRussell** [comment]
Thanks for reporting this. We are actively working on bringing back the widget. It should be with you again in an update very soon.

**Comment by CDRussell** [comment]
Fixed by #150

**Comment by haloboy777** [comment]
Thank you so much
