### ISSUE TITLE
2015 Redesign Feedback: 

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/android#148]
## Initial reactions and thoughts

- Wow the pics are way bigger, but I see less per page. I'd sacrifice image size for more results per page.
- Even with bigger images, the full text (title/description) for the story isn't fully readable. In most cases, following through to the article allows you to read that, but for Reddit/Imgur you usually can't and so you miss out on the context of the image (the worst is when you rotate the display and it still gets cut off. I wish I could drag the article description down/sideways to expand it and read it all)
- I thought clicking the category of the article (top right text) would filter the results to only those kinds of articles. Would be really useful.
- Not sure why we have a "menu" button (vertical dots) for each tile when long-press shows the same content. I would expect long-press to do more or remove the button for more text space.
- Tagging the article as a picture or video (in the same manner as how we've labelled the category) would be really sweet. I usually can't tell if an article is going to link to a video or a picture or a website with more to read
- After clicking the search box while viewing an image, the article disappears. Why?
    - Tried it again, I see now that we're showing recent searches there. That wasn't clear

## Bugs:
- Woah. Holding down on the top-right "Menu" button continuously opens new copies of the menu. Caused the app to crash.
- "Recents" view seems broken?
    - Images aren't loading
    - Small grey box in top-right corner where category label/text should be
- The detail view for IA tiles adds a black line below the search box -- is that intentional?
- "View in Browser" lists DuckDuckGo app as a browser you can view in -- seems redundant
- After clicking menu button beside search box, the 3-item menu has a scrollbar that seems unnecessary (there's nowhere to scroll)
    - Seems like the links to "Recents" and "Favourites" are missing from that menu?
- Favourites section has 2 tabs, ("favourites" and "favourite searches") but both give the same description:
    - "Add searches and stories to your favourites...they'll appear here"
    - What's the difference between the tabs?

**Comment by nilnilnil** [comment]
@chrismorast @thm

**Comment by nilnilnil** [comment]
Those categories, like lighthearted, are supposed to be tappable.
