### ISSUE TITLE
[Bug] "site:" search parameter interpreted as protocol

### ISSUE THREAD

**Issue by rainbowkitty227** [duckduckgo/Android#1495]
### Describe the bug

When using a search query such as `site:wikipedia.org list of common misconceptions`, I think the app is interpreting the `site:` part as it would `http:` or `https:`.

temporary solutions:
modify search to ` list of common misconceptions site:wikipedia.org` or `!ddg site:wikipedia.org list of common misconceptions`

### How to Reproduce

1. navigate to any website
2. type `site:wikipedia.org software bug` into url bar and press enter
3. notice error: "Unable to open this type of link"

### Expected behavior

Expected to navigate to duckduckgo search results page

### Environment

```markdown
- DDG App Version: 5.98.1
- Device: motorola moto g stylus
- OS: Android 11
```

**Comment by vinc3nz** [comment]
Not able to reproduce this on my Android 10 Phone. App version: 5.125.0

**Comment by joshliebe** [comment]
This was fixed with https://github.com/duckduckgo/Android/pull/1820
