### ISSUE TITLE
[Bug] Dropdown menu items hard to read in dark mode

### ISSUE THREAD

**Issue by Ammako** [duckduckgo/Android#1513]
### Describe the bug

The text is hard to read on dropdown lists in dark mode, because the background of the popup has been changed to dark, but the text color is still black.

<details>
  <summary>Screenshot</summary>
  
  ![image](https://user-images.githubusercontent.com/43770697/137633055-0e11ce9b-6944-49d6-9373-a19bd2c4141e.png)
  
</details>

### How to Reproduce

1. Set DuckDuckGo Browser to dark mode
2. Find a page with a dropdown list (example: https://archlinux.org/mirrorlist/)
3. Tap the list to bring up the popup

### Expected behavior

Text color should probably be set to white instead.

### Environment

```markdown
- DDG App Version: 5.98.1
- Device: Nexus 5
- OS: LineageOS 14.1 (Android 7.1.2)
```

**Comment by inomag** [comment]
Hi @cmonfortep, Can I work on this issue?
