### ISSUE TITLE
[Bug] Light mode not using proper color scheme when system is in dark mode

### ISSUE THREAD

**Issue by ryg-git** [duckduckgo/Android#1520]
### Describe the bug

When  light mode is selected in browser and android system is in dark mode then light mode does not work properly.

| System theme: Light, App theme: Light  | System theme: Dark, App theme: Light | System theme: Dark, App theme: Dark |
| ---------------------------------------------------- | ----------------------------------------------------| ---------------------------------------------------- |
| ![light](https://user-images.githubusercontent.com/69393483/138712245-eb77501b-d95b-4eea-8bf9-16ed6f10f376.jpg) | ![dark](https://user-images.githubusercontent.com/69393483/138712307-89aeedac-54ca-42bc-afca-6f52aa11b154.jpg) |  ![dark](https://user-images.githubusercontent.com/69393483/138712353-712e0d59-b1f1-4345-96c9-c0196627884f.jpg)|

### How to Reproduce

1. Select light mode in browser
2. Put system in dark mode
3. observe the app

### Expected behavior

Light mode should have same color scheme regardless of system theme mode.

### Environment

```markdown
- DDG App Version: 5.99.0
- Device: Xiaomi Redmi Note 8 Pro
- OS: Android 11
```

**Comment by cmonfortep** [comment]
@malmstein assigning this issue to you. Not sure if there's something we want to address here.

**Comment by malmstein** [comment]
This was fixed but never closed.
