### ISSUE TITLE
[Bug] Download URLs with dots in the path incorrectly assumed to be the file extension

### ISSUE THREAD

**Issue by asilvr** [duckduckgo/Android#1531]
### Describe the bug

For a URL which contains the `.` character in the path, the filename extractor logic was incorrectly guessing the filename as the earlier dotted segment of the path. According to [RFC1738](https://datatracker.ietf.org/doc/html/rfc1738#section-3.3), the `.` character is not one of the reserved characters, meaning it can be used anywhere in the path.

https://github.com/duckduckgo/Android/pull/1530 targets a fix of this incorrect logic, favoring the first best guess which contains a `.` (if applicable), which would be the last dotted segment in the path.

### How to Reproduce

1. Open the browser
2. Paste any of these URLs to download a PDF (I will drop these URLs if/when the PR is merged)

- https://d1x9zcshh2aa46.cloudfront.net/abc.def/example.pdf (saves as `abc.def`)
- https://d1x9zcshh2aa46.cloudfront.net/abc.123/example.pdf (saves as `abc.123`)
- https://d1x9zcshh2aa46.cloudfront.net/123.abc/example.pdf (saves as `123.abc`)
- https://d1x9zcshh2aa46.cloudfront.net/123.456/example.pdf (saves as `123.456`)
- https://d1x9zcshh2aa46.cloudfront.net/abc.pdf/example.pdf (saves as `abc.pdf`)

3. Observe how each of the above URLs attempt to save the file by the earlier dotted segment

### Expected behavior

All of the URLs in the `How to Reproduce` steps should save as `example.pdf`

### Environment

```markdown
- DDG App Version: 5.99.0
- Device: Pixel 4
- OS: Android 11
```

**Comment by cmonfortep** [comment]
This is now available in our latest release. Thanks for the work @asilvr
