### ISSUE TITLE
Unable to download PDFs

### ISSUE THREAD

**Issue by octavo** [duckduckgo/Android#1533]
The browser is unable to download invoices (PDFs) from [matas.dk](https://www.matas.dk/) while Chrome can.

![Imagepipe_0.jpg](https://user-images.githubusercontent.com/1730033/140162561-f559f015-1beb-400e-9f38-91311317a741.jpg)
![Imagepipe_3.jpg](https://user-images.githubusercontent.com/1730033/140162612-ada4a7df-58be-433c-b39f-bed87f36bfa7.jpg)
![Imagepipe_4.jpg](https://user-images.githubusercontent.com/1730033/140162638-22bc03c5-040e-479e-8a18-20666b40d428.jpg)

**Comment by asilvr** [comment]
@octavo can you share the URL for this screenshot? I'm working on a similar (but not exactly the same) issue in https://github.com/duckduckgo/Android/pull/1530 and might be able to improve it / handle this.

**Comment by octavo** [comment]
@asilvr It has PII. You could buy something cheap and see for yourself.

https://pastebin.com/A5HE1NeA

Password is password.

**Comment by cmonfortep** [comment]
Friendly reminder: please read our contribution guidelines. Only issues labeled as "help wanted" will be accepted as contributions.

https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#what-to-expect

**Comment by cmonfortep** [comment]
@octavo I've noticed you didn't use our bug template. Do you mind updating the description or creating a new issue following the template? Thanks.

**Comment by cmonfortep** [comment]
Closing. 

I haven't been able to validate if it has been fixed by https://github.com/duckduckgo/Android/pull/1547.
@octavo feel free to resubmit the bug if this is still not working for you.

**Comment by octavo** [comment]
@cmonfortep It hasn't been fixed by #1547.

Browser version 51040000

**Comment by asilvr** [comment]
@octavo Do you mind sharing the URL with your PII replaced with dummy, equivalent data? Your suggestion to purchase something cheap is good, but it’s difficult for me to navigate the site.

**Comment by octavo** [comment]
@asilvr Chrome can translate the page for you.

**Comment by octavo** [comment]
It is the same here: https://www.campz.dk/CustomerService-ReturnLabel/

ordrenummer: CDK543357
postnummer: 2100

![img_5.jpg](https://user-images.githubusercontent.com/1730033/220334034-b8f90f1f-4c98-4ea1-93df-b1a2bb870bd2.jpg)
