### ISSUE TITLE
[Feature] Integration with Mooltipass Mini BLE

### ISSUE THREAD

**Issue by talmage** [duckduckgo/Android#1545]
I want to use the DuckDuckGo browser on my Android phone with the [Mooltipass Mini BLE](https://www.themooltipass.com/) hardware authenticator.  There is already an [open source Firefox extension](https://github.com/mooltipass/extension).  How hard would it be to integrate the DDG browser with the Mooltipass?

**Comment by cmonfortep** [comment]
Thanks for reaching us. We are currently only accepting Github Issues for bug reports.

Please, use discussions to share feature requests. Only bug reports are expected to be accepted as issues. Thanks.

[Contributing guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code)
