### ISSUE TITLE
[Bug] App crash

### ISSUE THREAD

**Issue by Donk2u** [duckduckgo/Android#1559]
### Describe the bug

Updated Android to 12.0 on galaxy s21 ultra and unable to open app. Keeps closing upon open. Cleared data and cache, updated app, Uninstalled and reinstalled with no change. Uninstalled and installed with apk not through play store with no change.

### How to Reproduce

1 launch app
2 app crashes

### Expected behavior

Expect to work

### Environment

```markdown
- DDG App Version:
- Device:galaxy s21 ultra
- OS:Android 12.0
```

**Comment by cmonfortep** [comment]
Sorry about that. It seems a Samsung related issue. I think they are releasing to some devices a beta version of Android 12 which has some bugs. I've found a thread where users are facing the same issue in multiple apps:

https://eu.community.samsung.com/t5/galaxy-s21-series/official-android-12-one-ui-4-0-installed-on-s21-ultra-5g-but/m-p/4340763
