### ISSUE TITLE
Broken text,  weird characters appearing in Readability

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/android#156]
I'm seeing broken text in our Readability view. Seems like it's improperly encoding apostrophes and and other punctuation?

**Comment by moollaza** [comment]
![2015-02-28 22 31 41](https://cloud.githubusercontent.com/assets/873785/6429439/4c8301a8-bf9f-11e4-8e95-95484453fbfd.png)

**Comment by thm** [comment]
@moollaza do you still see this appear? @sdougbrown is this a bug in the readability-view's front end?

**Comment by thm** [comment]
closing this since we're addressing this internally.
