### ISSUE TITLE
App Fails to open after Adriod 12 update

### ISSUE THREAD

**Issue by beher17834** [duckduckgo/Android#1562]
### Describe the bug

My Phone got an update: Andriod 12 and that's it. DDG does not even open after the update. Feels kind of sad because that was the only browser I used. Uninstall/reinstall made no difference. Had to take the app away. I hope this issue gets fixed soon.

### How to Reproduce

1. After Andriod 12 update go to DDG
2. Tap on the icon
3. Tries to open but fails
4. No error on the screen

### Expected behavior

To reproduce the issue, have an Adroid phone update to Adrroid 12. Mine is Samsung S21. After the update, DDG is unusable.

### Environment

```markdown
- DDG App Version: 5.102.2
- Device: Samsung Galaxy S21
- OS: Andriod 12
```

**Comment by cmonfortep** [comment]
Sorry about that. It seems a Samsung related issue. I think they are releasing to some devices a beta version of Android 12 which has some bugs. I've found a thread where users are facing the same issue in multiple apps:

https://eu.community.samsung.com/t5/galaxy-s21-series/official-android-12-one-ui-4-0-installed-on-s21-ultra-5g-but/m-p/4340763
