### ISSUE TITLE
Open a new tab

### ISSUE THREAD

**Issue by altaf933** [duckduckgo/Android#157]
Usually user want to keep live it's current tab and move to other tab to open new address.
So here we can add features like multiple tab support.

Please correct if I am not wrong.

**Comment by subsymbolic** [comment]
Thanks @altaf933! We have had many requests for tabs and are working on it right now, check out our tabs branch.

**Comment by subsymbolic** [comment]
Thanks again for your feedback. This is now done https://github.com/duckduckgo/Android/pull/219 and ready for our next release.
