### ISSUE TITLE
I'd like to suggest an alternative logo/icon...

### ISSUE THREAD

**Issue by SecularSteve** [duckduckgo/Android#1575]
Just an option for some people to make the App/Site look more "Sport-y".

Modified it myself in Inkscape, CC BY-SA 4.0 (if it's compatible):

![logo_alternate](https://user-images.githubusercontent.com/33793273/143255574-4cf68237-1fae-448c-ae9e-016cc04aa57f.png)

ZIP contains SVG and PNG...

[logo_alternate.zip](https://github.com/duckduckgo/Android/files/7596364/logo_alternate.zip)

**Comment by cmonfortep** [comment]
Thanks for sharing @SecularSteve :) 

Going to close this issue since we only accept bug reports as Github Issues.
