### ISSUE TITLE
weird change source toggle animation

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/android#158]
When scrolling, the change source toggle flips around in a weird way.

**Comment by thm** [comment]
I think this got fixed. Though now, when you tap "Reset to Default" all sources are switched off. I believe this used to switch only a number of sources off and switch most on. If not, then we should probably rename the reset-button to "Reset", "Switch all Off" or something similar. cc @fgei

**Comment by fgei** [comment]
no it should just select the stock sources, as per a clean install, if it turns off all the sources there's definitely something wrong!
