### ISSUE TITLE
App crashes on One UI 4 beta

### ISSUE THREAD

**Issue by publicclassoverflow** [duckduckgo/Android#1582]
I have been on Samsung's One UI 4 (Android 12) beta for a while and I think the app has stopped working since the beginning of their beta program. There are some discussions on Reddit as well. Do we have any plan to take a look into it?
Thanks!

**Comment by cmonfortep** [comment]
Thanks for reporting @publicclassoverflow 

We are aware of that issue, but it seems a Samsung related issue:
https://eu.community.samsung.com/t5/galaxy-s21-series/official-android-12-one-ui-4-0-installed-on-s21-ultra-5g-but/m-p/4340763

Could you share here the reddit discussion link? I could go there and post a message as well. Thanks.

**Comment by publicclassoverflow** [comment]
Thanks for the reply @cmonfortep 

Good to know that it is a visible issue. Here's the [reddit discussion](https://www.reddit.com/r/duckduckgo/comments/qzrfu7/ddg_browser_not_working_samsung_beta_4/?utm_medium=android_app&utm_source=share)
