### ISSUE TITLE
[Bug] position: fixed, height: 100% should match available visible space

### ISSUE THREAD

**Issue by veesahni** [duckduckgo/Android#1589]
### Describe the bug

When body contains a div with ```position: fixed, height 100%```, container height should match **available height** irrespective of presence or absence of address bar

Other browsers have had similar challenges in the past.  The behavior Chrome and Safari have standardized on is that ```100vh``` should be "total height ignoring address bar" and ```position:fixed, height:100%``` should be "available visible height accounting for presence or absence of address bar".  Google has discussion about this on their official blog [here](https://developers.google.com/web/updates/2016/12/url-bar-resizing) and a demonstration page [here](https://bokand.github.io/demo/urlbarsize.html)

### How to Reproduce

```html
<html>
  <head>
    <style>
      .container { 
        position: fixed;
        height: 100%;
        width: 100%;
      }
      .bottom {
        position: absolute;
        bottom: 0;
        right: 0;
        height: 100px;
        width: 100px;
        background: red;
      }
    </style>
  </head>
  <body>
    <div class="container">
       <div class="bottom" />
    </div>
  </body>
</html>
```

### Expected behavior

For ```position: fixed, height: 100%``` container height should match **available height** irrespective of presence or absence of address bar

### Environment

```markdown
- DDG App Version: 51023000
- Device: Pixel 5 
- OS: Android 11
```

**Comment by veesahni** [comment]
Might be related to this one: https://github.com/duckduckgo/Android/issues/914 which describes problems with drawing apps that are trying to fit available screen space

**Comment by cmonfortep** [comment]
That's correct @veesahni, it's 100% related to the issue you linked.

Thanks for the detailed description. However, I'm going to close this issue as duplicated, hope you are ok. Just admin work.
