### ISSUE TITLE
In-app downloader and in-app Myanmar Unicode font support

### ISSUE THREAD

**Issue by aswedaw** [duckduckgo/Android#1596]
We use China ROM phones.
The downloader is under the control of third party Xunlei Accelerator. We hate it.
Most Chinese telephone manufacturers are INTENTIONALLY producing non-Unicode phones. So, in-app Myanmar Unicode font support is essential for Indigenous Scripts (Unicode).
If not, rendering went wrong.
We need in-app Myanmar Unicode font support like First Myanmar Browser.
[https://play.google.com/store/apps/details?id=org.firstmm.browser]![SS_2021-12-02_16-52-04.jpg](https://user-images.githubusercontent.com/71079395/144403583-1e784085-2cc0-4dda-8428-ba2e162eb005.jpg)

**Comment by cmonfortep** [comment]
Sorry to hear that. However, this seems to be more a feature request than a bug report.

We are currently only accepting Github Issues for bug reports.

Please, use discussions to share feature requests. Only bug reports are expected to be accepted as issues. Thanks.

[Contributing guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code)
