### ISSUE TITLE
[Regression] Cold start time increased after using build with "App Tracking Protection"?

### ISSUE THREAD

**Issue by vatonbero** [duckduckgo/Android#1606]
### Describe the bug

Hi there,

I have updated DDG from F-Droid and jumped from version `5.98.1` to `5.102.3` on Android 10. Cold start time increased visibly and the only visible change is "App Tracking Protection" functionality.

### How to Reproduce

1. Close browser
2. Open browser

### Expected behavior

I expected that cold start time would not change.

### Environment

```markdown
- DDG App Version: 5.102.3
- OS: Android 10
```

**Comment by cmonfortep** [comment]
Thanks for the feedback, I will share it with the team so we can observe if something may be impacting the app start process.
