### ISSUE TITLE
Remove red widget

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/android#161]

**Comment by The0x539** [comment]
Why not have a red widget in a new style, just a red rectangle?

**Comment by nilnilnil** [comment]
@thm what do you think?

**Comment by thm** [comment]
The widget is designed to represent the search-field as closely as possible. I believe a red rectangle looks more like a button rather than a search-field. I would personally rather strive for one widget done well, than two widgets that evoke different actions (input vs button).

**Comment by nilnilnil** [comment]
ok, let's remove it then
