### ISSUE TITLE
[Bug] Improve Tracking Protection

### ISSUE THREAD

**Issue by PseudonymIII** [duckduckgo/Android#1625]
### Describe the bug

Hi, i found duckduckgo app need some improvements in base for ads, tracking, malware protection by adding ETP(Enhanced Tracking Protection) like Firefox or at least similar that.
I know duckduckgo still block tracking but its need improvements also in fingerprint tracking duckduckgo need improvements too.
Just look at panopticlick.eff.org

### How to Reproduce

Go to panopticlick.eff.org  and make sure enable Test with a real tracking company and click test your browser and see how much fingerprints is unique.

### Expected behavior

Protection against fingerprints tracking, ads, trackers etc

### Environment

```markdown
- DDG App Version:5.104.0
- Device: Poco X3 PRO, Redmi NOTE 8
- OS: Android 11(MIUI 12.5), Android 11(MIUI 12)
```

**Comment by cmonfortep** [comment]
Thanks for filling the template but we don't think this is a bug report. I would classify it as a feature request or feedback.

Please, use discussions to share feature requests. Only bug reports are expected to be accepted as issues. You can share feedback as well from our app. 

[Contributing guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code)
