### ISSUE TITLE
no progress bar when loading search or webpage

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/android#163]
/cc @chrismorast @fgei

**Comment by thm** [comment]
I think we can use the [default linear progress bar](http://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators) here.

@fgei If the colors are customizable, then #98c5e7 or rgba(152,197,231,1) for the background and #4495d4 or rgba(68,149,212,1) for the front look ideal to me.

![screen shot 2015-03-11 at 12 56 22 pm](https://cloud.githubusercontent.com/assets/1379822/6595836/6bde1342-c7ee-11e4-909c-f67713488269.png)

**Comment by fgei** [comment]
always on, or just when needed? with any animation?

**Comment by thm** [comment]
Just when needed. From the moment the page comes into view, to the moment the page is fully loaded.

Here's an example demo that's as close to what we need as I could find: http://cl.ly/131b031T2O0O/components-progressactivity-typesofindicators-061101_Linear_Image_xhdpi_003.mp4

**Comment by nilnilnil** [comment]
This looks like it's done?
