### ISSUE TITLE
autocomplete not working

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/android#164]

**Comment by fgei** [comment]
never working, not at all?

**Comment by nilnilnil** [comment]
If you do a fresh install, it doesn't work. Only after playing around with it for a while, it does. I'm not exactly sure how to reproduce; but I am guessing it's related to the settings default value.

**Comment by nilnilnil** [comment]
Yeah, flipping it on and off seems to make it work.

**Comment by thm** [comment]
Is this fixed? @fgei @nilnilnil

**Comment by fgei** [comment]
yes, working fine now for me
