### ISSUE TITLE
[feature request] Enable to change default search engine

### ISSUE THREAD

**Issue by Maciejfiedler** [duckduckgo/Android#1644]
i know this is duckduckgos official browser, but i really would like to search the web with startpage with this browser, because this browser is the only on fdroid that is backed by a corporation and open source.

**Comment by cmonfortep** [comment]
Thanks for reaching us. We are currently only accepting Github Issues for bug reports.

Please, use discussions to share feature requests. Only bug reports are expected to be accepted as issues. Thanks.

[Contributing guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#contribute-code)

**Comment by voxrie** [comment]
> 

it's not cool. if someone just wanna use because of layout and fast interface, it can't use because of this reason. so that's why, you should add an option.

**Comment by lippfi** [comment]
@Bruising6802 @bakinazik @username0136 I've just created a fork of DuckDuckGo that allows to change the default search engine. Feel free to check it out or add your preferred search engine via a PR - https://github.com/lippfi/SearxDuckGo
