### ISSUE TITLE
[Feature Request] Google Safe Browsing

### ISSUE THREAD

**Issue by ghost** [duckduckgo/Android#1647]
I believe this is currently disabled in DuckDuckGo Privacy Browser and it is understanable. However, without Google Safe Browsing or any other "blocklist service" there is practically no protection against malware or phishing leaving users vulnerable. Most browsers implement Google Safe Browsing except for Microsoft Edge which uses Microsoft Smart Screen. Is it not common sense to add some protection / security measure to help keep users safe from malicious threats, not just privacy threats. It can make it difficult to be private without first being secure. Please consider adding some form of malware protection in a future release.

**Comment by marcosholgado** [comment]
Thanks for your feature request! We actually looked at this right before Christmas and decided (again) to not enable Google Safe browsing. However we do acknowledge the gaps this creates in terms of phishing, etc so our privacy team is working on a possible new list or a different integration (like MS Smart Screen) that does not use Google Safe Browsing.

**Comment by james0071111** [comment]
Thanks for your reply @marcosholgado Sorry, issues with account, this is my current one. I'm glad to here that the privacy team are working on an alternative. I understand why DuckDuckGo wouldn't want use Google Safe Browsing and I look forward to seeing what is to come.

**Comment by cmonfortep** [comment]
Thanks everyone. Closing this issue as it's not a bug. Feel free to open a Discussion if you want to discuss further on the feature request.
