### ISSUE TITLE
F-Droid package

### ISSUE THREAD

**Issue by lboklin** [duckduckgo/Android#165]
Would be nice to have this available on F-Droid for those of us who try to live outside of the Google eco-system on Android.

**Comment by subsymbolic** [comment]
That's a good idea. We have put in a request with F-Droid and they have confirmed that it will be up soon. In the meantime you can also get the app directly from our releases page https://github.com/duckduckgo/Android/releases.

**Comment by subsymbolic** [comment]
F-Droid has now uploaded to v4.1.1 of our app. While this is a recent version, it isn't our latest. We will work with them to see if we can keep the app up-to-date, see https://gitlab.com/fdroid/fdroiddata/issues/1105.

Thanks again for reporting this!
