### ISSUE TITLE
[Bug] geolocation not working

### ISSUE THREAD

**Issue by davidbtc2009** [duckduckgo/Android#1658]
### Describe the bug

Geolocation does not work after allowing location access. 

### How to Reproduce

1. Open maps.google.com
2. Tap "Your Location"
3. Tap "Enable"
4. Tap "Allow all rge time" as the other options besides deny are greyed out
5. Tap or swipe back
6. Tap "Always

The location icon just spins and spins.
7. Tap the fire button and tap "Clear All Tabs And Data"
8. Open maps.google.com again
9. Tap "Your Location" button
10. Tap "Always" again (shouldn't that have been remembered?)

The location icon just spins and spins.

### Expected behavior

The gps location should be found and tracked

### Environment

```markdown
- DDG App Version: 5.106.0 F-Droid
- Device: Motorola One 5G Ace
- OS: LineageOS 18.1 (Android 11) with no google play services
```

**Comment by cmonfortep** [comment]
I've followed the steps describing how to reproduce the issue and I can get the location without issues. We haven't received any feedback or any bug report similar to this one.

Now that I see your environment specs, it can be related with not having play services enabled. Does it work on other browsers in your device?

**Comment by cmonfortep** [comment]
Sorry, didn't want to close the issue.

**Comment by davidbtc2009** [comment]
Yes, other browsers (Fennec) get location just fine

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by cmonfortep** [comment]
We have been monitoring user feedback internally to see if there's any problem around geolocation not working, and we haven't seen any bug reports. Closing this as no action is planned.

**Comment by danpla** [comment]
I have the same annoying issue with the recent 5.146.0. Chrome works fine.

**Comment by cmonfortep** [comment]
@danpla could you validate in-app and android system location permissions are granted? 
You can access our in-app site permissions inside settings -> site permissions.

**Comment by danpla** [comment]
Yes, permissions are granted in both cases. I also tried to choose different combinations of system location permissions for the DuckDuckGo app, i.e., "Allow always" vs "Allow only for this session". Still no luck.

**Comment by danpla** [comment]
When trying to reproduce the issue, make sure that Google Location Accuracy is disabled so that only GPS is used.

**Comment by srednax** [comment]
I have a similar issue with ddg on my phone and tablet, both running ddg on /e/os. In my case, sites using leaflet to display location shows a popup saying "on <site> it says: Gelocation error: Unser denied Geolocation". Geolocation is permitted for ddg when app in use, and asking for geolocation is enabled in ddg settings.
