### ISSUE TITLE
On Lawnchair launcher with two row dock, DDG search widget is vertically squished

### ISSUE THREAD

**Issue by michel-slm** [duckduckgo/Android#166]
Using Lawnchair launcher 1.1.0.1742 on Moto x4, Android 8.0.0 OPW27.1.

The search widget for DuckDuckGo is sized the same in 4.1.2 as In 3.1.1 when dragged onto the home screen, but when I enable two row dock (similar to the dock layout on the Pixel launcher) using Lawnchair settings -> Dock -> Two-row dock, the widget in the dock is vertically squished.

I find that if I enlarge the dock (using Lawnchair settings -> Dock -> Height scale), once the scaling factor is around 150% the widget size is back to normal, so it looks like it requires more vertical space than the old widget.

v3.1.1:
![2018-01-29 14 46 54](https://user-images.githubusercontent.com/85603/35538782-e9221a7e-0503-11e8-90c6-f393ecb587e6.jpg)

v4.1.2 (same with 4.1.0 and 4.1.1):
![2018-01-29 14 46 47](https://user-images.githubusercontent.com/85603/35538795-f6f9da2e-0503-11e8-989f-b7d59d2b1b2a.jpg)

**Comment by CDRussell** [comment]
It's happening on other launchers under certain configurations too, so it's definitely something we need to fix.

Thanks for the detailed report - that will help us find the issue.

**Comment by subsymbolic** [comment]
This issue still persists, we don't have time to look at it right now but will leave it open in case someone in the community has time.

**Comment by CDRussell** [comment]
Great idea; it's a perfect task for community to pick up.

**Comment by gokhanaliccii** [comment]
Did you assign this bug for anyone ?

**Comment by subsymbolic** [comment]
No @gokhanaliccii we don't generally assign them. You are most welcome to work on it and send us a PR.

**Comment by CDRussell** [comment]
Closed by https://github.com/duckduckgo/Android/pull/291
