### ISSUE TITLE
Not an issue with the apk but with the download site

### ISSUE THREAD

**Issue by favdish** [duckduckgo/Android#1660]
I have just downloaded and installed the (Android version of the) DDG browser from its "official" website. Initially, I was disappointed that the only two OBVIOUS download options were via the Apple and the Google stores. It took me scrolling down screen after screen to the very end of the download page to find that there are indeed two other options (though presented only in "small print", almost like a dark pattern): directly from the DDG website and via f-droid (which I prefer).

Why not show these two options (for Android users) at the top and more prominently to boot? I do realise there are reasons why some people prefer the stores but many do not and those people (me included) should have a choice without scrolling down screen after screen. IMO of course.

Given DDG's vigorous attempts to make web privacy available to all (which I applaud), I find this sad and actually somewhat disconcerting. Either you take this privacy thing seriously or you don't. Again, strictly IMO.

**Comment by cmonfortep** [comment]
Sorry about that, I can take your feedback and share it internally. However, we only expect to receive bug reports of our app as issues, as per our contribution guidelines. Hope that's ok. Thanks.
