### ISSUE TITLE
[Bug] App crashes while browsing the saved Bookmarks

### ISSUE THREAD

**Issue by swordonfire** [duckduckgo/Android#1677]
### Describe the bug

There is definitely some issue with Bookmarks in the Android app and for me app crashes are not random.
So....I have a lot of Bookmarks saved in it.
 Whenever I scroll down my saved Bookmarks , the thumbnails of the sites keep refreshing.
If I scroll down really slow (such that the correct thumbnail is already there while I scroll past it) nothing happens..the app doesn't crash.
If I scroll even just a little bit faster such that the correct thumbnails of the sites are not there (that is they are still loading /refreshing) , then it just crashes..(it happens especially when I scroll really fast to reach down the page... after just a second of pause )
I have been having this issue for a while now.

### How to Reproduce

Steps to reproduce the behavior
 
 1.Clear the app Cache to really see the issue.
 2.Add a lot of Bookmarks in the app.
 3.Click on 'Menu' then 'Bookmarks'
 4.Scroll down really fast to the bottom.
 5.You can see the thumbnails refreshing ,and after a second of pause the app crashes.

### Expected behavior

The expected behavior is that the app doesn't crash while scrolling down the Bookmarks and this (expected behavior) happened the fourth time I tried to reproduce the issue (to be sure) after I gave it a lot of time to refresh and it didn't happen afterwards e.g the next time I opened the app and tried to replicate it.
But it (the app crash) happened again after I cleared the cache.

### Environment

```markdown
- DDG App Version:5.107.0(51070000)
- Device:Samsung Galaxy M21
- OS:Android 11
```

**Comment by cmonfortep** [comment]
related: https://github.com/duckduckgo/Android/pull/1987

we will review once we close that PR

**Comment by malmstein** [comment]
Closing this stall issue. This doesn’t apply anymore.
