### ISSUE TITLE
Address should start with https:// after loading page

### ISSUE THREAD

**Issue by satyammittal** [duckduckgo/Android#168]
Currently whenever I loads some webpage by entering address ex: https://www.duckduckgo.com

address bar looks like this
![screenshot_20180201-102711](https://user-images.githubusercontent.com/15922592/35661899-20d66a9a-073b-11e8-9cd2-325a52c31768.png)
It should look like this (start with https:// so that we can easily see the webpage domain name)
![screenshot_20180201-102728](https://user-images.githubusercontent.com/15922592/35661917-400ca29e-073b-11e8-93c4-c8db7a90314a.png)

Version: 4.1.2

**Comment by subsymbolic** [comment]
This is great feedback, thanks for taking the time to share it. I have passed it on to our design team. They have plans to display a different view altogether (with https status) when in non-editing mode, this will hopefully make things clearer.

**Comment by subsymbolic** [comment]
This issue still persists, we don't have time to look at it right now but will leave it open in case someone in the community has time.

**Comment by satyammittal** [comment]
I would like to work on this issue.

**Comment by subsymbolic** [comment]
That's great @satyammittal. Feel free to send us a PR when you're ready. If you have any questions or are making any architectural changes ping us either here or in the PR to chat through your approach.
