### ISSUE TITLE
Feature request: Mobile Application: Ongoing notification to run fire button in background

### ISSUE THREAD

**Issue by TomCos** [duckduckgo/Android#1686]
Similarly to Google Chrome's incognito mode, the option for an ongoing notification to close all tabs, or in this case, run the fire button, would be a nice feature to have, as opposed to having to open the app and run manually, or have the clear timer expire. My current usage is on Android. I am not sure if something like this would be possible on iOS.

**Comment by cmonfortep** [comment]
Thanks, glad you enjoy the feature and you want to use it more :)

Please use discussions to share feature requests or check how to send us feedback [here](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#share-feedback).

**Comment by TomCos** [comment]
This was a feature request.  Does this feature already exist?  I have not seen it anywhere in the settings.

**Comment by cmonfortep** [comment]
No, we don't have a pinned notification to clear data. I was referring to the fire functionality, I'm assuming you like it if you wanted to use it from the notification. 

What we have is an auto-clear setting you can use. Or just long-press on the ddg app icon, there's a shortcut to clear data.

I will share your feedback internally.

**Comment by TomCos** [comment]
@cmonfortep Yes sounds good thank you!
