### ISSUE TITLE
!bang autocomplete icons now missing

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/android#169]
@thm @chrismorast

**Comment by fgei** [comment]
it should display the icon if the icon is returned from the json call, otherwise we removed the placeholder

**Comment by nilnilnil** [comment]
feel free to close if you cannot replicate. I was on a nexus 5 with the latest build.

**Comment by thm** [comment]
I think I found out how to replicate this (Nexus 5, latest build here as well):
1. Search for "!a" (notice Amazon icon shows up perfectly well)
2. Scroll down until icon is out of view, and then back up (notice Amazon icon is gone)
