### ISSUE TITLE
[Bug] Not possible to connect to a Ameli account

### ISSUE THREAD

**Issue by bonninf** [duckduckgo/Android#1691]
### Describe the bug

When trying to connect to his Ameli account then the following error is shown:
"Service momentanément indisponible veuillez réessayer plus tard" --> "Service temporarily unavailable please try again later"
https://assure.ameli.fr/PortailAS/framework/skeletons/error/error.jsp

### How to Reproduce

Go to: https://www.ameli.fr/oise/assure
Select the menu: "Compte Ameli" then enter both login/password
The following error is displayed: 
![Screenshot_20220119-134946](https://user-images.githubusercontent.com/1090995/150151294-10ac14f9-2430-4138-9cca-eb065315d3a6.png)

### Expected behavior

It should be possible to connect to a Ameli account because it works fine with other browsers as Chrome for instance.

### Environment

```markdown
- DDG App Version: 5.106.0
- Device: G one
- OS: Android 7.0
```

**Comment by cmonfortep** [comment]
Please report those issues via "broken sites" in our app if you find that problem again. We have an specific team just to look into those issues :)

I personally don't have a login/password to test this, but our team will react if we see users report this site.

**Comment by bonninf** [comment]
@cmonfortep Thanks for your response. I just sent comments with both menus "Broken site" and "Share your comments -> Issues loading Web sites"

For information, you can check the issue without to have login/password because the error occurs now before the login/password form page is displayed.
