### ISSUE TITLE
[Bug] Writing to clipboard from JavaScript doesn't work

### ISSUE THREAD

**Issue by Compro-Prasad** [duckduckgo/Android#1695]
### Describe the bug

Copy to clipboard option on any website that uses JavaScript's `navigator.clipboard.writeText` doesn't work.

### How to Reproduce

Case 1: Your GitHub page
1. Go to https://github.com/duckduckgo/Android#building-the-project on Duckduckgo Android app
2. Use the copy button to copy the code block
3. Doesn't respond as Copied and the text is also not copied

Case 2: My website
1. Go to https://compro-prasad.gitlab.io
2. Use the `#` symbol beside any of the headers
3. Copied message is shown but the link doesn't get copied

### Expected behavior

In any of the cases the link should get copied. I have stated the cases in the **How to reproduce** section.

### Environment

```markdown
- DDG App Version: 5.108.0
- Device: Samsung Galaxy M31 SM-M315F/DS
- OS: Android 11
```

**Comment by marcosholgado** [comment]
Hi, for this to work we need Chromium to implement the clipboard write text permission which unfortunately is not implemented https://caniuse.com/?search=navigator.permissions

**Comment by renatolond** [comment]
Is there somewhere we can keep track of the Chromium implementation of this one? I can't see Chromium in the caniuse table, and I couldn't find the related bug on the chromium tracker

**Comment by Compro-Prasad** [comment]
That is what I thought. But then I thought I am so stupid to find the Chromium. I think it should be re-opened.
