### ISSUE TITLE
Usability: Scroll bars

### ISSUE THREAD

**Issue by OpinionatedGeek** [duckduckgo/Android#170]
Summary: The DuckDuckGo browser just doesn't seem to display a vertical scrollbar for any web pages, no matter how long they are. This leads me to lose context of where I am in the page, how long it is, and how much more there is to read or see.

To see what I mean, visit any long page - for example [New York Times](https://nytimes.com) - you can scroll the page, but no scrollbar appears.

It's much more of an issue with articles on Medium etc. With no proportionally-sized scrollbar, I have no idea how long the article is when I scroll down a bit. If I want to find out how long the article is, I have to repeatedly scroll down until I see the end, then scroll back up to where I was beforehand - something made more difficult by (again) not having a scrollbar to know my previous location.

It's possible it's using a white scrollbar on a white background ([Firefox Focus used to do this](https://github.com/mozilla-mobile/focus-android/issues/1447)) but I haven't seen any indication of this.

Is it possible for you to show a contrasting-coloured proportionally-sized scroll bar for long pages? I'm not sure what level of control you have over the rendering engine here.

**Comment by CDRussell** [comment]
Thanks for reporting this. I agree, this would be a nice improvement. 

I'll look into adding this in the coming few days if it's a small fix.

**Comment by CDRussell** [comment]
Addressed in #171

**Comment by OpinionatedGeek** [comment]
Yay! I have just installed the latest release and I have a scrollbar now!

Many thanks for doing this - and so quickly!

**Comment by CDRussell** [comment]
No problem; thanks for the suggestion
