### ISSUE TITLE
External browser setting

### ISSUE THREAD

**Issue by partition** [duckduckgo/android#171]
Hey,

So - first of all - I'm not quite sure whether this one is a bug or feature request. :)

Here's my usecase:

- I want to use the DDG application to present me search results inside of its WebView.
- Once I click on some search result I want to use an external application - so just let use ActivityManager to pick the application that can handle my Intent - be it my browser, or the YouTube application when I click on the youtube's link. (theirs app is registered for http ACTION_VIEW intents, as long as the link has youtube.com in the domain name)
- Same for some other external links - like news feed - I want to open them in my primary browser, like Firefox.

I tried to achieve that behavior using the current settings' implementation. I went to the 'Use external browser' item in the preferences and I picked 'For non-search results'. However, it didn't have any effect when I click on the search result items.

So my question is:

- Is that intended? If not, it could be easily fixed by commit I pushed to my own fork:
https://github.com/partition/duckduckgo-android/commit/992f363651a2c2a51babd242f1476bd0527dbd64

- If it should stay that way - maybe you should consider adding a new preference on the settings screen, so I can achieve desired behavior?

**Comment by partition** [comment]
Btw, the commit I mentioned makes DDG app open an external browser when you use !bangs. But I like it that way. Let me know what are your thoughts @fgei @nilnilnil

**Comment by fgei** [comment]
actually I think the external setting has been deleted in the new redesign, now you have a "view in browser" option in almost every menu

**Comment by partition** [comment]
Fair enough! Thanks
