### ISSUE TITLE
Consistent code formatter configuration

### ISSUE THREAD

**Issue by partition** [duckduckgo/android#172]
Hey,

I noticed that the code formatting is not consistent across the DDG's app codebase.

Examples (screenshots, because github's markdown automatically formates the code once you paste it):
![screen shot 2015-03-19 at 2 18 33 pm](https://cloud.githubusercontent.com/assets/336158/6731172/2e7933be-ce43-11e4-863f-e86a2040fd83.png)

1. Is there any code formatter configuration / guidelines of how should I format my code in order to do contributions?
2. If so, can we make a single commit that will autoformat all the repository?

**Comment by fgei** [comment]
1. not that I know of, I've tried to be consistent with the code that was already present, but sometime it's different inside each block.
2. Honestly, I think it would be a good idea, @nilnilnil, @sreilly ?

**Comment by sreilly** [comment]
A consistent coding style guide would be nice to have, but I'd worry that declaring one at this point might put off potential contributors.

On the other hand, if DDG already has an existing style guide that we could use, that'd be very helpful. Applying such a style in one coordinated commit would be do-able and a good idea IMO.

**Comment by partition** [comment]
Okay, so the problem is that DDG's repository has two active, long-running branches (master and Redesign_2015) and there's no way in reformatting globally both without falling into a nightmare conflict (tried it, once you try to merge these branches you fall into few-hundreds-lines-long 'both modified' entries).

Of course, we could eventually fix the Redesign_2015 but that makes merging master and its eventual changes way harder.

The best we can do here is probably wait till Redesign_2015 hits master (and perform global code rearrangement right before the merge).

I suggest keeping that issue open so it won't be forgotten. :+1:

**Comment by nilnilnil** [comment]
We don't have an internal style guide for Android. I think we should make it whatever the canonical Android formatting suggests. I have emacs restructure the whitespace for me because it's always crazy and I just don't personally care at all. If we're ok with blowing away git blame etc. I'm fine with whatever @sreilly and @fgei would like. After all, you spend the most time in here.
