### ISSUE TITLE
[Request] Move fire icon to bottom of menu & add tab icon

### ISSUE THREAD

**Issue by huuhaa** [duckduckgo/Android#173]
Move that fire icon to the bottom of the menu and please replace it with ether trashcan icon or 1-color flame icon, cause current flame icon seems a bit unprofessional.
When doing this, add tab icon ether  to the place where currently is fire icon, or move Privacy Dashboard icon next to menu which would leave tab icon after addressline.

**Comment by subsymbolic** [comment]
Thanks for your feedback @huuhaa I have passed it on to our design team.
