### ISSUE TITLE
Widgets take up more space than needed

### ISSUE THREAD

**Issue by Naudiz** [duckduckgo/Android#1752]
### Describe the bug

Widgets take up too much space without the possibility to resize them to a smaller ratio. The simple search bar looks like a 5x1 widget, but demands 5x2 space on the home screen. The favorites widget has a preview picture that looks like a 5x2 widget, but takes up 5x3 space with a minimum of 2 favorites rows, opposed to the one row shown in the preview.

![Screenshot_20220216-103924](https://user-images.githubusercontent.com/16839938/154241321-f103fc33-df17-45fa-a4d0-9eee51978736.png)
![Screenshot_20220216-103805](https://user-images.githubusercontent.com/16839938/154241415-cdd3212c-cac8-4e63-89e1-21798d8958ea.png)

### How to Reproduce

Simply place a widget on the homescreen.

### Expected behavior

Search widget should have a space requirement of 5x1 only.
Favorites widget should be freely resizable with a minimum of 5x2 (search bar + one row of favorites, like in the preview)

### Environment

```markdown
- DDG App Version: 5.111.0
- Device: Pixel 4a (5G)
- OS: Android 12 (CalyxOS 3.2.0)
```

**Comment by cmonfortep** [comment]
Hey @Naudiz this is something mostly handled by the launcher you use. We just indicate the size of our widget and the launcher calculates the required grids. Not sure why it shows 5x2 whereas we can see 5x1 on other launchers.

**Comment by bmx666** [comment]
Hi @cmonfortep why this bug was closed without any further investigation?

I have similar issue on Sony Xperia 1 III with native Sony Xperia Home Launcher and Android 12

**Comment by cmonfortep** [comment]
@bmx666 sony devices have their own launcher, not sure how they handle widget sizes. Do you want to share a screenshot of DDG widgets on the sony launcher widgets list? (as the first screenshot @Naudiz attached)

**Comment by bmx666** [comment]
@cmonfortep I recompiled project and located the bug is related to **minHeight** attribute
https://github.com/duckduckgo/Android/blob/61771a867e30ba4aea89238526939c4b37965bcf/app/src/main/res/xml/search_widget_info_light.xml#L24
https://github.com/duckduckgo/Android/blob/61771a867e30ba4aea89238526939c4b37965bcf/app/src/main/res/xml/search_widget_info.xml#L24

If set **minHeight** to **31dp** then Sony Launcher set width of SearchBar widget to 5x1

**Comment by bmx666** [comment]
@cmonfortep screenshots after set **minHeight** to **31dp**

# Widget window

![photo_2022-04-03 20 14 16](https://user-images.githubusercontent.com/2761506/161442184-045b8d69-21e6-4796-b3c5-b9a634eabc43.jpeg)

# Launcher desk

![photo_2022-04-03 20 14 13](https://user-images.githubusercontent.com/2761506/161442180-31ebe7ee-9d21-46ae-8a04-c3612306c31d.jpeg)

**Comment by cmonfortep** [comment]
I will review the values on the minheight, thanks. If I'm not wrong, our small widget uses more than 31dp.

**Comment by bmx666** [comment]
@cmonfortep I can be wrong, but maybe dp is related to wide-screen 21:9 and 40dp doesn't work correctly? If I set **minHeight** to **32dp** or higher value then SearchBar widget immediately sets as 5x2.

I made few quick checks of SearchBar widget with **minHeight** **40dp** and **31dp** on emulators Pixel 2 skin + API 29-32. I didn't notice any changes, but review and tests can show different result.

**Comment by bmx666** [comment]
I made a few extra test on Sony Xperia 1 III, in Settings -> Display -> Display size are presented several options:

`adb shell wm density`

### Small
Physical density: 420
Override density: 356

### Default
Physical density: 420

### Large
Physical density: 420
Override density: 462

### Larger
Physical density: 420
Override density: 504

### Largest
Physical density: 420
Override density: 548

`adb shell wm size`
Physical size: 1096x2560

I iterated over all possible display sizes and found minHeight valid for Largest display size if it 25dp or less
But 2nd strange behavior on Small display size, widget size if 4x1 instead of 5x1

**Comment by bmx666** [comment]
I read Android article about widget on Android 12 -> [Determine a size for your widget](https://developer.android.com/guide/topics/appwidgets/layouts#anatomy_determining_size)

I made **res/xml-v31/search_widget_info.xml** for Android 12 and higher it's replace **minHeight** on **targetCellHeight** attribute that is work perfectly. If mix **minHeight** with **targetCellHeight** then Sony Launcher display as 5x2 SearchBar widget

```xml
<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
    android:initialKeyguardLayout="@layout/search_widget"
    android:initialLayout="@layout/search_widget"
    android:minWidth="314dp"
    android:minResizeWidth="110dp"
    android:targetCellHeight="1"
    android:previewImage="@drawable/search_widget_preview"
    android:resizeMode="horizontal"
    android:updatePeriodMillis="86400000"
    android:widgetCategory="home_screen|keyguard" />
```

**Comment by Drag0nFly** [comment]
This widget took up almost half of the screen size; it could also not be moved and/or resized. It also cluttered up all the icons to make room for itself.

Along with its "smaller" companion widget, *more than half the screen was unusable*. After forcibly killing DuckDuckGo, and seeing the widgets persisting, the only remaining option was to uninstall it and reboot the phone.

This from a long time DuckDuckGo user. Way to go folks.

**Comment by bmx666** [comment]
Hi @cmonfortep any updates? I provided to you a final solution year ago, why this issue is still closed? Could you re-open it?
