### ISSUE TITLE
[Request] Improve startpage

### ISSUE THREAD

**Issue by huuhaa** [duckduckgo/Android#176]
Add summary of blocked trackers, blocked adds, https upgrades, average privacy enhanced (ex. from D=>B) & estimated time saved on top of startpage. In my opinion this is quite important thing, cause for Brave browser it has turned out to be great way to have good reputation. Just check at twitter how many images there are about this summary at brave. And not only for good PR but it's information nice to know for user too.

Also let user add speed dial icons to favorite page there. Also let user drag those elements to position user wants to, if possible.

**Comment by subsymbolic** [comment]
Thanks @huuhaa, I have shared your ideas with our design team!
