### ISSUE TITLE
[Bug] Desktop Mode

### ISSUE THREAD

**Issue by ag6ag1** [duckduckgo/Android#1769]
### Describe the bug

when applying the desktop mode for all the website that I tried, nothing changed in the behavior
the page only refreshed without any change

### How to Reproduce

applying desktop mode

### Expected behavior

see the page as seen on a computer 

### Environment

```markdown
- DDG App Version: 5.111.0.zg
- Device: Xiaomi Poco x3 pro 
- OS: Android 11
```

**Comment by cmonfortep** [comment]
Related https://github.com/duckduckgo/Android/issues/768 

It should work for many sites. However, some of them detect the screen viewport to force mobile site. We are open to receive technical proposals to cover those scenarios. Thanks.
