### ISSUE TITLE
[Request] Change Duckduckgo search-bar widget

### ISSUE THREAD

**Issue by huuhaa** [duckduckgo/Android#177]
Change Duckduckgo search-bar widget to the one with rounded corners (at least an option), but more importantly to be actual search-bar instead of shortcut to browser. 

At the moment I have 2 shurtcut to Duckduckgo privacy browser, the round one with duck icon and the one which prevents to be search widget, but is actually just shortcut to the Duckduckgo privacy browser.

**Comment by subsymbolic** [comment]
Thanks for the feedback @huuhaa. We added rounded corners as part of our redesign in https://github.com/duckduckgo/Android/pull/240. If there is specific search functionality that you would like to see in the widget feel free to raise new issues.
