### ISSUE TITLE
[Bug] Add the word "browser"

### ISSUE THREAD

**Issue by 89z** [duckduckgo/Android#1770]
### Describe the bug

This repo is for "DuckDuckGo Privacy Browser", but the word "browser" is not current used in the repo description or topics. That means people searching for "browser" will not find this repo.

### How to Reproduce

no

### Expected behavior

no

### Environment

```markdown
- DDG App Version:
- Device:
- OS:
```

**Comment by cmonfortep** [comment]
Thanks for the suggestion. We will consider adding the word to the description and topics 👍
