### ISSUE TITLE
Optimize size of app

### ISSUE THREAD

**Issue by huuhaa** [duckduckgo/Android#178]
When reading closed issues I got the picture that Duckduckgo privacy browser is based of using webview like Firefox Focus does, is this correect?

If so, could you optimize the size of your app. Currently when checking at Settings => Applications Duckduckgo seems to take 34,75MB space, while Firefox Focus takes 9,36MB space and has more features.

**Comment by subsymbolic** [comment]
Thank you for logging this. I have investigated and the app itself is a light ~8MB, the remaining space is used by content blocking data, user data and caches.
