### ISSUE TITLE
[Bug] Tabs list scrolls to top

### ISSUE THREAD

**Issue by huesie** [duckduckgo/Android#1785]
### Describe the bug

Update in last few weeks seems to have changed behaviour with tabs list.  The active tab still has the black surround but the tab list scrolls to the top - this is much less convenient.  Previously the active tab was centered in the tab list and this was much more usable when background tabs had been opened.

Thanks to the effort of all developers on this great project and I appreciate that this may have been a deliberate change but it's a deal breaker for me as it makes DDG too inconvenient when working with multiple tabs as I frequently 'open in background tab' but with more than a few screenfuls of tabs it's hard work to locate previous and the tabs opened in background.

### How to Reproduce

1. Open several screenfuls of tabs e.g. 20
2. Select a tab towards the middle
3. Open a link from that page in background tab
4. Select the tabs list 'square block'
5. The view has scrolled to the first tab

### Expected behavior

Rather than scrolling to the top of the tabs list - the old behaviour is much more convenient where the active tab is centered in the tabs list view.

### Environment

```markdown
- DDG App Version: 5.114.2 (51142000)
- Device: Pixel 3a
- OS: Android 12 SQ1A.220205.002
```

**Comment by eccul** [comment]
Yep, CR this on 5.114.2 (51142000)

**Comment by cmonfortep** [comment]
Thanks, we are investigating the issue. We can reproduce it as well.

**Comment by huesie** [comment]
Thank you for your responsiveness and willingness to look at this bug and I confirm it is resolved when I've updated to the latest release.
