### ISSUE TITLE
Add widget thumbnail

### ISSUE THREAD

**Issue by thm** [duckduckgo/android#180]
The widget thumbnail is not showing up for me. It's showing a placeholder instead:
![widget_thumbnail_bug](https://cloud.githubusercontent.com/assets/1379822/7090849/2418110a-dfa6-11e4-811c-387e16a7ade6.png)

**Comment by fgei** [comment]
this is on a fresh install or install from a previous build?

**Comment by thm** [comment]
It's on a fresh install of the most recent build

**Comment by fgei** [comment]
if you try to reboot it, still nothing?

**Comment by thm** [comment]
Correct, no difference

**Comment by fgei** [comment]
mmh weird, Android version?
I had some trouble with 5.0.1 because it seems to have some caching problem, it works fine with any other versions for me.
it shouldn't be the case, but if you do this: Settings -> Apps -> Google App -> Clear Cache
does it change anything?

**Comment by thm** [comment]
Yeah, that worked. Although, only after rebooting again. (incase it helps, I'm on Android 5.1 on a Nexus 5)
