### ISSUE TITLE
[Feature] Chrome like dark mode for pages

### ISSUE THREAD

**Issue by SosPosos** [duckduckgo/Android#1807]
Guys, it would be cool if you add night mode / dark view mode like one, that can be found in chrome:flags or in settings of kiwi browser
And a bottom bar.. It feels better to use browser with bottom toolbar if you have a phone with a large screen..
Maybe adblocking would be cool feature too, but for this, i think, i can find magisk module, so it isn't important

![Screenshot_20220315-145959_Kiwi Browser](https://user-images.githubusercontent.com/52379151/158373365-60141b17-cedd-42a8-b952-8ec99e4b3204.png)

**Comment by SosPosos** [comment]
Oh. If this pix is real, then nvm
![gj4znw61nkm81](https://user-images.githubusercontent.com/52379151/158744802-27e8dc3e-2685-4259-ab78-c5515ec4f257.jpg)
I liked part where "associated with RUSSIAN desinformation"
Yep, bbc's lies is ok for you, other non-russia media's lies - ok, good, maybe you can make it so when you go to search "Kiev" ddg will respond with photos of bombing Doneck and heroic Zelensky in armor, ready to kill some russian invaiders, ha? 
Thanks, never install this sh-t again

**Comment by cmonfortep** [comment]
Sorry about that. Closing as we only accept bug reports as issues in this repo. Please refer to our contributions guidelines.
