### ISSUE TITLE
No automatic upgrades to https

### ISSUE THREAD

**Issue by Schmensch** [duckduckgo/Android#1809]
While visiting m.yuntrack.com, I noticed I was on the http version of the site, even though there's a https version available. 

I think for a privacy-first browser like DuckDuckGo, automatic upgrades to htrps or forced https should be the standard.

The only way to tell that I was on an insecure http site was that a little B+ changed to a C+, however this can be easily overlooked when compared to big red warnings you get in Chrome / Firefox.

**Comment by cmonfortep** [comment]
@Schmensch could you reopen the issue using our bug template?

**Comment by Schmensch** [comment]
@cmonfortep done: https://github.com/duckduckgo/Android/issues/1811

**Comment by cmonfortep** [comment]
Thanks @Schmensch 🙏
