### ISSUE TITLE
Resource leaks -- cursor not closed -- found by Facebook's static analyzer

### ISSUE THREAD

**Issue by dulmarod** [duckduckgo/android#181]
Hello,
These resource leak reports, included with comments below, were found by running

Facebook's Infer static analyzer on duckduckgo.

Regards,
Dulma Rodriguez
Facebook Static Analysis Tools Team

For the following bugs, the problem is that Cursor objects need to be closed.

File: src/com/duckduckgo/mobile/android/db/DdgDB.java

Report: Resource Leak: resource acquired by call to query(...) at line 631 is not released after line 644

--------------------------------------------------------------------------------------

File: src/com/duckduckgo/mobile/android/db/DdgDB.java

Report: Resource Leak: resource acquired by call to query(...) at line 408 is not released after line 409

-------------------------------------------------------------------------------------

File: src/com/duckduckgo/mobile/android/db/DdgDB.java
Report: Resource Leak: resource acquired by call to query(...) at line 400 is not released after line 401

-------------------------------------------------------------------------------------

File: src/com/duckduckgo/mobile/android/db/DdgDB.java
Report: Resource Leak: resource acquired by call to query(...) at line 387 is not released after line 388

-------------------------------------------------------------------------------------

File: src/com/duckduckgo/mobile/android/db/DdgDB.java
Report: Resource Leak: resource acquired by call to query(...) at line 332 is not released after line 333

-------------------------------------------------------------------------------------

File: src/com/duckduckgo/mobile/android/db/DdgDB.java
Report: Resource Leak: resource acquired by call to query(...) at line 362 is not released after line 363

-------------------------------------------------------------------------------------

File: src/com/duckduckgo/mobile/android/db/DdgDB.java
Report: Resource Leak: resource acquired by call to query(...) at line 379 is not released after line 380

-------------------------------------------------------------------------------------

File: src/com/duckduckgo/mobile/android/db/DdgDB.java
Report: Resource Leak: resource acquired by call to query(...) at line 345 is not released after line 346

-------------------------------------------------------------------------------------

File: src/com/duckduckgo/mobile/android/db/DdgDB.java
Report: Resource Leak: resource acquired by call to query(...) at line 313 is not released after line 320

-------------------------------------------------------------------------------------

File: src/com/duckduckgo/mobile/android/db/DdgDB.java
Report: Resource Leak: resource acquired by call to query(...) at line 299 is not released after line 306

-------------------------------------------------------------------------------------

File: src/com/duckduckgo/mobile/android/db/DdgDB.java
Report: Resource Leak: resource acquired by call to query(...) at line 432 is not released after line 434

-------------------------------------------------------------------------------------

File: src/com/duckduckgo/mobile/android/db/DdgDB.java
Report: Resource Leak: resource acquired by call to query(...) at line 392 is not released after line 396

-------------------------------------------------------------------------------------

File: src/com/duckduckgo/mobile/android/db/DdgDB.java
Report: Resource Leak: resource acquired by call to query(...) at line 424 is not released after line 426

-------------------------------------------------------------------------------------

File: src/com/duckduckgo/mobile/android/db/DdgDB.java
Report: Resource Leak: resource acquired by call to query(...) at line 424 is not released after line 428

-------------------------------------------------------------------------------------

File: src/com/duckduckgo/mobile/android/db/DdgDB.java
Report: Resource Leak: resource acquired by call to query(...) at line 499 is not released after line 506

-------------------------------------------------------------------------------------

For this report, the problem is that os.flush could throw an exception, in which case os won't get closed.

File: src/com/duckduckgo/mobile/android/download/FileCache.java
Report: Resource Leak: resource acquired by call to FileOutputStream(...) at line 48 is not released after line 53

**Comment by nilnilnil** [comment]
nice -- so close @fgei

**Comment by dulmarod** [comment]
Hi, 
Facebook's Infer static analyzer, the tool that we used to find these issues, is open source now! Check it out! (http://fbinfer.com/).
