### ISSUE TITLE
Duckduckgo browser: I can no longer import my bookmarks

### ISSUE THREAD

**Issue by nettlebay** [duckduckgo/Android#1810]
Hello
After reinstall, I can no longer import my bookmarks in DuckDuckGo Privacy Browser. It offers me to open the Bookmarks.html file with another application (Browser or Files Manager). No probleme with my Galaxy Tab A7 lite, only with my phone Galaxy Xcover 4.

**Comment by cmonfortep** [comment]
@nettlebay could you reopen the issue using our bug template ? It's important for us to have more information.

In this case, if you can provide each step you follow to import bookmarks, and when exactly fails. That will be useful to help you with the issue.

**Comment by nettlebay** [comment]
Thank you. I will try

**Comment by nettlebay** [comment]
Tout est OK ! I re-exported my bookmarks from a Chromium based browser (Iridium) to my phone via Protonmail. Then, re-imported in DDG. No problem. It works! I think the previous bookmarks.html was altered. Thank you for your help. We can close the ticket.
