### ISSUE TITLE
Outdated Browser

### ISSUE THREAD

**Issue by mtris** [duckduckgo/Android#1837]
Dear DuckDuckGo: I know you provide updates regularly, but at least 1 website visited gives me a message that the browser is outdated/not supported.
![Capture+_2022-04-03-18-59-45_1](https://user-images.githubusercontent.com/24400330/161453861-d9bdbf39-5391-4c2c-946a-d115c8497e68.png)

**Comment by marcosholgado** [comment]
This is highly likely because of our user agent rather than because the browser is outdated. Any chance of knowing the website this is coming from for more testing?

**Comment by mtris** [comment]
Hello: I see the above mentioned when I visit CapitalOne login screens.
Also when viewing the capitalone offers page, I receive this error message (screenshot attached). Thank you for the reply
![Capture+_2022-04-07-16-40-42_1](https://user-images.githubusercontent.com/24400330/162336289-d0e267f5-626c-4097-ab11-a71ca22d7cad.png)

**Comment by mtris** [comment]
Hello: By using the Android WebView, does this allow android to view my browsing or collect data when using DuckDuckGo browser?
I will update my Android WebView and re-try the sites. Thank you for the reply. Sincerely,

**Comment by cmonfortep** [comment]
No, it doesn't. Thanks.

**Comment by mtris** [comment]
Hello: I updated my WebView. It cleared the grey error 'Please use one of our supported browsers' but the red 'outdated browser message' remained. Thanks again for your input and consideration. Sincerly,

**Comment by cmonfortep** [comment]
Thanks, that second warning might be related to our user agent. There's an option in the browser menu that says "Report broken site", feel free to report that site or any site showing a similar banner. We have a team dedicated to triage those issues. Thanks.
