### ISSUE TITLE
[request] Smarter External Browser Settings

### ISSUE THREAD

**Issue by BrainBlasted** [duckduckgo/Android#185]
I would like to see smarter options for opening links. Right now the only options are Always and Never. Never forces one to use DDG as a web browser instead if a search engine, while Always just opens DDG in a browser with your search, making the app pointless. I'd like to be able to use it as a replacement for the Google app.

**Comment by subsymbolic** [comment]
Thanks for your feedback @BrainBlasted. The latest version of our app has changed direction. It works more like a Browser and all links now open within our app. We will soon also add a long press option to "share" links with other apps.
