### ISSUE TITLE
[Bug] Discord.com with 2FA does not save login

### ISSUE THREAD

**Issue by vinc3nz** [duckduckgo/Android#1859]
### Describe the bug

Discord with 2FA does not keep me logged in, even after making the page protected. On github for example it works. 

### How to Reproduce

Enable 2FA in Discord
Go to https://discord.com/login
Make the page (I don't have the browser in English. In Germany it is called Feuerfest, the thing that protects your site from being deleted after closing browser) fire protected.
Close browser / Delete data with the fire button
You are logged out

### Expected behavior

I should be logged in. 

### Environment

```markdown
- DDG App Version: 5.120.0
- Device: Huawei Mate 20 Lite
- OS: Android 10 (Emui 10.0.0)
```

**Comment by cmonfortep** [comment]
Sorry about that. Probably the site is saving credentials information using the web storage (instead of using first-party cookies). Because of Webview limitations, we can't selectively delete local storage based on domains, so we remove everything, including fireproof websites.

**Comment by vinc3nz** [comment]
Is works now since an update. Just forgot to close
