### ISSUE TITLE
delete via long press on search history item

### ISSUE THREAD

**Issue by travisfw** [duckduckgo/android#186]
I have used the DDG app's search history as a note pad for some time. Even when I'm in airplane mode, I'll do a search so that I can remember to look it up later. When using the app this way it helps to be able to reduce some of the clutter in my search history by deleting items. I used to be able to do this, but recent updates have removed that feature. Is there reason for this? Can I get this feature back?

**Comment by fgei** [comment]
this is back with 3.0.7, so I'm closing this
