### ISSUE TITLE
No back navigation for secondary links in Settings

### ISSUE THREAD

**Issue by heypaulmcgrath** [duckduckgo/android#187]
Home icon always takes you back to the main list of stories, instead of back one hierarchy level on the settings page.

Could potentially just use the material back arrow to navigate the hierarchy.

**Comment by fgei** [comment]
I think having the home icon makes sense, you can always use the back button to go back one level to the settings page.

what do you think @thm ?

**Comment by thm** [comment]
@fgei Yeah, that was my thinking

**Comment by fgei** [comment]
ok, closing then
