### ISSUE TITLE
Make region setting persistent

### ISSUE THREAD

**Issue by thenktor** [duckduckgo/Android#188]
Please make region setting persistent also after clearing data. Or make it an option in  app settings so that it is used for autocomplete suggestions, too.

**Comment by subsymbolic** [comment]
Thanks for reporting this @thenktor, we will try and fix it soon!

Note to staff: we have an existing internal task in Asana at https://app.asana.com/0/414730916066338/560129298337416.

**Comment by subsymbolic** [comment]
This was fixed by https://github.com/duckduckgo/Android/pull/189 and we will release it early next week.
