### ISSUE TITLE
Remove requirement to grant photo and media permission

### ISSUE THREAD

**Issue by wbillan** [duckduckgo/Android#1886]
Issue:
Currently Duckduckgo requires users to grant grant photo and media permission when downloading files (e.g. PDF) , which gives it access to all of the user's photos and videos, which has privacy implications. The app doesn't actually need this permission as per Android scoped storage (https://source.android.com/devices/storage/scoped) in Android 11+, as an app does not require permissions to create files and access those created files.

Request:
Remove requests for and and the requirement for photos and media permission.

**Comment by cmonfortep** [comment]
We reviewed the need of using that permission on devices running >= Android 10, and we have removed it. This will be part of our next release. https://github.com/duckduckgo/Android/pull/1910

Thanks.
