### ISSUE TITLE
Menu Design

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#1891]
**Info**
For larger displays is it possible to make the menu width smaller

**UI**
 ![Screenshot_20220428-110815_DuckDuckGo.png](https://user-images.githubusercontent.com/48844761/165714109-895a2029-fa41-42ac-9e10-89693aac2052.png)

**Solve**
Make the menu width smaller

Thanks Team, also loving the new design looks amazing 🙌

**Comment by cmonfortep** [comment]
Thanks for the feedback @WillHick, glad you like the new menu, and you spotted really quick the change. About the width, it's a design decision to use that width, I can share feedback but I'm closing the issue as it's not a bug.
