### ISSUE TITLE
[Feature request] Add tabs

### ISSUE THREAD

**Issue by Pascal3366** [duckduckgo/Android#190]
Hi i would like to use this as my main Browser but im missing tabs to organize my browsing 
THX in advance

**Comment by anunaym14** [comment]
Yes, this is much needed. Please add!

**Comment by CDRussell** [comment]
Thanks for the requests; we are actively working on implementing tabs. Stay tuned!

**Comment by subsymbolic** [comment]
Duplicate https://github.com/duckduckgo/Android/issues/157
