### ISSUE TITLE
Allow widet to resize horizontally (for Nexus 6 and larger devices)

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/android#190]
Creating this ticket as a user had written in to ask for this functionality.

Personally I don't use the widget, but I do use NovaLauncher which lets me resize any widgets.

After switching to the native launcher, I noticed that on my Nexus 6 the widget takes up only 4 of the 5 available tiles and can't be resized which is a little disappointing.

**Comment by fgei** [comment]
available in the last release!
