### ISSUE TITLE
Select "save path" for images, Save pages (PDF option), better Cookie control

### ISSUE THREAD

**Issue by justadroid** [duckduckgo/Android#191]
Hi Duckduckgo team,

Glad you are working on a browser geared towards more privacy protection , just as the search engine you offer! ( I really hope you won't ever go towards the google model )

After testing your android version I have some suggestions and requests for future development:
I put them all in a single post instead of creating separate issue posts(hope is ok:)

1) Give the option to select the "save images" location, especially to the external sd card.

2) Add possibility to save pages, especially in PDF format

3) Give the possibility to select what kind of cookies are accepted/saved ( functional vs. third sites etc), for now it just says generically "Save cookies"

Thanks!

**Comment by CDRussell** [comment]
Thanks for the suggestions. I can't make any promises when we'll have time to pick them up, but they would all be good additions.

**Comment by justadroid** [comment]
The main one will be to select what cookies are accepted. Is the browser accepting all cookies by default including third parties? This would defeat its privacy purpose! Can you please clarify how this works at the moment.

Thanks!

**Comment by subsymbolic** [comment]
Yes, we do block third party cookies. We have also made a note of your enhancement requests internally. Thanks for submitting them!
