### ISSUE TITLE
Florisboard had the same issue, if that could help come up with a fix?

### ISSUE THREAD

**Issue by Dandysandy44** [duckduckgo/Android#1912]
Removed.

**Comment by Dandysandy44** [comment]
He's going to have all  what I sacrificed his hazbeen won't to see if uses well come over to face a fuck and!! Me FUCKING RUD- FORD!! HIS OWN  DEMISED ( DUMBASS) FOR ASSUMEING !! THAT  ASS-USE-MEN !!  GET FUCKED !!! 
BECAUSE WHAT'S THE CENT OF HAVING THEM IF I CAN'T MISUSED HIM  
DOWN STAIRS !!!!!  WHEN IT'S THE FACE I FUCKED🤥AND THE FUCK'S HE DEFACED

**Comment by WillHick** [comment]
Mate this is a GitHub repo not life notes
