### ISSUE TITLE
[Bug] Image download fails on meteoprades.net 

### ISSUE THREAD

**Issue by Kita2345** [duckduckgo/Android#1928]
### Describe the bug

Download fails.

### How to Reproduce

Navigate to https://www.meteoprades.net/webcams/webcam-castell-de-siurana/
Long press an image and select "download image" option.
Observe behavior.

### Expected behavior

The image is downloaded and available on the mobile device.

### Environment

```markdown
- DDG App Version: 5.124.0
- Device:
- OS: Android 9
```

**Comment by vinc3nz** [comment]
Able to reproduce. 
The Image Source (for example https://www.meteoprades.net/webcam/imatges/siurana_ara.jpg), returns 403, causing the image download to fail (I don't know why it is forbidden.)
Seems to be a website error. Have you tried the same on a different browser/on desktop?

**Comment by Kita2345** [comment]
https://www.pixiv.net/en/artworks/83953383
