### ISSUE TITLE
Cannot compile freshly checked out source tree

### ISSUE THREAD

**Issue by wfaulk** [duckduckgo/android#194]
It seems that there needs to be some definition needed for "libnetcipher".

This is the failure output from gradle:

    FAILURE: Build failed with an exception.

    * What went wrong:
    A problem occurred configuring root project 'android'.
    > Failed to notify project evaluation listener.
       > Cannot evaluate module libnetcipher : Configuration with name 'default' not found.
       > Could not resolve all dependencies for configuration ':compile'.
          > Module version :android:unspecified, configuration 'compile' declares a dependency on configuration 'default' which is not declared in the module descriptor for android.libs.OnionKit:libnetcipher:unspecified
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.
    
    BUILD FAILED
    
    Total time: 3.342 secs

**Comment by wfaulk** [comment]
Oh, I see.  After cloning the repo, I also have to run:

    git submodule init
    git submodule update

Surely there's some way to pull that into the build system.

**Comment by fgei** [comment]
you can also "git clone --recursive" that is what sourcetree does I think, or you can double click on each submodule on sourcetree
