### ISSUE TITLE
[Feature Request] Configure DDG search from app options

### ISSUE THREAD

**Issue by kenb0t** [duckduckgo/Android#196]
To set themes, advertising settings, etc for the search page from the app settings

**Comment by kenb0t** [comment]
It would be nice if this persisted through fire

**Comment by subsymbolic** [comment]
Thanks, we have now updated the app to persist settings made on our search page even when the Fire button is pressed. This is in beta and will be live in version 4.4.0 soon.

I have also internally shared your suggestion to add options to the in-app Settings page. Thanks for your feedback!
