### ISSUE TITLE
[Code Structure] Code Structure Issues

### ISSUE THREAD

**Issue by AndroidPoet** [duckduckgo/Android#1978]
### Describe the bug

App has code structure issues:
View binding in the app is handled by two different patterns.
(1.)kotlin delegates
(2.)using getter property to destroy object OnDestroy 
Using two different patterns to handle the same task creates irregularities in the app architecture.
This might cost a huge refactor or it might also arise bugs in the future. 
I observed this while I was working on the remaining files which are still using the findviewby id and kotlinextenstions. 
### View binding by kotlin delegate
![by](https://user-images.githubusercontent.com/13647384/171803416-78ab227c-87c5-480b-baa9-01da4c9acdcc.PNG)
### Getter property
![lifecycleaware](https://user-images.githubusercontent.com/13647384/171803609-14689af6-f990-4800-9ea8-ba09b6802798.PNG)

### How to Reproduce

This is not a bug but it will create issues in app architecture.

### Expected behavior

Either it should be kotlin delegate or Getter property but not both.

### Environment

```markdown
- DDG App Version:
- Device:
- OS:
```

**Comment by aitorvs** [comment]
Thanks for reporting! see https://github.com/duckduckgo/Android/issues/1478

Closing for now

**Comment by AndroidPoet** [comment]
I am working on that, but I need guidance on what is recommended structure from DuckDuckGo.
