### ISSUE TITLE
[Code Improvement] Kotlin Delegates are not null safe and contain deprecated OnLifecycleEvent.

### ISSUE THREAD

**Issue by AndroidPoet** [duckduckgo/Android#1983]
### Describe the bug

Currant kotlin delegates are not null safe and also accessing methods using getMethod("bind") is not very good practice, even though there will be no problem using these. There is also deprecated claas 
"@OnLifecycleEvent"
This annotation required the usage of code generation or reflection, which should be avoided,
alternative  "DefaultLifecycleObserver" can be used. We can also eliminate typecasting.

### Get Method
![get method](https://user-images.githubusercontent.com/13647384/172130503-5279d441-3e0e-43fd-9dfe-051ab93eaa42.PNG)
### Not null safe (can be fixed but lot of boilerplate code)
![nullunsafe](https://user-images.githubusercontent.com/13647384/172130509-13230289-73da-440f-a019-3a591386a5c7.PNG)

### Deprecated OnLifecycleEvent
![deprecated](https://user-images.githubusercontent.com/13647384/172130512-2dfdb5e8-8883-4521-ae6a-5c1a3b721be5.PNG)

## Soultion

I have added a link for the gist , which can be used to eliminate all the above issues. I have recently migrated most of the classes from the kotlin extension and findViewById to ViewBinding.I would love to implement this kotlin delegate with those classes also there is not much refactoring we have to replace only one line in every fragment or activity

Even though the current solution is ok and works fine, it might create issues in the future, with updated delegates code will become much cleaner and soild.

I need approval from the internal team to change these delegates.

## Gist:https://gist.github.com/AndroidPoet/907a7c39c6312ab4d6db6b2581d8a0a1
![soultion](https://user-images.githubusercontent.com/13647384/172135542-28931b67-939f-4e57-bb50-47440dff6270.PNG)

## Fragment
![fragment](https://user-images.githubusercontent.com/13647384/172138565-d20248f8-ff8a-431e-9282-236c0917c4ec.PNG)

## Activity
![activity](https://user-images.githubusercontent.com/13647384/172138569-efeea2be-7563-4cc1-a230-ce13d5cf28bd.PNG)

## DialogFragment
![DialogFragment](https://user-images.githubusercontent.com/13647384/172138570-30632800-d556-4d61-bce9-53f4d3f0480d.PNG)

```

**Comment by AndroidPoet** [comment]
Hi, @aitorvs please check these once and Let me know your thoughts on this, as we discussed about memory leaks, those are  bit untraceable but with this delegate, we can make sure that there is no memory leak as for as view binding is concerned.

**Comment by aitorvs** [comment]
Hey @AndroidPoet. Thanks for opening this issue and the time spent caring about the code base. 

Unless there's something fundamentally wrong with the current code and/or we find and are able to consistently repro a bug eg. memory leak in the viewbinding delegate logic, I'd personally not be very supportive of changing it just because.
