### ISSUE TITLE
Widget usefulness ?

### ISSUE THREAD

**Issue by breversa** [duckduckgo/android#199]
Hello,
I'm using duckduckgo 3.0.11 (from F-Droid) on a Samsung Galaxy Nexus running CyanogenMod 11/Android 4.4.4.

I don't understand what's the widget good for : it takes 4*1 squares on the homescreen, and simply opens the app when you tap it.

I'd expect to be able to type in a query in the widget's input box, and either directly see a list of results (in a drop-down list, or something similar), or launch the app and display the result there.

So far, the widget just feels like an app-starter that takes 4 squares instead of one. :-( I sure hope it's not the intended behaviour !

**Comment by fgei** [comment]
so far it just does that, it starts the app and it should display the search fragment, keyboard and the recent/favorite results
with some launcher you can also replace the google bar.

Unluckily you cannot use any edit text to directly write text on the widget, (probably using a textview it should be possible), one cool thing we could do is to add some sort of animation when clicking the widget and transition the widget to the app bar, maybe some activity with no background just for that would be also nice.

**Comment by breversa** [comment]
Oh… okay. So it's just a space-wasting app-starter then. :-(

But how does it behave when you replace the Google search bar (I don't have it installed) ? Can you type in it ?

(And HOW do you replace the Google search bar anyway ?)

**Comment by hangduykhiem** [comment]
@fgei, I might be able to do that. Maybe next week when I'm a bit less busy I'll make a pull request.
