### ISSUE TITLE
[Bug] favicon.ico privacy leaks

### ISSUE THREAD

**Issue by mikegriffin** [duckduckgo/Android#2004]
### Describe the bug

DDG browser leaks the build number of device when browsing a page while using non-DDG user agent, when requesting both favicon.ico and apple-touch-icon.png

Additionally, if you add a page as a favorite and have sufficient favorites to allow scrolling, the server will be flooded by requests as you scroll, eg:

- - - [19/Jun/2022:23:07:35 +0000] "GET /apple-touch-icon.png HTTP/2.0" 404 12139 "-" "Dalvik/2.1.0 (Linux; U; Android 12; Pixel Build/SQ3A.220605.009.A1)" "-"
- - - [19/Jun/2022:23:07:35 +0000] "GET /favicon.ico HTTP/2.0" 404 12139 "-" "Dalvik/2.1.0 (Linux; U; Android 12; Pixel Build/SQ3A.220605.009.A1)" "-"
- - - [19/Jun/2022:23:07:36 +0000] "GET /apple-touch-icon.png HTTP/2.0" 404 12139 "-" "Dalvik/2.1.0 (Linux; U; Android 12; Pixel Build/SQ3A.220605.009.A1)" "-"
- - - [19/Jun/2022:23:07:37 +0000] "GET /favicon.ico HTTP/2.0" 404 12139 "-" "Dalvik/2.1.0 (Linux; U; Android 12; Pixel Build/SQ3A.220605.009.A1)" "-"
- - - [19/Jun/2022:23:07:37 +0000] "GET /apple-touch-icon.png HTTP/2.0" 404 12139 "-" "Dalvik/2.1.0 (Linux; U; Android 12; Pixel Build/SQ3A.220605.009.A1)" "-"
- - - [19/Jun/2022:23:07:37 +0000] "GET /favicon.ico HTTP/2.0" 404 12139 "-" "Dalvik/2.1.0 (Linux; U; Android 12; Pixel Build/SQ3A.220605.009.A1)" "-"
- - - [19/Jun/2022:23:07:38 +0000] "GET /apple-touch-icon.png HTTP/2.0" 404 12139 "-" "Dalvik/2.1.0 (Linux; U; Android 12; Pixel Build/SQ3A.220605.009.A1)" "-"
- - - [19/Jun/2022:23:07:38 +0000] "GET /favicon.ico HTTP/2.0" 404 12139 "-" "Dalvik/2.1.0 (Linux; U; Android 12; Pixel Build/SQ3A.220605.009.A1)" "-"
- - - [19/Jun/2022:23:07:38 +0000] "GET /apple-touch-icon.png HTTP/2.0" 404 12139 "-" "Dalvik/2.1.0 (Linux; U; Android 12; Pixel Build/SQ3A.220605.009.A1)" "-"
- - - [19/Jun/2022:23:07:38 +0000] "GET /favicon.ico HTTP/2.0" 404 12139 "-" "Dalvik/2.1.0 (Linux; U; Android 12; Pixel Build/SQ3A.220605.009.A1)" "-"
- - - [19/Jun/2022:23:07:39 +0000] "GET /apple-touch-icon.png HTTP/2.0" 404 12139 "-" "Dalvik/2.1.0 (Linux; U; Android 12; Pixel Build/SQ3A.220605.009.A1)" "-"
- - - [19/Jun/2022:23:07:40 +0000] "GET /favicon.ico HTTP/2.0" 404 12139 "-" "Dalvik/2.1.0 (Linux; U; Android 12; Pixel Build/SQ3A.220605.009.A1)" "-"
- - - [19/Jun/2022:23:07:41 +0000] "GET /apple-touch-icon.png HTTP/2.0" 404 12139 "-" "Dalvik/2.1.0 (Linux; U; Android 12; Pixel Build/SQ3A.220605.009.A1)" "-"
- - - [19/Jun/2022:23:07:41 +0000] "GET /favicon.ico HTTP/2.0" 404 12139 "-" "Dalvik/2.1.0 (Linux; U; Android 12; Pixel Build/SQ3A.220605.009.A1)" "-"
- - - [19/Jun/2022:23:07:41 +0000] "GET /apple-touch-icon.png HTTP/2.0" 404 12139 "-" "Dalvik/2.1.0 (Linux; U; Android 12; Pixel Build/SQ3A.220605.009.A1)" "-"
- - - [19/Jun/2022:23:07:42 +0000] "GET /favicon.ico HTTP/2.0" 404 12139 "-" "Dalvik/2.1.0 (Linux; U; Android 12; Pixel Build/SQ3A.220605.009.A1)" "-"

### How to Reproduce

Have a site with no stored favicon.ico and view the server logs after visiting the page. Have many favorites and scroll that page.

### Expected behavior

* 1) Use the correct user agent when fetching /favicon.ico and /apple-touch-icon.png, ie:

"Mozilla/5.0 (Linux; Android 9) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.127 DuckDuckGo/5 Safari/537.36"

* 2) Never attempt to fetch favicon from the favorites/bookmarks to avoid fingerprinting attacks (only update favicon when the page has been loaded ref moz bz 1618257)

### Environment

```markdown
- Device: Fire / Pixel
- OS: Android 9 / Android 12
```

**Comment by cmonfortep** [comment]
Thanks for reporting, we will investigate the issue.

As you mentioned, those calls come from sites where the webview didn't provide us a favicon. In those cases, we try to retrieve them by directly calling `<domain>/favicon.ico` ([see code here](https://github.com/duckduckgo/Android/blob/e3d4d3e530a756ed92f40909a474f62ac0239e34/common/src/main/java/com/duckduckgo/app/global/UriExtension.kt#L93)).

We use Glide (an image loading library to perform those calls), I'm pretty sure we can override the user agent to remove the build number. Thanks

**Comment by cmonfortep** [comment]
https://github.com/duckduckgo/Android/pull/2005

**Comment by cmonfortep** [comment]
This will be out in our next release. Thanks for reporting @mikegriffin
