### ISSUE TITLE
Settings not stored

### ISSUE THREAD

**Issue by thm** [duckduckgo/android#202]
@fgei Any settings set in duckduckgo.com/settings aren't stored after restarting the app. Settings are active in the current session but after a cold start all preferences are reset to default. In the default browser on Android everything works as expected.

cc @sreilly, since the same thing is happening on iOS maybe there's a correlation between the two

**Comment by fgei** [comment]
ok, this seems to be some change in the CookieManager, fixed with the next commit.

@thm, when the Save Cookies option is disabled, do you prefer to dump the data when the app is closed or not track them at all? (I guess the second one?)

**Comment by thm** [comment]
@fgei please hold off on merging and/or publishing this change

**Comment by fgei** [comment]
ok, no problem!

**Comment by thm** [comment]
Closing this since not storing the settings is intentional.
