### ISSUE TITLE
Enabling Tor while Orbot is not installed

### ISSUE THREAD

**Issue by Urkki** [duckduckgo/android#205]
In settings, "Enable Tor" checkbox remains checked even if I click "No" in confirm installing Orbot window. I can bypass this confirm window by clicking somewhere else. I can accidentally remove confirm window without noticing it by double clicking.

**Comment by Urkki** [comment]
By the way, I tried it with Samsung Galaxy Nexus, Android version 4.2.1.

**Comment by kienme** [comment]
I can fix it. Can I work on this?

**Comment by fgei** [comment]
@kienme: sure!

@nilnilnil: how about if Orbot is already installed and the user click "no" on the "Start Orbot" dialog? preference should be still enabled or disabled?

**Comment by nilnilnil** [comment]
I don't think we should ever allow the user to be under the impression they're using Tor when they are not. That's bad UX. We should scream loudly in those cases. You either are using Tor, or not. Anything in the middle is confusing for general users trying to optimize for anonymity and decreases clarity on how they're being protected.

**Comment by fgei** [comment]
ok, just to clarify if the Tor Setting is enabled and Orbot is still not enabled, the app shows you the dialog to start Orbot every time you try to open a story or search anything, and if you don't start orbot the WebView won't load anything.

**Comment by nilnilnil** [comment]
Perfect :smile:. It should be pedantic about the use of Tor.

**Comment by kienme** [comment]
Yes, that is the issue.

On Thu, Feb 11, 2016 at 9:22 PM, fgei <notifications@github.com> wrote:

> ok, just to clarify if the Tor Setting is enabled and Orbot is still not
> enabled, the app shows you the dialog to start Orbot every time you try to
> open a story or search anything, and if you don't start orbot the WebView
> won't load anything.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/duckduckgo/android/issues/205#issuecomment-182928021>.
>



-- 
Ravikiran R
Student, Developer
<http://in.linkedin.com/in/kienme> <https://github.com/kienme>
<https://plus.google.com/+RavikiranIyerPlus>

**Comment by nilnilnil** [comment]
Wait, you're saying you want it to be less rigid @kienme?

**Comment by nilnilnil** [comment]
If we're going to continue this conversation, can we add screenshots as well?

**Comment by kienme** [comment]
@nilnilnil : The last comment by @fgei perfectly describes the issue

**Comment by nilnilnil** [comment]
That seems like a feature, not a bug to me.

**Comment by fgei** [comment]
yep, I agree with @nilnilnil

**Comment by kienme** [comment]
Oh, I thought the clarity was for the description of the bug. And yes, I suggest it be less rigid. It should suffice for the app to disable the checkbox if user chooses not to install Orbot.

**Comment by nilnilnil** [comment]
@kienme We really appreciate the feedback, but we don't think it's a good idea not to be pedantic about the use of Tor. We need to over communicate expectations about it's use, so people don't make mistakes. Thanks again!
