### ISSUE TITLE
[Bug] Trackers NOT correctly BLOCKED

### ISSUE THREAD

**Issue by Matty003** [duckduckgo/Android#2055]
m.cricbuzz.com in DDG Mobile :-
![Screenshot_2022-07-07-22-22-41-150_com duckduckgo mobile android](https://user-images.githubusercontent.com/109008434/178128716-1f25b5c2-2d45-4897-b74e-99ca9292bf9c.jpg)

Same Website in Firefox mobile:-
![Screenshot_2022-07-07-22-22-59-318_org mozilla fenix](https://user-images.githubusercontent.com/109008434/178128723-f2733eb8-e90a-4369-a8a0-7847422b5318.jpg)

CORRECT BEHAVIOUR :-
Two trackers ( ade.clmbtech and static.clmbtech ) must be blocked as they can lead to privacy issues since they are present in very few mainstream sites.

**Comment by Matty003** [comment]
Closing the issue as no response from anyone. Thanks

**Comment by Matty003** [comment]
Still trackers not blocked as of version 5.136.0

![IMG_20221017_211513](https://user-images.githubusercontent.com/109008434/196223058-53303110-2e75-4e31-b45f-918ca03101c7.jpg)

**Comment by cmonfortep** [comment]
@Matty003 our tracker blocking works using the data provided by https://github.com/duckduckgo/tracker-radar. If you have any questions / bug report, that's the best place for you to ask.

Please, if you report any other issue, follow our GitHub issue template for bugs. Thanks.

**Comment by Matty003** [comment]
My bad @cmonfortep . Will do the necessary steps as suggested by you. Thanks 👍
