### ISSUE TITLE
[Feature request] Incognito mode automatically in Gboard

### ISSUE THREAD

**Issue by BigNickBurgess** [duckduckgo/Android#206]
Firefox Focus seems to do this automatically and it would be great if duckduck could do it too as an added privacy feature.

Not sure if the same can be done for swiftkey too but Gboard would be a great start.

**Comment by dar5hak** [comment]
Turns out it's a new generic API, and not specific to Gboard. It's just that Gboard is currently the only one respecting the flag.

More information here: https://www.xda-developers.com/api-apps-keyboard-incognito-mode/

**Comment by BigNickBurgess** [comment]
Ahh nice info.  A good feature to add for when other keyboards support it though.

**Comment by BigNickBurgess** [comment]
Glad to see this added in the latest beta, great work guys.

**Comment by CDRussell** [comment]
Our pleasure! 👍
