### ISSUE TITLE
FB Infer Analysis reported potential NullPointerException in DuckDuckGo.java

### ISSUE THREAD

**Issue by martinoluca** [duckduckgo/android#207]
Hello everyone,
Here's a potential NullPointerException reported by Facebook Infer.

src/com/duckduckgo/mobile/android/activity/DuckDuckGo.java:867: error: NULL_DEREFERENCE
      object feedObject last assigned on line 866 could be null and is dereferenced by call to feedItemSelected(...) at line 867

Here seems that in the implementation of `DdgDB::selectFeedById(...)`, if the used Cursor is empty, then the variable `out` will remain `null` (https://github.com/duckduckgo/android/blob/8cc12ea7554d772fbecfcad224200a8f58a0656e/src/com/duckduckgo/mobile/android/db/DdgDB.java#L480) and the method will return `null`.

As a consequence of that, `feedItemSelected(...)`, in its implementation, will invoke `getUrl()` on `null`, causing a NullPointerException (https://github.com/duckduckgo/android/blob/c48ef18557aaf6f594aa99465dd8cfeab3ae9cce/src/com/duckduckgo/mobile/android/activity/DuckDuckGo.java#L847).

.

Infer analysis can be triggered on this app with the following command:
```
infer --incremental -- gradle build
```
More info at http://fbinfer.com/docs/getting-started.html

**Comment by peterogithub** [comment]
Hello DuckDuckGo friends.

I am on the Infer static analysis team. We would like to refer to this github issue as an example of Infer finding something in open-source code, which then got fixed. We would do so in a blog post, and maybe in a research paper.

Is this OK with you? Would you have any reservations about us using this example?

I think it casts you only in a positive light: you fixed, afterall! But I thought it wold be respectful to check with you before we go ahead.

Thanks!

Peter O'Hearn
