### ISSUE TITLE
Export/Import unprotected sites / allow list

### ISSUE THREAD

**Issue by IOI-655321** [duckduckgo/Android#207]
Allow an easy import/export of allow listed sites, even better would be a shared format with your privacy essentials browser extension.

**Comment by cmonfortep** [comment]
Hello @IOI-655321  , thanks for taking the time to submit this feature request. Sorry for the very late response, we are currently going through old feature requests.

After internal discussion with the team, we've agreed that there's no plan in the foreseeable future to support this request. Should this change in the future, we'll update this conversation appropriately.
