### ISSUE TITLE
Import/Export bookmarks

### ISSUE THREAD

**Issue by IOI-655321** [duckduckgo/Android#209]
You have bookmarks so please add a basic import/export to them.  Would make starting from scratch a lot smoother to be able to import from a file like a standard browser if we choose to.

**Comment by RichyHBM** [comment]
Have done a first pass on this, got it exporting a basic CSV style bookmarks list

Is there any particular list type that would be preferred? If something like Json are there any limitations to using a 3rd party library?

**Comment by subsymbolic** [comment]
Thanks for contributing @RichyHBM. You are welcome to submit a PR however we aren't in a position to accept many community PRs at the moment. This will hopefully change in the future, see https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md.

**Comment by tulanevolk** [comment]
I replaced phone and would like to port my duckduckgo bookmarks from old to new. I would appreciate knowing how.

Thank you.

**Comment by rlourette** [comment]
Same here

**Comment by subsymbolic** [comment]
Thanks all for showing interest in import/export, we don't currently support it but do have it in our backlog. Keep 👍 it to show you want it. If the demand grows we may be able to bump the priority and get to it sooner.

**Comment by jdcrutch** [comment]
Just switched from Chrome to DDG on my Adroid tablet, and was disappointed to find that I can't transfer my bookmarks.

**Comment by dg-demers** [comment]
Please add the bookmark import/export function.
And until you do please tell me where the bookmark file is stored, what format it's in, and whether rooting my Android phone is necesssary to access it.

**Comment by Jaason** [comment]
Actually, I have a similar question. I have opened more than >100 tabs. I want to check them, but it's easier to get through it on the desktop. Where I can find a file with opened tabs? Is there any?

**Comment by kolmercm** [comment]
We need import/export features for DuckDuckGo! I have so many bookmarks I can't spend the time to transfer them one by one!

**Comment by cooncreek40** [comment]
Yes, please implement a bookmark import feature. Also, set up a folder option for bookmark organization. These two issues are seriously the only items stopping my from setting DDG to my default browser.

Thank you.

**Comment by kso9** [comment]
> Please add the bookmark import/export function.
> And until you do please tell me where the bookmark file is stored, what format it's in, and whether rooting my Android phone is necesssary to access it.

That would work for me too short term. Is the bookmark file readable or encrypted on Android?

**Comment by alanStocco** [comment]
> > Please add the bookmark import/export function.
> > And until you do please tell me where the bookmark file is stored, what format it's in, and whether rooting my Android phone is necesssary to access it.
> 
> That would work for me too short term. Is the bookmark file readable or encrypted on Android?

Same situation. And I would be happy to help implement this important future.

**Comment by Gitoffthelawn** [comment]
I'm also very interested in having bookmarks import/export functionality.

A couple people have asked where and how they are currently stored, but there has been no response.  Could you answer those questions, please?

**Comment by icarus56** [comment]
Until you provide us with the basic non-brainer functionality of import/export bookmarks, surely the least you can do is tell us where they're stored.

**Comment by Dunkl** [comment]
I am using DDG within Safari, but if I could only export my bookmarks from there into your app, then I could use your app.
This is basic functionality, duckies.

**Comment by landry314** [comment]
Over 2 years and this isn't done? It seems like an easy job, no? export an HTML file with all the URLs to a directory of choice...

**Comment by X4l1b1** [comment]
> Until you provide us with the basic non-brainer functionality of import/export bookmarks, surely the least you can do is tell us where they're stored.
Not sure why no one has posted an answer about the bookmarks location, here's mine fwiw.

I tried to do that earlier today, ended up doing the following to extract the bookmarks using a terminal app (maybe the same can be done with adb):
> cd /data/data/com.duckduckgo.mobile.android/databases
> sqlite3 app.db
sqlite> .headers on
sqlite> .mode html
sqlite> .output data.html
sqlite> select * from bookmarks;
sqlite> .quit
> mv data.html /mnt/user/0/primary/Download/

I guess it requires the phone to be rooted though.

**Comment by calisamgal** [comment]
Please add an export bookmarks function!

**Comment by dg-demers** [comment]
> Not sure why no one has posted an answer about the bookmarks location, here's mine fwiw.
> 
> I tried to do that earlier today, ended up doing the following to extract the bookmarks using a terminal app (maybe the same can be done with adb):
> 
> ```
> > sqlite3 /data/data/com.duckduckgo.mobile.android/databases/app.db
> sqlite> .headers on
> sqlite> .mode html
> sqlite> .output data.html
> sqlite> select * from bookmarks;
> sqlite> .quit
> > mv /data/data/com.duckduckgo.mobile.android/databases/data.html /mnt/user/0/primary/Download/
> ```
> 
> I guess it requires the phone to be rooted though.

Much thanks to [**X4l1b1 (4libi)**](https://github.com/X4l1b1) for the above "DIY recipe." This is the most potentially useful comment so far, imho. But I haven't tried it yet (and may not if rooting is necessary).

And, although I sure wish they'd implement a bookmark export function, I charitably don't heap scorn on the developers of the DDG browser app. They must have more important (in their minds, at least) things to do right now.

**Comment by calisamgal** [comment]
Thanks X4l1b1 & dg-demers

**Comment by miGa77** [comment]
Please add bookmark import function! Since Firefox messed up, I wanted to switch to DuckDuckGo. I can't imagine you don't want take advantage of that massive failure of Mozilla... But it won't happen if you don't add import function!

**Comment by h908714124** [comment]
This is crucial, I have hundreds of bookmarks that will be lost when my phone breaks, even plain export (without import) would be enough to save me.

**Comment by Gitoffthelawn** [comment]
Given that basic import/export still has not been included in the DuckDuckGo mobile browser since that essential functionality was requested over 2.5 years ago, I underwent the painstaking process of manually exporting all my bookmarks from DuckDuckGo's mobile browser and then importing them into another browser that has import/export functionality (which turned out, surprisingly, to be a much better browser anyways).

My next step was to uninstall the DuckDuckGo mobile browser, as I now have no use for it.

I'm sorry to do this, but after 2.5 years, and almost no communication from DuckDuckGo, I had little choice but to move on.

**Comment by pal308** [comment]
Yes - agree with all prior posts - bookmark import capability from Safari, Chrome, and Edge would be much appreciated.  I am starting to use DDG and stop using Safari, Chrome, & Edge on 2 laptops, 2 iPhones, and 1 IPad.  
Import capability would be very helpful!

**Comment by timmyg558** [comment]
If this feature is not going to be added, at the very least it should be mentioned on in the application's help/info/tutorial areas. This will ensure that the browser isn't used for years and then users find out years worth of bookmarks are stuck on one device.

**Comment by marksjc** [comment]
I propose this missing and generally expected feature (import/export bookmarks) inhibits adoption by experienced users, often the most influential advocates.

**Comment by CityguyUSA** [comment]
Bump!

**Comment by Rsm61** [comment]
I'd love to be able to use DDG as my default, but unless I can mass import my 1k+ bookmarks, I won't be doing it, and I'm not about to do that manually. I can't believe this browser doesn't have an import/export feature? Too bad, this could've been a great thing.

**Comment by Paleogirl2003** [comment]
This is a huge missing feature, please add this

**Comment by tulanevolk** [comment]
We have been posting here for years,

...and no response.

I suspect DuckDuckGo us not monitoring it.

David

**Comment by cmonfortep** [comment]
Sorry folks for the no updates here. But yes, we listen to your feedback and it's something we are pushing internally to make this happen.

That being said, before having import/export we need to implement some kind of folder structure inside our bookmarks. That's our current main blocker here before implementing this very requested feature. But we will get to it 🤞

**Comment by marksjc** [comment]
Is this lack of folder issue related to DDG being a search app rather than a true browser?  I honestly don't know the difference, but from the general description I can see how the functions would diverge.

**Comment by Gitoffthelawn** [comment]
@cmonfortep wrote: *"Sorry folks for the no updates here. But yes, we listen to your feedback..."*

Then why no response for well over a year while *many* people have written posts and people like myself finally had to resort to manually exporting all bookmarks and then uninstalled the DuckDuckGo browser?

When people are truly listening, they tend to respond and provide constructive feedback.  "Listening" but not responding is quite inconsiderate.

Frankly, DuckDuckGo's actions do not match your words.

**Comment by strikinglyfamiliar** [comment]
> Is this lack of folder issue related to DDG being a search app rather than a true browser? I honestly don't know the difference, but from the general description I can see how the functions would diverge.

I suspect that it's because of the differences between a search app and a true browser. However, if the data is stored, it may be the file type creating the issue. Which if they could either code a file extension conversion or utilize a third party software that could possibly resolve the hiccup. But then we stand a chance of interrupting the whole individual privacy policy in Duckduckgo. Which brings to mind another question. If we utilize the cell phone as a drive on our computer, and use

**Comment by strikinglyfamiliar** [comment]
power shell IDE to extract, then have the data inserted into a new file with a different extension. I'm going to test this today.

**Comment by cmonfortep** [comment]
@strikinglyfamiliar will try to explain "the folder" reference. Based on the comments from many people here, there are 2 things to cover: to import/export bookmarks from our app into our app (another device maybe?) or another browser, or import/export bookmarks from another browser into our browser.

We want to build something that covers both. Currently, we don't have folders for bookmarks in our app, and we think in order to support importing bookmarks from other browsers we need to have that structure in place. This is just to honour the structure uses have for their bookmarks in other browsers. Thanks!

**Comment by UglyCasan0va** [comment]
So guess this is never happening.. Bummer.

**Comment by strikinglyfamiliar** [comment]
> @strikinglyfamiliar will try to explain "the folder" reference. Based on the comments from many people here, there are 2 things to cover: to import/export bookmarks from our app into our app (another device maybe?) or another browser, or import/export bookmarks from another browser into our browser.
> 
> We want to build something that covers both. Currently, we don't have folders for bookmarks in our app, and we think in order to support importing bookmarks from other browsers we need to have that structure in place. This is just to honour the structure users have for their bookmarks in other browsers. Thanks!

While I understand the folder issue, as you have explained you/they know what the problem or issue is, and what should be done to fix it. Next logical step would be to code it, test it and launch the fix. I'd love to run the app through MIT's app simulator, just to see what could be done.  Any idea who I would talk to about getting the source code for it? I don't want to just take without permissions, and think it would be fun to work on in my spare time.

**Comment by chefren** [comment]
For those that are still frustrated, would like to do the big effort of copying manually but don't have time. A workaround is to use the camera on the other phone with google lens as an OCR, tried on android, made it much faster although still painful

**Comment by tulanevolk** [comment]
Creative.

Definitely tedious.

Dave

**Comment by britchey5** [comment]
FYI microsoft edge can be set to use duckduckgo as the default search engine (and home page).  This isn't the same as using the ddg app, but until importing of bookmarks is released there is a solution.

**Comment by Gitoffthelawn** [comment]
@britchey5 I would not recommend using Microsoft Edge.  You are much better off using something like Privacy Browser, which is fully open-source and is freely available here: https://f-droid.org/packages/com.stoutner.privacybrowser.standard/

It has import/export functionality, and many more important functions.  IMHO, it makes DDG's browser obsolete.

**Comment by tulanevolk** [comment]
DuckDuckGo does not like that!

Dave

**Comment by Gitoffthelawn** [comment]
> DuckDuckGo does not like that!

LOL. I don't know about that. It depends on DuckDuckGo's values and goals.  People with virtuous values tend to like and support projects that promote similar values.

**Comment by daveraji** [comment]
I would also like the import/export bookmarks feature on duckduckgo mobile browser. (y)

**Comment by Paleogirl2003** [comment]
I just switched to Brave due to this, but I set DDG as my search engine

**Comment by Windstrings** [comment]
The ability to import bookmarks which took years to build may have a serious impact on duck ducks success for new downloads and real use.
Otherwise I will only use it on special occasions... It's not a real browser yet... At least not a usable one for real life.

**Comment by larkim66** [comment]
So for the developers of DDG, providing a simple way for potential new users to import  bookmarks accumulated over many years of Internet browsing, is 'NOT' seen as a highest priority??? 

Me thinks a reality check is in order, they need to get their priorities right!....I can't believe they have not identified that this issue is a REAL deal breaker. You guys need to talk to each other and decide if you want people to use DGG or not? It really is 'that' simple.

**Comment by UTalking2Me** [comment]
> So for the developers of DDG, providing a simple way for potential new users to import bookmarks accumulated over many years of Internet browsing, is 'NOT' seen as a highest priority???
> 
> Me thinks a reality check is in order, they need to get their priorities right!....I can't believe they have not identified that this issue is a REAL deal breaker. You guys need to talk to each other and decide if you want people to use DGG or not? It really is 'that' simple.

Amen Larkim66! After using another browser for years now why would anyone want to abandon their bookmarks. Looks like I’ll be looking for another browser that has an import feature. Really DDG?

**Comment by kgbandido** [comment]
> > So for the developers of DDG, providing a simple way for potential new users to import bookmarks accumulated over many years of Internet browsing, is 'NOT' seen as a highest priority???
> > Me thinks a reality check is in order, they need to get their priorities right!....I can't believe they have not identified that this issue is a REAL deal breaker. You guys need to talk to each other and decide if you want people to use DGG or not? It really is 'that' simple.
> 
> Amen Larkim66! After using another browser for years now why would anyone want to abandon their bookmarks. Looks like I’ll be looking for another browser that has an import feature. Really DDG?

Would love to fully commit to the switch from google but looks like there is too many basic features that DuckDuckGo doesn't have.

**Comment by Gitoffthelawn** [comment]
> 
> 
> > > So for the developers of DDG, providing a simple way for potential new users to import bookmarks accumulated over many years of Internet browsing, is 'NOT' seen as a highest priority???
> > > Me thinks a reality check is in order, they need to get their priorities right!....I can't believe they have not identified that this issue is a REAL deal breaker. You guys need to talk to each other and decide if you want people to use DGG or not? It really is 'that' simple.
> > 
> > 
> > Amen Larkim66! After using another browser for years now why would anyone want to abandon their bookmarks. Looks like I’ll be looking for another browser that has an import feature. Really DDG?
> 
> Would love to fully commit to the switch from google but looks like there is too many basic features that DuckDuckGo doesn't have.

If you want to get rid of Google, but are tired of waiting years for DDG, just use Privacy Browser:  
https://f-droid.org/packages/com.stoutner.privacybrowser.standard/

It's completely open-source and works very well.  Plus it has many more features than the DDG browser.

After trying it, I don't miss the DDG browser at all.  Sorry DDG, but as they say: *"you snooze, you lose".*

**Comment by alan933** [comment]
There's no way to get bookmarks across phones????? W            T          H!!

**Comment by LinuxJoeUser** [comment]
> @strikinglyfamiliar will try to explain "the folder" reference. Based on the comments from many people here, there are 2 things to cover: to import/export bookmarks from our app into our app (another device maybe?) or another browser, or import/export bookmarks from another browser into our browser.
> 
> We want to build something that covers both. Currently, we don't have folders for bookmarks in our app, and we think in order to support importing bookmarks from other browsers we need to have that structure in place. This is just to honour the structure users have for their bookmarks in other browsers. Thanks!

I understand wanting to have both at once, but in the short - to - medium term I'd urge you to consider just having at least one or the other.  At least don't lose your current, loyal users.  Give them a way to transfer their bookmarks from DDG on _one_ device into DDG on _another_ device or --- like me --- they'll be forced to choose another browser when they get a new phone.

Once you've secured your current users (maybe with something as simple as a .csv file?) you could wrestle with the trickier job of folder structures and other browsers and such.

Import/export notwithstanding, the DDG browser is my fave browser for phones.  I'll keep it installed, so as _soon_ as this issue is resolved somehow, I can return to it. Until then make do with Brave or something.

**Comment by alan933** [comment]
I copied all my bookmarks on one android phone to OneNote. That took a while. I am now in the process of copying all of those links in OneNote to my new Android phone with DuckDuckGo. It's taking a while.

**Comment by h908714124** [comment]
@cmonfortep I don't think this has to wait for the "folder structure" feature. Export could dump everything into a single folder, and import could ignore (flatten) the folder structure. That way, import/export to interoperable format is possible right now, just by adding two buttons "Import bookmarks" and "Export bookmarks". What's stopping you?

**Comment by oldphones68** [comment]
@alan933 Don't know how much bookmarks you had. But, imagine, if I have 2000+ bookmarks in a browser and I need to switch in thus way, it may become a nightmare.
Hope devs will give thus issue a triage.

**Comment by Gitoffthelawn** [comment]
> Hope devs will give thus [sic] issue a triage.

LOL.  Issue was reported over 2 years ago.
