### ISSUE TITLE
[Bug] Font color in dark mode

### ISSUE THREAD

**Issue by MedzikUser** [duckduckgo/Android#2099]
### Describe the bug

![image](https://i.imgur.com/BarWcbD.jpg)

### How to Reproduce

1. Go to 'Settings'
2. Scrool down to 'Fireproof sites'

### Expected behavior

Should be other

### Environment

```markdown
- DDG App Version: 5.130.0
- Device: Realme 8
- OS: Android 12
```

**Comment by NaaeemMalik** [comment]
Hi guys
can I fix this issue?

**Comment by MedzikUser** [comment]
Fixed in the latest version
