### ISSUE TITLE
Feature request: dark theme widget

### ISSUE THREAD

**Issue by JasperWeiss** [duckduckgo/android#211]
I'd like to have a dark theme widget.
Shouldn't be hard to make. If that could be done that'd be great!

Thanks

**Comment by Abledsoul** [comment]
dark theme search useing duck duck go for android. Sounds cool. Let's try.

**Comment by thm** [comment]
Closing this since this is over 3 months old. @JasperWeiss thanks for the feature-request, I'll move it internally.
