### ISSUE TITLE
Could not build using android studio

### ISSUE THREAD

**Issue by vyasgiridhar** [duckduckgo/android#212]
Building leads to error :

Error:Configuration with name 'default' not found.

**Comment by fgei** [comment]
can you check if you have all the support libraries?
did you clone the onion kit too?

**Comment by vyasgiridhar** [comment]
How do i do that?

**Comment by vyasgiridhar** [comment]
i have cloned the library but i still keep getting the same errors 

Error:A problem occurred configuring root project 'android'.
> Failed to notify project evaluation listener.
   > Cannot evaluate module libnetcipher : Configuration with name 'default' not found.
   > Could not resolve all dependencies for configuration ':compile'.
      > Module version :android:unspecified, configuration 'compile' declares a dependency on configuration 'default' which is not declared in the module descriptor for android.libs.OnionKit:libnetcipher:unspecified
