### ISSUE TITLE
Share menu requires extra step

### ISSUE THREAD

**Issue by thm** [duckduckgo/android#214]
How to reproduce:
1. Update to Android 6.0.1
2. Share a story from its 3-dot-menu
3. Result: you have to tap "Android System" before seeing the actual share menu

Here's a demo: http://cl.ly/0j283u0l2D1h

cc @moollaza

**Comment by fgei** [comment]
yep, same problem here, on 6.0 it shows the share intent fine, but on 6.0.1 there's the "Android System" options.
I think it has something to do with the intent chooser, checking now
