### ISSUE TITLE
[Bug] Ufile doesn't download and results in a html file instead of the download 

### ISSUE THREAD

**Issue by Kita2345** [duckduckgo/Android#2148]
### Describe the bug

When I press download, it downloads a HTML file instead of the actual file that I want

### How to Reproduce

I have some sample links here.

https://macapps.ufile.io/pfjlbgd5
https://macapps.ufile.io/w6apnkkl
https://macapps.ufile.io/4rl7pt16
https://macapps.ufile.io/bti1wgqe
https://macapps.ufile.io/wlfa9q5c

### Expected behavior

have to download the actual file

### Environment

```markdown
- DDG App Version: 5.132.0
- Device:
- OS: Android 9
```

**Comment by cmonfortep** [comment]
Tested this with our latest version and I couldn't reproduce the issue. 

Please, update the app and let us know if the issue is still present. Thanks.

**Comment by Kita2345** [comment]
Bagi saya ekstensi file sudah benar tetapi ukuran file tidak cocok.
