### ISSUE TITLE
Bug: Photo upload buttons are not working properly on the duckduckgo app

### ISSUE THREAD

**Issue by Daiky96** [duckduckgo/Android#218]
#### Expected behavior
I want to make a post steemit through busy site, but when I try to upload photos it turns out the menu does not work, should be when I press the upload button photo, I immediately confronted into the gallery to select the photo you want to upload. this also happens when i try it through steemit.com site. should after I pressed the photo upload menu, I was immediately confronted into the gallery to select the photos I wanted to upload.
#### Actual behavior
Button apload photos steemit, busy, and other sites do not work at duckduckgo applications. At that time I tried to access steemit via duckduckgo app to make a post, but I was very surprised when I tried to upload the photo was not able, I pressed it repeatedly but still not work. 

#### How to reproduce

* Browser: the latest duckduckgo app
* Operating system: Android 6.0.1
* Smartphone: Xiaomi 3s

#### Recording Of The Bug
https://youtu.be/wXnoyoB0bco

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@daiky69/bug-photo-upload-buttons-are-not-working-properly-on-the-duckduckgo-app">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ghavaunraaf** [comment]
Ghavaunbrooklyn@raafg.com

**Comment by ghavaunraaf** [comment]
Ghavaunbrooklyn@raafg.com

**Comment by hjoshi123** [comment]
@Daiky96 Can I be assigned to the bug?

**Comment by CDRussell** [comment]
This was implemented in https://github.com/duckduckgo/Android/pull/227

It will be available in the next release; likely next week.

**Comment by CDRussell** [comment]
@hjoshi123 feel free to check out the code on `develop` branch and have a play with it before it goes life if you want.

Feedback always welcome.
