### ISSUE TITLE
No README.md?

### ISSUE THREAD

**Issue by S2606** [duckduckgo/Android#22]
It seems as if this repo is lacking a basic readme.md where a basic description of the App followed by 2-3 snapshots of the app's UI would be beneficial.If yes,I would love to contribute on this one.

**Comment by ikocevski** [comment]
Just do it :D

**Comment by abhaymaniyar** [comment]
Hey @S2606 ! Have you prepared any template for README of this repo? If you have not started working on it yet, I would like to contribute to this project.

**Comment by S2606** [comment]
Hey @abhaymaniyar Sure go Ahead!

**Comment by abhaymaniyar** [comment]
Awesome! Thanks @S2606  :smile:  Apart from this I also want to contribute something else to this project and going through the code base for the same. :smile:

**Comment by S2606** [comment]
You'r welcome @abhaymaniyar and all the best!!

**Comment by abhaymaniyar** [comment]
I have written a README.md for this repo. Should I create a PR for the same?

**Comment by S2606** [comment]
@abhaymaniyar yes

**Comment by subsymbolic** [comment]
Great suggestion @S2606 and thanks for the PR @abhaymaniyar. We're still in the early prototyping phase for this app so I have added a specific readme to communicate this.
