### ISSUE TITLE
net::ERR_TIMED_OUT under TOR

### ISSUE THREAD

**Issue by moshpirit** [duckduckgo/android#222]
When I try to search anything, I always get this error (I always use TOR). After a reload, everything work perfectly.

I've just noticed that if I don't use it under TOR, it works as expected.

It's a pitty that such great searcher became an annoying one just because of this. Any idea of why is this happening?

Some information:

- Device: BQ Aquaris M5 (not rooted)
- Android 5.1.1
- DuckDuckGo Version 3.0.12 [from F-droid](https://f-droid.org/repository/browse/?fdid=com.duckduckgo.mobile.android)

**Comment by Skiamakhos** [comment]
Bump!
If we take it as read that Tor connections are going to be slower, we need a more tolerant client to be able to use it. Ideally some way to expand the amount of time that passes before you get this error. Personally I find timeouts frustrating: I don't want to see this. I want my device to keep trying till it gets somewhere, or if there's genuinely no traffic after a couple of minutes, fine, then error. As it is, this error just means "You're on a mobile network. It's slow."

**Comment by alohaas** [comment]
@nilnilnil do you want to weigh in here?

**Comment by nilnilnil** [comment]
@alohaas can you replicate this issue on your Android phone? I don't have one. @fgei what about you?

Also, it's unclear whether or not the F-droid version of the app is fully up to date. We only officially deploy via duckduckgo.com APKs and Google Play.

**Comment by fgei** [comment]
@nilnilnil I'm not sure about the problem exactly, the app is working fine for me, with Tor enabled or disabled

3.0.12 is the version we have on the play store, so I assume the F-droid is up to date

**Comment by nilnilnil** [comment]
@moshpirit are you still experiencing this issue? @Skiamakhos can you confirm as well?

**Comment by moshpirit** [comment]
Yes, I'm still experiencing it. It's really weird because I actually rooted my phone some weeks ago and disabling the Tor option on DDG but torifiying it directly from Orbot works perfectly and I get no errors.

So, both times under Tor, but by different ways.

**Comment by tagawa** [comment]
I'm not able to reproduce this either. Here's what I'm trying:

**Phone OS:** CyanogenMod 11
**DDG app:** 3.0.12 (74) from F-Droid (note: F-Droid is up-to-date)
**Orbot:** 15.0.1-RC-3-PIE (Tor 0.2.6.10)

**Steps:**
1. Start Orbot
2. Open DDG app
3. In Settings, check "Enable Tor"
4. Click "Check Orbot status"

I get the usual "Congratulations" message and any searching in the app after that is fine. Noticeably slower than without Tor but no timeout errors.

**Comment by Skiamakhos** [comment]
Interestingly it seems to be happening a lot less now. I wonder if it's
because I enabled TOR VPN for all apps..?

**Comment by moshpirit** [comment]
@tagawa could you please try to stop DDG, opening it again and search something under Tor? I think it might help to reproduce the steps

**Comment by alohaas** [comment]
if @tagawa cannot reproduce the issue, I'll give it a shot as well.

**Comment by tagawa** [comment]
@moshpirit Just tried that - still slow but it works eventually with no errors.

**Comment by edgesince84** [comment]
hey @moshpirit I wanted to see if you still were experiencing this issue.  Let me know!

In the meantime, I'd like to invite you to our [new forum](https://forum.duckduckhack.com/) to preview how we're improving programming-related searches. There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).
