### ISSUE TITLE
`Start Orbot?` popup is not dismissed when the app is minimised

### ISSUE THREAD

**Issue by gmarty** [duckduckgo/android#224]
With the `Enable Tor` settings enabled, when the app is launched or maximised, the `Start Orbot?` message opens. It stays there when the app is minimised.
As a result, opening and minimising the app several times will open as many popups with the same message.

I'm expecting the Orbot popup to be only displayed once at all time.

**Comment by seales** [comment]
I can re-reproduce it

**Comment by fgei** [comment]
It seems now OrbotHelper doesn't include any dialog, so we can implement our own and dismiss it whenever the activity is paused
reference to #227 as we are talking about upgrading NetCipher to the last release

**Comment by dev-vishalgaurav** [comment]
@fgei I have added a pull request for this issue. I think this will be good for existing version of the app and takes care of existing flow and Dialog UI. Let me know your views on it.
