### ISSUE TITLE
Can't download searched images

### ISSUE THREAD

**Issue by GAumala** [duckduckgo/android#226]
I like to look up funny images on duckduckgo and share them with my friends via messaging apps. I haven't seen a download button anywhere, even after pressing the "view file" button. I don't like having to open the image in my default browser just to download it. If it is Ok, I'd love to work on this feature.

**Comment by nilnilnil** [comment]
This is being worked on at: https://github.com/duckduckgo/android/pull/225. Feel free to join the discussion!

**Comment by GAumala** [comment]
Cool, thx!
