### ISSUE TITLE
[Bug] <Tracking Protection Feature>

### ISSUE THREAD

**Issue by TheGoldenSun** [duckduckgo/Android#2263]
### Describe the bug

 Your tracking protection feature should be improved and updated to scan every single app that has big companies tracking on Android users, especially when it comes to the NSA or MI6 department, we all need to be prepared and secured from spying networks, so please it'd be best to create an AI bot of duckduckgo to allow itself to scan every single android app just in case if your tracking protection feature disables itself your new AI bot will automatically scan all apps before enabling the tracking protection feature once again. 

### How to Reproduce

![Screenshot_20220907_152404](https://user-images.githubusercontent.com/104534608/188960721-a50d2cf2-98f6-432c-b5d2-f2e277cdcb89.png)

### Expected behavior

Long on-going bug issues should be fixed with an idea of improvement for all duckduckgo users. 

### Environment

```markdown
DDG App Version: 5.136.0

Device: SM-A215u & SM-S124DL

OS: Android 6.0 and up
```

**Comment by cmonfortep** [comment]
Thanks. We are currently working on improving that specific issue. We are aware our protection is sometimes disabled by the system and we are investigating ways to automatically enable it when that happens. Thanks.
