### ISSUE TITLE
[Bug] <Voice typing>

### ISSUE THREAD

**Issue by TheGoldenSun** [duckduckgo/Android#2281]
### Describe the bug

Voice typing from Google keyboard is disabled.

### How to Reproduce

1. Enable voice typing that's from google keyboard

2. Improve the app with brand new features not default features.

3. Users should receive a notification if the duckduckgo app had scanned every other app.

4. Update tracking protection statistic results for better usage when duckduckgo is scanning apps.

### Expected behavior

![Screenshot_20220914_140744](https://user-images.githubusercontent.com/104534608/190230911-92bee0be-d1bf-4e1e-8d7c-0a7e54e46364.png)

### Environment

```markdown
- DDG App Version:5.137.1
- Device: Galaxy a21 
- OS: android 6.0 and up
```

**Comment by TheGoldenSun** [comment]
My Tracking protection feature was disabled again when I just got home recently, idk why is this happening to me so I had to enable it again.

**Comment by cmonfortep** [comment]
About the keyboard issue. We request keyboards don't use anything typed into our app for personalization. It's up to each keyboard to decide how to honor that setting. In your case, microphone is disabled as well.

**Comment by TheGoldenSun** [comment]
That bamboozles me because if I don't know how to spell a word properly by using your duckduckgo search engine manually that means you guys holds nothing back to be fair for people  who simply wants to use the voice typing feature in YOUR app.
