### ISSUE TITLE
[Bug] javascript window.innerHeight not correct

### ISSUE THREAD

**Issue by Jehfen** [duckduckgo/Android#2288]
### Describe the bug

Javascript window.innerHeight does not return the correct height of the mobile window when the address bar is visible.
As a result, websites with a fullscreen layout are "clipped", content at the bottom of a fullscreen page is shifted below the "fold" (not visible in the initial screen).

### How to Reproduce

1. go to any website that has a fullscreen layout, e.g. with a fullscreen background on the initial page

### Expected behavior

window.innerHeight should return the correct height, that is **without** the address bar height.
This works fine in Chrome and Firefox.

### Environment

```markdown
- DDG App Version: latest
- Device: Mobile phone
- OS: Android 12
```

**Comment by cmonfortep** [comment]
It seems related to https://github.com/duckduckgo/Android/issues/914

Thanks.
