### ISSUE TITLE
Optimize Database Code

### ISSUE THREAD

**Issue by hkasera** [duckduckgo/android#229]
In the file [`DdgDB.java`](https://github.com/duckduckgo/android/blob/master/src/com/duckduckgo/mobile/android/db/DdgDB.java), I noticed that the code is not optimized. 
For example, the field names of tables are hard coded everywhere. I suggest that we create a file called `DdgContracts.java` which lists all the constants like the table name and the fields in the table. The file `DdgDB.java` should then use these constants everywhere. This will help make the code more maintainable. 

I would be happy to send a PR for the same. Let me know if this is a welcome contribution right now.

Thanks,
Harshita

**Comment by fgei** [comment]
Thanks yes, this would be a really nice addiction!

**Comment by hkasera** [comment]
@fgei Great! I will start working on this and send a PR as I am done :+1:

**Comment by mickeypash** [comment]
I was looking at the class. Have you submitted your PR?

**Comment by moollaza** [comment]
@mickeypash I don't see anything yet. It looks like this was discussed quite a while ago so you should be Ok to tackle it if you'd like.

@hkasera are you still interested in working on this?

**Comment by hkasera** [comment]
Apologies for the delay. I will finish it by this week. If I am unable to do so, @mickeypash you can go ahead :)

**Comment by edgesince84** [comment]
@mickeypash looks like you've got the go-ahead! 👍  Are you going to take this on?

**Comment by edgesince84** [comment]
@hkasera sounds like a plan!  We've invited you to the contributors team, so you should have that invite in your email.  When you accept that, we can assign this to you for the week. 👍

**Comment by hkasera** [comment]
@edgesince84 I just joined through the invite. Looking forward to working on the task :smile:

**Comment by edgesince84** [comment]
@hkasera awesome!

**Comment by hkasera** [comment]
@edgesince84 I just sent a PR with the fixes. 
I see that the Travis CI has failed, but I am not sure why. I need some help in understanding what is the issue. The code that I committed works fine and I even ran the app on my phone to cross check. Let me know if I can do anything to fix the CI check. 
       Also, I was just checking the older PR's, even in those the CI tests are failing. So, is there a bug in the CI test? 
Let me know if I can do any modification to resolve this.

Thanks,
Harshita

**Comment by edgesince84** [comment]
@hkasera I will have someone take a look at this for you ASAP!

**Comment by fgei** [comment]
Thanks for the PR @hkasera. Travis is always failing to build because it's not configured!
I'm gonna open an issue to fix that

**Comment by hkasera** [comment]
Sure @fgei 1 Thanks :+1:

**Comment by mickeypash** [comment]
Good job @hkasera 
Minor point, I would have imported the `DdgDBContracts` statically.
So instead of having `DdgDBContracts.APP_TABLE.TABLE_NAME` you would have `APP_TABLE.TABLE_NAME`

**Comment by hkasera** [comment]
@mickeypash : I think that is a fair ask. I would love to send another PR with this change. It will definitely be sensible to do it now. Let me know if I can go ahead and pick it up 😃

**Comment by moollaza** [comment]
> Let me know if I can go ahead and pick it up

@hkasera you're welcome to pick it up!

**Comment by hkasera** [comment]
@mollaza Great will send a PR as soon as possible 😃

**Comment by edgesince84** [comment]
@hkasera are you still planning on sending a PR for this?

If not, I hope you're still interested in contributing to DuckDuckHack! I'm reaching out to let you know that we recently launched a new forum with the initiative of improving programming-related searches, and I hope you'll [join us](https://forum.duckduckhack.com/)!

There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).
