### ISSUE TITLE
[Bug] Accessing the app download link does not redirect to Play Store

### ISSUE THREAD

**Issue by Kita2345** [duckduckgo/Android#2314]
### Describe the bug

The user is prompted to download the "apk" file.

### How to Reproduce

1. Go to https://m.intl.taobao.com/
2. Tap on the download app button located at the bottom of the page.
3. Observe the behaviour.

### Expected behavior

The user is redirected to Play Store.

### Environment

```markdown
- DDG App Version: latest 
- Device:
- OS: Android 9
```

**Comment by cmonfortep** [comment]
That seems a problem of the site you are sharing. We haven't received any similar feedback of that happening on other sites.
