### ISSUE TITLE
[Bug] <Tracking Protection>

### ISSUE THREAD

**Issue by TheGoldenSun** [duckduckgo/Android#2351]
### Describe the bug

When turning on the tracking protection sometimes it doesn't load my YouTube app properly which means I suspect that your HTTP exception is blocking other applications android users have on their smartphones.

### How to Reproduce

1. Fix http exception that's causing an issue 
2. Improve tracking protection feature
3. Add a new feature where it'll block any explicit content duckduckgo users would see from any website.
4. The loading sequence within other apps besides YouTube has been an ongoing issue till this day for me.

### Expected behavior

It is wonderful to use the VPN feature to block all malicious content however it seems that a conflict between the http exception and tracking protection is unsolved since most smartphone apps cannot load themselves faster. 

![Screenshot_20221004_052807](https://user-images.githubusercontent.com/104534608/193787221-beb5f6f8-1bc1-4e90-b116-5332f206d7e4.png)

### Environment

```markdown
- DDG App Version: 5.138.1
- Device: Galaxy a21 and Galaxy A02s
- OS: android 11
```

**Comment by cmonfortep** [comment]
youtube is currently disabled in our app tracker protection config because of known issues. So in this case, our vpn is not interfering with the connection.

**Comment by TheGoldenSun** [comment]
Yes it is interfering it because whenever continuously loads within my YouTube app while having YOUR duckduckgo von feature on that tells me that it is rejecting YouTube's client connections, it only works when I turn off duckduckgo's vpn feature, my apologies sir but it usually happens ONCE in a while whenever I launch any type of application I'm willing to use through my smartphone. I'm telling you the truth mate.

**Comment by TheGoldenSun** [comment]
So if you're willing to listen to my dearing feedback, then start being fair to duckduckgo users.

**Comment by cmonfortep** [comment]
I can only suggest going and ensuring youtube is disabled in your config: Settings -> App Tracking Protection -> scroll down to the bottom -> Having Problems with an App? -> Show All Apps -> then find Youtube app and ensure is disabled.
