### ISSUE TITLE
Last favourite not displaying when recent lists is empty

### ISSUE THREAD

**Issue by arrufat** [duckduckgo/android#236]
This first screenshot shows my recent and favourites:
![screenshot_20160515-173152](https://cloud.githubusercontent.com/assets/1671644/15275127/5afb5e26-1ac3-11e6-902b-8dab05b8d19f.png)

However, when I remove all my recent searches, the last favourite is not displayed either:
![screenshot_20160515-173207](https://cloud.githubusercontent.com/assets/1671644/15275128/5f218d18-1ac3-11e6-9715-d02a8bf3ade9.png)
Thanks in advance.

**Comment by arrufat** [comment]
Thank you :D

**Comment by alohaas** [comment]
@arrufat thanks for helping us with this issue!
