### ISSUE TITLE
Switch Tabs just by Swiping Address Bar

### ISSUE THREAD

**Issue by mightyjai** [duckduckgo/Android#237]

**Comment by mightyjai** [comment]
*my = by

**Comment by Paleogirl2003** [comment]
Yes pretty please! One of the only things I miss from chrome

**Comment by Cyberdroid1** [comment]
One of the most basic browser feature of current times. Please implement this!

**Comment by summersab** [comment]
Is this something @malmstein could tackle since they implemented swipe-to-refresh? Many users would love you forever...

**Comment by cmonfortep** [comment]
Hello @mightyjai  , thanks for taking the time to submit this feature request. Sorry for the very late response, we are currently going through old feature requests.

After internal discussion with the team, we've agreed that there's no plan in the foreseeable future to support this request. Should this change in the future, we'll update this conversation appropriately.
