### ISSUE TITLE
bug : empty title for a new tab

### ISSUE THREAD

**Issue by the-dagger** [duckduckgo/Android#24]
The new tab page shows empty title for new tabs opened.

Screenshot : 
![screenshot_20170624-192911](https://user-images.githubusercontent.com/6565270/27509133-aa1fe776-5913-11e7-8940-cfc7ccba224a.png)

It should show "New Tab" or 'Welcome" text instead.
I have fixed this locally, and waiting for the confirmation to send a PR for this if needed.

**Comment by subsymbolic** [comment]
Thanks for logging this! We're still at the prototyping phase at the moment but have a feature scheduled to implement a proper home page for a new tab, one which will not appear in the tabs list.
