### ISSUE TITLE
Browser popup menu height is too large

### ISSUE THREAD

**Issue by subsymbolic** [duckduckgo/Android#241]
The popup menu seems to be so large it goes out of bounds on the screen (especially on landscape mode).

The consequence is that the bottom menu item(s) aren't clickable as, even with the scrolling in there, they can never be scrolled up enough to be in view.

**Comment by subsymbolic** [comment]
Internal Asana Url: https://app.asana.com/0/414730916066338/595568080940526

**Comment by SmithSte** [comment]
I'v heard once before many time that the reponse of a website/theme/app is a nightmare for any developer. Can you give some details?
