### ISSUE TITLE
Can't stop audio when continuing to use app

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/android#241]
**Steps to reproduce:**
1. In the app, search for something that triggers the SoundCloud IA, e.g. "surfing girl soundcloud".
2. Click one of the items in the SoundCloud IA to start playing music.
3. Click on the "Home" icon (top left).
4. Continue browsing or searching in the app.

**What should happen:**
The music should stop when navigating away from the SoundCloud IA (or other active audio source).

**What actually happens:**
The music keeps playing and it's not possible to go back and stop it.

[Reported on Twitter](https://twitter.com/falconique/status/735578499117944837)

**Comment by fgei** [comment]
ok I can reproduce this
back button is working while the home button is not, so I assume we need to release the WebView when removing the WebView Fragment
going to check it now

**Comment by tagawa** [comment]
Very fast! Thank you @fgei
