### ISSUE TITLE
Can't open .apk files from notification after downloading

### ISSUE THREAD

**Issue by BDFrostbite** [duckduckgo/Android#243]
Steps to reproduce:
 - Go to any download site and download an .apk file. For example apkmirror.com
 - Open notification panel
 - Tap to Download completed notification
 - It will say "Can't open file" instead of opening .apk with Package installer

Side note: You'll need to add Install unknown apps permission to allow installing .apk files from DuckDuckGo for Android 8.0+

**Comment by CDRussell** [comment]
Fixed in #265
