### ISSUE TITLE
Github release apk's are downloading as .bin

### ISSUE THREAD

**Issue by BDFrostbite** [duckduckgo/Android#244]
Steps to reproduce:
 - Go to any repo's release section, for example github.com/DuckDuckGo/Android/releases
 - Select any .apk release, for example duckduckgo-5.1.0-release.apk
 - It'll be downloaded as <randomname>.bin

DuckDuckGo version: 5.1.0

**Comment by CDRussell** [comment]
Implemented in https://github.com/duckduckgo/Android/pull/265
