### ISSUE TITLE
Back button should close the browser

### ISSUE THREAD

**Issue by badener95** [duckduckgo/Android#245]
When opening a link from another app hitting the back button should close the browser to let users return to the app. At the moment this will bring up the start page of duckduckgo with the search bar. It takes 4 times hitting the back button to actually close duckduckgo and return to the previous app.

**Comment by waleedsamy** [comment]
+1

**Comment by badener95** [comment]
Any news on this? It has been here for 10 month now :(

**Comment by subsymbolic** [comment]
We are now actively working on this.

**Comment by badener95** [comment]
Seems like this got finally fixed. I will close the issue then.
