### ISSUE TITLE
Clearing cookies/cache doesn't clear local storage  - privacy risk

### ISSUE THREAD

**Issue by ryancastro** [duckduckgo/android#245]
On the Android App if you clear cookies, cache, and force stop the DuckDuckGo Application and reopen it, HTML5 local storage is still stored. This allows websites to store session information in local storage, and have you trackable even after you've cleared cache, cookies, and restarted the app.

Demo Steps:
1. Navigate to : http://html5demos.com/storage in duckduckgo
2. Save a value for local storage
3. refresh the page (Value is still saved)
4. Clear cache, cookies, and force stop the app, restart the app
5. Navigate to http://html5demos.com/storage

Result: 
Local storage value is still stored. Many websites use local storage for user tracking, and this presents a risk to users privacy.

**Comment by alohaas** [comment]
@nilnilnil related to https://github.com/duckduckgo/ios/issues/160 ?

**Comment by fgei** [comment]
I'm closing this, just merged PR #247 that solve this issue
