### ISSUE TITLE
[Bug] Fire button fade to white on dark theme 

### ISSUE THREAD

**Issue by Ammako** [duckduckgo/Android#2459]
### Describe the bug

The screen fades to white when using Fire button when on dark theme, since 5.141.0

### How to Reproduce

1. Be on 5.141.0
2. Be on dark theme
3. Use Fire button
4. Temporarily lose your eyesight from the resulting blinding light

### Expected behavior

It should fade to black as before

### Environment

```markdown
- DDG App Version: 5.141.0
- Device: Pixel 4a
- OS: Android 13
```

### Additional info

Possibly related? #2396

**Comment by cmonfortep** [comment]
Thanks, @Ammako, we are aware of this bug and it's in our short-term backlog. thanks.

**Comment by malmstein** [comment]
Fixed as part of https://github.com/duckduckgo/Android/pull/2569
