### ISSUE TITLE
Can be selected as Android assist app?

### ISSUE THREAD

**Issue by rugk** [duckduckgo/android#246]
![assistents](https://cloud.githubusercontent.com/assets/11966684/15807653/c48122ee-2b63-11e6-964d-6a36477b37f1.png)

I can select Firefox(-based) browsers and the DuckDuckGo app as assists on Android 6. I can find this setting under "Apps" -> "Default apps" -> "Assist &  voice input".
I wonder what this is and what DuckDuckGo (and Firefox) does when I enable it. I have not seen any difference and none of the apps offered me to read my screen or similar things...

**Comment by fgei** [comment]
this is the assist intent, if you try to long press the home button it will launch the app so you can use it to search something. by default on M you should get "Now on Tap", on sdk <=Lollipop you had to long press the home button and swipe up, it was called "the google now gesture"

**Comment by rugk** [comment]
Thanks for the information. However I'm a bit worried that enabling this also enables the app to take screenshots and read the screen output... Would be better if that is not neccessary for a simple search feature...
But well... DuckDuckGo is open source. :smiley:

**Comment by fgei** [comment]
well there's definitely no screenshot involved in here, when the app is launched with an ACTION_ASSIST intent we just display the SearchFragment

`else if(Intent.ACTION_ASSIST.equals(intent.getAction())){
            if(!DDGControlVar.mDuckDuckGoContainer.currentFragmentTag.equals(SearchFragment.TAG)
                    && !DDGControlVar.mDuckDuckGoContainer.currentFragmentTag.equals(SearchFragment.TAG_HOME_PAGE)) {
                displayScreen(SCREEN.SCR_SEARCH, true);
            }
        }`

**Comment by rugk** [comment]
Yeah, that's just what the "warning message" says when you enable this feature...
