### ISSUE TITLE
Option to dismiss all hints on first use

### ISSUE THREAD

**Issue by vatonbero** [duckduckgo/Android#2463]
Is there a chance to add option to disable all hints, after installation, with a single button click? Right now if you re-install app, it will show hints without the option to dismiss them all.

This includes prompts to add widgets and other stuff to the home screen.

I have tested this in version `5.138.1` and noticed no options to dismiss all hints at once.

**Comment by cmonfortep** [comment]
hey @vatonbero, all the hints (except the ones on the new tab screen) have a "hide" option at the right-top corner of the screen. That will allow you to skip the onboarding.
