### ISSUE TITLE
after upgrade to marshmallow, system search does not bring up ddg app

### ISSUE THREAD

**Issue by travisfw** [duckduckgo/android#250]
This may be an antifeature of Marshmallow, or the LG version of it. I have an LG G3 which did an OTA update from Lollipop to Marshmallow a few weeks ago. I used to launch DDG by dragging up from the home button. The upgrade immediately broke that. Now, Google always launches with no options given. So the question is, how did the mechanism for launching search change (is the intent different?) and regardless, is it still possible for DDG to be called via that mechanism?

**Comment by tagawa** [comment]
Hi @travisfw. Thanks for letting us know. Do you mean launching the DDG app or launching the DDG website from a bookmark?

**Comment by fgei** [comment]
@travisfw, the M upgrade just set Google No on tap as the default search, but you can still use DDG
on stock Marshmallow you can change it like this: Settings -> Apps -> the Gear icon on the toolbar -> Default Apps -> Assist & Voice Input -> (and finally) Assist app -> you should be able to find DDG in here, agree to the dialog and hopefully you should be all set.
The LG settings menu could be slightly different, I'm not sure, let me know if this is working

**Comment by travisfw** [comment]
Wow that's buried deep. But thanks @fgei, that works!
