### ISSUE TITLE
[Feature Request] Add support for FIDO security keys

### ISSUE THREAD

**Issue by brad2014** [duckduckgo/Android#2514]
### Describe the bug

Apps that login using OAUTH through the default android browser and require a security key (FIDO, FIDO2, WebAuthn, Yubikey, Solokey, etc) do not work if DDG is the default android browser.  The user is forced to set the default browser to something like Chrome.

To users, it looks like the app is broken, when it is a limitation of the browser.

### How to Reproduce

For example, issue mastodon/mastodon-android#326.

### Expected behavior

That DDG allow me to log in to a website that requires a FIDO security key for authentication.

### Environment

```markdown
- DDG App Version: 5.142.2
- Device: Pixel 4 XL
- OS: Android 13
```

**Comment by cmonfortep** [comment]
Thanks. We only accept issues as bug reports. I've found the feature request really interesting, and I will share it internally but closing the issue as not a bug.

Friendly reminder, a better way to share feedback is by sending it directly from the app (settings -> share feedback). We consume feedback on a daily basis and share it with many stakeholders.
