### ISSUE TITLE
[Bug] Your browser is no longer compatible with our site

### ISSUE THREAD

**Issue by bonninf** [duckduckgo/Android#2548]
### Describe the bug

When trying to browse the Web site transilien.com (https://www.transilien.com/) the Web page is showing the following erreur message: "Your browser is no longer compatible with our site". See the screenshot below:

![image](https://user-images.githubusercontent.com/1090995/203370605-eca48aeb-a4c5-4f4d-a2f4-f54ddbd60873.png)

### How to Reproduce

Go to: https://www.transilien.com/

### Expected behavior

The Web page is shown as displayed within Chrome for example: 

![image](https://user-images.githubusercontent.com/1090995/203372315-d51b2730-bcff-49cc-95ab-bc4c608830b3.png)

### Environment

```markdown
- DDG App Version: 5.143.1
- Device: Galaxy S10+ / Samsung SM-G975F/DS
- OS: Android 11
```

**Comment by bonninf** [comment]
Thanks for your feedback

**Comment by cmonfortep** [comment]
@bonninf if you find more scenarios like that one, you can also report us the site directly from the app (settings -> report broken site). 

But as commented above, most probably the site detects a webview or a user agent that they don't recognize.
