### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by Swastinaik** [duckduckgo/Android#2581]
### Describe the bug

Whenever I turn on any YouTube video on duck duck go, the recommendation videos turns off.

### How to Reproduce

1. YouTube on duck duck go
2. Turn on any video
3. Try to scroll videos 👇

### Expected behavior

Fix this issue, first YouTube doesn't have good interface on mobile browser it sucks up everytime.

### Environment

```markdown
- DDG App Version:
- Device:oppo a3s
- OS:android
```

**Comment by cmonfortep** [comment]
App version missing, and we are not able to reproduce the bug.
