### ISSUE TITLE
Open url with host and port instead of search

### ISSUE THREAD

**Issue by fredmaggiowski** [duckduckgo/Android#2625]
### Describe the bug

Hi, I have a raspberry pi hosting multiple servers on different ports in my local network but when I try to open web pages in the duckduckgo app it performs a search rather than opening the url.

Of course the server is properly running and I can open the same exact url on any other browser from my android device. 

Note: I've tried using the actual ip address instead of the hostname and it works (I've seen a pr about this in 2019) however I'd really love using the name I've set up instead of remembering the ip address 😅

I can try submitting a pr if anyone is willing to point me in the right direction

### How to Reproduce

* Open a url such as `http://raspberrypi:8080/`
* a search page is shown instead of the actual page

### Expected behavior

* Open a url such as `http://raspberrypi:8080/`
* view the page served by my server instead of the search page

### Environment

```markdown
- DDG App Version: 5.144.0
- Device: honor 20
- OS: Android 10
```

**Comment by cmonfortep** [comment]
Thanks, it seems the issue here is the URL doesn't have top level domain (.es, .com, etc.). I've logged the issue in our internal backlog (https://app.asana.com/0/1202552961248957/1203568844801448/f).

We will investigate and provide a fix. Thanks.

**Comment by fredmaggiowski** [comment]
Thank you very much
