### ISSUE TITLE
[Bug] Input Type Date Control Buttons are invisible by default

### ISSUE THREAD

**Issue by floriankapaun** [duckduckgo/Android#2638]
### Describe the bug

When opening a `<input type="date" />` on a website with DuckDuckGos Android Browser, I can't see the control elements because they are white on white.

### How to Reproduce

1. Go to [mdn web docs about `<input type="date">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date).
1. Click on the date input element.
1.  See the following problem:

<img width="382" alt="Screenshot 2022-12-14 at 08 32 05" src="https://user-images.githubusercontent.com/55788142/207533259-56b3fd90-6fad-4f74-9731-9a617f29903e.png">

### Expected behavior

I expected the control buttons to be visible, like they are on i.e. Firefox:

<img width="374" alt="Screenshot 2022-12-14 at 08 37 05" src="https://user-images.githubusercontent.com/55788142/207534145-3652fc88-58ac-44b7-a28a-9022857ad912.png">

### Environment

```markdown
- DDG App Version: 5.145.1 (51451000)
- Device: Pixel 4
- OS: Android version 13
```

**Comment by cmonfortep** [comment]
Thanks. I've created a task in our internal backlog. We will investigate and provide a fix.

**Comment by floriankapaun** [comment]
Thanks @cmonfortep! Is there an anticipated timeline for when we can expect the fix to be released? 😬
