### ISSUE TITLE
Excessive app tracking protection mobile data usage

### ISSUE THREAD

**Issue by andbleo** [duckduckgo/Android#2645]
### Describe the bug

What is the expected mobile/cell data usage of the DuckDuckGo Private Browser app when only using it for app tracking protection?  It has been using about 300MB of cell data per month for me (all foreground data).  At first I thought since it is acting as a vpn, maybe Android is categorizing all of my traffic as being DuckDuckGo but that doesn't seem to be the case (I see megabytes of data use from other apps, whether app tracking is enabled for those apps or not).  For now, I have disabled the app tracking protection and will monitor to see if there is still data usage from the app from simply having it installed but unused.

Otherwise, the app tracking protection appears to work great, so thanks!

### How to Reproduce

Install the DuckDuckGo Private Browser app and only use the App Tracking Protection.

### Expected behavior

I figure that there are blacklists that need to be downloaded to determine what URLs to block, so some data usage is required, but hundreds of megabytes per month seems excessive.  If that much data is required, it would be nice if it was possible to restrict/prefer the downloads to happening on unmetered connections like my home wifi.

### Environment

```markdown
- DDG App Version: 5.144.0
- Device: Pixel 4A
- OS: Android 13 with the Dec 5, 2022 security update
```

**Comment by cmonfortep** [comment]
Even if you only use our browser for app tracking protection (I assume you are not visiting any website from our app?), we need to download some config files that are required to improve our privacy protections in the different features we offer in the app (tracker blocking, app tracking protection, fingerprinting, cookie prompts, etc.).
300MB seems pretty high knowing our config files are just plain text json files, pretty lightweight, and we only download them when there's a new version available. We will keep an eye on this. 

Let us know if you disabling app tracking protection reduces the mobile/cell data usage. Thanks.

**Comment by sozifa** [comment]
for me its about 2.5 MB data usage per day without using the app for web browsing

**Comment by andbleo** [comment]
With the app tracking protection disabled, I haven't seen any large changes to data use in the duckduckgo app for the past week or so.  I am going to turn it back on and see how the data usage looks for the next week.

**Comment by aitorvs** [comment]
@andbleo , do you see any difference in data consumption (for the whole device) with app tracking protection on or off.

**Comment by andbleo** [comment]
Hard to say.  I was traveling last week so my data usage wasn't normal.  I will keep an eye on it.

**Comment by sozifa** [comment]
monitored it over the last week - without using duckduckgo for web browsing and track blocking on it constantly uses about 2.5 MB Data daily - no matter if wifi on or mobile data only - and no difference when roaming...

**Comment by andbleo** [comment]
I'm about 3 weeks into my month and my data usage appears to be normal overall with app tracking protections enabled.  I don't understand how Android assigns data usage to each app though.  DuckDuckGo is the second highest mobile bandwidth user after Android OS, which suggests that since it is a VPN, Android counts the traffic that runs through the VPN as belonging to DuckDuckGo.  But I have other apps that aren't part of the app tracking whitelist that are showing some mobile data usage (but it should be much more than what is accounted for).  Perhaps those apps are using data through google play services or something that is whitelisted, and Android is smart enough to assign the bandwidth usage to those apps?

**Comment by TheGoldenSun** [comment]
The funny thing is that whenever I use duckduckgo on an arm64 device (Samsung) it suddenly auto disables the tracking protection feature meanwhile I have to enable that feature everytime I either reboot phone or double check if it disables itself again which it does from time to time whilst the mediaoutput buttons says that duckduckgo is in working order, I disagree.

**Comment by andbleo** [comment]
Closing this issue since it doesn't appear that DuckDuckGo is using excessive data usage (only that the way data usage is reported in Android makes it look like it is using a lot of data).
