### ISSUE TITLE
[Bug] Text selection pop-up doesn't sync with the dark mode 

### ISSUE THREAD

**Issue by PraiseTheDuck** [duckduckgo/Android#2664]
### Describe the bug

By some strange reason the text selection pop-up on the websites is always in the light mode, even if the system or DDG themes are dark.

DDG is the only app on my phone with such behavior.

### How to Reproduce

1. Set the system or DDG themes to dark. 
2. Open the website contains some text.
3. Tap and hold the text to select it (but do not do this with links).
4. See the light mode text selection pop-up while the system or browser themes are dark.

### Expected behavior

Text selection pop-up should sync with the browser theme. Light with light themes and dark with dark ones.

### Environment

```markdown
- DDG App Version: 5.145.3
- Device: Samsung Galaxy S22
- OS: Android 13 with One UI 5.0
```
![Screenshot_20221219_012915_DuckDuckGo](https://user-images.githubusercontent.com/93687957/208328606-eefda064-05f6-4983-bca1-76a9816b77e8.jpg)
![Screenshot_20221219_012932_DuckDuckGo](https://user-images.githubusercontent.com/93687957/208328610-12eeeefd-a87f-4cc4-98b5-77dc1d157056.jpg)

**Comment by oyeraghib** [comment]
It works fine for me. Dark theme shows dark options menu and light theme shows light option menu.

Device Details ->
Model : Pixel 6a
Android : 13

**Comment by malmstein** [comment]
This was fixed, but never closed.
