### ISSUE TITLE
Android Backstack is not Cleared When Doing Each New Search

### ISSUE THREAD

**Issue by cavega** [duckduckgo/android#267]
**Steps to reproduce:**

1) Do a search via DuckDuckGo Android app
2) Clear the search bar by clicking X button
3) Perform a new search
4) Results are displayed
5) Press back button

**Current results:** When the user presses the back button the app navigates to the search results from Step 1 and the search box has the search query from step 1

**Expected results:** When the user presses the back button after any search the app should not keep track of previous search queries and instead go to the initial state/empty screen (no results and/or queries).

**Note:** This is not a duplicate (although related) to Remove search from input bar #203 as that ticket is for clearing the search box after clicking on a search result.

**Comment by fgei** [comment]
I think the X button in this scenario should just remove the text from the search bar, not clear the backstack

**Comment by cavega** [comment]
@fgei If I cleared my search query (by pressing the X button) before doing a 2nd search that means I'm no longer interested in the results of the 1st search. So when I do the 2nd search and press the back button I wouldn't want to see the prior/1st search because I already indicated to the app (by clearing it) that I no longer care for that first search.

I see that Google Search app does the same behavior but that doesn't necessarily make it the right approach. At the very least if I have the settings with "Save Recent" disabled this behavior should not be happening.

**Comment by fgei** [comment]
@cavega ok, I see your point, but I think the sole purpose of the X button is to clear the search bar from any previous input, not to clear the current session.
"save recents" generally should just prevent storing any searches/stories on the app.

re: @thm what do you think?

**Comment by GurpreetSK95** [comment]
Hi, is this issue still worked upon?

**Comment by cavega** [comment]
Since pressing the home button effectively does the same feature I was requesting for the X button (i.e. clear the back stack) I'm closing the ticket.
