### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by twsh** [duckduckgo/android#268]
I have the latest version of the widget from F-Droid, 3.0.13. I have a Fairphone 2 running Fairphone Open 16.10.0. DuckDuckGo crashes on launch. I've tried uninstalling and reinstalling.

**Comment by fgei** [comment]
we didn't publish 3.0.13 because of a library problem, the last release 3.0.14 will fix that

**Comment by twsh** [comment]
Thanks. 3.0.13 is the current version on F-Droid. I realise that that's not where the majority of users get the app though.
