### ISSUE TITLE
Legacy WebView supports insecure SSL ciphers

### ISSUE THREAD

**Issue by CryptKid** [duckduckgo/Android#272]
The integrated web browser has a not optimal ssl-configuration. It supports broken ciphers like rc4 and is vulnerable to Logjam, FREAK and Poodle. I don't know, if the app uses webview, but I get this results on an Android 5.1 - Device.
You can have a look by opening [this](https://www.ssllabs.com/ssltest/viewMyClient.html) or [this](https://badssl.com/dashboard/) test with the app. This concerns the security of connections made.

```
Version: 5.3.1 (50301)
Cyrus CS23
5.1
```

**Comment by CDRussell** [comment]
Perhaps you need to update your `WebView` on your device.

If you visit the site you linked, https://www.ssllabs.com/ssltest/viewMyClient.html, what do you see printed next to `User-Agent` ?

When I run this test, I see that the app is **not** vulnerable to `Logjam`, `FREAK` or `POODLE`.

**Comment by CryptKid** [comment]
I think, it's about the webview-version, so I think, it would be necessary to check if webview is new enough to be secure and use another engine like firefox otherwise or kill the app on other devices, to make it secure

**Comment by CDRussell** [comment]
Checking the `WebView` version and refusing to run the app (or giving the user the choice) if it's not acceptable is an interesting idea. Thanks for the suggestion.

**Comment by cmonfortep** [comment]
Hello @CryptKid  , thanks for taking the time to submit this feature request. Sorry for the very late response, we are currently going through old feature requests.

After internal discussion with the team, we've agreed that there's no plan in the foreseeable future to support this request. Should this change in the future, we'll update this conversation appropriately.
