### ISSUE TITLE
[Bug] HTML5 Date picker actions are very faint and unreadable

### ISSUE THREAD

**Issue by lynnewritescode** [duckduckgo/Android#2774]
### Describe the bug

Users have been struggling to set the date in the default HTML5 date picker.

After some investigation we discovered that this issue is only on DuckDuckGo. It appears that you can set the date, but the links to the actions (clear, cancel, set) are such a light grey that they are almost impossible to see, and therefore people were unable to use it as they needed.

![IMG_1254](https://user-images.githubusercontent.com/4159464/214887489-38bd80d2-956d-4fbc-b91e-39abcf4aacaf.JPG)

### How to Reproduce

On an Android mobile device open DuckDuckGo and:

1. Go to http://www.trustpilot.com/evaluate/trustpilot.com
2. Click on the star rating to expand the form
3. When the form expands, navigate to the "Date of Experience" field and click on it to open the calendar
4. Observe that the 3 actions at the bottom of the date picker are not clearly visible

### Expected behavior

The actions (clear, cancel, set) on the HTML5 date picker should be blue in colour, as seen in other browsers (see screenshot below).

![IMG_1255](https://user-images.githubusercontent.com/4159464/214887637-bc596ca2-2c43-4908-a705-fc459db136d7.JPG)

### Environment

```markdown
- DDG App Version: 5.146.0 
- Device: Samsung Galaxy S10
- OS: Android 12
```

**Comment by marcosholgado** [comment]
FYI @malmstein, accent color?

**Comment by marcosholgado** [comment]
Logged the bug in https://app.asana.com/0/488551667048375/1203849465655153/f, will try to get a fix out soon.

**Comment by lynnewritescode** [comment]
Thanks for the quick response :)
