### ISSUE TITLE
Not available for Android KitKat

### ISSUE THREAD

**Issue by HeinPauwelyn** [duckduckgo/Android#278]
I'm using the DuckDuckGo search engine for a wihile in Firefox browser and now I'll try the browser on my smartphone but I can't download it. The reason is because my device is not compatable for DuckDuckGo. I'm using Android version 4.4.2 KitKat. Is it possible to make it compatable for my device?

**Comment by CDRussell** [comment]
When we kicked off this project, we decided that our minSDK would be 21 (Lollipop) based on how the Android marketshare was looking.

Targeting Lollipop has allowed us to build features faster and reduced time required to test and build compatibility workarounds for KitKat and before.

While I appreciate that does cut some people's devices out, I think we're likely to continue with this approach.
