### ISSUE TITLE
[Bug] Favorite sites can show low quality, pixelated icons

### ISSUE THREAD

**Issue by Mugurell** [duckduckgo/Android#2795]
### Describe the bug

There are cases in which the available favicon may have a lower resolution.
If a different image scaling wouldn't help DDG could serve a better favicon from a local cache / assets.

![image](https://user-images.githubusercontent.com/11428869/215844240-eae8e2d9-82d1-4783-a2c0-63676a25e870.png)

### How to Reproduce

- access youtube.com
- save it as a favorite site
- check the homepage

### Expected behavior

All favorite pages should have quality images

### Environment

```markdown
The issue happens irrespective of the device or DDG version.
```

**Comment by cmonfortep** [comment]
Sadly this is a limitation of webview + our favicon logic.

A summary of our logic, when the user visits a site:
- webview has a few callbacks where we could receive the site favicon
- as a fallback, we try to obtain a favicon from some common URLs

We expect to cover most of the sites with that logic, but we are aware that, for some sites, the favicon has low quality. Not sure why. We haven't considered providing a local asset tbh, but I can share the idea internally. Thanks.
