### ISSUE TITLE
[Bug] Favorites menu remains fixed in place after dragging items around

### ISSUE THREAD

**Issue by Mugurell** [duckduckgo/Android#2796]
### Describe the bug

Favorites menu remains fixed in place after dragging items around.
If the user is to change the order of the favorite sites then the menu which remains open over a different site now may be confusing.

### How to Reproduce

- have >= 2 favorite sites shown on the homepage
- change the order of the sites starting with a long press gesture then move one item around with a continuous touch

https://user-images.githubusercontent.com/11428869/215846070-b74629f6-8c94-4394-abae-d8e3aefbe168.mp4

### Expected behavior

- an options menu appear following a long touch on a favorite site.
- the options menu disappears immediately as the user starts dragging the favorite site

### Environment

```markdown
Happens on all devices and recent DDG versions.
```

**Comment by cmonfortep** [comment]
Recently fixed https://github.com/duckduckgo/Android/pull/2761 👍
