### ISSUE TITLE
[Bug] No media notifications

### ISSUE THREAD

**Issue by Mugurell** [duckduckgo/Android#2801]
### Describe the bug

Playing a video or audio file does not show a media notification.
Notifications do help users with background playback and are a staple feature of other browsers.
Seems to be a limitation of `WebView` in the scenario of a browser.

### How to Reproduce

- access `youtube.com`
- choose a video to start playing

### Expected behavior

A media notification should be posted which would offer information about the current media playing and allow users control over the media playing status.

### Environment

```markdown
Happens on all devices and DDG versions.
```

**Comment by cmonfortep** [comment]
We are aware of the limitation and that we don't support background playback. Since we only accept bugs as issues, and this one is more of a feature request, I'm closing it. Thanks for reaching.
