### ISSUE TITLE
Picture in Picture support for fullscreen videos

### ISSUE THREAD

**Issue by Mugurell** [duckduckgo/Android#2802]
### Describe the issue

The picture in picture feature (https://developer.android.com/develop/ui/views/picture-in-picture) is a staple of other browsers and allow users  to have their media playing as a small overlay over other applications.
Seems to be a limitation of WebView in the scenario of a browser.
Could be left to the users to choose if the app should enter in PiP mode instead of relying on the media status.

### How to Reproduce

- access `youtube.com`
- choose a video to start playing in fullscreen
- switch to another app or go to the device's homescreen.

### Expected behavior

The fullscreen video will continue to play in a small window while users can interact with other applications.

### Environment

```markdown
Happens on all devices and DDG versions.
```

**Comment by cmonfortep** [comment]
Not a feature we currently offer. Closing as not a bug report. Thanks.
