### ISSUE TITLE
Please offer installed apps in the search widget results. 

### ISSUE THREAD

**Issue by cdysthe** [duckduckgo/Android#282]
Many, including me, will want to replace the the Google search widget with the DDG one. The one thing I miss is to get locally installed apps in search results like I do with the the Google widget. I also get contacts with Google but that I can live without. I installed app results could be added, at least as an option.

**Comment by cmonfortep** [comment]
🎉 Now our browser widget shows installed apps in the same way as Google search widget.

Better late than never 🖖
