### ISSUE TITLE
Feature requests - Dark/night mode and cookie manager

### ISSUE THREAD

**Issue by ghost** [duckduckgo/Android#284]
Hi there!
The duck would be my default browser if a couple of features were added:
- Dark/night mode
- A Cookie manager (with a whitelist buttom?)
Hope this could be possible in a near future.

**Comment by cmonfortep** [comment]
- Dark/night mode: Currently our browser supports light and dark theme. Users can select the theme inside settings.

- A Cookie manager (with a whitelist buttom?): We don't have a concrete way to allow or block cookies per site, but in our browser, users can use the fire button to remove all the cookies stored locally. Additionally, we introduced the option to fireproof websites. Fireproofing a website will retain cookies for that website even after using the fire button.
