### ISSUE TITLE
No changelog on F-Droid page

### ISSUE THREAD

**Issue by SarahTehCat** [duckduckgo/Android#285]
Why is there no option to see the changelog *before* updating?

**Comment by CDRussell** [comment]
Is this more of an issue to raise with F-Droid directly, or is there something we could do to improve this?

FYI, we post all the releases and change logs to https://github.com/duckduckgo/Android/releases if you ever need to check what's new before installing from anywhere, including F-Droid.

**Comment by Grossdm** [comment]
> Is this more of an issue to raise with F-Droid directly, or is there something we could do to improve this?
> 
> FYI, we post all the releases and change logs to https://github.com/duckduckgo/Android/releases if you ever need to check what's new before installing from anywhere, including F-Droid.

"Bug fixes and other improvements"
This is not a changelog.
Why not provide information?
