### ISSUE TITLE
[Bug] Search bangs with special letters

### ISSUE THREAD

**Issue by matthernet** [duckduckgo/Android#2851]
### Describe the bug

The bangs break (the `!` symbol) in the search bar doesn't work if you use words that end with the letters `ä, â, ã, å, à, ȁ, á, â, ó, ò, ö, ô, õ, ø, œ, ō`

### How to Reproduce

Go to the search bar in the mobile app and search any word that ends with the letters mentioned above and try to use any of the search Bangs (for example `bestå!g` or `bestå!a`)
Notice that you will not be redirected to the specified search Bangs

This problem also happens in other OS and in the desktop version

### Expected behavior

The Bangs break (the ! symbol) should be recognized in the use of other language letters

### Environment

```markdown
- DDG App Version:
- Device:
- OS:
```

**Comment by VISHNUONE8** [comment]
Hey @matthernet after seeing your description of the bug, I have to say you might have misunderstood how the bangs work.
The syntax of bang search is: (say for Wikipedia) '!w <searchquery>'
ex: "!w sachin tendulkar"  gives you the Wikipedia page of Sachin Tendulkar.
![duckduckgoBangs](https://github.com/duckduckgo/Android/assets/80620950/bca5cf59-a384-4ae9-934a-d420206701e1)

**Comment by matthernet** [comment]
Hi @VISHNUONE8 fhanks for the answer and sorry for the confusion, I'll use the search fringe before the indication
