### ISSUE TITLE
[Feature request] Force upgrade http to https.

### ISSUE THREAD

**Issue by dhammel** [duckduckgo/Android#2859]
Hello,

When going to any http website, it does not auto-upgrade to https when the sites support it.

I tested this by visiting: https://www.httpvshttps.com/
And clicking on http. It loads the unecrypted website.

On other browsers like Brave or Firefox, it will auto-upgrade to https and not even allow the http page to even load.

Can you implement this?

Thank you

**Comment by malmstein** [comment]
Discarding this case as it’s a test page that doesn’t allow for auto upgrading. Any other website will work.

**Comment by dhammel** [comment]
@malmstein The test page was just that, a test. The reason I used that site to test was because it wasn't working anywhere. If I go to an http site, it does not force upgrade to https which is available. It doesn't even warn me that it is insecure.

**Comment by malmstein** [comment]
@dhammel  Can you share an example?

**Comment by dhammel** [comment]
@malmstein If i go to the site http://www.httrack.com/

It will load instantly, no warning its insecure and no attempted force upgrade to https. Unless user directly pays attention to the url address bar, he/she will likely not know its insecure.

Screenshot:
https://drive.proton.me/urls/MJGCX01F88#0zTVOAK1GEtj

**Comment by malmstein** [comment]
Thanks @dhammel , will loop the team internally regarding the missed upgrade. The red dot indicator tells you the page is not encrypted, that’s as much as we can do for now.
