### ISSUE TITLE
[Bug] Recent Update breaks application dark theme setting 

### ISSUE THREAD

**Issue by djk2004** [duckduckgo/Android#2878]
### Describe the bug

The application settings, under Appearance -> Theme, has three settings: _System Default, Light, and Dark_.  Setting this value to dark now only applies to the application itself and not to web pages.  Dark mode should default to displaying pages in dark mode, especially when the web pages support a dark mode view.

### How to Reproduce

For example, even when the setting is _Dark_, by default, _https://www.duckduckgo.com_ renders using light mode.  The only workaround is to go into the web page settings (not the application settings), and select the dark mode image under _Appearance_.  This is somewhat acceptable for duckduckgo.com (since your web site preference is saved in the app for duckduckgo.com), but it doesn't work for other web sites which have implemented a dark mode in a browser that is intended to clear your local browser settings regularly.

Another example: youtube.com.  It will only render in light mode unless you navigate to the web page's settings (not the app settings) and change to dark theme.  At this point, it will look correct until the browser clears it's local history.

Other similar web sites that have similar repeatable behavior: google.com, bing.com, probably others.

### Expected behavior

Expected behavior is that dark mode should render web pages in dark mode as a priority, especially when the web pages support a dark mode theme.  If the web pages do not inherently support a dark mode, then it would be acceptable to render them as they originally appear.

### Environment

```markdown
- DDG App Version: 5.150.1
- Device: Pixel 7
- OS: Android v13
```

**Comment by gest01** [comment]
same here.

it seems that DuckDuckGo no longer passes the OS settings for dark mode to the website. I have this behaviour on all websites. 

E.g.: https://9to5linux.com/ is always displayed in light mode.

My Phone : OnePlus Nord2

**Comment by cmonfortep** [comment]
Thanks for reporting. We've recently bumped our targetSdk to 33, and that broke how webview applies dark theme. We are working on providing a fix asap.
