### ISSUE TITLE
Option to open external links in the appropriate app

### ISSUE THREAD

**Issue by SuperDuperUser** [duckduckgo/Android#288]
Right now, if I search "Uber Google Play" in the DDG app and I click the link to the Play Store, it opens in the internal browser instead of opening in the Google Play app, where I would ideally like to have it open so I can install. Moreover, if I click the "Open in Play Store App" button that the site displays, it causes a net::ERR_UNKNOWN_URL_SCHEME error. Links to YouTube and Amazon also don't make its way over to their respective apps. It would be really handy if there was a setting that allowed links to open in their default apps, either on a page-by-page (clicking something in the drop-down menu) or general basis. 

There were a couple of issues about this that were closed already, but those took place before the transition to the "Privacy Browser" version of the app in January 2018 and have not been adressed since. Also, the old version of the app used to have an option that kind of worked, but since the revamp it's no longer there https://imgur.com/gNw1tyD

Version 5.6.1
LineageOS 15.1, Android 8.1
Motorola Nexus 6

**Comment by CDRussell** [comment]
This has been partly implemented in #322 

The app will now launch the external app if it is installed for urls with custom schemes, such as the "Open in Play Store App" case highlighted.

It doesn't yet offer a way to open an equivalent native app from an HTTP/HTTPS page when the app which could accept that deep link is installed. ie, this hasn't been implemented yet 👇.

>Right now, if I search "Uber Google Play" in the DDG app and I click the link to the Play Store, it opens in the internal browser instead of opening in the Google Play app

**Comment by gostaDrivekitt** [comment]
This feature is needed for apps using Webviews and deep links/custom scheme links to go back to the app.
Would be awesome to have so that the DuckDuckGo browser work seamlessly as Chrome on Android.

**Comment by Poopooracoocoo** [comment]
I love how Firefox Focus handles links. Links to external apps don't open automatically and prompt me. I can open a link in the current tab (or for a link using the menu) in another browser or app by going to the menu.

I love browsing the web in Focus and then opening the ones I want in my browser. With Reddit I can open them in the app or not. I usually open Reddit links in the app to save them though. If I plan on commenting, I'll do it through the browser.

**Comment by uraza** [comment]
I am facing this issue with Youtube links on my side: they keep opening in the browser and I cannot figure out how to work around it.

**Comment by aitorvs** [comment]
Thanks for reporting this @uraza, indeed this bit is still to be done. I have created an internal task so that we can triage it.

https://app.asana.com/0/1198194956794324/1199533149091655/f

**Comment by Poopooracoocoo** [comment]
@aitorvs Is DDG Browser the browser to replace FF Focus? I outlined my frustrations above. FF Focus is kinda dead, with CRITICAL bugs that make you lose data, **not just** through it's poor Chrome-incognito-like design.
