### ISSUE TITLE
[Bug] app tracking protection incompatible with doh

### ISSUE THREAD

**Issue by corobin** [duckduckgo/Android#2943]
### Describe the bug

When app tracking protection is enabled and Android private dns is set to doh e.g. `cloudflare-dns.com` there are lots of internet connectivity problems: the system shows a connection error and many/most apps (but not all - a few still works) stop being able to connect to the internet.

confirming doh enabled:
![Screenshot_20230309-011855~2](https://user-images.githubusercontent.com/15662785/223980409-ea30847b-77ef-45cb-91c6-00b9c0e6704e.png)

Android error notifications:
![zScreenshot_20230309-011904~2](https://user-images.githubusercontent.com/15662785/223980415-fc450dd3-fda0-42c2-8a60-55854b470a15.png)

### How to Reproduce

enable app tracking protection

enable android private dns using doh. i.e. either `cloudflare-dns.com` or `dns.google`

### Expected behavior

no connectivity issues

### Environment

```markdown
- DDG App Version: 5.152.0 (51 520000) - this issue has existed for a long time probably ever since Android started supporting doh
- Device: pixel 7 - happened with older pixels too
- OS: 13
```

**Comment by aitorvs** [comment]
Hey @corobin, thanks for reporting this.
To clarify, I guess the debug information comes from https://1.1.1.1/help

I have tried to repro the issue in a Pixel 4XL devices running Android 13 and it didn't repro. I can configure cloudflare-dns.com in "private DNS" settings and all work as expected and 1.1.1.1/help tells me Android is using DoH.

**Comment by corobin** [comment]
huh, thanks for your comment. it's interesting you tried on 4xl because the older device that i saw with the same issue was a 4. on both wifi and mobile data. i can't think of anything else at the moment, perhaps we just wait to see if anyone else has seen this behaviour.

**Comment by aitorvs** [comment]
To be clear, I am not saying the issue doesn't exist. But haven't been able to repro it yet. Will also try to pixel 7 and see what I get. DoH support in Android is scattered, hardcoded just for dns.google and cloudflare-dns.com, and even the behavior is different between dns.google and cloudflare-dns.com.

Can you try with dns.google as well?

**Comment by corobin** [comment]
interesting, it didn't occur to me that different DNS servers might behave differently.

 just from a quick test right now, i see that cloudflare-dns.com currently shows the system error but dns.google *does not* show the system error. i didn't thoroughly test whether or not apps have connection issues, but firefox works with either DNS (even when there's a system error firefox still had no problem, but other apps would be unable to connect). also don't know if dns.google is intermittent.

**Comment by aitorvs** [comment]
Yeah DoH is not backported to all versions (I believe there's no support below Android 10) and not supported by all OEMs AFAIU.
Support it's currently hardcoded in their `DnsResolver` for:
* dns.google
* cloudflare-dns.com
* dns64.dns.google — which is a 6in4 DNS that returns AAAA for IPv4-only destinations

I guess the behavior is different because they may have different fallbacks, probably being the google ones the more resilients.

Will keep this open for now until we get another look at it.

**Comment by corobin** [comment]
so i just saw this reddit thread where apparently a bunch of people are suddenly seeing the same error on android. don't know what happened for this to become so much more widespread all of a sudden.

https://www.reddit.com/r/GooglePixel/comments/135z8a2/doh_cloudflare_changed_from_dnscloudflarecom/

no information about DDG on those devices - the widespread nature suggests an android problem. although when I originally reported this it was only with both DoH and DDG app tracking protection.

**Comment by corobin** [comment]
decided to give DoH another shot after upgrading to android 14, and it seems to be working now with DDG enabled. Not sure exactly at what point between my last post and now it was actually fixed, so cannot identify what fixed it.

**Comment by aitorvs** [comment]
Thanks for reporting @corobin 🙏
