### ISSUE TITLE
Incognito Keyboard throughout the application

### ISSUE THREAD

**Issue by NachiketaVadera** [duckduckgo/Android#295]
Hello DuckDuckGo, I like your application. I found out that Brave and Chrome support incognito keyboard mode (I use GBoard) throughout their app. DuckDuckGo, while provides this mode while searching from the url bar, dose not apply this to other search bars I visit.

**Comment by CDRussell** [comment]
This should already be the case.

Are you able to share any details of cases where you are not seeing this happen already? Are there any particular sites causing the issue or does it always happen for you?

**Comment by NachiketaVadera** [comment]
No. Every site works great. Also, there is no problem with the app. I tried search engines like google, aol, bing, wolfram alpha and even duckduckgo. None of these provide me with the keyboard incognito mode. Additionally, search bars within all websites do not switch on the incognito mode as well. I use a Moto G5s Plus which runs Android 7.1.1.

**Comment by CDRussell** [comment]
Sorry for the delay in responding.

The flag which is required for supporting incognito keyboard is only supported on Android Oreo (8.0) and up, and was implemented in this PR https://github.com/duckduckgo/Android/pull/217. It is expected that on OS versions below Oreo the flag will not be honoured.

Are you saying that you **do** see the incognito keyboard from Chrome and Brave on your Nougat device?

**Comment by NachiketaVadera** [comment]
Hey. No problem.

Yes, I run Android 7.1.1 and both Brave and Chrome and they **support incognito keyboard**. For the purpose of testing, I used the github.com and moretrackslikethis.com. 

In both of these cases, DuckDuckGo does not support incognito keyboard when I try to use the search bar of the aforementioned websites.

**Comment by CDRussell** [comment]
Interesting. I hadn't looked at pre-Oreo before as the flag indicated that it just wouldn't work prior.

However, you're right, I can see the incognito keyboard on an Android 7 device here in Firefox Focus. In the DDG app, the incognito keyboard is shown when you tap on the URL bar, but not shown when invoked from within the `WebView`, as you observe.

Ok, there's probably more we can do here. Thanks for reporting; I'll look into this.

**Comment by NachiketaVadera** [comment]
No problem. Happy to help

**Comment by CDRussell** [comment]
Ok, I see the solution.

We only add the flag on > Oreo because `EditorInfo.IME_FLAG_NO_PERSONALIZED_LEARNING` is only defined on Oreo. But we can just the underlying value `0x1000000` from pre-Oreo and it seems to work.

I have some slack to pick this up this week; I'll make this change more properly and test it out and report back if I see any issues.

**Comment by CDRussell** [comment]
Fixed in https://github.com/duckduckgo/Android/pull/316

The changes will be included in the next release (next week probably) or feel free to try it out sooner if you can build from the source code.

Thanks again for raising this issue.
