### ISSUE TITLE
[Request] Global Navigation Settings button in GUI

### ISSUE THREAD

**Issue by serrq** [duckduckgo/Android#3049]
Please adding this url as a button in GUI.

https://duckduckgo.com/settings

I had to work really hard to find these kinds of settings.
We try to make it easy and immediate to change global navigation settings.

A user does not have to go looking for, it must be there at hand.

**Comment by malmstein** [comment]
Thanks for the suggestion, and if it this ever comes into the roadmap we’ll let you know.
