### ISSUE TITLE
Add support for Android Adaptive Icons

### ISSUE THREAD

**Issue by dstaley** [duckduckgo/Android#305]
With the release of Android Oreo, support was added for adaptive icons that accommodate various shapes. For example, Pixel devices use a circular mask while Samsung devices use a squircle.

Adding support for adaptive icons to this project would be fairly simple since the icon would basically be Dax over a red background.

I mocked up what this could look like:
![image](https://user-images.githubusercontent.com/88163/42662719-91eb54fe-85e7-11e8-94b2-bde68f6eca88.png)

You can keep a specific round icon if you want to retain the white circle currently present, but I think it still looks good without it (and matches a few other instances of the Dax logo).

I'd be happy to send in a PR with updated resources to add this functionality if this is something you'd like to support. Currently, if a user is using an Android Oreo devices with a launcher that uses a mask other than the circular mask, the circular icon gets displayed inside a white frame. Here's an example of this:
![image](https://user-images.githubusercontent.com/88163/42662903-342b4076-85e8-11e8-8d96-1a2c876bdab8.png)

**Comment by JulienGenoud** [comment]
@subsymbolic do you have any plan to do it? Can i do a PR ?

**Comment by subsymbolic** [comment]
Hey @JulienGenoud thanks for the offer, that's awesome. I think our designers will cover this, I'll check-in with them and report back.

**Comment by subsymbolic** [comment]
I've checked with our designers and they are on the case. We will have adaptive icon support out soon.

**Comment by subsymbolic** [comment]
The adaptive icon is now PR https://github.com/duckduckgo/Android/pull/612 and will released in the next 1-2 weeks. Thanks for logging this issue and suggesting the change @dstaley.
