### ISSUE TITLE
[Feature Request] AdBlock, Install Chrome Extensions

### ISSUE THREAD

**Issue by Moxville** [duckduckgo/Android#306]
Hi,
I would like to know whether the browser has the following features ?
**AdBlock
Blocks pop-ups
3rd party cookie blocking
Https Everywhere**
If not, any future plan to add these features ?

Also I would like to know is it possible to install Chrome Extensions. If not any future plans to add this feature ?
I want to use extensions like uBlock Origin, Cookie AutoDelete, AdGuard AdBlocker, etc.

Thanks

**Comment by subsymbolic** [comment]
Hi @Moxville, thanks for your questions. We block pop-ups, 3rd party cookies and perform https upgrades. In terms of content blocking, we block trackers and so indirectly block many ads that are trackers however have no plans to do full-scale ad blocking nor do we plan to support Chrome Extensions.
