### ISSUE TITLE
It doesn't detect Tor

### ISSUE THREAD

**Issue by ZJaume** [duckduckgo/Android#31]
Tor is running on my device and Duckgo app says that "Orbot doesn't appear to be running".
I'm using Android 7.1.2

**Comment by subsymbolic** [comment]
Thanks for logging this. The source for the app you're thinking of lives at https://github.com/duckduckgo/android-search-and-stories and is unfortunately no longer being actively development.

Stay tuned, this new app will replace it in 2018. We hope you like it.
