### ISSUE TITLE
[Feature/Migration] - Migrate from Dagger To Hilt Dependency Injection

### ISSUE THREAD

**Issue by oyeraghib** [duckduckgo/Android#3114]
Wanted to know that are there any plans for migrating from Dagger to Hilt, I could see a lot of boilerplate could be removed also could be helpful for testing purposes.

Reference : [migrating from dagger to hilt](https://medium.com/androiddevelopers/migrating-from-dagger-to-hilt-is-it-worth-it-4cbbc8c93e33#:~:text=The%20most%20common%20implementation%20uses,by%20removing%20that%20boilerplate%20code.)

**Comment by aitorvs** [comment]
Thanks for the comment.
No, we don't have plans to migrate to Hilt. We're very happy atm with our current DI setup.

**Comment by oyeraghib** [comment]
Hi @aitorvs thanks for the response.

I would also love to know how can I began contributing quickly, like are there any "Good first issues" to get started with?
Or what are the current things the project is moving towards? Any migrations going ?
