### ISSUE TITLE
Ability to cut off a connection entirely from an app.

### ISSUE THREAD

**Issue by Flam3z** [duckduckgo/Android#3126]
I'd like to cut off certain app's connections as a whole that I know would not need it and would not try and siphon any form of data from me.

There is an app called Netguard in which you can disable an app's data & wifi connection while still using said app. I would use that app but then i'd run into another issue of other apps not being stopped by duckduckgo's app tracking protection.

I strongly feel like this would be a very important feature to implement as it would also go the extra mile to just close off any app's connection entirely for those who do not need any form of internet to use their apps. As DDG's app protection does already take over the VPN slot for android users, its really difficult to choose between netguard or the other.

**Comment by joshliebe** [comment]
Thanks for the feedback. This has been shared internally with the team.

We are currently only accepting Github Issues for bug reports, so I'm going to close this.
