### ISSUE TITLE
handling of SSL/TLS errors

### ISSUE THREAD

**Issue by jmue** [duckduckgo/Android#313]
DDG does not show any cert chain errors, it simply do not load such sites. This is bad, as the user do not get informed about the reason for that (like a not trusted CA, expired certificate or self signed certificate). It is even worse, as DDG shows a green lock icon with 'Encrypted connection' text beside in the privacy dashboard.
https://badssl.com/ hosts a set of cert chain error tests.

**Comment by cmonfortep** [comment]
Hello, we are reviewing old issues and we are going to close this one as we have plans to improve certificate handling.

https://github.com/duckduckgo/Android/issues/963
https://github.com/duckduckgo/Android/issues/1063
