### ISSUE TITLE
Do not send X-Requested-With

### ISSUE THREAD

**Issue by theel0ja** [duckduckgo/Android#315]
Image tells it all

![image](https://storage.theel0ja.info/imgup2/2018-07-28_18-39-14-cec8fa0e-2945-4668-a221-9ec42632a3e8.png)

Similar to https://github.com/anthonycr/Lightning-Browser/issues/317 and https://github.com/mozilla-mobile/focus-android/issues/1196

**Comment by CDRussell** [comment]
Sadly, the `X-Requested-With` header originates from inside `WebView` component and there isn't an easy way to prevent the header from appearing.

There is something we could do which would remove it from an initial page load, but there doesn't seem to be a reliable way of stopping the header reappearing for each subsequent fetch of an image, JS, CSS etc...

I have no idea why Android feels adding this header should be done with no control offered to the containing app to customise.

**Comment by pwittchen** [comment]
What do you think about clearing this header? I mean sending an empty string as a header value. Do you think this is a good idea to partially solve this issue?

**Comment by theel0ja** [comment]
@pwittchen Even if you clear it, it's still sent to JavaScript etc. files

**Comment by theel0ja** [comment]
Example:
https://github.com/theel0ja/x-requested-with
https://lab.theel0ja.info/x-requested-with/

![](https://user-images.githubusercontent.com/5832930/52171223-17677080-2751-11e9-97a7-90ddc8d45616.png)

Screenshot is taken from https://f-droid.org/packages/com.stoutner.privacybrowser.standard

**Comment by CDRussell** [comment]
As a follow up to this, I searched again for an issue on Chromium about being able to disable this header but I couldn't see one - really surprised there isn't an issue for this as it's been a known problem for years. 

Created this: https://bugs.chromium.org/p/chromium/issues/detail?id=960720
