### ISSUE TITLE
Feature Request -  more UI options

### ISSUE THREAD

**Issue by TheBlueAreComing** [duckduckgo/Android#3165]
Forward and backward nav buttons on the bottom of the main screen would be helpful when quickly navigating pages.  Safari on iOS does this; why can't we have a selectable option to do it, too?

You can also use the bottom navigation space to better manage the download dialogue (instead of opening a blank page like it does now).

Also...another option to move the Burn button off the main screen.  Not everyone needs this and it gets in the way.

**Comment by dryaz** [comment]
> Forward and backward nav buttons on the bottom of the main screen would be helpful when quickly navigating pages. Safari on iOS does this; why can't we have a selectable option to do it, too?
> 
> You can also use the bottom navigation space to better manage the download dialogue (instead of opening a blank page like it does now).
> 
> Also...another option to move the Burn button off the main screen. Not everyone needs this and it gets in the way.

Even more duck on iOS do this:

<img width="456" alt="CleanShot 2023-06-03 at 14 55 00@2x" src="https://github.com/duckduckgo/Android/assets/1395176/7aa7d03f-dc74-41e4-bfcb-3241a11720ea">

I bet the reason why it's not on Android 'cause android has back button by OS design while iOS doesn't.

More likely it makes sense to have option to move omnibox on the bottom as Safari introduced recently and Yandex browser did on android back in 2015 already.

**Comment by malmstein** [comment]
Thanks for the suggestion, and if it this ever comes into the roadmap we’ll let you know.
