### ISSUE TITLE
Image inside url doesn't allow opening in new Tab

### ISSUE THREAD

**Issue by jlHertel** [duckduckgo/Android#320]
When I long-press over a image with link, it doesn't open an option to open a new tab.
Let us take the following code as example:
`<a href="example.com"><img src="myimage.png"></a>`

Expected result:
Open a menu with the option to download the image **and** the option to open the link ` example.com ` in another tab.

Current result:
Open a menu with the option to download the image.

This issue is related to #175

**Comment by CDRussell** [comment]
Internal link: https://app.asana.com/0/414730916066338/800270854347855

**Comment by CDRussell** [comment]
Fixed by #368
