### ISSUE TITLE
remove tracking for the f-droid release. You can leave it on github only.

### ISSUE THREAD

**Issue by Wjxfi** [duckduckgo/Android#3237]
![b64bc504-e530-4492-ac23-61eba111e730.jpg](https://github.com/duckduckgo/Android/assets/113500363/de857080-9aee-453d-a220-fe92daf1c6ab)

it reduces the temptation to download. Increases the chance of leaving duckduckgo for another browser.

**Comment by malmstein** [comment]
Thanks for the suggestion, and if it this ever comes into the roadmap we’ll let you know.
