### ISSUE TITLE
[Request] Share image

### ISSUE THREAD

**Issue by tulsidas** [duckduckgo/Android#3264]
Hi, when I long press an image on a site I get only two options: download & open in new tab.

It would be useful (to me at least) to have the option to directly share said image, it would simplify the current flow of download, open, share, delete.

Is this possible?

**Comment by ImpenetrableNoble** [comment]
#898 @brindy

**Comment by malmstein** [comment]
Thanks for the suggestion, and if it this ever comes into the roadmap we’ll let you know.
