### ISSUE TITLE
Add swipe down 'Refresh' functionality.

### ISSUE THREAD

**Issue by abhaymaniyar** [duckduckgo/Android#33]
I think the app should have a refresh functionality like Google Chrome Android app. It is very comfortable to refresh webpages that way or there should be a refresh button at the bottom bar.

Please let me know if I should start working on this.

**Comment by gvklive** [comment]
Have you implemented it?

**Comment by abhaymaniyar** [comment]
Yes Sir! Will submit a PR soon.

**Comment by abhaymaniyar** [comment]
@subsymbolic I have done some work on this also. As you mentioned about not accepting PRs at this point of time, should I create a PR for this or not?

**Comment by subsymbolic** [comment]
If you've already done the work then feel free but it will likely languish here. We'll be better placed to accept contributions once this app has progressed past the prototype phase. Stay with us!

**Comment by abhaymaniyar** [comment]
Ok then I am not creating any PR for this. Waiting to pass the prototype phase.

**Comment by CDRussell** [comment]
I've looked at this functionality now and again and have never been happy with the UX when I previously added it. There was always something that just didn't feel right about my previous approaches.

That said, if there was a PR that implemented this well and maintained the existing functionality (such as the toolbar scrolling away as the `WebView` is scrolled) then we'd be open to accepting that PR.

It isn't being treated as a high priority feature internally, so happy to accept community contributions for it if it's desired.

**Comment by arunsathiya** [comment]
Voting for this as well! This would be a nice feature to have.

**Comment by samiuelson** [comment]
Yeah, not having swipe to refresh is so frustrating while browsing.

**Comment by Usiel** [comment]
After playing with it for a bit I think I'm able to do it based on the previous PR by @malmstein.
Would you like me to create a PR? I'm not quite sure since the 'help wanted' label was removed. Could do it today after work.

**Comment by malmstein** [comment]
@Usiel have a go at it if you like! Now that the `BottomNavigation` has been removed it should be easier to execute. Ping me if you need any help!
