### ISSUE TITLE
Search bookmarks

### ISSUE THREAD

**Issue by sanderbaas** [duckduckgo/Android#330]
I would really like it if my bookmarks were included in the suggesstions when searching from the address bar.

**Comment by CDRussell** [comment]
That's a really good idea! Thanks for raising this. I'll pass this idea on to the rest of the team for consideration.

Internal issue: https://app.asana.com/0/608920331025315/793359964050426

**Comment by marcosholgado** [comment]
This has now been released in **[5.30.0](https://github.com/duckduckgo/Android/releases/tag/5.30.0)**
