### ISSUE TITLE
Many Security Vulnerabilities

### ISSUE THREAD

**Issue by RustoMCSpit** [duckduckgo/Android#3321]
### Describe the bug

Compiled list:

https://privacytests.org/android.html

### How to Reproduce

Use

### Expected behavior

Patching

### Environment

```markdown
- DDG App Version:
- Device:
- OS:
```

**Comment by damronlouise** [comment]
660 676-6395

**Comment by damronlouise** [comment]
660 676-6395

**Comment by RustoMCSpit** [comment]
huh

Sent from Proton Mail mobile

-------- Original Message --------
