### ISSUE TITLE
Enhancement: Introduce a "Close all tabs" button that closes without clearing data

### ISSUE THREAD

**Issue by arunsathiya** [duckduckgo/Android#334]
I am not quite sure if this is a good idea, but it would be helpful if there is an option to close all the tabs without clearing data.

## Current scenario

Currently there is an option to close each tab individually, without clearing the data. This can done done by following the steps below:

- Open multiple websites on multiple tabs.
- Login into them.
- Click on the tabs icon at the top right, to the left of the three dots menu icon.
- Find `X` mark to close each tab, on the right of each tab.

## Enhancement request

Take this one step forward and introduce an option to close all these tabs in one go, by using a master `X` button to close all tabs.

This will **not** be the same as the `Clear data` icon to the right of the search bar/address bar.

**Comment by CDRussell** [comment]
This is a good idea, indeed. I'm going to be making a change in this area this week anyway, so I'll add this functionality in too assuming no one in the team objects to the idea.

Thanks for raising this.

**Comment by CDRussell** [comment]
Implemented in #340. I'll be releasing this to beta today/tomorrow and it'll be in production in the next release.

**Comment by arunsathiya** [comment]
Excellent news. 🎉
