### ISSUE TITLE
Quality of favicons used for home screen shortcuts

### ISSUE THREAD

**Issue by sanderbaas** [duckduckgo/Android#335]
First of all, I am very happy with the new feature to add shortcuts of websites to the home screen (#224). However, the quality of the icons used for the shortcuts is quite low for some sites. Of course not always a high quality icon is available, or it is not marked correctly on the website.

I am not sure what the process is of producing the icon for the shortcut, because the icons are fetched from https://icons.duckduckgo.com/ip3/%s.ico , but maybe you can try to fetch the best quality image available. Even if it is marked as `apple-touch-icon`.

For example for the website [Rijnmond.nl](https://www.rijnmond.nl/) this icon is used ![Low quality](https://www.rijnmond.nl/Content/Images/rijnmond/favicon.ico) when also this one is available on their website ![High quality](https://www.rijnmond.nl/Content/Images/rijnmond/touch-icon-iphone.png) .

**Comment by subsymbolic** [comment]
Thanks for reporting this. We have logged this internally and will fix it there. Thanks again!

**Comment by subsymbolic** [comment]
Internal link: https://app.asana.com/0/715106103902962/1115742071228982
