### ISSUE TITLE
Feature request: Copy URL

### ISSUE THREAD

**Issue by jfitie** [duckduckgo/Android#336]
When long pressing on a hyperlink, there should be an option to copy the URL to the clipboard.

**Comment by arunsathiya** [comment]
If I am not missing something, this would be a Android feature and not dependent necessarily on DuckDuckGo, right?

I just tried to copy a text from a page, a link from the address bar and everything works.

**Comment by arunsathiya** [comment]
Oh no, my bad. Sorry about the last comment. You were specifically mentioning an option to copy a link upon long pressing it. 👍🏽

**Comment by CDRussell** [comment]
Good suggestion, I agree this would be good. I'll try add this in when I can.

Thanks for raising.

**Comment by CDRussell** [comment]
Fixed by #368
