### ISSUE TITLE
Feature request: Add global Desktop Site setting

### ISSUE THREAD

**Issue by jfitie** [duckduckgo/Android#337]
Add global setting to enable Desktop Site automatically for all tabs.

**Comment by cmonfortep** [comment]
Hello @jfitie , thanks for taking the time to submit this feature request. Sorry for the very late response, we are currently going through old feature requests.

After internal discussion with the team, we've agreed that there's no plan in the foreseeable future to support this request. Should this change in the future, we'll update this conversation appropriately.
