### ISSUE TITLE
[Bug] WebRTC Leak on DuckDuckGo Android

### ISSUE THREAD

**Issue by Ironfist69** [duckduckgo/Android#3401]
### Describe the bug

![2ck82o6evmfb1](https://github.com/duckduckgo/Android/assets/70436487/3d24da89-f876-4ec3-a7cf-bbdf4be05a90)

### How to Reproduce

1. Go to 'https://browserleaks.com/webrtc'
2. Scroll down to 'Your WebRTC IP'
See error 'WebRTC exposes your Local IP address'

**_Seems like Brave, Microsoft Edge does prevent this issue out of the box_**

### Expected behavior

![Screenshot (3)](https://github.com/duckduckgo/Android/assets/70436487/1695f0af-8bc1-4167-9239-16ee8f5d89e4)

_Screenshot from Microsoft Edge_

### Environment

```markdown
- DDG App Version: 5.164.2 zp (51642000)
- Device: Samsung Galaxy A13 (SM-A135F/DS)
- OS: Android 13 (OneUI core 5.1)
```

**Comment by marcosholgado** [comment]
Thank your for bringing this up. We already looked at this problem in the past (and double checked now again), see https://github.com/duckduckgo/Android/issues/429 and the situation still persists, the IP permission callback is not implemented in WebView hence we never get it.
