### ISSUE TITLE
There are some adjustments that need to be made

### ISSUE THREAD

**Issue by ghost** [duckduckgo/Android#342]
1. Add white list mechanism, see attached pictures!
![d](https://user-images.githubusercontent.com/41664010/44836726-51948980-ac6a-11e8-98e9-380fac1c8d2c.jpg)

2.Can AD filter add these three lists?

"Adblock Warning Removal List"
https://adblockplus.org/subscriptions#type_anti-adblock

"ABP Anti-Circumvention Filter List"
https://github.com/abp-filters/abp-filters-anti-cv

"Reek Anti-Adblock Killer"
https://reek.github.io/anti-adblock-killer/

Thanak you!

**Comment by edentw** [comment]
#342
These are two of the news sites, but they all use facebook comment boards as a plugin.
However, it will be hidden by the APP, so the whitelist method is needed to strengthen the assistance,
But if you can solve this kind of problem with other parties, it's acceptable.
http://n.yam.com/Article/20180829560607
https://tw.news.appledaily.com/international/realtime/20180830/1420550/
thank you!

**Comment by CDRussell** [comment]
If you whitelist a site like appledaily.com inside the app, then you will see the Facebook comment boards.

**Comment by CDRussell** [comment]
![device-2018-08-30-104518](https://user-images.githubusercontent.com/1336281/44844118-ecc53900-ac41-11e8-9773-d51025836e16.png)
![device-2018-08-30-104546](https://user-images.githubusercontent.com/1336281/44844127-f353b080-ac41-11e8-9073-5453fe5d7559.png)
