### ISSUE TITLE
Ddg web browser used 250mb in background

### ISSUE THREAD

**Issue by nutpantz** [duckduckgo/Android#348]
Yesterday ddg web browser used 250mb in the background. I was not using it at the time (but had in the last hour) I was using Firefox klar when this happened. I checked everywhere and could not find a file downloaded or any other reason it should use 250 mb (it has only used 130mb since Jan)

**Comment by CDRussell** [comment]
😞 That's unexpected; sorry about that. We do download data in the background so we can upgrade sites from http to https for better protection and lists for knowing which resources are trackers so we can block them. But the lists aren't that size!

Would you mind sharing a few details to help us work out the problem?

- Device details: model, OS version
- App version: you can find this in the Settings page
- Was this the first time using the app, or the first time after an upgrade, or have you been using the same installed version for a while?

Thanks

**Comment by nutpantz** [comment]
Android TouchWiz 6.01 on a note 4 rooted and debloated with no Google play.

Version is unknown because I uninstalled it, but it was not the latest update from fdroid maybe one or two versions back

I've been using the app on and off since January, data usage for duckduckgo browser had been 130mb since  January.so It's not my default browser and spends most nights blocked by afwall+.

**Comment by CDRussell** [comment]
Thanks for that extra info!

I'm part-wondering if the app's networking being blocked by `afwall+` could have messed with the scheduling of the background jobs. Maybe it causes some of the missed ones to fire simultaneously instead of backing off and queuing up a re-try as they're supposed to do. I haven't used `afwall+` so I'm just guessing, though.

We can look to see if there's something more to be done here, or if the problem lies elsewhere. In any case, thanks for the info.

**Comment by subsymbolic** [comment]
The logic in this area has changed and we haven't seen any recent reports so we are now closing this issue but are happy to reopen if it appears again. Thanks for reporting it @nutpantz, if you see it again, do let us know.

**Comment by vetemi** [comment]
I experienced the same issue today or better say yesterday night.

The browser used 3gb (!) of my data in the background, right in the beginning of new cycle. Never experienced something like this before. It happened during the night, so I didn't actively used the app. Did I had tabs open? Maybe but only the ones I regularly use. 

App Version: 5.55.1
Android version: 9
Model: Motorola moto g7 power (XT-1955-4)

**Comment by cmonfortep** [comment]
@vetemi we are very sorry to hear that 🙇‍♂️.
For sure, we don't expect that to happen for a user that is not actively browsing (and like you said 3gb is a lot), so I will spend some time this week to investigate if we have any unknown bug or any unexpected behavior that could be the culprit of that data consumption.

As an additional question, have you experienced any situation where the app was crashing for you in the last few weeks?

Thanks.

**Comment by 012329emtP** [comment]
I haven't used ddg in months. Yet, at the beginning of my data cycle it took 2.61 gigs of data from me  I only have a 3 gig plan. This isn't right. And based on this thread it's a well known issue. DDG took all of my data and in going to get charged for going over my plan.
