### ISSUE TITLE
Show bookmarks as home Tab's content

### ISSUE THREAD

**Issue by pravi** [duckduckgo/Android#349]
When starting browser, it should show bookmarks instead of empty page. This makes it easier to visit favorite sites. Currently home tab is just empty. It should show bookmarks as content and keep the address bar visible (unlike going to bookmarks).

**Comment by CDRussell** [comment]
Thanks for the idea! 

We know the new tab page is a bit empty at the moment, and we have some plans on how we're going to make that more useful. We probably don't want to show bookmarks straight away, as currently that would make it harder for people who are looking to search or type a URL, but easier access to bookmarks definitely makes sense.

I'll pass on your suggestion to the team, and close out this issue for now. Thanks again!
