### ISSUE TITLE
Fix "bookmark_name_text_view".

### ISSUE THREAD

**Issue by abhaymaniyar** [duckduckgo/Android#35]
When a user bookmarks website with a long title, the bookmarks name overlaps the rearrange button as the image is showing:

I would like to fix this and please let me know if I can start working on this.

![screenshot_2017-07-16-21-47-42-500_com duckduckgo app](https://user-images.githubusercontent.com/17759582/28249332-79ba976a-6a71-11e7-809d-7a5aa1f1054e.png)

**Comment by abhaymaniyar** [comment]
I am working on this issue.

**Comment by subsymbolic** [comment]
Thanks for logging this. We haven't implemented the design for the bookmarks page yet (this is a functional placeholder) so I'll close this issue for now.

**Comment by subsymbolic** [comment]
I've just noticed your PR for this, thanks for submitting that, I've just merged it. We won't be able to accept any more for a while as the project is still in flux but I really appreciate your work so far. Thanks again!
