### ISSUE TITLE
Investigate Tor integration with Orbot on Android

### ISSUE THREAD

**Issue by herotux** [duckduckgo/Android#350]
Please provide an option to use app with orbot or other proxies.
we live in iran government block duckduckgo and need proxy to use your app

**Comment by CDRussell** [comment]
Internal issue: https://app.asana.com/0/search/828743867277629/564380980348685

**Comment by herotux** [comment]
Thanks alot

**Comment by RoestVrijStaal** [comment]
Any updates on this issue? 

Also #141 seems to be related....

**Comment by anna-seppala** [comment]
Just to add to this, if you use a manual proxy on your Android WiFi, unencrypted HTTP traffic seems to work fine. I set up a proxy on my laptop and am channeling traffic through it from my Android. However, even after installing a CA certificate on my phone, I can't browse SSL-secured sites on duckduckgo (on Chrome it works). Is there any work being done to add this feature?

**Comment by ozmy** [comment]
any news?

**Comment by ehsabd** [comment]
Any updates. I like this feature too.

**Comment by chromer030** [comment]
Any progress ?
This feature is essential for some users.
Thank you.

**Comment by Apfelwurm** [comment]
would also be interested in this one. Is there any help needed?
