### ISSUE TITLE
[Feature Request] Add option for Open in new tab in group

### ISSUE THREAD

**Issue by oyeraghib** [duckduckgo/Android#3502]
### Describe the bug

I would like to suggest a new feature for the browser. It's been a really helpful feature in Chrome and I don't use the new tab since I have been using this new feature. It's really helpful as well during the time of switching the tabs, and I think could be a great feature for DuckDuckGo. It's called "Open in new tab in group", to open a new tab but being on the same window and shift between the tabs by changing them from the bottom group.

### How to Reproduce

This option can be added here (when long pressing a link) : ![DuckDuckGo ScreenShot]

<img src="https://github.com/duckduckgo/Android/assets/40427461/0953c57f-8976-45fe-a4c0-d00ad7d927cf" width="300px" height="600px" />

### Expected behavior

<img src="https://github.com/duckduckgo/Android/assets/40427461/33fcdb9a-fcfe-43ca-a33b-d5012be9bf80" width="300px" height="600px" />

<img src="https://github.com/duckduckgo/Android/assets/40427461/714b9276-922a-43f5-99f7-896f615f919d" width="300px" height="600px" />

### Environment

```markdown
- DDG App Version: 5.162.0
- Device: Google Pixel 6A
- OS: Android 13
```

**Comment by malmstein** [comment]
@oyeraghib, as stated in our [Contribution Guidelines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md), requests for feedback should be addressed via the Feedback section in the Android app.
