### ISSUE TITLE
[Bug] Unable to open this type of link

### ISSUE THREAD

**Issue by jxd1337** [duckduckgo/Android#3518]
### Describe the bug

Yesterday, I was unable to access certain sites, and kept getting "unable to open this type of link" pop-up.
Restarting DDG / Clearing all data / cache didn't help, I had to restart my phone in order to fix this.

### How to Reproduce

1. Open DDG on your device
2. Type "youtube.com" into the search bar
3. Click Enter
4. Unable to open this type of link pop-up will appear at the bottom of screen
5. Click at the pop-up, and you'll get white blank page

### Expected behavior

Normally open youtube and play videos

### Environment

```markdown
- DDG App Version: 5.168.1
- Device: Samsung Galaxy S10 Lite
- OS: Android 13
```

**Comment by malmstein** [comment]
Hey @jxd1337 thanks for filing this.

Would you be able to record the interaction? I’ve trying to reproduce in several devices and I can’t reproduce. Do you have the Youtube app installed?

**Comment by jxd1337** [comment]
Hi, I currently can't reproduce this myself again. I don't have the youtube app installed, but I never needed to - I always watched YT videos in browser. Everything works great now, and I didn't do anything specific that could've lead to this bug that day.

Just to be clear though this wasn't happening just with youtube, but almost all sites I tried to go to wouldn't open, e.g: hackernews, youtube, github etc...

**Comment by malmstein** [comment]
Thanks @jxd1337. I’ll close this one out, but feel free to reopen if it happens again.
