### ISSUE TITLE
[feature request] disable incognito keyboard

### ISSUE THREAD

**Issue by GenerallyClumsy** [duckduckgo/Android#3577]
### Describe the bug

Congratulations team! Thank you for making such a fabulous browser. I'm not quite sure the best spot to enter feature requests, but it would be really useful if we could disable the incognito keyboard. Sadly, the incognito keyboard causes issues with usability.

### How to Reproduce

Whenever you enter text

### Expected behavior

Have the option to disable the incognito keyboard?

### Environment

```markdown
- DDG App Version: 5.171.1 zy (51711000)
- Device: pixel 7
- OS:13
```

**Comment by joshliebe** [comment]
Thanks for the suggestion, and if it this ever comes into the roadmap we’ll let you know.

**Comment by andrea-nisti** [comment]
this is what is keeping me from using duck duck app, is there a way to disable it?
