### ISSUE TITLE
Sinhala language

### ISSUE THREAD

**Issue by hanariyada** [duckduckgo/Android#3578]
### Describe the bug

I couldn't find the Sinhala language in https://github.com/duckduckgo/Android/tree/develop/app/src/main/res but i found this one https://github.com/duckduckgo/duckduckgo-locales/tree/master/locales/si_LK/LC_MESSAGES

Can you add Sinhala language to the app?

### Environment

```markdown
- DDG App Version: Latest
```

**Comment by joshliebe** [comment]
Thanks for the suggestion, the team has been notified.
