### ISSUE TITLE
Add homescreen widget back

### ISSUE THREAD

**Issue by nhatzHK** [duckduckgo/Android#363]
In the last release, the homescreen widget disappeared. Please add it back, it's very useful.

**Comment by CDRussell** [comment]
The widget is still available; there shouldn't have been any changes recently which affected this.

Can you try re-adding the widget... does it show up in the list of widgets?

If you're still not seeing it, let me know which Launcher you are using and which OS version and I'll see if something is up.

**Comment by CDRussell** [comment]
I'll re-open this if there's any more relevant info added.

**Comment by CDRussell** [comment]
That sounds right; Google specifically advise against allowing apps to be installed on the SD card when they contain a widget. 

See section `Applications that should NOT install on external storage` from https://developer.android.com/guide/topics/data/install-location

While we don't officially support moving the app to the SD card, some phones will still offer it up as an option, and will likely break the widget in the process. 😞 

Thanks for the info.
