### ISSUE TITLE
Network partitioning

### ISSUE THREAD

**Issue by arthuredelstein** [duckduckgo/Android#3640]
### Describe the bug

Currently it appears that DuckDuckGo Android does not have network partitioning enabled. Compare Chrome and DDG here:
https://privacytests.org/android.html
Relevant tests under "State Partitioning" include
Alt-Svc, H1, H2, H3.

### How to Reproduce

You can run https://privacytests.org/me.html

### Expected behavior

The browser should not share state between websites.

### Environment

```markdown
- DDG App Version: 5.173.1
- Device: Samsung Galaxy J3 Eclipse
- OS: Android
```

**Comment by nalcalag** [comment]
Hi @arthuredelstein, thank you for the suggestion. We are already looking into adding support.

**Comment by arthuredelstein** [comment]
Hi! I'm checking in again. Any chance these leaky features can be fixed? They are already mostly fixed in Chrome.

<img width="870" alt="image" src="https://github.com/duckduckgo/Android/assets/355566/10d6c662-5d9e-4739-a1bd-f0f746d796e3">
