### ISSUE TITLE
Cross-site Storage Partitioning

### ISSUE THREAD

**Issue by arthuredelstein** [duckduckgo/Android#3641]
### Describe the bug

It appears that DDG Android does not have cross-site storage partitioning enabled. See the results at https://privacytests.org/android.html

Chrome recently enabled cross-site storage partitioning and fixed the following items:
BroadcastChannel, CacheStorage, CSS cache, font cache, getDirectory, image cache, indexedDB, localStorage, locks, prefetch cache, SharedWorker

This protection can be enabled via the chrome://flags/#third-party-storage-partitioning flag

### How to Reproduce

You can run https://privacytests.org/me.html

### Expected behavior

Green checks :)

### Environment

```markdown
- DDG App Version: 5.173.1
- Device: Samsung Galaxy J3 Eclipse
- OS: Android
```

**Comment by nalcalag** [comment]
Hi @arthuredelstein, thank you for the suggestion. We are already looking into adding support.

**Comment by arthuredelstein** [comment]
Hi @nalcalag! Is there any progress on this? Here are the latest test results for state partitioning. Please note the comparison between DuckDuckGo and Chrome:

<img width="968" alt="image" src="https://github.com/duckduckgo/Android/assets/355566/dc0e8f5a-12d1-427b-adbc-3e57ab97782b">
