### ISSUE TITLE
Enforce Manual Page Zoom not functioning 

### ISSUE THREAD

**Issue by Des-Conocido-De** [duckduckgo/Android#3681]
### Describe the bug

SETTINGS > Accessibility > Enforce Manual Page Zoom.

The manual zoom override is not applied as expected. User has to set to false and re-enable in the current session(?) for it to apply.

### How to Reproduce

SETTINGS > Accessibility > Enforce Manual Page Zoom.

1. Android.
2. Enforce Manual Page Zoom = true
3. Navigate to a known website that prevents zoom.
4. Zoom doesn't function.
5. Zoom only functions when switch/flag is set to false and the immediately set to true again for the current session.
6. Then example website can be zoom over-ridden.

### Expected behavior

Once set to `true` it should work everywhere all the time.

### Environment

```markdown
- DDG App Version: 5.171+ and many versions less.
- Device: PXL 5
- OS: Android
```

**Comment by marcosholgado** [comment]
@Des-Conocido-De thanks for your bug report, can you add a website to test this? Your third step says `Navigate to a known website that prevents zoom.` and it would be great to have an actual example.

**Comment by Des-Conocido-De** [comment]
citynews.com.au

**Comment by Des-Conocido-De** [comment]
citynews.com.au
