### ISSUE TITLE
Include German translation

### ISSUE THREAD

**Issue by florian19982** [duckduckgo/Android#373]
Is there any attempt to include translations of the string.xml into other languages?
If so, I would be willing to work on a German translation.

**Comment by CDRussell** [comment]
Thank you for your kind offer.

At the moment, we're not looking for contributions for translations. While we do want to better localize the app in future, we're not yet ready for full support of it, and don't want to introduce any additional languages we can't commit to keeping fully updated.

**Comment by CDRussell** [comment]
Hi @florian19982, if you're still interested in helping us improve the app for German speakers, we have just opened this up for community contributions. Please see #559 for details.

**Comment by florian19982** [comment]
Sure! I'll have a look at it as soon as possible.
