### ISSUE TITLE
[Bug] Subject is empty when sharing page via email

### ISSUE THREAD

**Issue by danpla** [duckduckgo/Android#3739]
### Describe the bug

When you share a page via an email app, DDG puts the URL in the message body, but doesn't use the webpage title as the subject.

Chrome can do this without problems even if you use an email app other than GMail (mine is K-9 Mail).

### How to Reproduce

1. Open any page
2. Select "Share" from the kebab menu
3. Select your email app
4. Observe that the email subject is empty

### Expected behavior

Fill the email subject with the webpage title.

**Comment by cmonfortep** [comment]
Thanks for reporting that scenario. It was a quick fix, so we've just added it and it will be available soon in our next release.
https://github.com/duckduckgo/Android/pull/3763

**Comment by danpla** [comment]
Thank you!
