### ISSUE TITLE
Change Repository name

### ISSUE THREAD

**Issue by divyanshub024** [duckduckgo/Android#374]
## Description

I think the repo name should be more specific like "Duckduckgo.Android" or "Duckduckgo-Android". It makes easy to find the repo in the local directory.

**Comment by brindy** [comment]
Hi, that's unlikely to ever change, I'm afraid.

But when you do do a git clone you can specify any name you like, e.g.

`git clone --recursive git@github.com:duckduckgo/Android.git duckduckgo-android`

Hope that helps.

**Comment by divyanshub024** [comment]
@brindy Thanks for the help.
