### ISSUE TITLE
Ability to block pop up from website.

### ISSUE THREAD

**Issue by 3ekodomo** [duckduckgo/Android#3802]
### Describe the bug

**It's not bug.**
I am writing to kindly request the addition of a popup blocker feature within the DuckDuckGo Android application's browser. Some websites employ popups to serve ads and, at times, malicious content, which can be both intrusive and potentially harmful. Currently, there is no option to block these popups in the DuckDuckGo browser. I believe that implementing a 'Block Pop Ups' button would significantly enhance the browsing experience by allowing users to selectively prevent popups, ensuring a safer and more user-friendly environment. Additionally, it would be beneficial if the browser could issue warnings when apps attempt to redirect users to other webpages. These enhancements would further align DuckDuckGo with its core principles of privacy and user empowerment, and I believe they would be highly appreciated by your user base. Thank you for your consideration of this request.

### How to Reproduce

1. open a website
2. scroll/click on url 
3. You'll get pop up

### Expected behavior

Duckduckgo should not allow opening pop up which are annoying.

### Environment

```markdown
- DDG App Version: -
- Device: -
- OS: Android
```

**Comment by joshliebe** [comment]
Thanks for the feedback. This has been shared internally with the team.

Closing this since we are currently only accepting Github Issues for bug reports.
