### ISSUE TITLE
No Basic Auth

### ISSUE THREAD

**Issue by dmaes** [duckduckgo/Android#383]
### App Version
5.11.1 (via PlayStore)
### Device make and model
Motorola Moto G3
### Android version
7.1.2 (LineageOS 14.1-20171109-NIGHTLY-osprey)
### Steps to reproduce the bug
Visit a site with Basic Auth (try [httpbin.org](http://httpbin.org/#/Auth/get_basic_auth__user___passwd_))
### Expected behavior
A prompt opens to ask for your username and password
### Actual behavior
No prompt is opened, and you get a 401 status code with the message "unauthorized"

**Comment by CDRussell** [comment]
Internal issue: https://app.asana.com/0/414730916066338/555891326561611

**Comment by CDRussell** [comment]
Hi, thanks for raising this. We have this on our internal backlog but it's never bubbled up to the top priority wise so we haven't got to implementing it yet. If users vote on this issue with 👍 we'll maybe get it prioritised sooner.

**Comment by dmaes** [comment]
Nice to hear it's already in the backlog, looking forward to see it implemented.

**Comment by jd666** [comment]
Please implement.

**Comment by dapacheco** [comment]
@CDRussell is there any desire to have a community PR to resolve this issue?

**Comment by CDRussell** [comment]
Good suggestion; this probably should be flagged for community help to get it done. @subsymbolic you agree?

**Comment by subsymbolic** [comment]
Great shout. It'll be a while before we can look at this, help from the community would be awesome. I've added the "help wanted" label.

**Comment by CDRussell** [comment]
Implemented in https://github.com/duckduckgo/Android/pull/460
