### ISSUE TITLE
Inconsistent behavior from DDG image search

### ISSUE THREAD

**Issue by JeffAment** [duckduckgo/Android#385]
**App version:** 5.12.0 release apk.  Not sure if 5.12.0 introduced this bug, however; I might do one of those log time git search things and report back when I have time.
**Device:** Google Pixel XL 9.0.  This also happens on a friend's phone, who had brought this issue to my attention earlier today.
**Steps to reproduce:** Perform an image search on DDG search engine, select an image and then click "view file" at the bottom of the page.  It shouldn't take long to find an offending image.
**Expected behavior:** Page opens with image.
**Actual behavior:** For _some_ images a blank white page appears and the image does not appear until the page is refreshed.  Sometimes the page is properly displayed if you are persistent enough, but most of the time it is not, so this seems very easy to reproduce (it is for my friend and I at least).

Finding an image to reproduce this issue shouldn't be hard, but if you want to expedite the process, do an image search for "pearl jam msg mazur" and the first* image displayed should demonstrate the behavior mentioned here.  The offending images seem to load a blank page an estimated 94% of the time for me, but will occasionally work correctly multiple times in a row, so it may take a few tries to reproduce this (in my experience no more than 3 or 4 tries; usually happens first try).

**My conjecture:** Take this with a kilo of salt and a glass of carbonated water, but I suspect this may be an intermittent https upgrade problem that happens when an image url starts with "http://" and can be upgraded to "https://", but is not upgraded.  I also suspect that this behavior is not exclusive to the image search function, but is part of a bigger problem for links processed in a certain context.  Maybe this is correct, maybe it's not :woman_shrugging::stuck_out_tongue_closed_eyes:.

*(http://www.billboard.com/files/styles/promo_650/public/stylus/107632-Pearl-Jam-MSG-5212010-Mazur-Wireimage.jpg)

**Comment by JeffAment** [comment]
**Update:** I did a git bisect and the problem presented itself in commit 54d682ca5ab7db1bb145b7c261be5ec22f5250d2  Everything works perfectly before these changes.

**Comment by CDRussell** [comment]
Thanks so much for all this info, and for narrowing down on the likely problematic commit; that really helps!

**Comment by subsymbolic** [comment]
We have a backend image encoding header issue that may be causing this. I'll report back when the backend is fixed and we can then retest to see if this is still happening.

**Comment by subsymbolic** [comment]
I have just retested this on develop and it seems to be fixed. @JeffAment thanks for reporting it, please let us know if you can still reproduce it

**Comment by JeffAment** [comment]
@subsymbolic 
I just pulled down from develop, and it appears to be working fine on my end also.  Very nice! :+1::tada:

**Comment by subsymbolic** [comment]
Great news, thanks for checking it for us.
