### ISSUE TITLE
Issue with tabs and bookmarks

### ISSUE THREAD

**Issue by ashucg** [duckduckgo/Android#386]
**App version**
5.12.0
**Device make and model**
Micromax/Yuphoria - YU5010A
**Android version**
5.1.1
**Steps to reproduce the bug**
See the screencast (GIF)
![ddg](https://user-images.githubusercontent.com/11291284/47600769-eeae3d00-d9e3-11e8-992a-9a3c8194dc5c.gif)
**Expected behavior**
Should be able to use tabs and add bookmarks
**Actual behavior**
I am unable to add bookmarks or use tabs. You can see the attached screenshot, **Add Bookmark** is greyed out and if I try to open a new tab it just open it within the current view. Also if I close the app and re-open it, I lose the page I had opened before.
I've tried reinstalling the app but it still doesn't work properly.

**Comment by CDRussell** [comment]
Thank you so much for raising this issue. We've had a few people mention similar type problems with the latest release, but it wasn't clear exactly what they were describing or when it was happening from their reports.

This, however, is fantastic. This will definitely help identify the problem. In fact, I have a pretty good suspicion on where to look already.

My problem so far was that I was unable to replicate the problem. If I can continue to have this problem, would you (or anyone else looking at this ticket) be in a position to test a fix?

**Comment by ashucg** [comment]
Sure, I don't mind testing :)

**Comment by CDRussell** [comment]
Excellent; much appreciated.

Can you tell me which version of Chrome you have installed, and if it is
enabled?

**Comment by ashucg** [comment]
WebView (Beta) version: 71.0.3578.20

**Comment by CDRussell** [comment]
Thanks so much for all this info. Hopefully I'll be able to replicate this now.

I'll post back when I have more info, or if I need help testing a fix (hopefully won't be needed).

Current line of thinking is that the problem might like around the way in which we moved the timing of when the current URL property was set to a different `WebView` callback.

Will update later when I have an update. Thanks again for all this info.

**Comment by CDRussell** [comment]
Internal issue: https://app.asana.com/0/488551667048375/885011869511894

**Comment by CDRussell** [comment]
Brief summary: 
>It turns out, that on (some versions of?) Android System WebView, onPageCommitVisible isn't called. 😞
>
>If the user has Chrome installed, this problem won't likely present itself. This will happen for people who don't have Chrome installed, or have it disabled, as they will be using the System WebView. It isn't yet clear if all System WebViews have this problem, or only certain versions.

**Comment by ashucg** [comment]
Thanks for the update, I will try to downgrade WebView and update you

**Comment by ashucg** [comment]
Did some tests:

DDG browser: 5.12.0
WebView: 69.0.3497.100 - not working
WebView beta: 71.0.3578.20 - not working

DDG browser: 5.11.1
WebView: 69.0.3497.100 - working fine
WebView beta: 71.0.3578.20 - working fine

**Comment by CDRussell** [comment]
It turns out the `WebView` version isn't the problem; rather, `onPageCommitVisible` is only called from API 23 onwards.

**Comment by CDRussell** [comment]
Fixed by https://github.com/duckduckgo/Android/pull/387

A hotfix will be going out for this today. Thanks for the help!

**Comment by ashucg** [comment]
@CDRussell I've tested `5.12.1` version and it is working fine now :1st_place_medal: Thanks for fixing it!

**Comment by CDRussell** [comment]
Much appreciated!
