### ISSUE TITLE
F-Droid request

### ISSUE THREAD

**Issue by ghost** [duckduckgo/Android#3889]
Hi!

Can you please publish your app on F-Droid officially? Or at least make your own F-Droid repo [like Tor did (link)](https://guardianproject.info/fdroid/repo/)?

F-Droid allows custom keys [(more info)](https://f-droid.org/2023/01/15/towards-a-reproducible-fdroid.html)

**Comment by malmstein** [comment]
DuckDuckGo is already published in F-Droid. https://f-droid.org/en/packages/com.duckduckgo.mobile.android/
