### ISSUE TITLE
Searching "std::[...]" gives "Unable to open this type of link" message

### ISSUE THREAD

**Issue by MrHallows** [duckduckgo/Android#391]
While researching C++ related topics, I searched for "std::fabs" (with and without the quotation marks), but no search results were loaded; only a toast with the message "Unable to open this type of link." I assume that this has something to do with the "site:[...]" search feature, but if so, shouldn't it know the difference between "site:[...]" and "std::[...]"? I thought that surrounding the search term with quotation marks would allow the term to be searched normally, but apparently not. Is this a bug or am I missing something here?

**Comment by CDRussell** [comment]
Thanks for reporting this. Yeah, this is a bug, likely the same one captured in #347. Once a fix for 347 is made, that should fix this one, too. Will close this issue for now and you can watch that issue for progress.

Thanks
