### ISSUE TITLE
[Request] Publish real release notes

### ISSUE THREAD

**Issue by Woebin** [duckduckgo/Android#3911]
### Describe the bug

The release notes for each release on GitHub tend to just read "bug fixes and other improvements". This is needlessly opaque and unhelpful, and I for one would like to know more about what I'm installing. I've had issues when using the browser which made me switch to another for the time being, and having clear release notes would help me decide if I should try DuckDuckGo again or keep waiting.

This issue was also brought up in the comments on #285, but that was after it had been closed and no further response was given 

### How to Reproduce

1. Check ["releases"](https://github.com/duckduckgo/Android/releases) section of this project.
2. Notice the lack of helpful release notes.

### Expected behavior

I expect release notes to describe the changes made between versions.

### Environment

```markdown
- DDG App Version:
- Device:
- OS:
```

**Comment by joshliebe** [comment]
Thanks for the feedback. This has been shared internally with the team.

We are currently only accepting Github Issues for bug reports, so I'm going to close this.
