### ISSUE TITLE
DDG doesnt block yandex ad anymore

### ISSUE THREAD

**Issue by Minalinsky007** [duckduckgo/Android#3936]
### Describe the bug

Going to my usual sites I started to see ads from https://yandex.ru/an/count/ (etc... Very long URL)

It's never happened before because these ads have been blocked before.
Because I could see it from my computer, but not my phone.

### How to Reproduce

 1

### Expected behavior

 2

### Environment

```markdown
- DDG App Version: 51.77.1
- Device: Pixel 6a
- OS:Android 13
```

**Comment by malmstein** [comment]
Thanks @Minalinsky007. 

We are aware of the issue and will be working on a fix.

**Comment by karlenDimla** [comment]
This should be fixed now. Thanks!
