### ISSUE TITLE
Feature request: Title bar in browser

### ISSUE THREAD

**Issue by flatcap-monty** [duckduckgo/Android#4]
A lot of full-fledged browsers have the title bar hide itself when you start to scroll in the webpage. It would be cool if the same happened with the browser here!

**Comment by subsymbolic** [comment]
Thanks for your feedback. This repo is for a new prototype app that we're building, I wonder if you meant to log this against our existing app at https://github.com/duckduckgo/android-search-and-stories? The good news is that the design for this app does include auto-hiding.
