### ISSUE TITLE
{suggestion} change Images internals PNG to SVG

### ISSUE THREAD

**Issue by EvertonMelo** [duckduckgo/Android#40]
The images PNG is Big Size and Obscure. 
But The SVG is small Size and equal quality, The file use resources of memory the SmartPhone no CPU ond Part Server. 

more information in:
https://www.w3.org/TR/SVG/svgdtd.html 
and:
https://en.wikipedia.org/wiki/Scalable_Vector_Graphics

**Comment by gvklive** [comment]
I can look into that, Can you help with the conversion?

**Comment by subsymbolic** [comment]
Great suggestion. This is an early prototype and is currently using temporary assets as the design has not been developed yet. Rest assured our designer will create svg assets for us.
