### ISSUE TITLE
Feature Request: Prompt confirmation for downloads

### ISSUE THREAD

**Issue by christophergeiger3** [duckduckgo/Android#400]
It would be nice if before every download a notification prompt would pop up, asking to confirm or deny the download, and would notify as to whether a file with the same name already exists within the downloads folder.

It may be helpful to look at the Opera browser's implementation for this, which I find convenient.

**Comment by subsymbolic** [comment]
We have now added a download confirmation dialog with the following PRs and will include these in the next release:
* https://github.com/duckduckgo/Android/pull/663
* https://github.com/duckduckgo/Android/pull/766

Thanks for the suggestion @christophergeiger3 and for your contribution @jainsahab 🎉
