### ISSUE TITLE
[Bug] Google blocked DuckDuckGo Browser Agent

### ISSUE THREAD

**Issue by vinc3nz** [duckduckgo/Android#4007]
### Describe the bug

A login is no longer possible. Google says that the browser agent is insecure. See screenshot for more information.
![Screenshot_20231214_162837_DuckDuckGo](https://github.com/duckduckgo/Android/assets/63001507/3f919815-e9da-4d95-8600-a66216c77a7d)

### How to Reproduce

Try to authorize using your Google account. In this case, it was LeonardoAI

### Expected behavior

I cab log into google

### Environment

```markdown
- DDG App Version: 5.181.1
- Device: Samsung S20 Ultra 5G
- OS: Android 13
```

**Comment by marcosholgado** [comment]
@vinc3nz does this work if you disable privacy protections?

**Comment by vinc3nz** [comment]
Yes, nothing changes when disabling it

**Comment by joshliebe** [comment]
This was fixed with https://github.com/duckduckgo/privacy-configuration/pull/1716
