### ISSUE TITLE
Adressbar disappear by swiping up on a mainactivity, unable to make it appear again.

### ISSUE THREAD

**Issue by tankmohit** [duckduckgo/Android#412]
I have also mentioned this issue long ago, on play store. When you swipe up the address bar, it goes away, and swiping down or doing anything can't help to make it appear again. You have to close the browser, and open it again to enter a new address.

**Comment by pwittchen** [comment]
In my case, it behaves as follows:
- swiping down hides the address bar
- swiping up shows the address bar

I'm using Android 9 (Pie) and Pixel 2 phone.

I think, this is correct behavior. Maybe your case appears on a specific Android version, customized OS or specific model of a phone?

**Comment by CDRussell** [comment]
There is a partial fix for this in https://github.com/duckduckgo/Android/pull/432. It will prevent it from happening if there is no web view available (so you can't now scroll the omnibar away on the blank tab view)

@tankmohit, can you clarify if this scenario is the only place you have saw this problem? or does it affect you when you have a site loaded in the web view?

**Comment by CDRussell** [comment]
Will close for now on the assumption that #432 fixes it, at least in the most egregious of cases. I'll re-open if I hear back it's still a problem.

Thanks for raising it providing the info! 👍
