### ISSUE TITLE
Question about webview 

### ISSUE THREAD

**Issue by heberjeur** [duckduckgo/Android#4144]
### Describe the bug

It's a question...

### How to Reproduce

Hi, I want to know if any sensitive data can be transmitted to Google via WebView. Also, are browsers based on Firefox Geckoview more secure because they don't use WebView?

### Expected behavior

Using firefox geckoview ?

### Environment

```markdown
- DDG App Version:
- Device:
- OS:
```

**Comment by malmstein** [comment]
Hi @heberjeur.

I’m afraid I can’t give you an answer regarding what information can be transmitted to Google. You’d have to ask in their [issue tracker](https://issuetracker.google.com/issues).

For questions regarding GeckoView, please refer to [their issue tracker](https://bugzilla.mozilla.org/index.cgi)
