### ISSUE TITLE
Opening a link in another app opens homepage requiring opening the link again before opening

### ISSUE THREAD

**Issue by Mikaela** [duckduckgo/Android#415]
I am on Android 8.0 on OnePlus 3. When I attempt opening a link from e.g. Telegram or initiate a search from KISS Launcher, DDG opens homepage and I have to switch app to open the link again before it opens as expected.

This doesn't happen on other web browsers on this device and I am unable to reproduce it with DDG on Nokia 1 with Android 8.1.

_Sent from my OnePlus3 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by CDRussell** [comment]
Thanks for reporting this.

Can I clarify something: when you share to the app, and you see the new tab page, does the shared link open in a background tab or not at all?

Also, can you share with me details of 
• which app version you're using?
• if you've enabled automatic data clearing or not?
• does it do it sometimes, or every time?

This is sounding very related to a bug I've just fixed (merged, but not yet released). 

Hopefully it's the same thing and the bug will be fixed for you in the next release.

**Comment by Mikaela** [comment]
> Thanks for reporting this.

You're welcome.

> Can you clarify something: when you share to the app, and you see the new tab page, does the shared link open in a background tab or not at all?

I had just opened links, not shared them, but when I share links, I see the same thing. DDG opens to the start page with the logo and "DuckDuckGo" text and in URL bar tehre is "Search or type URL". It's the only tab, so it doesn't open into background app unless I close the browser from recent apps and open it again.


> which app version you're using?

5.15.1 sa (51501)

> if you've enabled automatic data clearing or not?

In settings/PRIVACY I see "Automatically clear... Tabs and data" and "Clear on... App exit only".

> does it do it sometimes, or every time?

Every time it's not in recent apps, or nearly as I can consistently reproduce it.

**Comment by CDRussell** [comment]
Thanks for the update.

I'm hoping this will be fixed in the next release; likely be available this week. I'll ping back here when it's released and find out if you're still having the problem with that version.

**Comment by Mikaela** [comment]
This seems to work on 5.16.0 based on quick text, I changed my primary phone as the replacement doesn't have circuit/battery problem and has VoLTE/VoWiFi.

**Comment by CDRussell** [comment]
You beat me to it... I was just coming here to post that the new release was out.

Thanks for testing it out. And thanks again for the feedback! 🙏
