### ISSUE TITLE
Possible fragment lifecycle issue?

### ISSUE THREAD

**Issue by JeffAment** [duckduckgo/Android#422]
During normal usage of the app I noticed a strange behavior that felt sort of like a lifecycle issue, but I was unable to reproduce.  Upon further investigation I went into developer options and turned on "Don't keep activities" and consistently noticed similar behavior to what I had initially experienced, but only much, much worse.  The bug is relatively self-documenting but I will mention some example behaviors here so you will know what to look for:

- view state loads unpredictably.
- when switching back and forth between tabs, parts of a different tab fragment may load instead of the intended tab.  My favorite example of this is "ubiquitous duck mode."  I won't spoil the surprise of what ubiquitous duck mode is, and will instead leave this as an exercise for the reader (switch back and forth between two tabs a few times to reproduce this).

I would have looked into this some more, but my schedule is pretty hectic and uncertain at the moment so I don't really have much time for that right now.  If you would like for me to expand on anything here, however, I would be happy to do so; I tried to keep this as brief as I could, as I tend to write way too much sometimes :p.

**App Version and device info:** Version 5.16.0 (note that I am not necessarily saying that this version introduced this bug - during normal usage, the bug is very subtle and could have very well went unnoticed for a long time), Google Pixel XL, Android 9.0.
**How to reproduce:** Go to developer options and turn on "Don't keep activities."  Notice the view state and tab behavior when fragments are destroyed and restored.

**Comment by subsymbolic** [comment]
Thanks for reporting this @JeffAment. I think I know the incredible "ubiquitous duck mode" feature you refer to. I have logged this internally so we can get it fixed. Thanks again for letting us know.

**Comment by JeffAment** [comment]
I was kind of hoping that ubiquitous duck mode was an intended feature, but that's okay!  Thank you very much for your reply, @subsymbolic; I sincerely appreciate you taking the time to investigate, respond to, and formally log this report!

**Comment by subsymbolic** [comment]
@JeffAment we have changed a lot of logic in this area and I believe this is now fixed. Please let us know if you see it again and we can reopen this task.

**Comment by subsymbolic** [comment]
Thanks so much for testing this for us @JeffAment, I have reopened the issue.

**Comment by cmonfortep** [comment]
We have been trying to reproduce this issue without any luck (using Don't keep activities). Probably this was solved by previous changes in our browser (I hope so).

Closing this until someone manages to reproduce it again. Thanks.
