### ISSUE TITLE
Partial display of the table dedicated to the “Settings” option of the search page in “Mobile site” display mode

### ISSUE THREAD

**Issue by Ricky-Tigg** [duckduckgo/Android#4265]
### Describe the bug

**v.:** 5.192.2 | **screen resolution:** 1920 x 1200 | **screen size (mm):** 218 x 136

Hello. While the _Mobile site_ display mode option is selected, and the search page is viewed along the vertical axis of the screen, the display of the table dedicated to the _Settings_ option of the search page is partial.

![duckduckgo_android_vertical_axis_view](https://github.com/duckduckgo/Android/assets/26058215/02fb1cf8-ad80-493c-b4be-382b0ea93a96)

### How to Reproduce

1. Select the _Mobile site_ option.
2. Display the search page along the **vertical axis** of the screen by rotating the screen accordingly; this requires Android's _Auto-rotate_ option to be selected.
3. Click the _Settings_ option which is found in the search page.

### Expected behavior

The table dedicated to the Settings option that is found in the search page must be displayed in its entirety. See the case illustrated in this image, which was taken while the search page was viewed along the horizontal axis of the screen.

![duckduckgo_android_horizontal_axis_view](https://github.com/duckduckgo/Android/assets/26058215/7a7fe7c7-a26b-4d09-b8b0-cec349fcc4e5)

**Comment by CDRussell** [comment]
Thanks @Ricky-Tigg.

>conclude that this is not an issue specific to Duckduckgo for Android

Agreed. I will close this task on that basis, and share the feedback internally with the right team. Thanks for reporting!
