### ISSUE TITLE
[Bug] Cannot generate or use passkeys at passkeys.io

### ISSUE THREAD

**Issue by RecedingHare** [duckduckgo/Android#4268]
### Describe the bug

Passkey button is disabled. Cannot generate or use passkeys.

### How to Reproduce

1. Visit https://www.passkeys.io
2. Try to tap "Sign in with a passkey"

...the button is disabled.

* Same thing happens with protections activated or not.
* Signing up first allows you to "Add a passkey" but that button is also disabled

### Expected behavior

* The button should be available
* When clicked, the button should prompt for passkey

Note that passkeys.io list the OS and browsers that should work (all of them):

https://www.passkeys.io/compatible-devices

### Environment

```markdown
- DDG App Version: 5.191.0
- Device: Obscure
- OS: Android 11
```

**Comment by CDRussell** [comment]
Hi @RecedingHare, thanks for the report.

You are correct that passkeys aren't supported at the moment, but it is absolutely on our radar. 

As for _this_ task, I'll close it as a known issue since we are looking at what all needs done to support passkeys internally already and is on our roadmaps. It isn't trivial to support them in our app, so I can't offer a timeline yet but I would personally also love to have support in place for them as soon as we can.

Thanks for taking the time to report, and also, I love the GH handle name 👏

**Comment by Knuust** [comment]
Hi there, are there any news on this topic? I like your work and would love to use passkeys with duckduckgo.

**Comment by deanhumphreys** [comment]
@CDRussell, is there an update on the timeline on passkey support?
Thanks,
Dean

**Comment by CDRussell** [comment]
@deanhumphreys, passkey support is not generally available yet, however, it is in progress. I added the required integrations for it but it's only available internally to testers at the minute while we evaluate the overall UX. 

I'm hoping to get passkey support enabled for everyone soon. Can't promise any dates, but I can say it's in progress.

**Comment by deanhumphreys** [comment]
@CDRussell, great news! I love duckduckgo's new subscription service, so I'm really looking forward to support.

**Comment by redbit86k** [comment]
@CDRussell Any updates on this? 

Would be huge for me, to be able to auth and access my self-hosted services on my phone via pocket-ID without needing to change browser :(
Any way to support besides donations?

Great piece of software already, it can go get better.
Thanks!

**Comment by fellipetav** [comment]
For those have similar problems on Win 11:

I just selected "Don't allow Duck Duck Go create or use passkeys" in a particular website. The solution is not on DuckDuckGo settings, but in Windows settings. Open it and search for "passkeys" >> choose "see which apps have requested to create or use paskeys in the last week" >> look for DuckDuckGo >> expand it >> switch the button to "On".

**Comment by kja999** [comment]
Hi, Is this the correct issue to follow passkey support ?
I had to stop using DDG browser as all my internal apps use pocket-id for auth.

**Comment by vslinko** [comment]
I am really looking forward to passkey support. I fell in love with DuckDuckGo browser, but I cannot use it due to the need to authenticate via passkey.

**Comment by Tapter** [comment]
Any update on this? Passkeys are really getting common now and thus it's getting harder to even login to those sites with duckduckgo on android due to the missing passkey support :-(

**Comment by CDRussell** [comment]
Passkey support will be available in the next release 🎉

All the PRs are merged now ready to go. The next release likely cut next week and then the feature flag to enable passkeys will get enabled soon after. So should be available to you in ~2 weeks or so.

Apologies for the delays; nearly there 😄
