### ISSUE TITLE
Enable accessibility service to use a password manager

### ISSUE THREAD

**Issue by ismaelpuerto** [duckduckgo/Android#427]
The possibility to enable accessibility seevice by demand (maybe), to use a password manager like password androis store

**Comment by subsymbolic** [comment]
Thanks for the suggestion. We have had a number of requests for password manager integration and hope we can add this in the future.

**Comment by cmonfortep** [comment]
@ismaelpuerto we have been checking this request, and I can use my password manager to fill in login forms.

![image](https://user-images.githubusercontent.com/4747865/113894644-81b04b80-97c8-11eb-8cc1-8a6612517e79.png)


We are closing this feature request. Create a new discussion if your request was about something different. thanks.
