### ISSUE TITLE
[Bug] entering a url or domain name opens a http connection not https

### ISSUE THREAD

**Issue by PJVervoorn** [duckduckgo/Android#4293]
### Describe the bug

When I enter a url (or domain name) in the address/search bar, it opens a connection via port 80.
This is a security (and privacy) issue.
Most sites will automatically redirect to https, but that is possibly too late...
Since i have blocked port 80 on the firewall, duckduckgo browser can’t load the page.

### How to Reproduce

Enter a domain name (without protocol), i.e. _netscape.com_

### Expected behavior

Expected is that https is the default protocol; it should be tried first (or only?)

### Environment

```markdown
- DDG App Version: 5.192.2
- Device: Motorola Edge Ultra, Realme pad.
- OS: Android, MacOS (it happens with DuckDuckGo browser on MacOS too.)
```

**Comment by karlenDimla** [comment]
Hello! Thanks for your report.

This feature is actually working as intended as we also don't want to increase site breakages by assuming https option always exists. For more information, you can also read through https://spreadprivacy.com/duckduckgo-smarter-encryption/.

**Comment by PJVervoorn** [comment]
I disagree..
When I enter "netscape.com" (so without protocol) in ddg browser, it tries to open "http://netscape.com".
The firewall in my network rejects that, otherwise the provider could hijack that connection and show ads.
I think ddg browser should either default to https and use http as fallback, or -as your link seems to suggest- verify ddg's database and use the appropriate protocol.

**Comment by marcosholgado** [comment]
@PJVervoorn we already check with our smarter encryption db. If you believe netscape.com or other domains are missing from the db you can open an issue in https://github.com/duckduckgo/smarter-encryption although I see netscape.com redirects to aol which loads with https.
