### ISSUE TITLE
Recommendation: Having the app gives you result on the apps already install on the device

### ISSUE THREAD

**Issue by Bandito11** [duckduckgo/Android#43]
I sent you a feedback through the app but found this by accident, while trying to see if you guys are open source or not ;)

Basically aside from the results it gives you on the suggestions also suggest apps already installed on the device. 

Evie Launcher already do this if you want to see what I mean.

**Comment by subsymbolic** [comment]
Thanks for the idea, I've passed it on to our design team :)
