### ISSUE TITLE
[Bug] Download confirmation dialog is cut off in vertical/tablet mode

### ISSUE THREAD

**Issue by solargazr** [duckduckgo/Android#4342]
### Describe the bug

Download confirmation dialog is cut off in vertical/tablet mode. One has to swipe up from the bottom of the screen to see full dialog and actually commence the download. This is either a bug or bad design choice.

### How to Reproduce

1. Hold your android device in vertical position.
2. Select a file to download
3. Observe the dialog hiding beyond bottom screen border

![screen](https://github.com/duckduckgo/Android/assets/59263827/6c7ce7e1-431e-4a53-8ee5-ba71b43e9a38)

### Expected behavior

The whole download confirmation dialog is visible.

### Environment

```markdown
- DDG App Version: 5.194.0
- Device: Blackview BV5200 Pro and Lenovo Tab M10
- OS: Android 12 and Android 10
```

**Comment by anikiki** [comment]
@solargazr Thank you for bringing this issue to our attention. We'll be working on a fix.
