### ISSUE TITLE
[Bug] Accept-Language request header leaks your keyboard layouts

### ISSUE THREAD

**Issue by stigok** [duckduckgo/Android#4359]
### Describe the bug

Hello!

The HTTP `Accept-Language` request header leaks all your installed keyboard layouts. The value for **all** my outgoing requests is
```
Accept-Language: en-US,en;q=0.9,nb-NO;q=0.8,nb;q=0.7,pt-BR;q=0.6,pt;q=0.5,pl-PL;q=0.4,pl;q=0.3
```

I accept there might be other explanations for the ordering of these values and that this might just be a coincidence. However, all the languages I am using are still leaking. I am concerned as the amount of other people sharing this setup is most probably close to 0.

- My system laguage is English (US) (my 2nd most used language)
- My native language is Norwegian, (my most used language)
- I write Brazilian Portuguese, because I am learning (my 3rd most used language)
- I write Polish, because I am learning (my 4th most used language)

Related to #2068 which seems silently closed, but sure is a valid feature requests and privacy concern.

### How to Reproduce

Dump incoming requests headers on your own server, then visit it using the DuckDuckGo Browser.

### Expected behavior

A less fingerprintable value.

### Environment

```markdown
- DDG App Version: 5.193.1
- Device: FairPhone 3
- OS: /e/ OS v1.20-s
```

**Comment by karlenDimla** [comment]
Hello! Thanks for reporting this issue.

We actually have a task internally for this issue which is waiting to be prioritised at some point. l will close this task for now as this is already being tracked internally and would circle back here once the feature has been implemented.
