### ISSUE TITLE
[Bug] WebView not updated

### ISSUE THREAD

**Issue by andreassar** [duckduckgo/Android#4375]
### Describe the bug

How to update WebView the thing that DDG Android browser relies on it? I just checked the useragent and it's not the recent one. I'm on Chrome 92
I use Huawei device, the app is working fine but some websites won't open in desktop mode, like in a Galaxy A34 phone I tried
I can't have Chrome on it. Can you please include the WebView module in the apk file?

### How to Reproduce

It's not something you can reproduce, each device I tried it shows different useragent 

### Expected behavior

Website webapps won't open properly in desktop mode

### Environment

```markdown
- DDG App Version: latest
- Device:
- OS:
```

**Comment by aitorvs** [comment]
WebView updates are not part of the DDG android app but the Android system. One can update webview from the Play Store directly, [here](https://play.google.com/store/apps/details?id=com.google.android.webview)

**Comment by andreassar** [comment]
> WebView updates are not part of the DDG android app but the Android system. One can update webview from the Play Store directly, [here](https://play.google.com/store/apps/details?id=com.google.android.webview)

Hey thanks. I tried this but won't work, i think. I will try restarting but maybe it's different on Huawei phones because they can't use Google services
