### ISSUE TITLE
Replace 'Data cleared' Toast with Snackbar

### ISSUE THREAD

**Issue by jfitie** [duckduckgo/Android#438]
Internal Issue: https://app.asana.com/0/inbox/608920331025313/1109324284462152/1109385503500087

Please get rid of the toast showing 'Data cleared' after clicking on 'Clear All Tabs and Data'.
Seeing the browser in an empty state is enough of a confirmation. Also, I usually click the Clear Data button before I exit the browser, so it's annoying to have the toast visible for a few seconds after moving to the home screen or another application.

**Comment by jatinkumarg** [comment]
Hey, can I work on this feature? 

I can either reduce the duration of toast or completely remove it.

**Comment by CDRussell** [comment]
Hi, thanks for the request. I'm not sure we'd want to remove it to be honest. I know it might feel redundant to see it every time, but I figure for some people they will appreciate the confirmation that the data is gone. 🤔 

I'll raise it with the team and see what the thinking is, though.

**Comment by jfitie** [comment]
> Hi, thanks for the request. I'm not sure we'd want to remove it to be honest. I know it might feel redundant to see it every time, but I figure for some people they will appreciate the confirmation that the data is gone. 
> 
> I'll raise it with the team and see what the thinking is, though.

How about the way Focus does this?

![screenshot_20190212-104612_firefox focus](https://user-images.githubusercontent.com/23396293/52626611-d7705e00-2eb3-11e9-99e6-1dd7e42a25c1.jpg)

**Comment by CDRussell** [comment]
Ah, I see. So it isn't the fact that it's displaying the message that's the real issue, but more the fact specifically that it uses a `Toast` to do so? If it was a using a `Snackbar`-like approach (like FF does) you'd find that more appealing?

**Comment by jfitie** [comment]
Yes, that would be much better as the message would then remain in-app and not follow the user outside of it.

**Comment by jatinkumarg** [comment]
```Snackbar``` seems to be more suitable instead of ```Toast```. 

@CDRussell, can I still work on this feature?

**Comment by subsymbolic** [comment]
Thanks for the report @jfitie, those Toast messages are pretty outdated and could do with a UI refresh. We have asked our design team to have a look at making them nicer. 

@jatinkumarg, thanks for the offer to work on this. Keep an eye on this issue, if we open it up to community development in the future we'll add the "Help wanted" label to it.

**Comment by Cyberdroid1** [comment]
Any updates?

**Comment by Ammako** [comment]
On my end, there is no notification when I clear data (5.79.0)

**Comment by cmonfortep** [comment]
As @Ammako pointed out, we have improved our data clear process. We decided to remove the "data cleared" message when the user manually clears data via the Fire button. Closing this issue.
