### ISSUE TITLE
[Bug] Voice Search toggle not present

### ISSUE THREAD

**Issue by imageck** [duckduckgo/Android#4430]
### Describe the bug

The "Private Voice Search" toggle is not available to me. 

### How to Reproduce

1. Go to **Settings** > **Accessibility**.
2. No "Private Voice Search" toggle there.

### Expected behavior

It should appear there as normal.

### Environment

```markdown
- DDG App Version: 5.196.3
- Device: Samsung Galaxy M14 5G
- OS: Android 14

Up-to-date _Speech Recognition and Synthesis (Google TTS)_, locale set to en_US.
```

**Comment by imageck** [comment]
The visibility of the toggle depends on these conditions:

```kotlin
    override val isVoiceSearchSupported: Boolean
        get() = configProvider.get().run {
            voiceSearchFeature.self().isEnabled() &&
                hasValidVersion(sdkInt) &&
                isOnDeviceSpeechRecognitionSupported &&
                languageSupportChecker.isLanguageSupported() &&
                hasValidLocale(languageTag) &&
                voiceSearchFeatureRepository.manufacturerExceptions.none { it.name == deviceManufacturer }
        }
``` 

The first five appear to be met, but I'd like to debug properly.

**Comment by joshliebe** [comment]
@imageck Thank you for the report, I believe this will be fixed by https://github.com/duckduckgo/Android/pull/4443 (Available in the next release).

If the problem still persists, please open another issue and I will investigate further.
