### ISSUE TITLE
[Bug] <Switching between landscape and portrait cause browser to display things incorrectly >

### ISSUE THREAD

**Issue by Spiratatoe** [duckduckgo/Android#4433]
### Describe the bug

![IMG_4147](https://github.com/duckduckgo/Android/assets/95253269/2145c104-ef5f-4ae7-bc73-a3e5ae76784a)

the video is supposed to not have any black space, and be full screen, switching back and forth doesn't 'fix' it either

### How to Reproduce

keep switching screen view 

### Expected behavior

keep the proper format depending on how you hold your phone 

### Environment

```markdown
- DDG App Version:
- Device:
- OS:
```

**Comment by malmstein** [comment]
@Spiratatoe we can’t really help with issues from other browsers.
