### ISSUE TITLE
[Bug] Exact terms interpreted as URLs

### ISSUE THREAD

**Issue by imageck** [duckduckgo/Android#4472]
### Describe the bug

Exact search terms resembling domain names are loaded as pages when double-quoted.

### How to Reproduce

1. Enter `"com.android"`.
2. It's transformed into `http://"com.android"`.

### Expected behavior

Double-quoted, exact terms should not be interpreted as domain names.

### Environment

```markdown
- DDG App Version: 5.197.0
- Device: Samsung Galaxy M14 5G
- OS: Android 14
```

**Comment by joshliebe** [comment]
Thanks for the report @imageck!

This has been fixed with https://github.com/duckduckgo/Android/pull/4762 and will roll-out with the next release.
