### ISSUE TITLE
[Bug] A bit distorted showing of image when pulled to the left

### ISSUE THREAD

**Issue by Kaldesyvon** [duckduckgo/Android#4480]
### Describe the bug

When I zoom on the image and when I pull the image to the left with my finger, I can see these stripes on the right of the image. It does not do this when I pull image to the right.
![image](https://github.com/duckduckgo/Android/assets/48415649/fe3d8fd1-665a-4641-b568-0201522fbbdc)

### How to Reproduce

Open image, zoom and pull image to the left

### Expected behavior

I should not be there

### Environment

```markdown
- DDG App Version: 5.197.1
- Device: Pixel 6a
- OS: Android 14 (AP1A.240405.002)
```

**Comment by VISHNUONE8** [comment]
Tested this on Poco m2 pro with version 5.197.1 and haven't got the buggy behaviour as stated here.

**Comment by cmonfortep** [comment]
Tested on my side and I can't repro. However, another member of our team was able to reproduce it with different browsers, so there are to possible factors here: webview version, or device specific issue. Both are external to our app and we can't fix it from our app.
