### ISSUE TITLE
Long tapping on an article link shows images options

### ISSUE THREAD

**Issue by issueseverywhere** [duckduckgo/Android#449]
Hi!

First, thank you for maintaining duckduckgo privacy browser, which is my default android browser.

On a number of news websites, long tapping on an article link/item on the website homepage shows the options menu for the image of the article, and not the article page.

For example, if i am on the homepage of french news websites such as lemonde.fr / liberation.fr / francetvinfo.fr, longtapping on an article opens the options menu for the image of the article, while i'd like to be able to open the article in a background tab.

I reported it sites by sites through the broken site button, but it seems to be a general issue in DDG so i created this issue.

**Comment by subsymbolic** [comment]
Thanks for reporting this @issueseverywhere, I have opened it up to community contributions.

**Comment by subsymbolic** [comment]
Thanks for submitting this @issueseverywhere and for fixing it @dapacheco. We'll include the fix in our next release.
