### ISSUE TITLE
[Bug] VPN and App Tracking Protection no longer working

### ISSUE THREAD

**Issue by ADeadPixel** [duckduckgo/Android#4493]
### Describe the bug

Both VPN and App Tracking Protection services no longer work on my Pixel 8. I attempt to turn them back on but they immediately turn back off and give the message to check the System VPN settings to ensure it is still set to Always-On. It double checked it was still in and it still didn't work.

I toggled the switch, reset the VPN (removed and re-added), and rebooted my phone. Nothing worked. I have a premium account if that matters.

### How to Reproduce

Go to DDG settings
Attempt to turn in VPN or App Tracking Protection

### Expected behavior

Services turn on/work

### Environment

```markdown
Phone Information:
- Android version 14 
- Android security update April 5, 2024 
- Google Play system update April 1, 2024 
- Baseband version g5300i-231218-240404-B-11673025,g5300i-231218-240404-B -11673025 
- Kernel version 5.15.131-android14-11-gd99d9fe08eOc-ab11209359 #1 Tue Dec 12 17:18:56 UTC 2023 
- Build number AP1A.240405.002.B1

DDG Version:
- 5.197.1
```

**Comment by aitorvs** [comment]
Thanks for flagging this, QQ is this a recent regression you have experienced? or it never worked for your device?
If it was a regression, what was the last DDG app version that worked?
If it was a regression, have you had any OS update from it working till now?

**Comment by ADeadPixel** [comment]
The VPN was working perfectly for about a week. It stopped this morning when I attempted to manually change servers (which I have done a few times before successfully).

I have been using App Tracking Protection since it came out with some minor app specific issues but nothing major like this.

**Comment by aitorvs** [comment]
Do I understand correctly that it stopped working and neither Android OS nor DDG app were updated?

**Comment by ADeadPixel** [comment]
Correct. To my knowledge neither was updated. It is possible my phone auto-updated something overnight but I don't know of a way to know that for sure.

**Comment by aitorvs** [comment]
Do you have the possibility to re-install the app?

**Comment by ADeadPixel** [comment]
I attached a screen recording of the behavior. By reproduce do you mean attempt to turn on the VPN and capture that in the bug report?

**Comment by aitorvs** [comment]
> I attached a screen recording of the behavior. By reproduce do you mean attempt to turn on the VPN and capture that in the bug report?

Yeah. If you're willing to do that, not sure what the best way to share it with me, file can be slightly big.

**Comment by ADeadPixel** [comment]
Here is a link where you can download the bug report zip https://cloud.berryhaus.com/s/rH4XyBPJrTX4SZi

I'll email you a 1 time password to access the zip, it will expire tomorrow

**Comment by aitorvs** [comment]
@ADeadPixel can you try to re-enable the VPN now? (we discovered something that we could fix in the backend)

**Comment by ADeadPixel** [comment]
@aitorvs whatever backend change that was made appears to have fixed it! My VPN and App Protection are both working as expected. I did need to toggle the VPN system settings but once that was done it worked.

You now have me curious haha, was it a credential expiring or a service that failed silently

**Comment by aitorvs** [comment]
It's a bit long to explain, but TL;DR one backend call during the wireguard key registration (multi-step) process was mistakenly returning error in some cases to production users.

Closing this issue now as it's resolved.
Thanks a lot for flagging.

**Comment by ADeadPixel** [comment]
Thanks for the prompt response and resolving this so quickly!
