### ISSUE TITLE
How to change search engine

### ISSUE THREAD

**Issue by Gamer750** [duckduckgo/Android#4511]
### Describe the bug

 .

### How to Reproduce

.

### Expected behavior

 .

### Environment

```markdown
- DDG App Version:
- Device:
- OS:
```

**Comment by VISHNUONE8** [comment]
Hey @Gamer750 I don't think this issue can be labeled as a bug. Maybe you can request this as a feature request.
Also after seeing your issue #4511, I went to DuckDuckGo android browser and searched for search engine change option, I was unable to see the option to change.

**Comment by CrisBarreiro** [comment]
Thank you for reaching out with your question. Our DuckDuckGo browser is intentionally designed to use DuckDuckGo as the default search engine to ensure privacy for our users. As a result, the option to change the search engine is not available within our browser.

**Comment by lippfi** [comment]
I've just created a fork of DuckDuckGo that allows to change the default search engine
Feel free to check it out or add your preferred search engine via a PR - https://github.com/lippfi/SearxDuckGo

**Comment by freijon** [comment]
@lippfi : this is great, thank you! However, not everyone is a developer and can add their own search engine. Any chance you could make it configurable so you can enter the search url?
