### ISSUE TITLE
Navigation bar clipping into action bar

### ISSUE THREAD

**Issue by JeffAment** [duckduckgo/Android#455]
**App Version:** 5.19.0
**Device:** Pixel XL, Android 9.0
**The problem:** When scrolling up and down such that the navigation bar is hidden and then revealed, part of the navigation bar bleeds into the action bar.  See gifs below (it’s a little hard to see, so Gabe will show you the first one and the second one is a two-frame animation showing the part that is bleeding into the action bar flashing red so you can more easily see it).
**Steps to reproduce:** Scroll up and down until the navigation bar bleeds into the action bar.  Once the navigation bar clips into the action bar, it will stay there until you interact with the search bar or a new tab is opened etc.  On my device this is easily reproducible, ~~but I have not been able to reproduce this on an emulator yet (granted I could have tried harder).~~  Update: I have been able to reproduce this a few times on an emulator (Pixel XL, Android Q), but from my experience it takes a solid minute or two of scrolling for it to happen.

**Possible fix:** This no longer happens on my device after removing `android:fitsSystemWindows="true"` from the `AppBarLayout` in `include_omnibar_toolbar.xml` and moving it to the `CoordinatorLayout` in `fragment_browser_tab.xml`.

If this is something you would like to fix, I would be happy to submit a PR with this fix or review/test a PR that fixes this issue.  If this isn’t on the list of importance and you want to put this in your back pocket and save it for a rainy day, that’s cool too!  As always, if you need any more information on this or are having trouble reproducing this, feel free to ping me and I will do whatever I can to help.

![premiere mock_11](https://user-images.githubusercontent.com/21976019/54471391-9c9d6680-478e-11e9-9e1f-134033065d69.gif)
![DDGgif](https://user-images.githubusercontent.com/21976019/54471393-9dce9380-478e-11e9-8401-4ff72eb67727.gif)

**Comment by subsymbolic** [comment]
Thanks for the bug report and for entertaining us @JeffAment  😆😆😆
Regarding your question about submitting a PR, that would be great! I should have time to review it later this week.

**Comment by JeffAment** [comment]
Sounds good @subsymbolic.  I'll submit a PR as soon as I have a spare moment, most likely sometime tomorrow (Tuesday).  Also, thanks for not getting mad about the [very unprofessional] gif!  :smile:

**Comment by CDRussell** [comment]
For the record, I love the gif! 😍

**Comment by JeffAment** [comment]
Thanks for saying something, @CDRussell!  The running joke this year has been that the only movie I watch in 2019 is “How to Lose a Guy in 10 Days” and that it has been on repeat for three months.  This alludes to my many short-lived interpersonal relationships in 2019 that met an untimely demise because of memes that I made.  So, yeah, I genuinely appreciate the both of you taking it in stride and not blacklisting me [yet]!

**Comment by subsymbolic** [comment]
Thanks for submitting this @JeffAment. I never managed to reproduce the original bleed issue you reported but would have accepted this change, however it introduces a new issue. When switching from landscape to portrait the omnibar can no longer be scrolled away.

To reproduce:
- Launch the app in landscape
- Enter a search
- Rotate to portrait
- Scroll to make the omnibar disappear, it is now glued in place

**Comment by subsymbolic** [comment]
Thanks again for logging this @JeffAment. We have struggled to reproduce it so are now closing it however we are happy to open it again should we receive more requests to fix it.
