### ISSUE TITLE
[Bug] font size for plaintext should mirror html font size

### ISSUE THREAD

**Issue by akkana** [duckduckgo/Android#4555]
### Describe the bug

I have font size set to 120% in Accessibility Settings, and basic web pages look fine (as long as they have a <meta name="viewport" content="width=device-width, initial-scale=1"> or equivalent, otherwise they're tiny).

But plaintext files, .txt, and HTML files that don't have that meta viewport directive, display in a font that's absolutely microscopic. Please, can the browser obey the accessibility settings in those two cases?

Chrome on android now defaults to a nice readable font for .txt files and for html files without meta viewport. But I'd rather use DDG for all my android browsing. :-)

### How to Reproduce

Go to: https://shallowsky.com/python/lesson1.txt
(or any file ending in .txt).

Notice the tiny font size.

Call up Settings -> Accessibility and drag the slider to set the font size larger, say, 120% or more.

Go back to the text file. Still tiny.

To see the meta viewport difference in HTML files:
https://shallowsky.com/python/
is a page that has <meta name="viewport" content="width=device-width, initial-scale=1">
https://shallowsky.com/obsreport.cgi
is an HTML page that doesn't include the meta viewport line.

Notice how tiny the text is on the obsreport page compared with the python page/

### Expected behavior

A font large enough to be readable.
If I need to increase the text for accessibility reasons, I need it for all types of files, not just one type.

I can pinch-zoom to make the font bigger temporarily, but then the lines disappear off the right side of the screen, whereas if the font size had been larger to begin with, long lines would wrap.

### Environment

```markdown
- DDG App Version: 5.199.5 (51995000)
- Device: Pixel 6a and Lenovo Tab M9
- OS: Android 14 and 13
```

**Comment by malmstein** [comment]
@akkana thanks for the bug report. We’ll be working on this in the near future, closing this as triaged.
