### ISSUE TITLE
Feature Update the F-droid Version

### ISSUE THREAD

**Issue by Chungaa** [duckduckgo/Android#4600]
### Describe the bug

Why are there no new versions of duckdduckgo on f-droid l? The app has not been updated for a long time.
https://f-droid.org/packages/com.duckduckgo.mobile.android/

### How to Reproduce

No

### Expected behavior

No

**Comment by nalcalag** [comment]
Thanks for opening the issue @Chungaa. This is something we have in our backlog and we plan to address. 
For more context, since we released our [Privacy Pro](https://spreadprivacy.com/meetprivacypro/) service, we need to change the way we build our app so it's compatible with F-droid again.
