### ISSUE TITLE
[Bug] Favourited Bookmarklets Search Instead of Running

### ISSUE THREAD

**Issue by Hamsteroonie** [duckduckgo/Android#4638]
### Describe the bug

When running a bookmarklet let that is favourited, it will search the contents of the bookmarklet instead of running it.

### How to Reproduce

1. Bookmark a site
2. Click 'Edit Bookmark'
3. Add to favourites and change the URL to a bookmarklet (e. g. 'javascript:alert("example")' )
4. Open any website
5. Tap on the search bar
6. Click on the bookmarklet

https://github.com/duckduckgo/Android/assets/144549336/941517f5-2562-4c62-8fcf-614fc489392c

### Expected behavior

It should run the bookmarklet in the same way that it runs when you type the name of the bookmarklet into the search bar and press the autocomplete for that bookmarklet.

### Environment

```markdown
- DDG App Version: 5.203.1
- Device: Doogee T20 Mini
- OS: Android 13
```

**Comment by cmonfortep** [comment]
Thanks for sharing. Currently we don't officially support bookmarklets on mobile, but we can take a look an see if there's any quick win we can safely introduce.
