### ISSUE TITLE
Allow to toggle on/off images

### ISSUE THREAD

**Issue by issueseverywhere** [duckduckgo/Android#464]
Hello,

First, thanks a lot to all the maintainers of duckduckgo android, which is my default browser.
Then, thanks again for solving the last issue i added here: problem with opening a link in background tab when there was an image linked to it, on many news websites.

I would like to be able to toggle on/off images in the parameters, has it is possible on opera mini for example (by loading a unique color box and the replacement text, in replacement of the picture). The fact that duckduckgo privacy browser blocks trackers natively helps a lot when you have a poor connection and its a good feature to "sell" to people who wouldn't care/understand privacy problems.

Leaving in a country where 3g connection on mobile is paid by the Mo and where the connection is quite slow, loading images has a cost in money and in websites loading time, while it is often unnecessary.

Thanks

**Comment by allmfrd** [comment]
My ex hacked my account and is tracking me deleting accounts driving me nuts what do I do

**Comment by allmfrd** [comment]
I cant figure out why duckduck go wont allow me to install it so I can set my privacy settings
