### ISSUE TITLE
Close the current tab

### ISSUE THREAD

**Issue by casibus** [duckduckgo/Android#466]
A "close current Tab" button/optiom seems to be missing. One always has to navigate through the list of open tabs first to close it.

**Comment by subsymbolic** [comment]
Thanks, this is a great idea, I've shared it with our product team.

**Comment by subsymbolic** [comment]
Internal link: https://app.asana.com/0/search/1118831380832670/1118831380832671.

**Comment by thinasdf** [comment]
I can't seem to find this feature, using DDGG version 5.184.0 on Android.
