### ISSUE TITLE
Store all open tabs as bookmarks 

### ISSUE THREAD

**Issue by casibus** [duckduckgo/Android#467]
That feature would be important when dealing with high numbers of tabs.

**Comment by subsymbolic** [comment]
Great suggestion, I've shared it with our product team.

**Comment by subsymbolic** [comment]
Internal task: https://app.asana.com/0/1114312848812008/1114312848812012

**Comment by Poopooracoocoo** [comment]
@subsymbolic hey uh what happened to this

**Comment by subsymbolic** [comment]
We close out ideas after sharing them with our product team, if they are unlikely to ago ahead in the foreseeable future. We're a small team and it's our way of managing the issues list.

That said, this one might happen as we did something similar on iOS so I'm reopening. Thanks for the ping!

**Comment by rkiddy** [comment]
Why is the suggestion only to store the tabs as bookmarks? Why would it not make sense to store all open tabs to the pasteboard. Issue #728 got closed, but would it not have been a more general and also more empowering and less intrusive and controlling solution.

Right next to 'Close All Tabs', there could be a 'Save Tabs To' option. That could bring up options like Bookmarks, Pasteboard, .... or some other things.

This would be a better solution than just writing to bookmarks.

**Comment by Poopooracoocoo** [comment]
@rkiddy I think of bookmarking as the more powerful option. I imagine being able to copy and share a whole folder of bookmarks like you said.


@subsymbolic it's a bit strange that y'all closed this before. to us it can look like you declined or implemented this.

**Comment by cmonfortep** [comment]
Hello @IOI-655321  , thanks for taking the time to submit this feature request. Sorry for the very late response, we are currently going through old feature requests.

After internal discussion with the team, we've agreed that there's no plan in the foreseeable future to support this request. This feature was also removed from the iOS app, so no plans to do similar on Android. That being said, we will soon run a project to improve our bookmark management, hope that will address some of the ideas posted in this thread.

**Comment by owlicious** [comment]
Is it really that difficult to implement a "select all open tabs" or "share all open tabs" or "bookmark all open tabs" feature? This is commonly available in most browsers! I had no idea that it was not available in DuckDuckGo - a highly rated browser - years ago when I set it as my default browser, and now I am up to my neck in tabs (which automatically open every time I'm doing research) and no way to efficiently go through them aside from a laborious scrolling process. Can't see the titles of the websites, and the thumbnail of each doesn't even load until I click it, so there's no efficient way to go through these hundreds, perhaps over a thousand or so, tabs aside from clicking...every...single...one -- else losing it?

I've literally been waiting for years for this feature to be developed, and am highly frustrated that it's being closed again! This is a critical feature. How long would it really take to implement? Is there any third party tool that can pick up the slack on this & automate the process?

**Comment by iferc** [comment]
Is there any way of extracting open tab data like via `adb`? I've got many years of tabs I'd love to keep and transfer to my desktop.

I could have sworn I was able to extract them once upon a time with `adb`, but I can't seem to find or get access to the folder for the app. Though probably my old phone was rooted and this one is not.

Any tips would be appreciated as the number of open tabs I'd like to keep is incredible.

**Comment by Lighter01** [comment]
Writing to confirm that the feature would still be very useful. I have an insane number of tabs open in browser, and I would like to transfer them all at once to my PC. But making bookmarks for each open tab separately is so inconvenient and takes hours (no joke, that's how many tabs I actually have opened).

**Comment by wo1fmane** [comment]
How can a search organization that has a major browser so completely misunderstand how people use browsers? The sync feature is completely useless without including open tabs. How many bookmarks do you have compared to the number of open tabs? I have all of 3 bookmarks, which would be trivial to transfer manually, and a hundred open tabs, which will be a nightmare to transfer manually. Tabs are FAR quicker and easier to use than bookmarks, which is why most people don't use bookmarks at all anymore.

But apparently the powers that be at DuckDuckGo want me to go back to Firefox. Permanently. Because Firefox lets me transfer open tabs in a plethora of ways without having to sign in.

**Comment by VetleHvoslef** [comment]
@cmonfortep Are PRs welcome if someone is interested in implementing this feature?

**Comment by wo1fmane** [comment]
> Universal Copy app, for example, can grab those links from the tab view. There are other apps that can do it most likely but that's what I used. Only 166 tabs fortunately. The output is a list containing the titles and urls. Bookmarks would be better...

Yeah, install yet another app just to do one thing for another app that should be supported by the other app natively. DuckDuckGo is supposed to be about privacy and security. That means not offloading fundamental - and extremely private/sensitive - functions like this to other apps.
