### ISSUE TITLE
DuckDuckGo Android browser is still crashing

### ISSUE THREAD

**Issue by NotepadPlusUser** [duckduckgo/Android#4679]
### Describe the bug

I have seen your succession of hopeful update notes on the Google Play pages, but unfortunately, I have to report that the crashing that you are addressing has not yet been fixed on my phone.

I have been using Duckduckgo as my default browser on Android for years now — very successfully and happily until three or four months ago, when it began crashing.

THE PROBLEM: I open a few web pages in three or four tabs, then I switch apps — perhaps I receive an SMS, or make a phone call, or look something up — and when I try to return to it, Duckduckgo has completely shut down, and I have lost all the searching and reading that I was doing.

This has made Duckduckgo impossible to use, and with great sadness, I have made Vivaldi my default Android browser.  How I miss the Fire button!

Could you please sort this out.  Clearly it is not an easy fix.

PS:  I launched Duckduckgo yesterday and got a popup to comment on Duckduckgo.  I began to write about this, but the app crashed, and I lost all that I had written.  What an irony!

### How to Reproduce

As described above.

### Expected behavior

As described above

### Environment

```markdown
- DDG App Version: 5.204.1
- Device: Samsung Note10+
- OS: 12, OneUI 4.1, Kernel 4.14.113-24230781
Using VPN from PIA V4.0.7
```

**Comment by CrisBarreiro** [comment]
Thank you for your input! We've looked into it but unfortunately haven't find a way to reproduce the issue, and so we can't take any further action at this moment
