### ISSUE TITLE
DNS over HTTPS support and encrypted SNI?

### ISSUE THREAD

**Issue by Mikaela** [duckduckgo/Android#470]
Firefox supports them also on Android and currently using DNS over HTTPS or DNS over TLS requires installing Intra or similar app acting to be a VPN (unless using Android 9 where enabling a VPN disables DoT).

I think DoH should be opt-in and the server configurable even if you ran your own resolver.

**Comment by Poopooracoocoo** [comment]
If it's based on Chromium, DDG Browser could use Bromite's patches for DoH! :)

**Comment by 3j9fkyahunqoxwqu** [comment]
> If it's based on Chromium, DDG Browser could use Bromite's patches for DoH! :)

Agree 
I also hope so but because DuckDuckGo uses the webview and not bundled chromium in itself so I don't know if they could use that or not

**Comment by eliliam** [comment]
Any updates on this? It's a major security feature and a must-have for the a security focused browser.

**Comment by Ryan451** [comment]
I found this [article](https://www.androidpolice.com/2020/03/26/make-android-use-dns-server-choice/) on how to connect android phones to a dns server of your choice. Hope it helps!

**Comment by Ryan451** [comment]
Better Encrypted SNI: Encrypted Client Hello

Good-bye ESNI, hello ECH: https://blog.cloudflare.com/encrypted-client-hello/

More information: https://tools.ietf.org/id/draft-ietf-tls-esni-08.html
