### ISSUE TITLE
Authentication and Verification [Bug] <title>

### ISSUE THREAD

**Issue by Yunglow22** [duckduckgo/Android#4727]
### Describe the bug

I found a lot of visitors on my business account from Facebook and they are promoting pages that are strange and suspicious .

### How to Reproduce

N/A

### Expected behavior

I never expected anything. 

### Environment

```markdown
- DDG App Version:
- Device:
- OS:
N/A
```

**Comment by joshliebe** [comment]
This is not related to DuckDuckGo, closing.
