### ISSUE TITLE
Allow encoded spaces in url path

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/Android#476]
App version: 5.21.2 (via F-Droid)

When opening a link (in a new tab, or typing the URL in manually) which has `search/X%20Y` at the end, the page will open as a DDG search (with the URL Decode IA showing) rather than on the expected webpage.

For example, the search `http://foo.com/search/bar%20baz` displays as a DDG search, but `http://foo.com/search/bar` loads the expected webpage.

**Comment by subsymbolic** [comment]
This is now fixed and will be available in the next release. Thanks @GuiltyDolphin and @donfuxx.
