### ISSUE TITLE
Setting off automatic redirection

### ISSUE THREAD

**Issue by bopoh13** [duckduckgo/Android#478]
In the third world countries, mobile operators create viral advertising networks, where they make paid subscriptions through redirects and push notifications.

Can you add a setting to disable automatic redirects from the browser? Legally, it is impossible to fight them, because they are monopolists.

Thanks for attention.

**Comment by cmonfortep** [comment]
Thanks for sharing and sorry for the 1year late response. I'm currently checking old issues in our repo.

I understand the problem you described, but blocking automatic redirection will break many different website functionalities that are not harmful to the user. We could introduce some kind of allow/deny list but that will add complexity to this feature, and it's not something that has been requested by many users. It's also a big product change and not something we plan to do so I'm going to close this issue.
