### ISSUE TITLE
[Bug] App hides itself when minimizing and sometimes even closes

### ISSUE THREAD

**Issue by bergamin** [duckduckgo/Android#4791]
### Describe the bug

When minimizing the app, it doesn't show up in the recent items.

I have set up DuckDuckGo to clear browsing data when I close the app. This bug makes it look like I closed the app, while I did not, so next time I open it, since I had never actually closed it, it will keep the browsing data from my last session.

Not always, but sometimes it also closes when I minimize, so I lose the opened tabs.

### How to Reproduce

Here is a video. This video will be automatically deleted in 3 or so months, so if you need me to reupload it in the future, please let me know

https://streamable.com/lk5ptm

### Expected behavior

The app should show up in the recent apps list

### Environment

```markdown
- DDG App Version: 5.207.2
- Device: Motorola Edge 40
- OS: Android 14
```

**Comment by anikiki** [comment]
@bergamin Thanks for reporting this. It should be fixed. Can you please try again using the latest version?

**Comment by bergamin** [comment]
Hello, @anikiki. It's working now! Thank you very much!
