### ISSUE TITLE
[Bug] Reloading page clears conversation with AI chat

### ISSUE THREAD

**Issue by 4rnv** [duckduckgo/Android#4804]
### Describe the bug

Reloading the page (accidentally or otherwise) clears the conversation with DDG AI chat. 

### How to Reproduce

- Open [Duckduckgo AI chat](https://duckduckgo.com/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1)
- Choose any model and interact with it
- Reload page, responses are gone

### Expected behavior

Chat history should not be cleared if user reloads the tab. If the user wants to clear the conversation they can simply press the clear conversation button on bottom left. Maybe the chat history could be stored in the device's local storage, so that clumsy people like yours truly won't end up losing responses upon unintentionally reloading the page. 

### Environment

```markdown
- DDG App Version: 5.208.1
- Device: Nokia 5.1
- OS: Android 10
```

**Comment by lmac012** [comment]
Thanks for reaching out! To clarify, this is a known limitation of AI Chat and not a bug specific to the Android app. Unfortunately, this means chat history won’t be saved if the page is refreshed, regardless of the browser you’re using. We really appreciate your feedback and have passed it along to the relevant team.
