### ISSUE TITLE
Amazon app store version out of date

### ISSUE THREAD

**Issue by arunsathiya** [duckduckgo/Android#483]
I just downloaded DuckDuckGo Android on Amazon app store and noticed that the app version is 3.1.0. Is this something you might be able to update on Amazon app store?

**Comment by subsymbolic** [comment]
Thanks for reporting this. We aren't currently publishing to the Amazon app store but will investigate if we can start again soon.

**Comment by cmonfortep** [comment]
@arunsathiya we are not publishing our app to the Amazon App. However we publish it into the F-droid app store -> https://f-droid.org/en/packages/com.duckduckgo.mobile.android/

Thanks.
