### ISSUE TITLE
[Bug] Add an easier way to bulk delete bookmarks

### ISSUE THREAD

**Issue by vext01** [duckduckgo/Android#4857]
### Describe the bug

Not really a bug. More of a feature request.

I had a big purge of my bookmarks just now. I wanted to delete about 50 and keep some 10.

I had to manually click `...` and `delete` on every row in the list that I wanted to delete. This is laborious.

### How to Reproduce

1. Go to bookmarks
2. Try to delete many of them quickly.

### Expected behavior

I expected to be able to:

1. Go to bookmarks.
2. Long press a bookmark to delete to enter "select mode". The initial item is selected.
3. Tap any others bookmarks you want to delete to add them to the selection.
4. Tap a delete button somewhere on the UI to delete the selected bookmarks.

Bonus points: a "select all" button for those wishing to delete all bookmarks.

### Environment

```markdown
- DDG App Version: 4.209.2
- Device: Samsung.
- OS: Android 14
```

**Comment by marcosholgado** [comment]
Thanks for this. I'm gonna close because this is not really a bug but a feature request. I have forwarded it to the product team for prioritization though.

**Comment by syntactic-sour** [comment]
Would be a major improvement for users from countries where police is permitted to go through your bookmarks / search history etc to frame you for something bizzare.

**Comment by vext01** [comment]
I feel like someone could quickly implement this with an LLM. Would that be allowed?

(I have a ever growing list of ephemeral bookmarks that really need sorting out and i can't bear to remove them one-by-one)
