### ISSUE TITLE
[Bug] Content visible for a split section after tapping "clear all tabs and data"

### ISSUE THREAD

**Issue by vext01** [duckduckgo/Android#4858]
### Describe the bug

When you tap "clear all tabs and data" an animation is displayed (fire by default) that signifies permanent deletion of all data. It's a neat UI cue that I find very satisfying.

However after the animation has finished, the page that was visible "pre-burn" flashes up for a fraction of a second, thus spoiling the metaphor.

### How to Reproduce

1. click the fire icon
2. tap "clear all tabs and data"
3. marvel at the fire animation
4. previously visible web page flashes up for a fraction of a second.

### Expected behavior

1. click the fire icon
2. tap "clear all tabs and data"
3. marvel at the fire animation
4. app goes directly back to a blank slate without showing remnants of what was there before.

### Environment

```markdown
- DDG App Version:5.209.2
- Device: Samsung
- OS: Android 14
```

**Comment by marcosholgado** [comment]
Thanks for your report. We are aware of this and currently prioritizing a fix, I'll add this report to it so it can hopefully be added soon to the roadmap.

**Comment by vext01** [comment]
Thanks so much.

Love the app. Thanks for making it!

**Comment by anikiki** [comment]
@vext01 Thanks for reporting this. It has been fixed in the latest version (5.213.0).

**Comment by vext01** [comment]
Fantastic! Thank you!

**Comment by vext01** [comment]
Can confirm that this is fixed.

There's a small flicker towards the end of the animation, but it's not a big deal.

**Comment by anikiki** [comment]
Thanks @vext01 :tada:
