### ISSUE TITLE
Changing default settings

### ISSUE THREAD

**Issue by lorenzo-a** [duckduckgo/Android#492]
I looked at the source & documentation but have not found a way to achieve the following goal:

Is it possible to adapt the source in a way such that default settings are changed?

**Comment by subsymbolic** [comment]
What do you want to change?

**Comment by lorenzo-a** [comment]
Changing the default privacy settings to the strictest. I have been looking at the code but couldn't wrap my head around the best way to go about this.

**Comment by subsymbolic** [comment]
I'm closing this as your issue is unclear. I'm not sure what settings you mean however we aim to be as private as possible. If you notice a specific area where you think we can improve feel free to open a new issue with details.
