### ISSUE TITLE
Feature Request: Centre on current tab

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/Android#494]
I quite often have a large number of tabs open, with relevant tabs close together.

It would be really useful if, when pressing the tabs button, the view centred on the current tab, rather than the first.

This would make it easier to e.g., delete the current tab, as well as find tabs opened from the current one.

Maybe this could be an option in the settings, if there is still call to be able to start at the first tab.

**Comment by subsymbolic** [comment]
Thanks for the feedback @GuiltyDolphin, this is something we are working on internally right now

**Comment by subsymbolic** [comment]
Thanks for requesting this. We now have this in PR in #540. It should be in test soon and then available to everyone in the coming weeks.
