### ISSUE TITLE
Site-specific search doesn't work; attempts to open as a link instead and fails

### ISSUE THREAD

**Issue by arunsathiya** [duckduckgo/Android#499]
When searching for `site:producthunt.com change password` using the search/URL box at the top, the process fails with a `Unable to open this type of link`.

Visiting DuckDuckGo.com and typing the same works though. 

It's just that searching on the URL box fails.

**Comment by GuiltyDolphin** [comment]
See also #347

**Comment by arunsathiya** [comment]
Oh, I completely missed that. I see an open PR against this issue. @subsymbolic, could you advise on which issue could be closed at this stage? 🤔

**Comment by subsymbolic** [comment]
Thanks @arunsathiya and @GuiltyDolphin. I'll close this one as a duplicate as it came after https://github.com/duckduckgo/Android/issues/347.
