### ISSUE TITLE
Feature request: Open search results in external browser

### ISSUE THREAD

**Issue by ZeRoZeRoRaZ** [duckduckgo/Android#5]
Now there are two options in Use External Browser:
Never - results and sites are opened directly in app
Always - results are redirected to default browser

Please add something between:
Just sites - search results are displayed in app, but sites are opened in default browser.

This solution works perfectly with "flying" browsers line flyperlink, because you can open many results one by one, and then browse them later.

**Comment by uncertainquark** [comment]
Yeah, this makes total sense. That's what a search app is for ideally.

**Comment by Null-Senpai** [comment]
Also hope this gets implemented. Literally the only reason I am using firefox (it has a search activity) rather then DDG's own app.

**Comment by abhaymaniyar** [comment]
Is anyone working on this? I am willing to work on this. Please comment if I can start working on it.

**Comment by uncertainquark** [comment]
It is open source, so you can create a parallel branch by forking it and work on the feature. Then you can submit a pull request.

**Comment by gvklive** [comment]
I would start working on it now.  @abhaymaniyar ,get in touch, will work together.

**Comment by gvklive** [comment]
Hey guys, I compiled & ran the DDG app, it shows version 0.1.0. while the latest version on play store is a different one. Also the app is almost different from the the play store version. Did I make any mistake or something?

**Comment by abhaymaniyar** [comment]
Yeah Sure @gvklive :) 
About your question, The present version of the app on the Play Store is a released version and the version that you compiled is from 'develop' branch. The changes in develop branch are yet to be implemented to the release version of the app.

**Comment by gvklive** [comment]
I figured it out
the version on play store is ddg search & stories app, 
which development is currently on hold

**Comment by gvklive** [comment]
Quick question: Should there be a preference with open search result in external browser or it should be default behaviour?

**Comment by gvklive** [comment]
Done, Check the PR & update me.

**Comment by uncertainquark** [comment]
> Quick question: Should there be a preference with open search result in external browser or it should be default behaviour?

IMO, its should be the default. This is how all search apps work: Google app/Bing/Firefox Search activity, etc.

**Comment by gvklive** [comment]
Okay, will change it in next commit, let this PR get closed first.

**Comment by subsymbolic** [comment]
Thanks for logging this - this feature really makes sense for the search and stories app. This repo is for a private search and browsing prototype. Do you think a global option to open links externally makes as much sense  here?

Our plan is to have links open internally by default and let users long press for an option to open externally. Let me know if you think that would work for you.

**Comment by uncertainquark** [comment]
@subsymbolic Yes, the feedback is for the search and stories app and it would be very much appreciated to get it working in the suggested way.

**Comment by gvklive** [comment]
Actually, most people really like to use a search app to search & transfer them to browser. browsing in the app actually doesn't make sense. Even for private purposes. there are better alternatives for that e.g. firefox & stuff. & the search & stories app development is put on hold (as in description). So, this'll be mainstream app in next days if I'm not wrong

**Comment by ZeRoZeRoRaZ** [comment]
@subsymbolic Yes it would work.
@gvklive can you please provide apk with your changes?

**Comment by subsymbolic** [comment]
Thanks again for the feedback. As this is really for our other app, I am now closing it. This app will be built for browsing so the UI for opening external links will be really different. Feel free to have a play once we release it and let us know how we can improve.
