### ISSUE TITLE
Open Link in New Tab (target="_blank")

### ISSUE THREAD

**Issue by thecliguy** [duckduckgo/Android#502]
When clicking a link where `target="_blank"` the resultant page loads in the current tab.

EG: 
`<a href="https://www.github.com" target="_blank">GitHub</a>`
<a href="https://www.github.com" target="_blank">GitHub</a> 

The expected/conventional behaviour is to open such links in a new tab.

Can the app either adhere to the conventional behaviour or provide the ability to enable/disable it via the options menu?

**Comment by thecliguy** [comment]
@subsymbolic I don't mean to chase, just curious to know if PR #511 hasn't been reviewed because no one has had time to do so or whether you have no intention of reviewing it?

**Comment by subsymbolic** [comment]
@thecliguy it's a good suggestion and we are tempted to make the change but still discussing the pros and cons internally as it can be abused by sites and many users find the new tab launch unexpected. I'll update this issue again once we have made a decision.

**Comment by donfuxx** [comment]
It could be a setting to allow opening of new tabs, so the user can decide what he actually wants.

**Comment by subsymbolic** [comment]
@donfuxx definitely - that's one of the options we are considering.

**Comment by subsymbolic** [comment]
A lot of users are asking for this so we have decided to add it. We'll start by honoring the default behavior without a toggle but may introduce one if we need to later.

**Comment by subsymbolic** [comment]
This final fix for this is now merged and will be available in the next release. Thanks for reporting it @thecliguy and for helping us solve it @donfuxx.
