### ISSUE TITLE
Freedom from the Google Recaptcha Abusive

### ISSUE THREAD

**Issue by fakeNewsDay** [duckduckgo/Android#506]
I come towards you for help.

I find the Recaptcha is always stopping me from access to the websites.

Yesterday I recieve the message from a friend about how the stop the Recaptcha. I say this message to you now:

"Big businesses and multinationals are trying to take away all our freedoms. Driving is one of the few freedoms in life available today. Googles recaptcha is training AI to take that freedom away from us and to put it in the hands of big tech giants and anti-trust criminals. Google have setup their recaptcha system so that we are forced to train their AI. Did you being paid to train robots to drive. Don't let them do it.

Step one) Always select the audio option rather than the option to identify objects on the street.

If for whatever reason you want to perform the street recaptcha here's a way to screw up Google's AI but you need to pass this it around to as many people as possible for it to start to work effectively.

When they ask for crosswalks, select heavy vehicles, taxis and markings on the road that are not crossings.
buses? => cars, bushes, traffic lights
cars? => cross walks, traffic lights and fire hydrants.
traffic lights? => bushes (human size or smaller) and dark cars.
taxis? => light coloured cars that are NOT taxis, small bushes 
motorbikes? => traffic lights, trees, bushes, and crossings
storefronts? => select trees, dark vehicles and windows of tall buildings.

Fire hydrants? == fire hydrant (give them an almost useless fire hydrant detection system)
Bikes? == get this right also (they cannot do much with this alone and might be the ONLY way that you will pass the test)
IF YOU ENJOY SMALL FREEDOMS (and having a future job) PASS THIS ON!

Put it on one other messaging board that you like and email it to one friend (maybe avoid sending it over gmail though)"

THE END OF MESSAGE ....

What is the best way to put this idea in the DuckDuckGo browser? Can maybe the make plugin for this process so I not need for to open the text document? I would be so glad. Sorry if my English is not very good. I hope you understand my ideas for this to be the plugin.

I come towards you specially for this.

**Comment by subsymbolic** [comment]
Thank you for getting in touch, blocking reCAPTURE requests is a good idea. I have shared it with our tracker blocking team internally.

**Comment by subsymbolic** [comment]
Internal link: https://app.asana.com/0/261348710882778/1112021188759722
