### ISSUE TITLE
Feature request: delete tab by swipe

### ISSUE THREAD

**Issue by donfuxx** [duckduckgo/Android#510]
In the tab list screen it would be nice to be able to delete a tab by swiping it. Clicking the small x-icon to close a tab is quite inconvenient for users with fat-finger-syndrome.

**Comment by subsymbolic** [comment]
Thanks for requesting this. We now have this in PR in https://github.com/duckduckgo/Android/pull/540. It should be in test soon and then available to everyone in the coming weeks.
