### ISSUE TITLE
Add a login-password manager 

### ISSUE THREAD

**Issue by issueseverywhere** [duckduckgo/Android#512]
Hi!

A lot of websites need to sign up/sign in to be usable, is it possible to add a login/password manager in ddg privacy browser?

Thanks

**Comment by teemue** [comment]
I'd prefer better support for autofill when using external password manager such as KeePass; Currently DDG won't pass on the address of website, only com.duckduckgo.mobile.android and you have to pick the right entry manually.

**Comment by whichbuffer** [comment]
I think password managers are just a security holes but maybe it's possible to use with 2FA verification

**Comment by uraza** [comment]
I also feel that this should better be done by an external app, as suggested by @teemue .
The browser seems to support external password managers now: I am using LastPass and it can fill website passwords.

**Comment by cmonfortep** [comment]
Hi! We currently support password managers like LastPass.

I like the idea of having a DDG password manager but we don't have plans to do so yet. Closing this issue.

**Comment by RoestVrijStaal** [comment]
@cmonfortep That's ok, since building a secure and reliable password manager is not trivial. 

However, als @teemue pointed out with an example, the support of external password managers could be improved.
