### ISSUE TITLE
No option to put address bar on the bottom

### ISSUE THREAD

**Issue by rafnov** [duckduckgo/Android#5132]
### Describe the bug

Address bar on top

### How to Reproduce

Open the app and see address bar on top then search the proper option in settings - none found.

### Expected behavior

Toggle option to place address bar on the bottom

### Environment

```markdown
- DDG App Version: 5.215.0
- Device: Realme 7 pro
- OS: Android 12 stock
```

**Comment by marcosholgado** [comment]
We are actually releasing this very soon so I'm gonna close.

**Comment by rafnov** [comment]
![Screenshot_2024-10-13-13-24-08-97_cbf47468f7ecfbd8ebcc46bf9cc626da.jpg](https://github.com/user-attachments/assets/a635c8f0-d302-4693-8e9c-8aed900e121f)

Seems that I am already having this after install from Google store. Other source was outdated, had older version.
Thank you for your developement.

**Comment by marcosholgado** [comment]
We started rolling this out a few days ago. Great to hear it has reached you already. :)
