### ISSUE TITLE
Duck Player shows empty page instead of requested video content

### ISSUE THREAD

**Issue by Ricky-Tigg** [duckduckgo/Android#5148]
### Describe the bug

Hello. Duck Player that is provided via the Videos page is not operational; at `duck://player/_11-character string_`, an empty page is shown.

### How to Reproduce

1. In Videos page, select an video item for which an option for viewing a video with Duck Player is exhibited.
2. Click  _Turn on Duck Player_.
3. Observe the resulting behavior.

### Expected behavior

The resulting redirect to `duck://player/<11-character string>` not to show an empty page, but instead queried video content.

### Environment

```markdown
- DuckDuckGo version: 5.216.2
- Android version: 8.0.0
```

**Comment by CrisBarreiro** [comment]
Hi @Ricky-Tigg,
Thank you for reporting the issue. It looks like there's some issue on Android 8 preventing Duck Player from loading. We'll try to address it
