### ISSUE TITLE
[Bug] Censorship in Private Voice Search with asterisks

### ISSUE THREAD

**Issue by cevznriny** [duckduckgo/Android#5162]
### Describe the bug

With Private Voice Search enabled any rude words entered by voice will be censored with asterisks.
Is there a method to remove this censorship? 

Gboard and Google Voice Typing have options to "Block offensive words".

### How to Reproduce

Enable Settings\Accessibility\Private Voice Search.
Click the microphone in the search bar.
Say something rude.
The result will be censored eg: F*** Censorship

### Expected behavior

The result should say: Fuck Censorship

### Environment

```markdown
- DDG App Version: 5.216.2 (52162000)
- Device: Samsung S21+
- OS: Android 14
```

**Comment by joshliebe** [comment]
@cevznriny Thanks for the feedback! The speech recognizer masks offensive words by default, so I’ve forwarded this request to the product team for prioritization.
