### ISSUE TITLE
[Bug] Distorts URL

### ISSUE THREAD

**Issue by Noitarud** [duckduckgo/Android#5170]
### Describe the bug

This URL gets changed and host does not recognise it, 403 error
https://www.chipsourcetek.com/en/technology/1876.html

the URL works in monocles (Hmm - only if java is off)

### How to Reproduce

1. paste
2. enter

### Expected behavior

https://www.chipsourcetek.com/en/technology/1876.html
To continue to be shown in address bar when retrieving instead of
https://www.chipsourcetek.com/web/?ckurl=https%3A%2F%2Fwww.chipsourcetek.com%2Fen%2Ftechnology%2F1876.html

### Environment

```markdown
- DDG App Version: 216 (and as far back as 145)
- Device: lenovo
- OS: 10
```

**Comment by Noitarud** [comment]
Probably not your problem

**Comment by cmonfortep** [comment]
Thanks, that's correct, the same problem happens on any other mobile browser, so the issue is on the site itself.
