### ISSUE TITLE
Ineffective exit by clicking `Save and Exit`

### ISSUE THREAD

**Issue by Ricky-Tigg** [duckduckgo/Android#5185]
### Describe the bug

Hello. Ineffective exit by clicking _Save and Exit_.

### How to Reproduce

1. **Section path:** _Settings_ > _Private search_ > _More search settings_
2. Modify a setting; one is enough
3. Click _Save and exit_
4. Observe the resulting behaviour

### Expected behavior

**Effective** exit, once the configuration of the parameters has been saved.

### Environment

```markdown
- DuckDuckGo application version: 5.217.0
- OS: Android, version 8
```

**Comment by cmonfortep** [comment]
Thanks, we will forward the feedback to the team as that screen is shared with the search page.
