### ISSUE TITLE
"App tracking protection" view not respecting device "Auto-rotate screen" option

### ISSUE THREAD

**Issue by Ricky-Tigg** [duckduckgo/Android#5195]
### Describe the bug

Hello. _App tracking protection_ view is not respecting device _Auto-rotate screen_ option.

Relatively to screen auto-rotation; _How to Reproduce_ -steps,:
_2._ | effective; choice therefore respected.
_4._ | not effective; choice therefore not respected, **demonstrating** an issue.

### How to Reproduce

1. In Android _Settings_, enable the option corresponding to _Auto-rotate screen_.
2. Orient the device screen so that you are placed in its **length axis** to look at it; thus doing so, the resultant of the auto-rotation, when effective, makes the length of the text line displayed the **greatest**.
3. In this application, in the _Settings_ section, click _App tracking protection_.
4. Orient the device screen so that you are placed in its **width axis** to look at it; thus doing so, the resultant of the auto-rotation, when effective, makes the length of the text line displayed the **shortest**.

note: It goes without saying that steps _2._ and _4._ are to be considered as **choices**.

### Expected behavior

_App tracking protection_ view respecting device _Auto-rotate screen_ option

### Environment

```markdown
- DuckDuckGo application version: 5.217.0
- OS: Android, version 8
```

**Comment by cmonfortep** [comment]
Thanks for the report, this is a known issue and we are tracking it internally.
