### ISSUE TITLE
Add widget panel on our home screen not working on some devices

### ISSUE THREAD

**Issue by akshay-kapase** [duckduckgo/Android#528]
Hi, I'm trying to click on add widget. But, I don't see any widget in the homescreen.

App Version - 5.28.3 se (52803)
Device Model - Redmi 5A (Xiomi)
Android Version - 8.1.0
Steps to reproduce the bug - Click on Add Widget Button
Expected Behaviour - Show widget in home screen
Actual Behaviour - No Widget shown in home screen

**Comment by subsymbolic** [comment]
Thanks for sharing this @akshay-kapase. We check to see if widget pinning is supported with `AppWidgetManager.isRequestPinAppWidgetSupported` and have a fallback option if it is not. This seems to work on most devices.

I wonder if your device is responding to this incorrectly or if there is a bug in our logic? I have added the [help wanted](https://github.com/duckduckgo/Android/labels/help%20wanted) tag to open this task up to the community.

**Comment by subsymbolic** [comment]
Thanks for submitting this. We have investigated and found that a small number of devices have non-standard widget behavior. Unfortunately we don't see a way to fix this at this stage.

**Comment by akshay-kapase** [comment]
Thanks for taking your time to look into this issue
