### ISSUE TITLE
[Bug] App Tracking Protection - Phone Overheat/Battery Drain 

### ISSUE THREAD

**Issue by danbeav** [duckduckgo/Android#5298]
### Describe the bug

When using the App Tracking Protection, my Pixel 7 Pro will overheat and dramatically lose battery life compared to when the feature is turned off

### How to Reproduce

N/A

### Expected behavior

Look into the bug causing this

### Environment

```markdown
- DDG App Version: 5.219.0 (52190000)
- Device: Pixel 7 Pro
- OS: 15 (AP3A.241105.007)
```

**Comment by karlenDimla** [comment]
Hello! Thanks for filling the report. This is an issue that we are already actively monitoring internally and continuously trying to improve.
