### ISSUE TITLE
Original view state not returned while the 'App tracking protection' option is disabled

### ISSUE THREAD

**Issue by Ricky-Tigg** [duckduckgo/Android#5345]
### Describe the bug

Hello. From the **first** activation of the _App tracking protection_ option, and after having opted for its deactivation applying to all applications, DDG persists in displaying the announcement relating to this deactivation, shown here in this picture, even though when DDG was in its original state, no announcement relating to the _App tracking protection_ option was displayed.

![Screenshot_20241204-140432](https://github.com/user-attachments/assets/f60dc7af-8504-4f8b-9b54-66f8818e389b)

P.S.: For the time being, in order to return to the original state, there is no choice other than resetting DDG via Android's Settings.

### How to Reproduce

1. Enable the _App tracking protection_ option.
2. Disable the _App tracking protection_ option for all applications.
3. Quit DDG then relaunch it.
4. Observe the resulting behaviour.

### Expected behavior

Original view state returned

### Environment

```markdown
- DDG application v.: 5.229.0
- OS: Android, v. 8.0.0
```

**Comment by lmac012** [comment]
Hi @Ricky-Tigg! Thanks for reporting this and providing the steps to reproduce. Toggling App Tracking Protection doesn’t immediately clear its data in case you’re only disabling it temporarily, so this is working as intended. However, if you want the message to disappear, there’s no need to reset the entire app via Android’s Settings. Instead, go to App Settings -> App Tracking Protection and use the `Disable and Delete Data` option. The next time you launch the app, the message about the App Tracking feature will no longer appear.
