### ISSUE TITLE
Move address bar to bottom of screen

### ISSUE THREAD

**Issue by reno-a** [duckduckgo/Android#538]
The current smartphones are bigger and the URL bar is is not easy to access with one hand.
Maybe placing the address bar at the bottom of the screen would be a good solution?

**Comment by subsymbolic** [comment]
Thanks for sharing this! It's one of many options that our designers are considering for the search bar. I'll pass this on to them.

**Comment by Poopooracoocoo** [comment]
@subsymbolic How come this was closed? I'm sure y'all use an internal issue tracker but closing triaged issues just results in duplicates such as #661

**Comment by subsymbolic** [comment]
It's a big product change and not something we plan to do so I've closed it out. I really like the idea though and the product team is aware of it, maybe one day.

On the duplicate side of things - it happens. People should search open and closed issues before raising a new one but sometimes forget

**Comment by Poopooracoocoo** [comment]
@subsymbolic but by default open issues are searched. If an issue is closed, people will assume it was implemented, turned down or is a duplicate/spam.

**Comment by vollh4rD** [comment]
It has been 3 years since the initial request for a bottom search bar. Would be great if we got one :D

**Comment by Bourjois** [comment]
> It has been 3 years since the initial request for a bottom search bar. Would be great if we got one :D

Now approaching 4 years. I started using the DDG browser yesterday and I'm already about to ditch it, due to the address bar placement. It's a very shortsighted omission by the DDG team; accessibility should be a priority.

**Comment by zekasolest** [comment]
It’s weird because this feature in DDG on iOS is enabled..

**Comment by tanato-cit** [comment]
The lack of a ability to set the search bar to the bottom is to me the only thing that currently prevents DDG to become my default browser on Android.

Sad to see that this is not even being in the roadmap.
