### ISSUE TITLE
Play Store Description: link to this project is broken (5.30.0)

### ISSUE THREAD

**Issue by GeoffMaciolek** [duckduckgo/Android#547]
## Description
This is an easy one! In the Google Play store, at the end of the description for this app, the text reads 
> This app is open source at https://github.com/duckduckgo/Android.

The link is including the period at the end of that sentence - it should be removed. (I suspect the hyperlink is generated automatically, so there should either be a space before the period, or it should just be taken out entirely).

## Expected Behavior
Link in Google Play Store brings you to The duckduckgo/Android project

## Actual Behavior
Link in Google Play Store brings you to a 404 page, due to a trailing period in the URL.

**Comment by GeoffMaciolek** [comment]
After a quick search, I don't think the Google Play Store dsscription exists as part of this repository, unlike the changelog etc. This will need to be changed via the Google developer / play store web interface. I think that's accessible here: https://play.google.com/apps/publish/

See: https://stackoverflow.com/questions/26436865/app-description-update-on-play-store

**Comment by CDRussell** [comment]
Good spot! Fixed it now; Google Play should show the change within the next few hours.

Thank you!
