### ISSUE TITLE
Feature request - Manage bookmarks

### ISSUE THREAD

**Issue by t-arn** [duckduckgo/Android#557]
Please add the possibility to sort (manual / automatic) the bookmarks and to organize them in groups or categories. A search within the bookmarks would also be handy.

**Comment by Poopooracoocoo** [comment]
Add importing and exporting to the list too! Oh and being able to tap and hold on a bookmark search result and view it in its folder (it would scroll down to where the bookmark is to show context).

I don't really know much about DDG Browser yet. It seems that it doesn't use Chromium's UI?

**Comment by cmonfortep** [comment]
We have done an exploration for introducing Bookmark folders (internal task: https://app.asana.com/0/72649045549333/1199721190800677/f). It will be soon implemented in iOS and Android will follow too. 

Search was implemented some time ago by an external contribution.

Closing this issue. Thanks.

**Comment by p91dc40cal** [comment]
Hello @cmonfortep Feature request - Manage Bookmarks was closed after it had been merged with create folders in Bookmarks.  I know Create Folders was done and is now possible.  But as far as I can tell we can not rearrange our bookmarks.  I would like to be able to control what order the bookmarks are in.  Thanks.
