### ISSUE TITLE
application in the GP, the link is incorrect

### ISSUE THREAD

**Issue by torerobo** [duckduckgo/Android#562]
In the description of the DDG application in the GP, the link is incorrect:
https://github.com/duckduckgo/android

True link:
https://github.com/duckduckgo/Android

GP:
https://play.google.com/store/apps/details?id=com.duckduckgo.mobile.android

**Comment by pwittchen** [comment]
I see link with uppercase "A" in the GP. Moreover, both links redirects to the correct repo anyway.

**Comment by torerobo** [comment]
Location RU GP
screen
![IMG_20190819_173433_378](https://user-images.githubusercontent.com/35532898/63274144-f529e000-c2a7-11e9-9d25-9bbb584a6dc3.jpg)

link open
![IMG_20190819_173436_774](https://user-images.githubusercontent.com/35532898/63274172-01ae3880-c2a8-11e9-9451-c56e9332e67c.jpg)

**Comment by pwittchen** [comment]
It looks like an issue with the dot in the end of url - not the address
itself.

--
Piotr Wittchen,
http://wittchen.io

pon., 19 sie 2019, 16:38 użytkownik torerobo <notifications@github.com>
napisał:

**Comment by torerobo** [comment]
Yes, that's right, the dot is substituted and does not open (I didn’t notice it, so others may not notice it).

**Comment by subsymbolic** [comment]
Thanks for reporting this, I have updated the link to remove the full-stop so it should work now. Let us know if you continue to see the issue.
