### ISSUE TITLE
Internationalized domain name

### ISSUE THREAD

**Issue by rafaelmr2** [duckduckgo/Android#569]
DDG does not convert characters properly Internationalized domain name (IDN) in URL bar.

![photo_2019-08-22_11-51-46](https://user-images.githubusercontent.com/4471805/63524967-436ef700-c4d3-11e9-80e3-97424d765c39.jpg)

**Comment by subsymbolic** [comment]
Thanks for submitting this @rafaelmr2. Unfortunately as these URLs can be used in phishing attacks, we display them in punycode for security reasons. Most other browsers do the same. I hope we find a way to overcome this one day.
