### ISSUE TITLE
Popup for saving files

### ISSUE THREAD

**Issue by FlorianSb** [duckduckgo/Android#581]
I think a useful extension for the browser would be to ask if you want to save a file. How Firefox does it

![Screenshot_20190830-000523_Firefox_Klar](https://user-images.githubusercontent.com/54689374/63979742-e4544800-cab9-11e9-8565-1c26243d5f29.png)

**Comment by subsymbolic** [comment]
Closing as this is a duplicate of https://github.com/duckduckgo/Android/issues/400. Thanks for submitting it though, it's a good suggestion.
