### ISSUE TITLE
Close tabs when pressing the back button and there is no history left

### ISSUE THREAD

**Issue by malnvenshorn** [duckduckgo/Android#588]
I'd like that tabs are closed when pressing the back button and there is no history left for this tab. After that the browser could jump to the previous used tab.

**Comment by subsymbolic** [comment]
Thanks for posting this @malnvenshorn, this could work well if pressing back on a tab that was opened from another tab, however might break expectations if it jumps to an unrelated tab. We'll explore and consider it internally. Thanks again for sharing.
