### ISSUE TITLE
User is able to submit blank text in positive feedback

### ISSUE THREAD

**Issue by nikit19** [duckduckgo/Android#591]
User is able to submit blank text in positive feedback. In my opinion this shouldn't be blank because this could be done by mistake.
I understand in case of negative feedback it makes sense to leave it optional as some kind of feedback has already been shared by selecting the options before but in case of positive feedback nothing is conveyed.

Please let me know if it is a valid issue, I would love to work on it. Thanks!

**Comment by subsymbolic** [comment]
@nikit19, we are interested in positive feedback numbers, even when the comment box is left blank, so don't plan to change this.
