### ISSUE TITLE
Download via php script does not work

### ISSUE THREAD

**Issue by KaiRoesner** [duckduckgo/Android#599]
- App version: 5.34.0.mx (53400)
- Device model: Motorola Moto G6
- Android version: 9 (PPSS29.55-37-4-3)
- Steps to reproduce the bug
Go to
https://spo.handball4all.de/Spielbetrieb/index.php?orgGrpID=35&score=47146
In the top table on this page under the column heading "Bem." tap the "PI" link.
- Expected behavior
A pdf file should be downloaded and displayed in Acrobat Reader.
- Actual behavior
The php download script is downloaded but not executed. Using other browsers (I've tried Firefox and Chrome) everything works as expected.

**Comment by 1007tejas** [comment]
Having a similar issue downloading a file, *.vcf, with content-type "text/vcard". The mime type, magic number, is correctly set on the server. Using the Android Files utility shows that the  file type of the downloaded file is described as a html document. In android Contacts/settings/import selecting .vcf masks the file and it is not considered a valid text/vcard. The server is debian9 and it sets the mime content to text/vcard not text/x-vcard. Android duckduckgo is not handling the mime type correctly.

Thanks for your help

**Comment by KaiRoesner** [comment]
My issue appears to have been fixed - can't reproduce.
