### ISSUE TITLE
Feedback text boxes have unreadable text labels

### ISSUE THREAD

**Issue by subsymbolic** [duckduckgo/Android#605]
**Issue:** Text field labels on Feedback screens are unreadable when activated

**Steps to reproduce:**

1. Open the app, tap on the overflow menu and select **Settings**
1. Select **Leave Feedback**
1. Tap the smile button
1. Note the text field looks readable
1. Tap inside the text field and the label will move to the top
*Expected behavior:* Text label should be the same cornflower blue color as active text box
*Actual behavior:* Text label color changes to dark and contrast is low making it unreadable

**Goal:**
- Fix *all* the text fields in the feedback screen
- Test against both light and dark themes (toggle for this is available from app **Settings**)

<img width="487" alt="inactivate_fine" src="https://user-images.githubusercontent.com/1652407/66568639-c6bad980-eb61-11e9-822b-28d6e3eeb888.png">
<img width="487" alt="active_unreadable" src="https://user-images.githubusercontent.com/1652407/66568641-c6bad980-eb61-11e9-8384-59256fbac6a4.png">

**Comment by AriqAhmad** [comment]
Hi,
I was able to reproduce this. I'm trying to clone the repo and see if I can find a fix for it. If it does then I'll do a pull request.

**Comment by subsymbolic** [comment]
The PR fixing this has now been merged, ready for the next release. Thanks for the contribution @JeffAment.
