### ISSUE TITLE
Search queries of the form `.*:.*` results in bad response

### ISSUE THREAD

**Issue by denizevrenci** [duckduckgo/Android#618]
For example, the query "std::string" gets interpreted as a link and returns the response "Unable to open this type of link".

Possibly related to https://github.com/duckduckgo/Android/issues/347.

**Comment by cmonfortep** [comment]
Hello @denizevrenci, thanks for taking the time to submit this feature request.

After internal discussion with the team, we've agreed that there's no plan in the foreseeable future to support this request. Should this change in the future, we'll update this conversation appropriately.
