### ISSUE TITLE
Fingerprint when leave the app

### ISSUE THREAD

**Issue by FlorianSb** [duckduckgo/Android#626]
What do you think of a function that allows you to spear the app with a fingerprint after leaving it?

**Comment by subsymbolic** [comment]
@FlorianSb are you communicating a vulnerability or suggesting a new functionality? If the former please submit it via https://hackerone.com/duckduckgo so we can fix it. If the latter, we put privacy first so wouldn't consider fingerprinting.

**Comment by cd1063** [comment]
I do not understand what I need to do more.  My 2 phones a two laptop's are down and to top it off I received 413 emails in the last 3 4 hours asking me and suggesting to me what to do about the situation.  I just a new learner that was eager to get involved then all this.  It was not my fault someone back doored the duckduckgo.  EXTention in Firefox and took all my CV information and screwed up all settings and all site setting and cookies are gone.
I could use help not getting on me.
Thanks Tim

Tim S
________________________________
