### ISSUE TITLE
Inquiry and Feature Request

### ISSUE THREAD

**Issue by Laicure** [duckduckgo/Android#636]
Version: 5.36.3

Why run at start-up permission?
I don't like apps doing that.
May you please explain why?

Also, I am using a custom DDG url bookmark settings (you know, for theming and ddg settings).
Will users have the option to customize the default search duckduckgo engine by using the said url thing above?

**Comment by CDRussell** [comment]
We need to periodically download data in order to keep users safe. This data includes updates to tracker lists and https upgrades.

In order to ensure that our download jobs continue to happen even after the user restarts their device, we need to include this permission. 
Without this permission, our scheduled job to update the lists would stop after the device was powered off.

More info:
https://developer.android.com/reference/android/app/job/JobInfo.Builder.html?#setPersisted%28boolean%29

**Comment by CDRussell** [comment]
As for the other part of your question, I'm not sure what you mean. Can you elaborate? Thanks

**Comment by JeffAment** [comment]
@Laicure If you are referring to the bookmarklets for DDG with the URL params, this was patched by PR #633 and is available in the latest release, so you should not need to use the custom bookmarklet any longer as the cookies with the settings are now persistent.

**Comment by Laicure** [comment]
@CDRussell and @JeffAment, thanks for the clarifications!

> As for the other part of your question, I'm not sure what you mean. Can you elaborate? Thanks
Oh sorry, it was the ddg bookmarklets (I forgot the term).

> @Laicure If you are referring to the bookmarklets for DDG with the URL params, this was patched by PR #633 and is available in the latest release, so you should not need to use the custom bookmarklet any longer as the cookies with the settings are now persistent.
I think, on my end, that would suffice without a specific setting. As long as it is persistent, I'm good.
Thanks for linking the reference.

Issue cleared ;)

**Comment by Poopooracoocoo** [comment]
> We need to periodically download data in order to keep users safe. This data includes updates to tracker lists and https upgrades.
> 
> In order to ensure that our download jobs continue to happen even after the user restarts their device, we need to include this permission.
> Without this permission, our scheduled job to update the lists would stop after the device was powered off.
> 
> More info:
> https://developer.android.com/reference/android/app/job/JobInfo.Builder.html?#setPersisted%28boolean%29

@CDRussell 
You guys should include this in the readme or description! You should also include a link to the [Play Store](https://play.google.com/store/apps/details?id=com.duckduckgo.mobile.android) and [F-Droid](https://f-droid.org/en/packages/com.duckduckgo.mobile.android/) listings! :)
