### ISSUE TITLE
Search engine 

### ISSUE THREAD

**Issue by lemanno** [duckduckgo/Android#641]
How can I change the search engine?

**Comment by shahsurajk** [comment]
Duckduckgo is a search engine, having to change the search engine would probably make this just a privacy centric browser, for which there are already existing solutions like [Firefox focus](https://github.com/mozilla-mobile/focus-android) and [Firefox fenix](https://github.com/mozilla-mobile/fenix). 

The whole idea of this app is to use duckduckgo as the default search engine, with it's privacy essentials.

**Comment by subsymbolic** [comment]
@lemanno thanks for posting. Search selection isn't a feature that we currently plan to support, we want to provide full privacy protection for users.

**Comment by lippfi** [comment]
@lemanno I've just created a fork of DuckDuckGo that allows to change the default search engine. Feel free to check it out or add your preferred search engine via a PR - https://github.com/lippfi/SearxDuckGo
