### ISSUE TITLE
Feature request: Do not track

### ISSUE THREAD

**Issue by sinus-x** [duckduckgo/Android#648]
Would it be possible to add "Do not track" option to the settings? It's the single feature I'm missing in comparison with Firefox Focus.
Thanks a lot, for both the app and the project in general

**Comment by Poopooracoocoo** [comment]
DNT is itself a fingerprinting issue but choices and defaults are what is important.

**Comment by sinus-x** [comment]
Well, yes. The W3C discontinued the project calling it "a failed experiment" a year ago, as I just found out.

There isn't much data on support, however, Google isn't using it and Safari dropped the support completly. Maybe there really is no reason for adding it, if it is ignored as a privacy and used as a tracking feature.

**Comment by Ryan451** [comment]
@sinus-x DuckDuckGo Privacy Browser uses "Global Privacy Control" (GPC) instead of "Do Not Track" (DNT)

https://spreadprivacy.com/announcing-global-privacy-control/

**Comment by Ryan451** [comment]
@sinus-x DDG Privacy Browser uses "Global Privacy Control" (GPC) instead of "Do Not Track" (DNT)
https://spreadprivacy.com/announcing-global-privacy-control/

**Comment by cmonfortep** [comment]
Our browser supports GPC as commented above (enabled by default in settings). We don't have plans to introduce DNT support. Thanks.
