### ISSUE TITLE
Dark mode improvements

### ISSUE THREAD

**Issue by francescosoave** [duckduckgo/Android#660]
Hello,
There are a couple things that bug me about the app dark theme:

- The menu (dropdown) is still white (shouldn't it be dark too?)
- The search results page is not in dark mode (and I wish it was)

Please see screenshot attached.
![Screenshot_20191226-140122](https://user-images.githubusercontent.com/26126452/71480160-18d1d980-27f8-11ea-8098-d0d8e7309c3b.jpg)
![Screenshot_20191226-140130](https://user-images.githubusercontent.com/26126452/71480169-25eec880-27f8-11ea-83c4-eaca2b6cff5f.jpg)

**Comment by Poopooracoocoo** [comment]
*cough* prefers-color-scheme *cough*

**Comment by dar5hak** [comment]
In addition to this, when a new page is loading, the blank page that shows up until the target is loaded, is also white. This sudden flash of white blinds me at night time.

**Comment by 8of** [comment]
Found several other menus / pickers where black theme isn't applied.

- Settings -> Privacy -> Automatically clear
- Tabs screen -> three dots button
- Tabs screen -> Clear data (fire icon) button

Screenshots below:

![Screenshot_20200802-124325](https://user-images.githubusercontent.com/6408861/89120347-47b2db00-d4be-11ea-9c3f-88e239c00c96.png)

![Screenshot_20200802-124745](https://user-images.githubusercontent.com/6408861/89120423-e50e0f00-d4be-11ea-802c-e0bdd58e3888.png)

![Screenshot_20200802-124751](https://user-images.githubusercontent.com/6408861/89120426-eb9c8680-d4be-11ea-9f6a-63aca1868d41.png)

**Comment by Cyberdroid1** [comment]
I really want this issue to be sorted. Especially the white page blink when loading some website for first time after opening app.
