### ISSUE TITLE
Ad blocking settings like Bromite

### ISSUE THREAD

**Issue by Poopooracoocoo** [duckduckgo/Android#681]
To clarify, I'm referring to being able to set an adblock filter. Bromite has its own and Chrome has its own. DuckDuckGo Browser does need one by default but the ability to would be awesome.

**Comment by Poopooracoocoo** [comment]
Don't mind my stupid mistake.

**Comment by cmonfortep** [comment]
Thanks for the feedback. There are a few related issues to this topic:
https://github.com/duckduckgo/Android/issues/306
https://github.com/duckduckgo/Android/issues/482

Yet, this isn't something we are currently planning. Closing this issue.
