### ISSUE TITLE
Make "Add bookmark" an icon left of refresh in menu

### ISSUE THREAD

**Issue by Poopooracoocoo** [duckduckgo/Android#684]
![Screenshot_1581139339](https://user-images.githubusercontent.com/51363864/74079711-364cc100-4a8f-11ea-81c5-a58e7c2b84b3.png)

**Comment by cmonfortep** [comment]
Thanks for the feedback, I will share it with the product team. It could be helpful to replace the option for an icon and reduce the list of options we offer inside the overflow menu. Thanks

**Comment by cmonfortep** [comment]
https://app.asana.com/0/0/1181157652739449/f

**Comment by cmonfortep** [comment]
👋  Good news also here. We have a project to revamp our menu and settings. Many things will be changed there as currently, it's a bit overloaded. It's currently in progress for iOS and we will follow on Android soon.

Closing this one. Soon we will be moving pending feature requests as discussions, but it's already tracked and scoped internally, so no need to migrate it. Thanks.
