### ISSUE TITLE
Show information about connection when a user has tapped on "Encrypted Connection" in Privacy Dashboard

### ISSUE THREAD

**Issue by Poopooracoocoo** [duckduckgo/Android#685]
Stuff like what TLS version and certs. You get the gist.

**Comment by cmonfortep** [comment]
Thanks for sharing, I may revisit our privacy dashboard UI and we will share this feedback with our product team.

**Comment by oldphones68** [comment]
I also think, this would be a great enhancement.
Hope it will be added soon and get a triage.
