### ISSUE TITLE
Pressing back after dismissing keyboard in find in page should close find on page toolbar

### ISSUE THREAD

**Issue by Poopooracoocoo** [duckduckgo/Android#686]
I think some users will be surprised to see that it just navigates back in the tab and doesn't close the find in page toolbar

**Comment by AndrewR8** [comment]
I would like to work on this issue.

**Comment by cmonfortep** [comment]
@AndrewR8 👍 thanks!

**Comment by AndrewR8** [comment]
Looks like this issue has already been fixed.

**Comment by Poopooracoocoo** [comment]
thanks andrew. imma close this.
