### ISSUE TITLE
Missing typing indicator in feedback form input fields

### ISSUE THREAD

**Issue by Poopooracoocoo** [duckduckgo/Android#687]

**Comment by cmonfortep** [comment]
Thanks, def we should fix this. 

This is the layout used in the feedback screen: `content_feedback_open_ended_feedback.xml`

**Comment by donfuxx** [comment]
Hi @cmonfortep 

I have fixed this here with this one-liner: https://github.com/duckduckgo/Android/pull/872

cheers,
