### ISSUE TITLE
Make scrollbar in webpages less prominent

### ISSUE THREAD

**Issue by Poopooracoocoo** [duckduckgo/Android#688]
![Screenshot_1581139447](https://user-images.githubusercontent.com/51363864/74079736-7d3ab680-4a8f-11ea-8b4b-7da118a6250b.png)
I have the light theme on and am on a white page. The scrollbar appears on a black line. This is probably for contrast. I'm not sure what Chrome does but I never notice it and can see it when I actively want to. The black line obscures the page.

**Comment by Manavpreeet** [comment]
I would like to work on it, is it available ?

**Comment by Poopooracoocoo** [comment]
@Manavpreeet thanks!

**Comment by Manavpreeet** [comment]
There is error in BrowserTabFragment.kt at (532, 17)

**Comment by Cyberdroid1** [comment]
Any updates to this?

**Comment by MohitMandalia** [comment]
HI @cmonfortep ,

I would like to work on this, is it available?

Please let me know.

**Comment by cmonfortep** [comment]
Closing as we don't have any plans to update that component.
