### ISSUE TITLE
Option to disable searching bookmarks in address bar

### ISSUE THREAD

**Issue by Poopooracoocoo** [duckduckgo/Android#692]
Some people may only want bookmarks to show in the bookmarks page and nowhere else.

**Comment by cmonfortep** [comment]
Thanks for letting us know about this feature request.

Bookmark section is something we will improve/change in a future project. I will keep this as feedback to be shared with our product/design team once we start working on that section. In any case, this should be approved by them and be aligned with our product direction.

**Comment by subsymbolic** [comment]
We A/B tested this a few months ago with an option in settings however it unfortunately received very little engagement suggesting that this isn't a feature users generally want. We removed it and don't currently have plans to add it again.

**Comment by Poopooracoocoo** [comment]
@subsymbolic I imagine that once/if it's possible to bookmark all open tabs, this feature would get a lot more use.

**Comment by oldphones68** [comment]
@cmonfortep & @subsymbolic 
Can there be an option to _separate_ the address suggestion from **bookmarked** and **non bookmarked** sites?

So, users can separately switch on/off each options...
