### ISSUE TITLE
Should not be able to show or hide toolbar when typing in a website (when keyboard is open)

### ISSUE THREAD

**Issue by Poopooracoocoo** [duckduckgo/Android#693]
It's pretty annoying.

I have no idea how Chrome for Android works with a keyboard and mouse but it is also worth thinking about those too.

**Comment by tvalle** [comment]
Can I work on this one?

**Comment by AndrewR8** [comment]
It seems that this issue needs to be fixed first #755

**Comment by Cyberdroid1** [comment]
Well, since #755 has been fixed, would it be fixed now?

**Comment by cmonfortep** [comment]
@Poopooracoocoo I think I understand what you mean hear, but just to be sure, could you post a gif or a video as sample? Also it would be nice to understand why it's annoying for you that behavior. Thanks.

**Comment by Poopooracoocoo** [comment]
@cmonfortep Jesus, it's been a year and a half. I haven't used DDG Browser since then. 

It's worth just looking at Chrome's behaviour. Same applies for the other issues I created here.

**Comment by cmonfortep** [comment]
It's ok, and sorry for the late response, just wanted to understand if there was something else I was missing.

We haven't received any further feedback related to the issue (neither from users using our embedded feedback option in settings). Closing this as there's no plan in the foreseeable future to support this request.

**Comment by Poopooracoocoo** [comment]
ok but know that most users are just going to stop using the browser altogether and won't be bothered submitting feedback.
