### ISSUE TITLE
Make the navigation bar light grey in light mode

### ISSUE THREAD

**Issue by Poopooracoocoo** [duckduckgo/Android#695]
This would also look a lot nicer with the Android 10 gestures

**Comment by cmonfortep** [comment]
@Poopooracoocoo it would be really helpful for us if you could include any screenshots (of the part we are talking about) to understand better your proposal. That component usually changes between different devices/brands and it would really nice to have a visual example of your scenario. Thanks!

**Comment by Poopooracoocoo** [comment]
@cmonfortep I'm talking about the Android system navigation bar at the bottom of the screen. 

In apps like Settings, the navigation bar is translucent (I think they call it a scrim?) and in some fully transparent. I've heard some stuff about window insets and how you can make the navigation bar fully transparent (which looks great with apps that have bottom navigation). 

In DDG Browser, the navigation bar is black in light and dark mode.

**Comment by malmstein** [comment]
@Poopooracoocoo thanks for raising this! It's now fixed and will be out in the next release :shipit:
