### ISSUE TITLE
Too much interaction to go back to previous tab

### ISSUE THREAD

**Issue by damluk** [duckduckgo/Android#696]
If I am not mistaken, with the last update the app started to honor `target=_blank`. At least it opens links in new tabs without being explicitly told so. This is not bad per se, but now the browser seems to need too much interaction to go back to the site that provided the link. The back button goes back to blank when pressed once, and closes the app when pressed twice. One has to explicitly select the previous tab via tab management.

This is Android 9 / OxygenOS 9.0.10

**Comment by subsymbolic** [comment]
Great feedback @damluk, thanks for sharing, I'll look into this.

**Comment by damluk** [comment]
I realized today that the issue has been fixed, thanks!
