### ISSUE TITLE
Feature request:background video playback

### ISSUE THREAD

**Issue by gothmog123** [duckduckgo/Android#712]
Thanks

**Comment by cmonfortep** [comment]
Thanks for submitting this. It would be nice if you could elaborate a bit more on your feature request.

**Comment by gothmog123** [comment]
Sure, thanks, so in most android browsers if you are playing a video and switch to another app the video playback stops. But in Brave for instance you can continue listening to the video if you switch to another app or another tab in the browser.

**Comment by cmonfortep** [comment]
Sorry for the delay here. I was taking a look again at this feature request. 

We rely on the WebView component, and when we change to another tab o switch to another app, WebView gets paused or killed and we can't reproduce any audio.

However, `Brave` is reproducing sound via a background service, also you need to enable that feature (disabled by default) in their settings.

I haven't explored how they are doing that, I guess using youtube api(?)...I'm a bit surprised they can offer that feature. Youtube asks you to pay a subscription if you want the same 😅...

If anyone can bring more info here, feel free to share it.
