### ISSUE TITLE
[FR] allow sharing all open tabs

### ISSUE THREAD

**Issue by fazlerabbi37** [duckduckgo/Android#728]
It would be great to have an option to share all open tabs just like the close all tabs option. User may need to save all tab before hitting clear all tab and data and enabling share all tab would allow the user to either copy it in clipboard or save it in a note taking app. 

A heartfelt thank you for all that you’ve done.

**Comment by cmonfortep** [comment]
As you already saw (you commented about that in https://github.com/duckduckgo/Android/issues/729), we have a related feature logged in our internal backlog that will make possible to store all open tabs as bookmarks https://github.com/duckduckgo/Android/issues/467

In any case, thanks for the feedback, this gives us visibility of what users are missing in our browser.

**Comment by cmonfortep** [comment]
Closing this task in favor of https://github.com/duckduckgo/Android/issues/467 and https://github.com/duckduckgo/Android/issues/209

**Comment by owlicious** [comment]
So no traction on #467? 209 is great, it's phase 1 to make #467 a workable solution for a lot of people, most likely, but #467 or #728 are pretty essential features for a mobile browser. The processing power & screen real estate just isn't there to efficiently manage bookmarks any other way. If you do a ton of reading or research on your phone, you really need some way to quickly refer to the titles of pages, to catalog in folders (i.e. by exporting to manage the tabs/bookmarks on desktop) & bulk delete accordingly. Trying to click through hundreds of open tabs on a tiny phone screen one by one just to see what each one is (the title either doesn't show or fit on the thumbnail, the thumbnail doesn't load before clicking into the site) is not viable.
