### ISSUE TITLE
Allow selecting bookmarks to perform bulk operations

### ISSUE THREAD

**Issue by fazlerabbi37** [duckduckgo/Android#729]
Going through the issues I saw two requests related to bookmark, import/export(#209) and sort (#557). Also, a request for storing all open tab in bookmarks (#467) which seems may get implemented soon. Allowing the user to select bookmarks would enable user to do the existing tasks like delete and coming tasks like export/import in bulk which is always helpful. 

Thanks again for this awesome open source tool!

**Comment by juniorjainsahab** [comment]
@cmonfortep and @subsymbolic are the import/export feature in bookmarks is completed? if not, I would like to work on it.

**Comment by cmonfortep** [comment]
Hi @juniorjainsahab. We don't have green light for that feature yet, and pretty sure, once it's ready to be implemented, it will be done internally as it will involve design and product work. Thanks for offering your help here.

**Comment by cmonfortep** [comment]
Hello there. We have been received similar feedback to improve our bookmark management from users (using our embedded feedback form within the app + the feedback received here). We have a project to improve bookmarks management, not sure if that will include bulk operations. We will revisit all the collected feedback at that point.

Everyone can continue sending feedback using the feedback option inside settings (from our browser) or just using the web form. We process that feedback internally every day and scope projects when we see enough activity.

Closing this issue as it's already tracked internally. Thanks.

Check "share feedback" guidelines here (https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#share-feedback).
