### ISSUE TITLE
duckduckgo hackerone ip logging and xss

### ISSUE THREAD

**Issue by epicodertime** [duckduckgo/Android#743]
![duckduckgo xss](https://user-images.githubusercontent.com/41688975/76707187-8d176d00-66c3-11ea-929f-712742737cb4.jpg)
![xssip logging](https://user-images.githubusercontent.com/41688975/76707188-8e489a00-66c3-11ea-9e3f-b5e01d54da51.jpeg)
![Inkedintresting_LI](https://user-images.githubusercontent.com/41688975/76707189-8ee13080-66c3-11ea-9469-8d01cbcdfe03.jpg)
hi, duckduckgo staff I reported a vulnerability related to duckduckgo.com/iur/ where I found a vulnebrilty that I was able to execute XSS on the server without a user noticing which I was able to log the IP address of a user remotely and one of them you fixed that nice but you should look at the report and reward me because you fixed it and also xss executing in the server you might want to look into it as a HackerOne staff member is trying to contact duckduckgo. my case number is #791366

**Comment by epicodertime** [comment]
if you need additional information please ask

**Comment by epicodertime** [comment]
It also disappointing that duckDuckgo is not abiding by its time to triage time  Time to first response (from report submission) - 2 business days
Time to triage (from first response) - 2 business days
It's been 20 days

**Comment by epicodertime** [comment]
And if needed I will help duckduckgo create a patch and help protect users

**Comment by cmonfortep** [comment]
Hello @epicodertime, thanks for taking the time to submit this issue on HackerOne and also here. According to our [Contribution guideduilines](https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#report-an-issue) security issues should be posted directly through https://hackerone.com/duckduckgo.

As far as I see, this doesn't seem related to our Android App, so just to avoid duplicated info, and following our guidelines, I will close this issue. I hope that's ok with you.

I would suggest you continue the conversation in HackerOne. If there has been any delay from our side, I apologize, but please ping the team again with a new comment. Thanks.

**Comment by epicodertime** [comment]
Hi @cmonfortep I wanted to comment this because hackerone staff is ignoring me and I wanted to get the attention of the DuckDuckGo security team and sorry for putting this on github I just wanted to protect DuckDuckGo users I know it’s off topic but I believe in putting users first as there any way you can talk to DuckDuckGo staff to review my case and I will close this issue

**Comment by cmonfortep** [comment]
No problem. Thanks for your comprehension. I will try to ping the team internally 👍
