### ISSUE TITLE
Android App Can't Handle Intent Format URIs

### ISSUE THREAD

**Issue by zsweigart** [duckduckgo/Android#744]
- App version -> 5.46.0
- Device model - > Pixel 3a
- Android version -> Android 10
- Steps to reproduce the bug ->

1. Create an app that has a package of com.example.app and an intent filter for test://redirect
2. Create a webpage that fires an intent format intent https://developer.chrome.com/multidevice/android/intents  
intent://redirect/#Intent;scheme=test;package=com.example.app;end"
3. open the webpage

- Expected behavior -> The app should open
- Actual behavior -> Toast shown "Unable to open this type of link"

**Comment by AndrewR8** [comment]
It looks like this issue is no longer relevant.

- webpage that contains intent format URL which  should redirect to Twitter app
https://output.jsbin.com/rupaxu/latest

If there is Twitter app on the device the app opens, otherwise  toast shown "Unable to open this type of link" .

**Comment by zsweigart** [comment]
This actually still seems to be an issue.  Our flow is now
1. Go from sample app to hosted webpage
1. Web page has a button to fire the intent to return to the sample application

We see see this dialog:

<img width="370" alt="Screen Shot 2020-09-30 at 10 57 14 AM" src="https://user-images.githubusercontent.com/1391816/94709822-bc15c900-030b-11eb-9182-4a53ef7dfe4c.png">

But then when we click continue it seems to open a new instance of the corresponding activity but within the Duck Duck Go process.  I'm not sure how that's possible but we end up seeing the old activity (status bar changes color) inside Duck Duck Go and we can kill the other activity.

**Comment by cmonfortep** [comment]
@zsweigart sorry for the late response, I'm currently reviewing old issues and I'm trying to understand this one.

In your last comment, what do you mean by "Go from sample app to hosted webpage"? I guess by "sample app" you are referring to "an app that has a package of com.example.app and an intent filter for test://redirect", but I don't understand how to "go" from sample to hosted webpage.

Could you provide us that sample apk or a github link so we can checkout the code and use the same scenario as you are testing. Thanks.

**Comment by cmonfortep** [comment]
Closing this issue as it has been inactive. Feel free to reopen it once we can get more insights to proper investigate the issue. Thanks.
