### ISSUE TITLE
Downloading a file link with target=_blank opens a new blank tab

### ISSUE THREAD

**Issue by cmonfortep** [duckduckgo/Android#753]
**Background**
PR https://github.com/duckduckgo/Android/pull/666/ added support for handling target=_blank links, which allows for a link to be opened in a separate tab.

Some of these links can be files that the user wants to download. Downloading any of these files results in the app opening a new blank tab.

**Steps to reproduce**
Navigate to http://www.granditaliaperth.co.uk/menus.html and click on the download link for the menu.

The download will start and a new blank tab will be opened.

**Objective**
Ensure that this action does not open a new blank tab.

**Comment by rajkumaar23** [comment]
I would like to work on this issue.
