### ISSUE TITLE
Navigation buttons hidden on some devices

### ISSUE THREAD

**Issue by cmonfortep** [duckduckgo/Android#754]
**Background**
After clicking on fire button, a bottom dialog appears to request user confirmation to clear all tabs and data.

**To reproduce:**
- Install app
- Go to settings and switch to light theme (if you're not already on it)
- Go to the browser and press the fire button

Seen on:
Pixel 3 XL device, API 29
Pixel XL emulator, API 29

**Actual behavior:** Fire dialog appears and however system buttons disappear. See following screenshot:
<img src="https://user-images.githubusercontent.com/4747865/77910946-4b282280-7290-11ea-983a-620e5367e0cd.png" width="360px"/>

**Expected behavior:** Fire dialog appears and system buttons are visible. Example, see how in the following screenshot navigation buttons are visible:
<img src="https://user-images.githubusercontent.com/4747865/77911140-9b06e980-7290-11ea-9d77-9365a391d461.png" width="360px"/>

**Comment by sm600gg** [comment]
Halo me!!!!!

**Comment by cmonfortep** [comment]
Fix has been merged. Thanks to everyone involved here.
