### ISSUE TITLE
Address bar loses focus when scrolling web page.

### ISSUE THREAD

**Issue by AndrewR8** [duckduckgo/Android#755]
**Steps to reproduce**:

1) Open any web page.
1) Click on address bar.
2) Start scrolling web page.

**Expected result**:
I'm not sure.
It seems to me one of the following should happen:
1) Address bar loses focus and the keyboard disappears.
2) Address bar keeps focus.

**Actual result**:
Address bar loses focus but the keyboard does not hide.

**Comment by cmonfortep** [comment]
Thanks for reporting this @AndrewR8 I think the **expected result proposal 1** could fit pretty well here.

**Comment by cmonfortep** [comment]
Closing this issue, thanks for the contribution @AndrewR8
