### ISSUE TITLE
Desktop site feature loads mobile layout

### ISSUE THREAD

**Issue by Johennes** [duckduckgo/Android#768]
Experiencing this on 5.49.1 mg (54901).

URL: https://stackoverflow.com/questions/tagged/swift

Layout in DuckDuckGo:

![Screenshot_20200407-212159](https://user-images.githubusercontent.com/1137962/78711012-98eafd80-7916-11ea-9a8b-82723d804cb6.png)

Layout in Firefox:

![Screenshot_20200407-212217](https://user-images.githubusercontent.com/1137962/78711020-9be5ee00-7916-11ea-86e0-8b0a3759b5e6.png)

Note that DuckDuckGo loads the desktop site but laid out responsively for a mobile viewport. I think this might not be intended because some responsive sites hide parts of the UI and trim down features on smaller screens.

**Comment by cmonfortep** [comment]
Thanks for reporting the issue, I was able to reproduce this issue on my device. I will take a look to see if I can see where the issue is coming from. 👍

**Comment by Johennes** [comment]
Interestingly I see it on the DDG iOS app as well. I was wondering if maybe the particular user agent string you use might influence it but I'm not seeing any apparent differences to what Firefox uses on a glance.

**Comment by Johennes** [comment]
Here is some evidence of what Firefox seems to be doing: https://hg.mozilla.org/mozilla-central/file/tip/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoSessionSettings.java#l219

```
    /**
     * Mobile-friendly pages will be rendered using a viewport based on their &lt;meta&gt; viewport
     * tag. All other pages will be rendered using a special desktop mode viewport, which has a
     * width of 980 CSS px.
     */
    public static final int VIEWPORT_MODE_MOBILE = 0;

    /**
     * All pages will be rendered using the special desktop mode viewport, which has a width of
     * 980 CSS px, regardless of whether the page has a &lt;meta&gt; viewport tag specified or not.
     */
    public static final int VIEWPORT_MODE_DESKTOP = 1;
```

**Comment by Johennes** [comment]
I've been able to showcase a potential fix using a user script to force a larger viewport in https://github.com/duckduckgo/iOS/issues/624.

**Comment by cmonfortep** [comment]
Thanks for the write up and the investigation @Johennes . I will align with the iOS team and discuss about a possible fix.

**Comment by Johennes** [comment]
I am not proficient in Android development but what seemed to work well on iOS in my testing was to add a content script that modifies / inserts the view port meta header to force the size (see the snippet in https://github.com/duckduckgo/iOS/issues/624). I couldn't find another way of forcing the view port on `WKWebView`. I suppose theoretically this should work on Android as well but unsure if Android maybe has better APIs to do this without JS hacking.

**Comment by cmonfortep** [comment]
no problem @Johennes, I was just being explicit that we are open to receiving any proposals from contributors. You already did a good effort here and we highly appreciate the feedback you brought us.

**Comment by Ammako** [comment]
Desktop Site toggle basically never works on most sites, tbh. The same happens with LineageOS's default browser though (Jelly), so it could just be a webview limitation rather than a duckduckgo bug. I don't know of any other webview-based browsers that have desktop view toggle that I can try though.

**Comment by Lalisfeed** [comment]
when desktop site mode is enabled

- https://github.com/duckduckgo/ page loads in mobile view
- https://github.com/orgs/duckduckgo/people/ page loads in desktop view

**Comment by extroonie** [comment]
Is there any insight on this? This now seems to be an issue with plenty of sites. Would appreciate prioritizing it now.

**Comment by malmstein** [comment]
Duplicated.
