### ISSUE TITLE
No Password Manager 

### ISSUE THREAD

**Issue by raaju-kolpolok** [duckduckgo/Android#772]
Need a option for viewing saved login passwords for sites like chrome.

**Comment by cmonfortep** [comment]
Hi @raaju-kolpolok, could you elaborate a bit more about this?

**Comment by raaju-kolpolok** [comment]
Need AutoFill Password manager like chrome browser. After successful login to a site , users credentials will be saved. I already make it for websites with basic http authentications. But could not get the required info for other sites as no handler found for managing those authentication. 

please see this apk:- https://i.diawi.com/LGQcS9

navigate to passwords from the popup menus. login to a test website with basic authentication. you will see saved credentials info in Password Menu. Need the credentials for every websites that logged in. For helping the user not to forget the password and help him to autofill when he tries to login again.

**Comment by cmonfortep** [comment]
Thanks for the feedback. Like you described, we don't have a password manager in place. It will be for sure a nice feature to have in the future, but our small team is currently focused on different features that currently have more priority.
