### ISSUE TITLE
Opening link after inactivity data clear time fails to load page.

### ISSUE THREAD

**Issue by sephelps** [duckduckgo/Android#780]
1. Open a new tab and visit a website.
2. Leave the browser by hitting the home button.
3. Wait the amount of time data is automatically cleared after.
4. Click a link that will open the browser.
5. The browser shows a "data cleared" message and fails to open the link clicked.

**Comment by cmonfortep** [comment]
Thanks for reporting that issue @sephelps.
That's related to how the automatic data clearer is implemented, and I agree that we should improve that part. I would expect that same as a user.

**Comment by CDRussell** [comment]
Which version of the app did you see this happening on @sephelps ?

**Comment by sephelps** [comment]
@CDRussell 

This was happening on 5.51.p (55100).

After updating, the issue is still present on 5.52.4 (55205).

**Comment by OnizukaX** [comment]
Hi there,

any progress on this?
5.114.2 shows the same behavior.

**Comment by cmonfortep** [comment]
We are closing this issue as we don't have plans in the short-mid term to address it. Sorry about that.
