### ISSUE TITLE
shouldOverrideUrlLoading does not work in API level <24

### ISSUE THREAD

**Issue by strooonger** [duckduckgo/Android#79]
Hi,

I found that the class [BrowserWebViewClient](https://github.com/duckduckgo/Android/blob/0a3546d03df3f1886c30e34332863d7461b0776d/app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt#L44) uses shouldOverrideUrlLoading(view: WebView, request: WebResourceRequest), which is added in API 24 (see this [link](https://developer.android.com/reference/android/webkit/WebViewClient.html)), the former method is deprecated, however the newer method cannot execute in API level < 24, meaning that the code snippet you wrote in "shouldOverrideUrlLoading" will not execute.

In this case, you may consider override both new method and "deprecated" method and check the API version to determine which kind of method should execute.

**Comment by CDRussell** [comment]
Thanks for reporting this @strooonger . I have created a PR to fix this; pending review from my team.

**Comment by CDRussell** [comment]
_Merged_
