### ISSUE TITLE
www.iherb.com - Unsupported browser on tablet

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [duckduckgo/Android#792]
First reported on https://github.com/webcompat/web-bugs/issues/51731

URL: https://www.iherb.com/

Browser / Version: Duckduckgo Web Browser 5.50.1
Operating System: Android (Tablet)
Tested Another Browser: Yes Chrome

Problem type: Something else
Description: Browser upgrade notice
Steps to Reproduce:
A pop up shows up saying that the duckduckgo browser is unsupported

**Comment by cmonfortep** [comment]
Thanks for reporting this issue, sometimes this happens for some sites and we have, inside our app, an option to "report broken sites" (check the three buttons menu in our browser). In there you will be able to assign a category, "the browser is incompatible" for example. Those reports are really helpful for us, and they are digested by a different team. 

Closing this issue, thanks.
