### ISSUE TITLE
BloomFilter.cpp file is missing 

### ISSUE THREAD

**Issue by Deepshikha01** [duckduckgo/Android#795]
Bloom Filter.cpp file is missing from      src/main/cpp/third-party/bloom_cpp/src/BloomFilter.cpp

**Comment by JeffAment** [comment]
@Deepshikha01,

The bloom filter is maintained in a separate repo and is pulled in as a submodule.  Cloning with the `--recursive` flag should fix this.

If you already have the repo checked out, you can also execute the following within the git repo without having to clone it again:
```
$ git submodule init
$ git submodule update
```

This is also explained in the repo's README in the "Building the Project" section.

**Comment by cmonfortep** [comment]
thanks @JeffAment for the explanation.

@Deepshikha01 is your problem solved following the described steps? Thanks.

**Comment by Deepshikha01** [comment]
Hello Sir/Madam,


Greetings of the day!


Thanks for the explanation ...My problem is solved .



Thanks and regards
Deepshikha shaw
