### ISSUE TITLE
Opening new tab from tab opens it in the end of the all tabs.

### ISSUE THREAD

**Issue by AndrewR8** [duckduckgo/Android#812]
**Steps to reproduce**

1. Navigate to [jw.org](https://www.jw.org).
2. Click on tabs button in browser.
3. Add one more tab with any query.
4. Return to tab with [jw.org](https://www.jw.org) and click on [Watchtower ONLINE LIBRARY™](https://wol.jw.org/en/wol/h/r1/lp-e) (at the bottom of the page).

**Actual result:**
The tab with [Watchtower ONLINE LIBRARY™](https://wol.jw.org/en/wol/h/r1/lp-e) opens in the end of the all tabs.

**Expected result:**
The tab with [Watchtower ONLINE LIBRARY™](https://wol.jw.org/en/wol/h/r1/lp-e) opens next to the  [jw.org](https://www.jw.org) tab.

(This does not happen when opening a new background tab)

**Comment by cmonfortep** [comment]
Thanks, we are aware of this behavior (and some others you also mention), and we are going to revisit this in a project to bring a better user experience when navigating between tabs or through your tab history.

**Comment by cmonfortep** [comment]
This issue should be fixed by https://github.com/duckduckgo/Android/pull/897

PR merged in develop, closing this Issue.
