### ISSUE TITLE
Pressing back on a freshly opened tab doesn't close it

### ISSUE THREAD

**Issue by ArttuLai** [duckduckgo/Android#813]
Having used several different browsers on Android, I got used to that if I open a link which in turn opens my default browser, I can press the system back-button and it closes the tab (while returning me to the origin app where I tapped the link). With DuckDuckGo, it takes me to the origin app when I press back but doesn't close the tab, and I'm often left with a big pile of "read" tabs which would've been closed by other browsers.

I don't know, maybe it's supposed to be like that. But other browsers on Android don't behave like this, so I thought I'd mention.

I'm using version 5.52.6, Pixel 4XL, Android 10.

### Steps to reproduce
1. Set DDG as default browser
2. Open any 3rd party app with clickable web links and tap any link
3. After DDG opens, press back button
4. Go back to DDG and see the tab you backed out from is still open

**Comment by AndrewR8** [comment]
I'll fix it

**Comment by AndrewR8** [comment]
This happens even if the new tab is open from the DDG explicitly.

**Comment by cmonfortep** [comment]
Thanks, I have to say that personally, at the beginning, I also saw that behavior as not expected, but I ended up kind of liking it 😅

In any case, we have received some feedback about this issue and some others, and we will try to improve it in a project. Thanks!

**Comment by cmonfortep** [comment]
Update: The project we created to improve our tab navigation was accepted and this scenario will be tackled inside it https://app.asana.com/0/715106103902962/1175421826172153/f

The project still needs to be prioritized, but it's already in our backlog, so we can close the issue. Thanks.

**Comment by milindrao** [comment]
So this has been closed for two years. But this annoying behavior is still present. I couldn't find any setting to change this behavior. Is this still not released?

**Comment by kercdbh** [comment]
I too agree that pressing back on a freshly opened tab should close it

**Comment by jaune-rouge** [comment]
Still an issue.

**Comment by senhalil** [comment]
This is still an issue. @cmonfortep an update would be very much appreciated.
