### ISSUE TITLE
Pressing back when new tab is open does not return to the previous tab

### ISSUE THREAD

**Issue by AndrewR8** [duckduckgo/Android#815]
**Steps to reproduce**

1. Navigate to [jw.org](https://www.jw.org).
2. Click on [Watchtower ONLINE LIBRARY™](https://wol.jw.org/en/wol/h/r1/lp-e) (at the bottom of the page).
3. Click on back button on browser.

**Actual result:**
The back button leads to home page.

**Expected result:**
The back button returns user to the [jw.org](https://www.jw.org) tab and closes [Watchtower ONLINE LIBRARY™](https://wol.jw.org/en/wol/h/r1/lp-e) tab.

**Comment by cmonfortep** [comment]
Thanks, we are aware of this behavior, and we are going to revisit this in a project. 👍

**Comment by cmonfortep** [comment]
The issue was fixed by #897 and it's now fixed.
