### ISSUE TITLE
Missing translations file

### ISSUE THREAD

**Issue by unbranched** [duckduckgo/Android#832]
Why do you use a file values/string-untranslated.xml ?
There's no reference on the TRANSLATIONS.md and adds a lot of confusion.

If you put untranslated strings in there, then for which language? And how does one know which strings really are, needs to check one by one in his language file...

**Comment by cmonfortep** [comment]
The usage of `values/string-untranslated.xml `is part of our internal development process for features released without being translated in other languages (only English).
We usually add all the corresponding translations within a few weeks.

Does this solve your question?

**Comment by unbranched** [comment]
Got it, thank you.
