### ISSUE TITLE
Why the exit button is not in the program?

### ISSUE THREAD

**Issue by tigerbit85** [duckduckgo/Android#837]
Why the exit button is not in the program?
**Android marshmallow
After close tabs and clear data, still open app I can't close app show keyboard for search , please add exit button.
Thank you

**Comment by cmonfortep** [comment]
Hi @tigerbit85 
We don't have a "close app" button as we think it's not necessary (pretty rare in the android ecosystem). Users can always press home (and let android close the app whenever it's needed) or close the app from app switcher.

After pressing fire button, we remove all tabs and any related data, but many users want to continue using the browser after that. We have auto-clear option inside settings, where you can trigger the same when the app is closed or after the app has been inactive for an amount of time.

Thanks!

**Comment by cmonfortep** [comment]
Closing this issue as it has been inactive for some time and question has been addressed.
