### ISSUE TITLE
Add SwipeRefreshLayout for more accessible refreshing

### ISSUE THREAD

**Issue by sanogueralorenzo** [duckduckgo/Android#849]
**Steps to reproduce**

Navigate to any webpage.
Overscroll upwards

**Actual result:**
Nothing happens

**Expected result:**
For ease of use, as a user I would expect to be able to refresh the webpage instead of having to navigate to the 3 dots & refresh

![image](https://user-images.githubusercontent.com/5630683/83954356-34a4c700-a7fd-11ea-90d1-0c937dc203ba.png)

Kiwi example
![Swipe-Refresh-Kiwi](https://user-images.githubusercontent.com/5630683/83954379-89484200-a7fd-11ea-9000-e75778cbeeff.gif)

**Comment by cmonfortep** [comment]
I agree, and it has been requested in the past, see issue: https://github.com/duckduckgo/Android/issues/33

We received some contributions but none of them got merged:
https://github.com/duckduckgo/Android/pull/293
https://github.com/duckduckgo/Android/issues/33
https://github.com/duckduckgo/Android/pull/750


I will close this issue as duplicated.
