### ISSUE TITLE
NFC tags don't open in duckduckgo

### ISSUE THREAD

**Issue by andreaskern** [duckduckgo/Android#851]
**1. What I do:**
Scan an NFC tag that holds web url

**2. What happens:**
Google Chrome opens the url

**3. What should happen:**
Duckduckgo opens the url

After some investigation it seems that duckduckgo is missing the intent-filter.
a quick search for 'nfc' in the google chrome app manifest reveals two entries.
I don't know if nfc permissions are needed to.

![image](https://user-images.githubusercontent.com/739277/83968983-42c21880-a8cd-11ea-888d-9016adfdef89.png)

https://chromium.googlesource.com/chromium/src/+/b71e98cdf14f18cb967a73857826f6e8c568cea0/chrome/android/java/AndroidManifest.xml#245

**Comment by ashwinpilgaonkar** [comment]
Hi @cmonfortep, can I work on this?

**Comment by cmonfortep** [comment]
@ashwinpilgaonkar sure!

**Comment by ashwinpilgaonkar** [comment]
Hi @cmonfortep,

Since I dont have any physical NFC tags to test out my changes with, I'm trying to emulate it using another test application that I'm building. 

I just have one question - when the NFC tag is detected, does it broadcast an intent in a similar manner as the code snippet given below?
```
                Intent intent = new Intent("android.nfc.action.NDEF_DISCOVERED");
                intent.setType("text/plain");
                intent.putExtra(NfcAdapter.EXTRA_NDEF_MESSAGES, "Test text");
                sendBroadcast(intent);
```

**Comment by cmonfortep** [comment]
According to the docs, yes, it does -> https://developer.android.com/guide/topics/connectivity/nfc/nfc#filter-intents

There's more information about the nfc tags also there https://developer.android.com/guide/topics/connectivity/nfc/nfc#dispatching

**Comment by ashwinpilgaonkar** [comment]
> According to the docs, yes, it does -> https://developer.android.com/guide/topics/connectivity/nfc/nfc#filter-intents
> 
> There's more information about the nfc tags also there https://developer.android.com/guide/topics/connectivity/nfc/nfc#dispatching

Yes, I had gone through these docs earlier but could only find info pertaining to filtering an NFC intent. Whereas, I was more interested in finding out how to mock a physical NFC tag.

Anyway, I've made a PR with the changes, which I was able to test successfully using the following code snippet -
```
                Intent intent = new Intent();
                intent.setAction("android.nfc.action.NDEF_DISCOVERED");
                intent.setData(Uri.parse("https://www.example.com"));
                startActivity(intent);
```
IMO it should work the same way with a physical NFC tag as well. Perhaps if someone else has access to one, they can help us out by testing it.

**Comment by cmonfortep** [comment]
Thanks, I will review the PR this week and will do the testing part too.

**Comment by cmonfortep** [comment]
PR has been merged and this feature will be available in our next release.

Shout out to @ashwinpilgaonkar @JeffAment and @andreaskern!
