### ISSUE TITLE
Please add options to disable all these privacy popups

### ISSUE THREAD

**Issue by micwoj92** [duckduckgo/Android#855]
I've used it before and it was good, but today I downloaded it again and all the popups about spying and protection are annoying. Please add option in menu to disable them.

**Comment by cmonfortep** [comment]
Hi! @micwoj92. Thanks for the feedback. They are just a few, and we think important for users that may not be so familiar with how creepy the internet can be and how we can help them.
Having said that, there's a "hide" button on the top right corner to disable them. I hope that works for you!

**Comment by micwoj92** [comment]
Unfortunately I am not able to locate this button, I am not version  5.55.1 (55501) latest from F-Droid.

**Comment by micwoj92** [comment]
Updated to 5.56 downloaded from github. Still do not see button.

**Comment by cmonfortep** [comment]
So just below the URL bar, on the right side, there's an option that says "hide".

<img src="https://user-images.githubusercontent.com/4747865/85066748-d211da80-b1af-11ea-9d0c-451ad90122d2.png" width="360px"/>
