### ISSUE TITLE
Add option to not hide bars when scrolling

### ISSUE THREAD

**Issue by micwoj92** [duckduckgo/Android#856]
When scrolling the url and function bar do hide, I do not like this behaviour and would like an option for these to remain visible at all times.

**Comment by micwoj92** [comment]
Yes, I meant the URL Bar, but also the bar below the screen, so that's why I called it "function bar" I do not know if that's right name.

This is just general feeling. The ability to see and copy/paste url at all times and beinf able to switch tabs without having to scroll, which changes your position on page. Also when typing this comment right now(1) I sometimes scroll up/down and the URL bar stays in the same place. It would be annoying if it was just showijg up and then hiding again.

(1)Currently I am using Fennec F-Droid and in the settings it has checkbox called "fullscreen browsing"

**Comment by micwoj92** [comment]
Also this is a feature request not a question

**Comment by cmonfortep** [comment]
Thanks for your quick response.

We have revisited a few times the behavior of our URL bar and we try to follow how other browsers behave. It's pretty common in Android to hide the top bar when the user scrolls. Yet, I took note of your request and your suggestion to introduce the option under settings.

I'm going to close this issue since I don't think we are going to apply any change in a short/mid-term. We can reopen it if at some point we see interest from more users.

**Comment by micwoj92** [comment]
If someone was to search for this feature and see the request closed it might discourage them to open new or comment on this one. Perhaps it is good idea to add priority labels to issue/request tracker?

**Comment by willemm** [comment]
Plus one for this feature request. Although in my case, I have a very specific reason:

There is this interactive web app that is single screen (sudokupad) that you constantly tap and swipe to interact with. The auto hiding address bar  therefore is constantly popping in and out, causing it to resize which is extremely annoying.

**Comment by ozGarius** [comment]
Yeah I also welcome having this option in the settings. Same reason as William there are some web app that are not designed to scroll but with the address bar hiding they constantly shift. Vivaldi doesn't seem to have this problem.
Simply go to maps.google.com to test it out.
