### ISSUE TITLE
New UI is cluttered

### ISSUE THREAD

**Issue by micwoj92** [duckduckgo/Android#857]
Coming back to this browser after couple months. The old UI with URL bar on top only was good. Now there are too many buttons on screen. Please consider adding "compact mode" which will use only one bat (doesnt matter if above or below screen). The layout used in previous versions was much better than current one.

**Comment by cmonfortep** [comment]
@micwoj92 I agree. That was part of an experiment where we introduced a bottom bar. Having that bottom bar made it possible to move some of the options there and have a minimalistic URL bar on the top. But the experiment didn't go as we expected so we removed it. We may revisit that in the future, so I really appreciate your feedback.

**Comment by micwoj92** [comment]
Was it removed in 5.56.0?

**Comment by micwoj92** [comment]
I just downloaded 5.56.0 

I do not understand why this wasn't in patchnotes on github...

**Comment by cmonfortep** [comment]
Yes, we removed the bottom bar in 5.56.0

The UI with the BottomBar was part of an experiment. When we do experiments that means that we release a feature only for some of our users to see how it performs. That's why that wasn't in our release notes. We only post changes that affect all our users.

**Comment by micwoj92** [comment]
Ah, makes sense. Thanks for explaining.
