### ISSUE TITLE
Do you need help? )

### ISSUE THREAD

**Issue by coffeeplanter** [duckduckgo/Android#86]
Hi, guys!
I think, it's a very useful project.
Do you need some help with it? I'm developing Android apps in Java & Kotlin. But I don't know C/C++.
Maybe you need a translation? I'm a native speaker of the Russian language.

**Comment by subsymbolic** [comment]
Thanks @coffeeplanter! Opening up the app to the community is one of our 2018 goals. The architecture is still in flux so it may take a few more months before we can start accepting contributions but stay with us, we'd love your help and will update the readme page as soon as we're ready.

**Comment by CDRussell** [comment]
Hi @coffeeplanter, if you're still interested in helping us improve the app for Russian speakers, we have just opened this up for community contributions. Please see #559 for details.
