### ISSUE TITLE
Feature Request: Site blocking/parental control

### ISSUE THREAD

**Issue by christophergeiger3** [duckduckgo/Android#860]
It would be nice if users had the option to block sites that they don't want accessible on their phone (e.g. sites that store information, are inappropriate, etc).

Perhaps this could be an option in settings -- a user could add sites they want blocked to a list. Then if the user attempts to access one of these sites, they would be redirected to a page that tells them they are blocked, for example.

Thanks!

**Comment by cmonfortep** [comment]
Thanks for the feature request, really interesting. I will share it internally with the team.

**Comment by cmonfortep** [comment]
Friendly reminder that we are a small team with a big backlog of features. We try to prioritize all our work based on our users' needs and the impact of each feature. We keep issues open so other users can show interest too, so thanks again for sharing it here.

**Comment by donfuxx** [comment]
If you want to block some sites that aren't family-friendly you could just set a child-safe ip in your device dns settings, like for example https://support.opendns.com/hc/en-us/articles/228009007-Android-Configuration-instructions-for-OpenDNS
The nice thing about this is that this would apply also to other browsers / apps that are installed on the same device.
However that obviously only works as long the child doesn't figure out how to reset that again :-)

**Comment by cmonfortep** [comment]
Tracking this feature request: https://app.asana.com/0/0/1199514257586724/f

**Comment by cmonfortep** [comment]
Hello @christophergeiger3.

I did a small demo project of this will look like in our app, but we've agreed that there's no plan in the foreseeable future to support this request. Should this change in the future, we'll update this conversation appropriately.
