### ISSUE TITLE
Feature request: Reader mode

### ISSUE THREAD

**Issue by rodolphe74** [duckduckgo/Android#861]
Displaying only the text legibly.
Thanks.

**Comment by cmonfortep** [comment]
Thanks for the feature request. It will be a very nice feature to have.

Friendly reminder that we are a small team with a big backlog of features. We try to prioritize all our work based on our users' needs and the impact of each feature. We keep issues open so other users can show interest too, so thanks again for sharing it here.

**Comment by lerbeso** [comment]
I'm also interested in this feature.
Love your browser but I keep fennec too on my phone for reading articles.

**Comment by cmonfortep** [comment]
Created an internal task to track this issue: https://app.asana.com/0/0/1199514257586723/f

**Comment by cmonfortep** [comment]
Hello there. We have been received similar feedback from users using our embedded feedback form within the app. I've also shared this with others whe I created a task som time ago. However, no plans yet to support this.

Everyone can continue sending feedback using the feedback option inside settings (from our browser) or just using the web form. We process that feedback internally every day and scope projects when we see enough activity.

Closing this issue as it's already tracked internally. Thanks.

Check "share feedback" guidelines here (https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#share-feedback).

**Comment by flutterbird** [comment]
Hi, 
I don’t mean to be redundant. Is there any progress on the inclusion of a reader in DDG’s mobile browser?
If it isn’t something that’s easy to build in, especially keeping privacy in mind, couldn’t a !bang be used that could move the content you’re looking at to a reader service Online? 
One of the best DDG features is !bang. Is there a way to use a reader service that already exists that would move the content being viewed to a reader or text-only service?

Thank you.

**Comment by loleg** [comment]
+1 @cmonfortep would be great to hear if there's progress, roadblocks, or workarounds available.

**Comment by georgeanderson** [comment]
> +1 [@cmonfortep](https://github.com/cmonfortep) would be great to hear if there's progress, roadblocks, or workarounds available.

There is a workaround. You can install Reading mode from Google and it will enable you to achieve reading mode from DDG or any other place in your phone. It works great.

**Comment by loleg** [comment]
> install Reading mode from Google

https://play.google.com/store/apps/details?id=com.google.android.accessibility.reader
