### ISSUE TITLE
Adblock dosen't block all type of ads

### ISSUE THREAD

**Issue by JonO7694** [duckduckgo/Android#862]
I just ran a few tests with the adblock and it seems that it doesn't block popup ads or redirect ads as seen in this url https://canyoublockit.com/extreme-test/
This specific test uses a bunch of different ad servers that is not specific to google ads.

**Comment by cmonfortep** [comment]
Thanks for the feedback. We block trackers and Ads based on a list of common cross-site trackers that we continuously update. So this is part of our app that is continuously improving 🚀

**Comment by cmonfortep** [comment]
Related issues:
https://github.com/duckduckgo/Android/issues/306
https://github.com/duckduckgo/Android/issues/482

Closing this issue.
