### ISSUE TITLE
How am I supposed to contact DuckDuckGo with a bug report?

### ISSUE THREAD

**Issue by bat999** [duckduckgo/Android#871]
*Hi
I know this is not the correct place.
But I want to report a bug about the DuckDuckGo LITE website.

I've filled in the form at https://duckduckgo.com/feedback
And I've sent emails to bd@duckduckgo.com

But I haven't received any replies, not even confirmation of my messages.

Does DuckDuckGo not respond to bug reports? 

Is there some other email address that I should be using?

**Comment by bat999** [comment]
Hello again
I've received a reply about the email...
It's not deliverable!
Does anybody here know an email address for DuckDuckGo that works?
**Delivery has failed to these recipients or groups:**

**bd@duckduckgo.com (MALITO:bd@duckduckgo.com)
Your message couldn't be delivered. Despite repeated attempts to deliver your message, querying the Domain Name System (DNS) for the recipient's domain location information failed.

For more information and tips to fix this issue see this article: https://go.microsoft.com/fwlink/?LinkId=389361.**

**Comment by cmonfortep** [comment]
Hi @bat999 

https://duckduckgo.com/feedback is the right place for any bug report or feedback related to our search engine. I'm sorry you didn't get any response yet, there could be some delays.

I'm not familiar with the bug report process but I guess you have a hackerone issue number. You can check the current status there, and any follow up will happen inside hackerone.

Sorry I can't help much here.

**Comment by bat999** [comment]
Hi
I tried again with duckduckgo.com/feedback
This time I have had to set up an account with hackerone.
There doesn't seem a way to submit a "bug" report.
I have had to submit it as a "vulnerability" report.
That's weird.
Thanks for your help

**Comment by 21e8** [comment]
agree, please add a general bug report channel
