### ISSUE TITLE
Request favicon directly from site

### ISSUE THREAD

**Issue by catehstn** [duckduckgo/Android#877]
Current favicon requests go via the icons service. Replace these by calling directly to the site.

First: /favicon.ico
Fallback: default icon (exists in app).

[Internal tracking](https://app.asana.com/0/72649045549333/1182909349293473/f).

**Comment by CDRussell** [comment]
Fixed by https://github.com/duckduckgo/Android/pull/878

**Comment by GavJenks** [comment]
Why would you not just write all of this in ticket #527 ?

**Comment by waltercool** [comment]
> Why would you not just write all of this in ticket #527 ?

Ideally please comment: "Pull request merged at upstream", and close the comments section. Too much c**cer already there.
