### ISSUE TITLE
Add force enable zoom for accessibility

### ISSUE THREAD

**Issue by yawnoc** [duckduckgo/Android#882]
Could we please add an option to force enable zoom, even on sites which (annoyingly) have a meta viewport element with `maximum-scale=1`?

In Firefox this option is called "Always enable zoom" under Accessibility:

![Firefox accessibility options: always enable zoom (Force override so you can zoom any page)](https://user-images.githubusercontent.com/48375680/86517695-8d4b9c00-be5d-11ea-8e22-d79616a6f3ff.png)

**Comment by cmonfortep** [comment]
Thanks for the feature request. I created an internal task to keep track of it in our backlog.
https://app.asana.com/0/0/1187616573788674/f

**Comment by cmonfortep** [comment]
Hello @yawnoc. We have received similar feedback about being able to zoom and some more accessibility options from users (using our embedded feedback form within the app + the feedback received here). 

Everyone can continue sending feedback using the feedback option inside settings (from our browser) or just using the web form. We process that feedback internally every day and scope projects when we see enough activity.
Closing this issue as it's already tracked internally. Thanks.

Check "share feedback" guidelines here (https://github.com/duckduckgo/Android/blob/develop/CONTRIBUTING.md#share-feedback).
