### ISSUE TITLE
Fix handling of URLs with local domain and port

### ISSUE THREAD

**Issue by 8ware** [duckduckgo/Android#886]
**Description**
When entering URLs without scheme but local domain and port, e. g. `foo.fritz.box:3000`, the error *Unable to open this type of link* is shown. Prepending `http://` works, though.

**How to Reproduce**
1. Run a service locally, e. g. `python -m SimpleHTTPServer` (serves at port 8000)
2. Go to `<host-running-service>.<your-local-domain>:8000` (without specifying the scheme)
3. See the toast *Unable to open this type of link*
4. Prepend the scheme, i. e. `http://<host-running-service>.<your-local-domain>:8000`
5. See the directory index

**Expected behavior**
I expect that the scheme is prepended automatically if it's missing.

**Smartphone:**
 - DDG App Version: 5.55.1 (55501)
 - Device: – (ask if this information matters to you)
 - OS: Android 9 (Lineage OS)

**Comment by 8ware** [comment]
Maybe related to #384

**Comment by cmonfortep** [comment]
Hello @8ware  , thanks for taking the time to submit this feature request.

After internal discussion with the team, we've agreed that there's no plan in the foreseeable future to support this request knowing that adding the schema will fix the issue reported. 

Should this change in the future, we'll update this conversation appropriately.
