### ISSUE TITLE
Swipe to refresh triggers when address bar is hidden

### ISSUE THREAD

**Issue by JeffAment** [duckduckgo/Android#900]
Device: Google Pixel XL
OS: Android 10
DDG Version: 56000

On http://raosrestaurants.com/, the swipe to refresh triggers when it isn't supposed to (see gif below; very easy to reproduce on my device). Possibly related to #638. I've had similar issues on a handful of other sites also. I don't have a way to reproduce the bug on the other sites, but what I can say is that in every instance, the address bar was hidden.

Not sure if it matters, but I would also like to note that the other sites I mentioned, unlike raosrestaurants.com, did not render themselves to fill the `WebView` and had room to scroll up and down [in the `WebView`] when the unwanted refresh happened; the bug only happened one time on each site and could not be reproduced. Perhaps a check to see if the address bar is fully docked would fix, or at least mitigate, this issue.

I really don't think this is relevant, but if you wanted to know which other sites I had issues on, I will list them below. Please note that it is **_very hard to reproduce on these sites, and likely has nothing to do with the sites themselves_**:
https://portal.311.nyc.gov/
https://www.chess.com/
https://www.5dimes.eu
http://cooper.edu/

-------
**Edit:**

I found two more examples of sites where this bug is easy to reproduce:

**reddit.com**
- Go to reddit.com
- Wait for the site to lose focus, and for the overlay to appear with the bottom dialog asking whether to continue in the Reddit app or with the browser.

**linkedin.com**
- Visit LinkedIn profiles until you hit the authwall. (example: https://www.linkedin.com/in/chadchampion a.k.a. "the final boss of LinkedIn")

Both of these examples seem to distill themselves to the base case we saw on raosrestaurants.com (i.e. they fill the `WebView`)

**_End of edit_**

-------
![Raos](https://user-images.githubusercontent.com/21976019/89692436-b4244480-d8d9-11ea-80a0-2d31f46b7825.gif)

**Comment by Usiel** [comment]
Thanks for finding this. Adding a PR suggestion, which fixes the issue and makes the mentioned websites usable. However it's not quite as smooth as Chrome is unfortunately (more on that in the PR).

**Comment by Ammako** [comment]
This happens on 5.75.1 sometimes, with the refresh being far too sensitive and triggering too easily when you don't want it to. I'll see if I can get a recording at some point, once it happens again. It doesn't happen every time and doesn't seem to be too reliably reproducible.

**Comment by Ammako** [comment]
One thing that is probably relevant to this issue, though: the swipe to refresh *can* still trigger when the address bar is not fully shown yet. Happened over here on Youtube, scrolled up to the top of the page, trying to pull down the address bar, but while pulling down the address bar it also starts trying to refresh the page.

The thing is, it doesn't consistently happen every time. Not sure how to reproduce other than just using the app for a while until it happens.
