### ISSUE TITLE
Some sites hang when loading on Kindle Fire

### ISSUE THREAD

**Issue by redeveloper3** [duckduckgo/Android#906]
**Describe the bug**
Intermittently some sites do not load, the progress bar stops halfway and the browser hangs.

**How to Reproduce**
1.  Open browser and enter 'bbc.co.uk/news'.   For me this site has crashed multiple times, not every time though.
2.  Bug also happens intermittently when trying to access sites via Twitter's URL shortener (t.co).

**Expected behavior**

Blue progress bar fills from left to right & site displays.

**Actual behavior**

Blue progress bar fills halfway from left to right & white screen displays.  	All onscreen buttons are then unresponsive.
To resolve:  restart the Kindle > go to Kindle home screen, load F-Droid > Manage My Apps > DuckDuckGo > Links and click one of the links (e.g. Issues), this normally loads OK.  Close the hanging tab.

**Smartphone (please complete the following information):**
 - DDG App Version: 5.55.1

 - Device: Kindle Fire 7 (9th generation) 
 - OS: Android 6.3.1.5

Thanks for developing DuckDuckGo Android!

**Comment by redeveloper3** [comment]
Thanks for coming back - I've searched online & in the Kindle settings but unfortunately can't see the version of Webview, sorry.

**Comment by cmonfortep** [comment]
@redeveloper3 I think we have found a way to check what webview version you are using:

- Visit device Settings
- Apps & Games
- Manage all applications
- Swipe across and choose ALL tab
- Amazon System WebView

Thanks

**Comment by redeveloper3** [comment]
Thanks, got it - 

Webview is version70.amazon-webview-v70-3538.3538.110.137

**Comment by cmonfortep** [comment]
Possibly related to this one: https://github.com/duckduckgo/Android/issues/919

**Comment by cmonfortep** [comment]
Hi @redeveloper3, our latest release may fix the described issue here. Could you check if that's still happening for you or if it's fixed? Thanks!

**Comment by redeveloper3** [comment]
Thanks so much, I've just installed so will try it out & let you know :-)

**Comment by cmonfortep** [comment]
@redeveloper3 I've noticed our latest version is still not available in f-droid, should be there soon. 5.64.0

**Comment by cmonfortep** [comment]
Update: 5.65.0 is available in F-droid!

Sorry for the delay, it seems f-droid may be having some delays on our side to merge new app requests.

**Comment by redeveloper3** [comment]
Thanks very much, I upgraded to 5.65 a couple of days ago and the issue has not returned :-)
