### ISSUE TITLE
Open local HTML file from storage

### ISSUE THREAD

**Issue by femto-code** [duckduckgo/Android#912]
When trying to call a local HTML file from the sdcard the app says

> This kind of link cannot be opened.

Stock browser (based on System WebView) is able to open local files. Is it possible to add this feature also in DuckDuckGo?
Thank you!

**Comment by cmonfortep** [comment]
Hello @femto-code, thanks for taking the time to submit this feature request.

After internal discussion with the team, we've agreed that there's no plan in the foreseeable future to support this request. Should this change in the future, we'll update this conversation appropriately.
