### ISSUE TITLE
Update in-app DDG logo if user changes app icon

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#917]
Quick Design Idea:
• Small Design Idea For The Homescreen Whatever Icon You Choose Can Replace The Orange Icon On The Homescreen And Possible Privacy Tips To Help Others Out

**Comment by cmonfortep** [comment]
Thank you for sharing this idea with us.

I've added a task in our backlog with this proposal and will share it with the team.
https://app.asana.com/0/0/1190561305733441/f

I'm going to close the issue since it's already documented internally.
