### ISSUE TITLE
Web Settings

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#918]
From A Prior Request:

Web Settings For The WebView
• Enable/Disable Website JavaScript May Speed Up Sites Or Increase Someones Privacy If They Value It (Many Browsers Offer This)
• Block Third Party Cookies Or All Cookies (You Can Test This Of Many Different Test Sites, The Browser Excepts All)
• Form Data From The WebView (Make It Possible To Enable/Disable This)

Potential Other Web Setting:
• User-agent spoofing (Example When Tested On Sites Your Platform Etc Is Exposed E.g. Android, Spoofing Would Allow Us To Change It From Our Devices Being Recognised)
• Do Not Track Requests To Be Added As An Option

**Comment by cmonfortep** [comment]
Comments around some of your requests:
- Cookies: We block third party cookies by default. This fits with our product being a privacy browser and we see no reason to make the option configurable. In case the user wants to clear all cookies, our Fire button does a great job there.
- Form data: For users that want to clear all data, including Form data, to use the fire button is our recommended approach.
- Do not track: duplicated https://github.com/duckduckgo/Android/issues/648 duplicated

About javascript and user-agent, currently, we don't have plans to change how we handle those. It will introduce breakages to many websites, so new options should be added to settings for our advanced users.
We are currently focused on projects that will have an impact on protecting all our users. For sure, at some point, we will start adding more advanced settings but not in the short/mid-term.
