### ISSUE TITLE
App versions >5.59.2 give back blank pages

### ISSUE THREAD

**Issue by Breizhelle** [duckduckgo/Android#919]
Hi!

The last 2 updates of DDG 5.60.0 & 5.61.2 available on F-Droid are just giving back blank pages at search or entering a website url.

I had to downgrade back to the last working previous version.

And using the downgrade option on F-Droid, it succeeds in downloading the previous version but failed at installing it. I each time had to unistall the versions and then install the 5.59.2 version that works. But this might be a F-Droid issue...

**How to Reproduce**
1. Upgrade DDG version through F-Droid
2. Click on DDG app icon
3. Enter whatever search words or full website url
4. There is the blue line of the loading of the page but at the end it stays like a blank page and I never get either the search DDG page results or the website appearing

**Expected behavior**
I expect to get the pages to load and have either the page results of DDG or the website properly loaded

**Smartphone (please complete the following information):**
 - DDG App Version: 5.60.0 AND 5.61.2
 - Device: Fairphone 2
 - OS: Android 7.1.2

**Comment by cmonfortep** [comment]
Thanks for reporting. We haven't received any similar issue related to blank pages on those versions, but we will keep this under our radar.

**Comment by cmonfortep** [comment]
Hi @Breizhelle, our latest release (5.64.0) may fix the described issue here. Could you check if that's still happening for you or if it's fixed? Thanks!

**Comment by Breizhelle** [comment]
It hasn't been uploaded yet on F-Droid tho. I'll check this once it's in there.

**Comment by Breizhelle** [comment]
What happens with the 5.63.1 which is on F-Droid is this.

I type something on the main url/search space. There is the blue line that tells you the page loads, this blue line goes all the way till it's done and I stay on a blank page nothing appears.
But if I leave the app and come back on it then the page appears.

I don't know if it makes sense...

And if I search for something on a tab that I already used for something else then no issues at all. It's like when I start a new tab it needs a kick by me doing something else and come back on it to finally showing me the page I want to...

**Comment by juliahop** [comment]
Hi,
I'm having a similar issue, but for so far I know only with a Gatsby(React) site. When I try to open it, the page is loading, you see the images appear, and then when it's done - white page. 
I'm using version 5.64.0 on Android 7.1.1.

**Comment by cmonfortep** [comment]
Thanks for checking @Breizhelle , we submitted 5.64 to f-droid 9 days ago but request is still pending
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7413

Hope it can be available soon 🤞

**Comment by cmonfortep** [comment]
@juliahop if you could share with us any example it will be nice. It could be the same issue or a new one. Thanks

**Comment by juliahop** [comment]
This is the site I'm talking about: https://www.essentia-consultancy.nl
Thank you.

**Comment by cmonfortep** [comment]
Thanks @juliahop I tried that site on some devices, and loaded successfully in all of them. It could be an issue related to the webview version.

**Comment by cmonfortep** [comment]
@Breizhelle 5.65.0 is finally available in F-droid, you can try it and tell us if the issue was fixed for you.

Sorry for the delay, it seems f-droid may be having some delays on our side to merge new app requests. 5.64.0 didn't make it for an unknown reason, but we published a new version that went faster.

**Comment by juliahop** [comment]
> Thanks @juliahop I tried that site on some devices, and loaded successfully in all of them. It could be an issue related to the webview version.

Thank you @cmonfortep . I have tried it on Android 10, and it works just fine. Didn't realise I had such an old telephone.

**Comment by cmonfortep** [comment]
Thanks @juliahop for trying it on your side.

In https://github.com/duckduckgo/Android/issues/906, another user reported that the issue has been fixed. I will proceed closing this issue too as both reported the same problem. Thanks!

Feel free to reopen the issue again if the problem persists.
