### ISSUE TITLE
Downgrading version of DDG on F-Droid doesn't work

### ISSUE THREAD

**Issue by Breizhelle** [duckduckgo/Android#920]
**Describe the bug**
Got issues with new versions of DDG so had to downgrade.
I'm using F-Droid which shows the last 3 versions of an app.
When trying to downgrade the app, It downloads the app version I want and fails to install it. I have to unistall the app to then actually install an older version directy through F-Droid.

Upgrading works.

I don't know if it's a DDG issue or an F-Droid issue tho.

**How to Reproduce**
1. Go to F-Droid
2. Find the DDG page on F-Droid
3. Go at the end of the page to the section "Versions"
4. Click on "Downgrade" on the version you want to downgrade the app to
5. Once the download is complete click on "Install"
6. Sends back this message :
"Error installing DuckDuckGo Privacy Browser
Failed to install due to an unknown error
OK (button)"

**Expected behavior**
Should downgrade without error

**Smartphone (please complete the following information):**
 - DDG App Version: From 5.60.0 or 5.61.2 to 5.59.2
 - Device: Fairphone 2
 - OS: Android 7.1.2

See screenshot attached
![Screenshot_20200828-105454](https://user-images.githubusercontent.com/33866592/91582212-7dac7900-e91d-11ea-8e04-bc2df4ec3311.png)

**Comment by cmonfortep** [comment]
Can you downgrade other apps? I think this is a F-droid issue.

Found this on reddit https://www.reddit.com/r/fdroid/comments/b3obp9/problem_downgrading_app/ 
it's 1y old but it seems related, not sure if still valid.

**Comment by resynth1943** [comment]
This may be downgrade protection. Can you try downgrading other apps?

**Comment by Breizhelle** [comment]
So no it does not work with other apps either.
So it's an F-Droid issue :)

**Comment by cmonfortep** [comment]
Thanks for checking @Breizhelle 🙌
