### ISSUE TITLE
Scroll Etc.

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#926]
Websites That Have Anchored Features To Them, Trigger Scroll To Refresh Out Of Nowhere.

E.g. Websites with anchored features to the top and bottom if scrolling up and down the Scroll to Refresh appears and refreshes a page that does not need to be refreshed.

I am aware an issue similar has been said before but it does get in the way of functionality for browsing sites

(Possible Ideas For The Next Update: Address scroll related bugs, improve dark theme design as this would be great for many users and allow users to move the navbar to the bottom or top)

**Comment by cmonfortep** [comment]
In https://github.com/duckduckgo/Android/issues/900 we fixed pull to refresh for websites that fill the whole viewport. Could you validate if our latest app version still has the behavior you described?

If so, please share with us any website where we could reproduce the issue. Thanks.

**Comment by cmonfortep** [comment]
We think the issue was solved by #900. I will proceed to close this issue as we didn't get any more reports.

**Comment by Ammako** [comment]
One thing that happens sometimes, when there is a scrollable frame within a website, is that when you try to scroll up or down in that frame, instead it gets stuck and scrolls the entire page, which sometimes ends up causing a page refresh if you were trying to scroll that frame back up. This may be related?
