### ISSUE TITLE
Bookmark Folder

### ISSUE THREAD

**Issue by maximustheone** [duckduckgo/Android#927]
To use Duckduckgo Privacy browser as allday browser,  I really miss the option to add Folders to sort and organize my bookmarks.

Simply add the possibility to add new folders in the bookmarks. 

This would improve the browser for anyone who wants a privacy browser but not to resign a bookmark function without scrolling down 100 of bookmarks.

**Comment by cmonfortep** [comment]
@maximustheone Thanks for sending us this feature request, we agree with you that user experience will be better in that part of the app if we add any kind of management functionality, you are totally right!. It's on our roadmap to improve bookmarks, however, we are a small team and I can't give any estimation here.

I'm going to close this one in favor of https://github.com/duckduckgo/Android/issues/557 This automatically links both feature requests, so nothing is lost. Thanks again for reaching us.
