### ISSUE TITLE
Blocklist

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#932]
Add A Custom Domain Blocklist, So We Can Manually Add Domains/URL's To Be Blocked

This Would Be Great For Blocking Redirecting URL's Etc 

Would Be Good To See:
• Bookmark Folders
• Better Themes And Designs
• More Site Information
• Add More Protection Features (Block Third Party Cookies Etc)

**Comment by cmonfortep** [comment]
Thanks @WillHick ! we received a similar feature request -> site blocking (https://github.com/duckduckgo/Android/issues/860).

I'm going to close this one as duplicated in favor of the oldest one. Feel free to reopen this issue if you think they are not related.
