### ISSUE TITLE
Privacy Features

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#935]
Add Fingerprint Protection And Third-Party Cookie Blocking (Would Be Some Nice Security Options To See) 

A Stat Counter Would Be Nice For The Homepage (Brave Recently Added A Stat Page)

![Screenshot_2020-09-15-16-59-27-51](https://user-images.githubusercontent.com/48844761/93167523-205d5800-f764-11ea-898b-3aca5a3a454d.png)

Something Like This Would Be A Nice Idea To Give Some More Lively Hood To The Home Page

Seeing Options Like This Sooner Than Later Would Be Nice (I Am Aware You Guys Are A Small Team But To See More Updates More Often Would Be Nice) (Maybe Bring Back DuckDuckHack To Bring Updates Etc Faster)

**Comment by cmonfortep** [comment]
Thanks for sharing those ideas. Some of them are already in our backlog, like improving our fingerprinting protection or the stats screen. About third-party cookies, we already block those related to trackers.
