### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#937]
Would Be Nice To See An Interface/UI And Functionality Update In The Next DDG Update A Few Ideas Being:

• Move Toolbar To Top Or Bottom (On/Off Feature)
• Bring Back The Control Bar For The Bottom (Like IOS, Make It A Changeable Option - On/Off)
• Improve Dark Theme UI (Has Been Said A Few Times But Would Be Nice To See)
• Site Certificate And Permission Interface 
• Script Blocking

**Comment by cmonfortep** [comment]
Thanks for sharing all those feature requests.

Some users already shared those ideas to improve our browser, so closing this task as duplicated by:

- https://github.com/duckduckgo/Android/issues/850
- https://github.com/duckduckgo/Android/issues/840
- https://github.com/duckduckgo/Android/issues/685
- https://github.com/duckduckgo/Android/issues/918

We appreciate new feature requests coming from our community, but please try to split them into different issues so we can address them separately. Thanks.
