### ISSUE TITLE
DuckDuckGo Lite

### ISSUE THREAD

**Issue by ghost** [duckduckgo/Android#939]
**Is your feature request related to a problem? Please describe.**
I have slow internet connection

**Describe the solution or the user experience you'd like**
i do have option to set DuckDuckGo Lite as my default search engine

**Additional context**
![IMG_20200924_050011](https://user-images.githubusercontent.com/70332632/94074134-e1459b80-fe22-11ea-9cb4-fda9c34c2207.jpg)

**Comment by WillHick** [comment]
There is a !bang for DuckDuckGo Lite. You can do !lite into the search bar (example: !lite puppy)

Not a bad idea to add this as a search setting to the app though.

**Comment by cmonfortep** [comment]
Thanks @WillHick for suggesting using Bangs for that usecase.

We don't have plans in the short/mid-term to provide Lite as an option inside the browser settings because we are currently focused in other areas.
