### ISSUE TITLE
Replace dialogs for snackbars on Bookmarks + fireproof websites

### ISSUE THREAD

**Issue by malmstein** [duckduckgo/Android#945]
**Is your feature request related to a problem? Please describe.**
Currently, we show a confirmation dialog when a user deletes a bookmark or deletes a fireproof website. See attached screenshot

**Describe the solution or the user experience you'd like**
Introduce a Snackbar with an action button to "Undo".

**Additional context**

***Proposed copy***
Description: {website} deleted
Action: Undo

**Screenshots**:
| Before  | After |
| ------ | ----- | 
![image](https://user-images.githubusercontent.com/531613/94670805-4f063180-0313-11eb-9249-1bad4de741f1.png)|![image (1)](https://user-images.githubusercontent.com/531613/94670801-4e6d9b00-0313-11eb-9425-5f3360d50916.png)|

**Comment by abdulbasit75** [comment]
I would like to work on this issue, olease assign me.

**Comment by abdulbasit75** [comment]
I would like to work on this issue, please assign me.

**Comment by malmstein** [comment]
Thanks @abdulbasit75, but there is a PR already opened for it https://github.com/duckduckgo/Android/pull/951. Feel free to comment on it or look at https://github.com/duckduckgo/Android/labels/help%20wanted and https://github.com/duckduckgo/Android/labels/hacktoberfest if you are looking to contribute.

**Comment by cmonfortep** [comment]
Tracking this here: https://app.asana.com/0/414730916066338/1199514257586717/f

**Comment by cmonfortep** [comment]
Closing this. This was done in https://github.com/duckduckgo/Android/pull/1056
