### ISSUE TITLE
Show favourites or pinned bookmarks on Home screen

### ISSUE THREAD

**Issue by neatwheat** [duckduckgo/Android#946]
I think a way to pin bookmarks, so that they are shown as <del>symbols</del> icons when a new tab is opened would be a great workflow addition

**Comment by KiberneticWorm** [comment]
Have you solved this problem? What do you mean "as symbols". Site icons?

**Comment by neatwheat** [comment]
Not a problem, a feature request ... Yes i mean icons, symbols may be a misleading term. Of course with the site name as text. Opera for android e.g. does it in a very convenient, customisable way

**Comment by neatwheat** [comment]
> 
> 
> Have you solved this problem? What do you mean "as symbols". Site icons?

Not a problem, a feature request ... Yes i mean icons, symbols may be a misleading term. Of course with the site name as text. Opera for android e.g. does it in a very convenient, customisable way

**Comment by cmonfortep** [comment]
Thanks @neatwheat I think the idea you are suggesting is pretty similar to the concept of `Favourites` we have on our iOS app.

On the iOS app, we show a grid showing user's favourites on a new tab.
![image](https://user-images.githubusercontent.com/4747865/94925556-b06b0380-04bf-11eb-8bef-07e3b3db4537.png)

is that what you wanted to describe on your feature request? Thanks!

**Comment by neatwheat** [comment]
@cmonfortep 
Yeah, that looks like it's pretty much what I meant! I think it would be a great feature that could improve usabilty a lot - especially if someone can choose their own favorites!

**Comment by cmonfortep** [comment]
We created a task to explore this internally: https://app.asana.com/0/715106103902962/1198217253840085/f

**Comment by cmonfortep** [comment]
This one is coming soon. We are currently working on a project to add favorites in the same way as the iOS works. 

Closing this one as it's currently in progress.

**Comment by holgerbrandl** [comment]
What's the status here? In DDG v5.102.3 this feature seems still missing.
