### ISSUE TITLE
Being able to UNDO closing a tab in the tabs screen

### ISSUE THREAD

**Issue by aitorvs** [duckduckgo/Android#968]
**Is your feature request related to a problem? Please describe.**
It has happened several times that I have closed a tab by mistake in the tabs screen.

**Describe the solution or the user experience you'd like**
An "UNDO" Snackbar could be added that would popup when a tab is closed (or swiped to close), similar to the experience offered in other browsers like Chrome.

**Additional context**
na

**Comment by cmonfortep** [comment]
Thanks @aitorvs , definitely something any user will expect to have 👍 

I've created an internal proposal to include this feature (https://app.asana.com/0/0/1198899768811973/f)
