### ISSUE TITLE
please add an exit button in three dot menu

### ISSUE THREAD

**Issue by 3j9fkyahunqoxwqu** [duckduckgo/Android#969]
Hello
thank you for this great app the only things that I miss is that I don't know when the app clears tabs and data automatically.

Because the app don't have any exit button in the menu.

So I don't know what action will assumed by the app as existing.

I want to know this so the app don't accidentally clear my data.

Thanks.

**Comment by ashoksinghal** [comment]
I would like to work on this if it's available?

**Comment by cmonfortep** [comment]
@3j9fkyahunqoxwqu 

There are two different modes to clear your data:
1. Manual mode: you can clear your browser data using the Fire button. Using this mode you can decide when it's the right moment to clear all the data. 
2. Automatic mode: Inside settings, you can enable our automatic data clearer and select `when` to trigger it. If you select "App exit only", that's when you manually kill the app from the task manager or after the systems kills the app.

If you are unsure about when to clear your data, I suggest you to disable the automatic data clearer and do it manually when you think it's the time to clear all.

About the three dot menu, we already got the same suggestion in https://github.com/duckduckgo/Android/issues/837. Please check details there.

Thanks.
