### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#971]
Bug:
New Tab, Tool Bar Disappearing.

Happens:
At Random The Toolbar Disappears At Different Times, Might Be Something To Do With The Keyboard Appearing (Currently Unsure)

Image Proof:
![Screenshot_2020-10-21-16-04-11-44](https://user-images.githubusercontent.com/48844761/96668442-8316c480-139e-11eb-8155-bcefe313b4a2.png)

**Comment by cmonfortep** [comment]
Thanks for reporting and sharing that screenshot. However, if we can't reproduce it (I tried on my device), we can't provide a fix.

Let us know if at some point you have a scenario to follow. Also, as the template indicates, it also helpful for us if you provide device and app information so we can focus on a concrete App version or device.
