### ISSUE TITLE
privacy practices rating doesn't match tosdr

### ISSUE THREAD

**Issue by cauerego** [duckduckgo/Android#973]
it's all explained in much detail here already:

https://forum.tosdr.org/t/duckduckgo-browser/211

that is, supposing they should match, to begin with. which isn't very clear to me yet.

**Comment by cmonfortep** [comment]
Thanks for flagging this, we're aware of this and we're reviewing how we approach site ratings on our Privacy Dashboard. We expect to make some product changes over the next few months.
