### ISSUE TITLE
Bookmark Icons

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/Android#975]
Issue:
Bookmark icons are not the sites original one's, my guess this would be a fetching issue or a local issue, ive noticed this as in the image below i dont think DuckDuckGo Traffic has a google icon. 😂

Image:
![IMG_20201024_084509](https://user-images.githubusercontent.com/48844761/97047458-5b04ac80-15bc-11eb-963c-df86592bcafd.jpg)

**Comment by cmonfortep** [comment]
😱 thanks for reporting. Will check on Monday what can be the issue.


p.s: @WillHick that screenshot made me suffer 😂

**Comment by WillHick** [comment]
Haha sure does 😂

**Comment by oldphones68** [comment]
Still facing the issue...
