### ISSUE TITLE
Problem with build the project

### ISSUE THREAD

**Issue by AminMoradian** [duckduckgo/Android#977]
app/CMakeLists.txt : C/C++ debug|x86 : CMake Error at app/CMakeLists.txt:13 (add_library):
  Cannot find source file:

    /src/main/cpp/https-bloom-lib.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

app/CMakeLists.txt : C/C++ debug|x86 : CMake Error: CMake can not determine linker language for target: https-bloom-lib
app/CMakeLists.txt : C/C++ debug|x86 : Failed to compute build system.
executing external native build for cmake app/CMakeLists.txt

**Comment by AminMoradian** [comment]
Anybody here for help me

**Comment by cmonfortep** [comment]
Please, check this issue https://github.com/duckduckgo/Android/issues/537 or follow the guide here https://github.com/duckduckgo/Android#building-the-project

Thanks!
