### ISSUE TITLE
Persian language support

### ISSUE THREAD

**Issue by AminMoradian** [duckduckgo/Android#978]
Support for Persian language as well as right to left languages

**Comment by AminMoradian** [comment]
I can add this feature

**Comment by cmonfortep** [comment]
Thanks. Personally, I would love to translate our app into many different languages. However, we are currently only supporting a subset of languages and we don't have current plans to support new ones.

Please check our translation guidelines here. https://github.com/duckduckgo/Android/blob/develop/TRANSLATIONS.md

> " Please note we are not looking for help with other languages at this time; only the languages listed above. We may open up requests in future for additional languages."
